### ISSUE TITLE
Provide a way to arbitrary directories to classpath

### ISSUE THREAD

**Issue by michaelklishin** [technomancy/leiningen#1063]
Inspired by #1062.

I think there should be a way to just add arbitrary directories to the classpath. In some cases people want to use Clojure REPL with `.class` files being generated by other tools
(possibly as part of other projects).

Think of it has "checkout dependencies for all JVM languages". Current workarounds for this
are counterintuitive and fragile. So maybe introducing such a feature is not a bad idea?

Are there any pitfalls or downsides I may be overlooking?

**Comment by kul** [comment]
actually adding `:resource-paths ["lib_managed/*" "resources"] works for adding floating jars!!!

HTH
