### ISSUE TITLE
javac/aot order

### ISSUE THREAD

**Issue by vemv** [technomancy/leiningen#1064]
given a project like this:

```
:source-paths ["src/clojure"]
:java-source-paths ["src/java"]
:aot all
```

And being the Java sources dependent on the generated Clojure packages/classes, the build will break, as javac gets executed before Clojure compilation.

Clojure sources could depend on the Java generated packages/classes just as well, so there's not a better ordering between the two.

I reckon the quickest possible fix would be to let the user which compilation process to start first. It looked like `:prep-tasks ["compile" "javac"]` would do the trick, but nope.

So the `:prep-tasks` functionality could be extended so as to address the described issue. Or an additional directive could be added, like:

```
:compile-order [:java :clojure]
```

This would not address interleaved dependencies (e.g. namespace A depends on package B which depends on namespace C...), for which surely some sort of dependency resolution mechanism would be needed. I don't think there are a lot of projects like that though.

**Comment by qdhaiqiang** [comment]
the answer please refer [luminus-template](https://github.com/luminus-framework/luminus-template/issues/319).
just modify default user.clj namespace in `dev/user.clj` to your project namespace, such as  `demo.user.clj` in `dev/demo/user.clj`

**Comment by qdhaiqiang** [comment]
and change` :repl-options {:init-ns user} ` to your own user in project.clj file, such as `:repl-options {:init-ns demo.user}`
