### ISSUE TITLE
Lein on Windows is much slower than lein on OSX

### ISSUE THREAD

**Issue by amanu** [technomancy/leiningen#1136]
lein on Windows is much slower than lein on OSX: visibily and almost unusable :(.

Even the ```lein --version``` is visibly slow on windows (XP and Vista). 

_(I can reproduce this with 3 equally fast laptops on my desk here, and OSX is the only that's usable)_

Is there any way to activate some profiling/logging in lein to help pinpoint the problem? or is this problem already known ?

regards.

**Comment by winks** [comment]
It's been nearly 2 years, I just tried to reproduce this.
```
Leiningen 2.5.1 on Java 1.7.0_17 Java HotSpot(TM) 64-Bit Server VM
```

measured with this:
```
ECHO Start Measure %Time% >> timer.txt
call c:\apps\bin\lein.bat version
ECHO Stop Measure %Time% >> timer.txt

ECHO Start Measure %Time% >> timer.txt
call c:\apps\bin\lein.bat help
ECHO Stop Measure %Time% >> timer.txt
```

In a non-project dir, 2nd run:
```
Start Measure 23:58:39,76 
Stop Measure 23:58:41,66 (1.9s)
Start Measure 23:58:41,66 
Stop Measure 23:58:43,88 (2.22s)
```
In a [project dir](https://github.com/winks/multiplex), 2nd run:
```
Start Measure 23:58:28,08 
Stop Measure 23:58:30,24 (2.16s)
Start Measure 23:58:30,25 
Stop Measure 23:58:33,78 (3.53s)
```
