### ISSUE TITLE
Support grouping arguments to higher-order tasks

### ISSUE THREAD

**Issue by mtopolnik** [technomancy/leiningen#1138]
If I write the following;

```
$ lein do clean, thrush uberjar, upload
```

`do` will parse it into

``` clojure
["clean"] ["thrush" "uberjar"] ["upload"]
```

which will prevent me from combining `do` with `thrush`. It would be more useful if `do` realized that `thrush` is a higher-order task and turned everything over to it for further parsing:

``` clojure
["clean"] ["thrush" "uberjar," "upload"]
```

I have already implemented this in my [lein-nix](https://github.com/mtopolnik/lein-nix) project and it works very well, for example, with this complex expression:

```
$ lein xdo git-check-clean, \
  thrush version-update :release, edit-version, \
  xdo deploy clojars, commit "New release", tag, \
  thrush version-update :new-snapshot, edit-version, \
  xdo commit "New snapshot", push
```

where `xdo` is my `do` with the changed semantics. The above is a complete deployment script laid out as a single `lein` invocation, which can be easily turned into an alias.

Please consider applying the same semantics to leiningen's `do`.

**Comment by technomancy** [comment]
Looking back at this, I don't think this complexity is justified given that this ambiguity does not exist in aliases, which are a better way to accomplish this.
