### ISSUE TITLE
lein deploy does not seem to honor :checksum :ignore

### ISSUE THREAD

**Issue by sundbp** [technomancy/leiningen#1139]
I'm having trouble deploying a new snapshot to clojars, no matter what :checksum setting I set it always fail on checksum.

grep'ing through the code I don't see checksum being used in deploy.clj - perhaps it's only used for getting dependencies, not pushing deploys?

**Comment by sunng87** [comment]
I think we do need a command-line option to ignore checksum failure on deployment. In China the `lein deploy` timeouts frequently. Once it fails, a dirty checksum is left on the server that stops further retries.

**Comment by technomancy** [comment]
This seems like a way to address the symptoms instead of the cause of the problem.

**Comment by sunng87** [comment]
I found the `checksum` option in `repositories` works well for this issue. And the `checksum` option at root level is for dependencies only. Sometimes a command-line option for disable checksum is handy, because the connection issue only happens at some time. Perhaps I can create a PR for this feature?

**Comment by okal** [comment]
@technomancy Thanks for all the great work you do on leiningen.

Are you suggesting that the high latency Internet connections is the problem that needs solving in the case @sunng87 illustrated?

**Comment by hyPiRion** [comment]
@okal: I am guessing Phil meant that ignoring the warning is not the right answer – we/Clojars should probably handle incomplete deployments better.

I think the best solution would be to ensure that deployments are atomic – either they fail, or they succeed, not end up in some state in between.

**Comment by okal** [comment]
@hyPiRion Ah, that makes sense. Thanks for clarifying. Atomic deployments would be a great enhancement.

**Comment by hyPiRion** [comment]
Atomic deployments to Clojars is clojars/clojars-web#226. I'm pretty sure that is independent of Leiningen.
