### ISSUE TITLE
local_repo not being used for resolving plugin dependencies

### ISSUE THREAD

**Issue by kornysietsma** [technomancy/leiningen#1140]
(Note: this is on Windows, not sure if it's platform specific)

I've been trying to use lein-kibit on a project that has a :local_repo setting (as ~/.m2 is on a network drive so slow).

If I add [lein-kibit "0.0.8"] to :plugins and run "lein kibit", the "jonase/kibit" and "lein-kibit" jars are downloaded to my local repo, but then I get the error: 

```
Could not find artifact jonase:kibit:jar:0.0.8
This could be due to a typo in :dependencies or network issues.
```

If I remove the :local_repo setting, the jars are downloaded to ~/.m2 and then "lein kibit" works.

If I restore the original :local_repo value, "lein kibit" _continues to work_ - it seems the jar is being accessed from ~/.m2/repository despite my :local_repo setting.  If I remove the ~/m2/repository directory, "lein kibit" breaks again.

**Comment by JakePi3** [comment]
I am seeing this when :local-repo is specified in any profile (other than at the top level).  All plugins are resolved against and downloaded to ~/.m2/repository

Issue goes away if :local-repo is specified at the top level in project.clj, or if no plugins are specified at project level.

Workaround: Move all plugins into the :dev profile inside the project.clj, then the profiles.clj :local-repo setting will be correctly picked up.

Steps to reproduce:

1) Have a top-level :plugins directive in the project.clj
2) Do not have a top-level :local-repo directive (put it in a profile)

Outcome: Plugins will be resolved against default m2 repo location while depdendencies of the project will correctly use the :local-repo

Summary: Resolution of plugins declared at the top level only obey :local-repo directives also declared at the top level.

**Comment by tvaughan** [comment]
I've just been bit by this, on Linux. I can't get this to work other then by deleting :local-repo from project.clj. Other plugins work fine, but not kibit. Could maybe possibly be related to https://github.com/technomancy/leiningen/issues/2111. However, I'm using a much different setup than the one I mention in the leiningen issue. This is what I have now:

```clojure
(defproject villarrica-backend "0.1.0-SNAPSHOT"
  :description "The new new Content Manager backend."
  :url "https://github.com/lynxtp/villarrica-backend"
  :dependencies [[com.datomic/datomic-pro "0.9.5350" :exclusions [commons-codec]]
                 [compojure "1.5.0"]
                 [org.clojure/clojure "1.8.0"]
                 [org.clojure/data.json "0.2.6"]
                 [ring-middleware-format "0.7.0"]
                 [ring/ring-core "1.4.0"]
                 [ring/ring-defaults "0.2.0"]]
  :repositories {"my.datomic.com" {:url "https://my.datomic.com/repo"
                                   :password :env/datomic_repo_password
                                   :username :env/datomic_repo_username}}
  :local-repo "/srv/lein/repo"
  :target-path "/var/cache/target/%s"
  :clean-targets ^{:protect false} [:target-path ".coverage"]
  :profiles {:ancient
             {:plugins [[lein-ancient "0.6.10"]]}
             :cloverage
             {:plugins [[lein-cloverage "1.0.6"]]}
             :cider
             {:plugins [[cider/cider-nrepl "0.11.0"]]}
             :dev
             {:dependencies [[com.cognitect/transit-clj "0.8.285"]
                             [org.clojure/test.check "0.9.0"]
                             [ring/ring-mock "0.3.0"]]}
             :eastwood
             {:plugins [[jonase/eastwood "0.2.3"]]}
             :environ
             {:plugins [[lein-environ "1.0.2"]]}
             :kibit
             {:plugins [[lein-kibit "0.1.2"]]}
             :prone
             {:dependencies [[prone "1.1.1"]]
              :ring {:stacktrace-middleware prone.middleware/wrap-exceptions}}
             :ring
             {:plugins [[lein-ring "0.9.7"]]
              :ring {:handler villarrica.backend.ring/api}}
             :squiggly
             {:dependencies [[acyclic/squiggly-clojure "0.1.5" :exclusions [org.clojure/tools.cli]]
                             ^:replace [org.clojure/tools.nrepl "0.2.12"]]
              :env {:squiggly {:checkers [:eastwood :kibit]}}}
             :ultra
             {:plugins [[venantius/ultra "0.4.1"]]}
             :uberjar
             {:aot :all}}
  :aliases {"coverage"
            ["with-profile" "+cloverage,+ultra" "do" "clean," "cloverage" "-o" ".coverage"]
            "eastwood"
            ["with-profile" "+eastwood" "eastwood"]
            "emacs"
            ["with-profile" "+cider,+eastwood,+environ,+kibit,+squiggly,+ultra" "repl"]
            "kibit"
            ["with-profile" "+kibit" "kibit" "src" "test"]
            "repl"
            ["with-profile" "+ultra" "repl"]
            "serve"
            ["with-profile" "+ring" "ring" "server-headless" ~(System/getenv "VILLARRICA_BACKEND_PORT")]
            "test"
            ["with-profile" "+ultra" "test"]
            "update-dependencies"
            ["with-profile" "+ancient,+cloverage,+cider,+eastwood,+environ,+kibit,+prone,+ring,+squiggly,+ultra" "ancient" "upgrade" ":all" ":check-clojure"]})
```

What's funny is that kibit works in the emacs profile (via squiggly-clojure) but not in the kibit profile alone.

**Comment by overthink** [comment]
I believe I have a very simple repro for this with leiningen 2.7.1: https://github.com/overthink/lein-local-repo-issue

It looks like lein will happily download dependencies into the local repo (i.e. when resolving deps), but when the plugin (kibit) is actually run it doesn't look in the local repo.

**Comment by overthink** [comment]
Bizarrely, this may be specific to kibit / only a certain class of plugins. If you add eastwood (`[jonase/eastwood "0.2.3"]`) to `:plugins` in my example repo and follow all the same steps except run `lein eastwood`, it seems to work fine :confused:
