### ISSUE TITLE
"lein run &" hangs if sent to background

### ISSUE THREAD

**Issue by hypirion** [technomancy/leiningen#1173]
Whenever `lein run &` is performed (or a `lein run`-call is sent to the background) and system input is not redirected, shell terminals will suspend Leiningen regardless of whether the program reads from system in or not. Related to #957.

To reproduce, issue following commands on a linux or mac(?) machine:

```
$ lein new app background-suspension
(Creating new project)
$ cd background-suspension
$ lein run &
```

One would expect this to print out `Hello, World!`, but it suspends instead.

As a temporary workaround, one can do `lein trampoline run &`, as the program itself

**Comment by hyPiRion** [comment]
It may be possible to resolve this with JDK7.

**Comment by fenoloftaleina** [comment]
FYI, only `lein run <&- &` works for me.
