### ISSUE TITLE
lein2 install script fails behind proxy when trying to download clojure jar

### ISSUE THREAD

**Issue by jablub** [technomancy/leiningen#1204]
The  
  export TRAMPOLINE_FILE line failed in the install script when I ran behind a proxy.

Not sure where to set proxy credentials for org.apache.http.auth. on linux

andrew.potgieter.mit@gmail.com

Jun 04, 2013 7:25:09 PM org.apache.http.client.protocol.RequestAuthenticationBase process
WARNING: NTLM authentication error: Credentials cannot be used for NTLM authentication: org.apache.http.auth.UsernamePasswordCredentials
Jun 04, 2013 7:25:09 PM org.apache.http.client.protocol.RequestAuthenticationBase process
WARNING: NTLM authentication error: Credentials cannot be used for NTLM authentication: org.apache.http.auth.UsernamePasswordCredentials
Could not transfer artifact org.clojure:tools.nrepl:pom:0.2.3 from/to central (http://repo1.maven.org/maven2/): Not authorized by proxy , ReasonPhrase:Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  ).
Could not transfer artifact clojure-complete:clojure-complete:pom:0.2.3 from/to central (http://repo1.maven.org/maven2/): Not authorized by proxy , ReasonPhrase:Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  ).
This could be due to a typo in :dependencies or network issues.

**Comment by flaing** [comment]
Greeting, dear sirs, 

I have this problem, too, while the solution didn't help.

Here is the error message:
* * *
>Could not transfer artifact incanter:incanter-svg:pom:1.5.7-SNAPSHOT from/to clo
>jars (https://clojars.org/repo/): Not authorized by proxy , ReasonPhrase:Proxy A
>uthentication Required ( Forefront TMG requires authorization to fulfill the req
>uest. Access to the Web Proxy filter is denied.  ).
* * *
Environment:
I run leiningen behind proxy(*.company) and firewall (Forefront TMG) on Windows 7. And I am sure that my manager gave me the authority to access to the central repo servers. I only have domain network activated. (but I can go to public via proxy.)

manual:
I can download the jar manually from central repos. I manually set up basic repl environment for Emacs, while I still can't do several things like 'lein test' , './script/install' ... and so on.
