### ISSUE TITLE
Improve documentation around remote repl connections

### ISSUE THREAD

**Issue by kanej** [technomancy/leiningen#1217]
By default the `lein repl :start` and `lein repl :headless` commands select localhost (127.0.0.1) for the host of the nrepl server port, but this stops connections from remote machines. The trick to allowing remote connections is to set the host to be any (0.0.0.0) using the `:host` key of `:nrepl-options` in project.clj i.e.

```
:repl-options {:host "0.0.0.0" :port 12454}
```

I am not sure of the best place to document this: the FAQ, the repl section of the tutorial, or a new guide on remote connections (any of which I am happy to provide a patch for).

As a start though the `lein help repl` documentation should indicate that the host to attach to can be changed for the `:start` and `:headless` subcommands using `:repl-options`. Currently that is only indicated for the `:connect` command.

**Comment by holtzermann17** [comment]
Hi, 2013. In your timeline, docker was just released a couple months ago. Here in 2019, I found that using the `:repl-options {:host "0.0.0.0" :port 12454}` from the OP on this thread is more effective than `CMD ["lein", "repl", ":headless", ":host", "0.0.0.0", ":port", "12454"]`.
