### ISSUE TITLE
Separate io functions in leiningen-core to avoid cyclic deps

### ISSUE THREAD

**Issue by hypirion** [technomancy/leiningen#1227]
dff5865b2e045118207d725bf6530ae891319af8 had the intention of relocating logging functions so that they could be used without cyclic dependencies within `leiningen-core`. However, that would require moving a lot of dynamic bindings, which would break a lot of plugins.

For 3.0.0, io-related functions and vars should be moved into another namespace. (e.g. `io.clj`) This would avoid cyclic dependencies inside `leiningen-core` (I had some issues with this when I wanted to use `eval/sh` inside `user/gpg` for #1080)

**Comment by technomancy** [comment]
Any changes to the public API at this point are likely to be more disruptive than the problem they're solving.
