### ISSUE TITLE
Lein new doesn't use installed snapshot templates (and fails to retrieve from Clojars if present)

### ISSUE THREAD

**Issue by qtrfeast** [technomancy/leiningen#1235]
Hey there. Folks on this [pedestal-dev thread](https://groups.google.com/forum/#!topic/pedestal-dev/fM4YAb0yP-E) (and myself) have run into a rather interesting set of circumstances that seem to force leiningen to _not_ use a SNAPSHOT template dependency that exists in the local maven repository **and** fail to fetch that dependency from Clojars **if** it was installed via `lein sub install`.
### Steps to reproduce:
- Remove any existing pedestal templates `rm -rf ~/.m2/repository/pedestal-*`
- `lein new pedestal-service delete-me`
  - This should retrieve the template from Clojars
- Remove pedestal templates again `rm -rf ~/.m2/repository/pedestal-*`
- Clone [pedestal](https://github.com/pedestal/pedestal) and `lein sub install` from inside the repository
- `lein new pedestal-service delete-me`
  
  ```
  ▸ lein new pedestal-service delete-me                                                                                                             
  Failed to resolve version for pedestal-service:lein-template:jar:RELEASE
  This could be due to a typo in :dependencies or network issues.
  Could not find template pedestal-service on the classpath.
  ```

**Comment by daveliepmann** [comment]
I encountered this issue on lein 2.7.1 and resolved it with @kasterma's workaround of removing SNAPSHOT from my template's *project.clj*. The template has never been pushed to Clojars. Is this expected behavior?

```
$ lein -version
Leiningen 2.7.1 on Java 1.8.0_25 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by technomancy** [comment]
Can you specify what command you used?

**Comment by daveliepmann** [comment]
`lein install` in the template directory, then `lein new <template name> <project name>` in another directory.

**Comment by technomancy** [comment]
That explains it; you need a `--snapshot` argument when running `lein new ...`.

**Comment by cloojure** [comment]
I just ran into the same problem.  Seems to work if I remove -SHAPSHOT  suffix from the version prior to "lein install".
