### ISSUE TITLE
AWS Repository 403 Forbidden

### ISSUE THREAD

**Issue by agj32mrgibbits** [technomancy/leiningen#1236]
$ lein
Downloading Leiningen to /home/user/.lein/self-installs/leiningen-2.2.1-SNAPSHOT-standalone.jar now...
--2013-06-21 14:21:42--  https://leiningen.s3.amazonaws.com/downloads/leiningen-2.2.1-SNAPSHOT-standalone.jar
Resolving leiningen.s3.amazonaws.com (leiningen.s3.amazonaws.com)... 205.251.242.128
Connecting to leiningen.s3.amazonaws.com (leiningen.s3.amazonaws.com)|205.251.242.128|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2013-06-21 14:21:42 ERROR 403: Forbidden.

**Comment by jsnmoon** [comment]
@hyPiRion, thank you for the solution!

I was running into a problem installing on OS X 10.10.1 with Homebrew 0.9.5.
