### ISSUE TITLE
user.clj executed before java files are compiled

### ISSUE THREAD

**Issue by lynaghk** [technomancy/leiningen#1245]
I've got a `user.clj` file on my source path that transitively requires some Java classes from Java source files in my project.
On a fresh checkout of my project, when I try to run `lein javac` I get an error about the Java classes not existing.
Presumably this is because `user.clj` is executed before the javac task.
I have to comment out my `user.clj`, then run `lein javac`, then I can uncomment `user.clj` and get on my merry way.

Is there a nicer way to handle this situation?

This is with:

```
Leiningen 2.2.0 on Java 1.7.0_21 OpenJDK 64-Bit Server VM
```

**Comment by xpe** [comment]
I've found these tickets have to do with the same problem: #1245, #1477 #1764, #1787. There may be more, too!
