### ISSUE TITLE
Windows: lein.bat can't handle spaces in %USERPROFILE%

### ISSUE THREAD

**Issue by icooper** [technomancy/leiningen#1248]
If leiningen is installed in a path with a space (for example `C:\Users\Joe Schmoe\.lein`), lein.bat fails to run.  To fix, on line 24, `LEIN_HOME` should be set to `!USERPROFILE!\.lein`, and on line 292, `%CLASSPATH%` should be quoted.

**Comment by bcalco** [comment]
For anyone reading this, as I am, three years anon, and finding the lein.bat file slightly different than described above, the only change I had to make to the lein.bat file from the windows installer to get everything to work was to modify line 115 from:

         set CLASSPATH=%LEIN_JAR%

to
         set CLASSPATH="%LEIN_JAR%"

After that single change I was able to run lein on my Windows 8.1 VM.

**Comment by josteink** [comment]
@bcalco If that's true, I reccomend you send in a PR.

It *would* barely take me a minute to do so myself, but if I was asked to test or investigate anything I wouldn't be able to provide responses, so it's better for everyone if you could go ahead and do it.

You can even fork and edit on githib, without the need for messing with git or code locally.
