### ISSUE TITLE
:test-selectors doesn't suppress clojure.test fixtures

### ISSUE THREAD

**Issue by gfredericks** [technomancy/leiningen#1269]
The implementation of `:test-selectors` hooks `clojure.test/test-var`, which is responsible for running just the tests, not the fixtures.

This means that, for example, if I have an `:each` fixture around a set of five tests that are all excluded by my `:test-selectors`, the fixture will still run five times.

Given that one use case for `:test-selectors` is to exclude tests that require some unavailable external resource, and a use case for fixtures is for managing external resources, this is rather inconvenient.

One fix for just the `:each` fixtures is to stop hooking `test-var` and instead hook `test-all-vars` and for each var in the namespace remove the `:test` metadata when the `:test-selector` requires it.

This doesn't address `:once` fixtures though, which seems much trickier.

**Comment by ehashman** [comment]
Drive-by comment: I just ran into the `:once` fixture issue on Leiningen 2.7.1. It looks like CLJ-866 has been merged since this was closed. Is this something we're interested in revisiting?

**Comment by truemped** [comment]
Another *drive-by comment*. Also ran into exactly this today. Any possibilities or ideas to deal with this situation? I also have one clojure test file that only contains integration tests. Would be nice to not have it spin up dependencies...

**Comment by codeasone** [comment]
+1 

I'm on `2.7.1` and have failing unit tests due to `:once` fixtures for `^:slow` tests being invoked on `lein test` as well as `lein test :slow`.

**Comment by technomancy** [comment]
This implementation is a mess; due to the fact that `clojure.test` doesn't accept patches we have to do it all with monkeypatches, and the result is fairly problematic and unmaintainable.

I would recommend moving to [circleci.test](https://github.com/circleci/circleci.test) going forward if you can instead of relying on a combination of the unmaintained `clojure.test` library and the pile of hacks that lives in Leiningen. It should be easy to switch over to because it allows you to continue using your existing `clojure.test/deftest` calls but just provides a more flexible mechanism for running them.

**Comment by codeasone** [comment]
Thanks for the advice @technomancy. I'll start using `circleci.test`.

**Comment by codeasone** [comment]
So, I've used `circleci.test` for a bit. I like the `isolatation/enforce` fixtures. 

However it doesn't appear to limit `:once` fixture invocation based on `test-selectors`. In my case I have a `db_test.clj` file with some `deftest ^:unit` expressions, and a `(use-fixtures :once with-data)`. 

The fixtures are setup regardless of whether I `lein test` or `lein test :unit`. Am I missing something, or is this simply not supported functionality and I should look at coding it up?

**Comment by technomancy** [comment]
> The fixtures are setup regardless of whether I lein test or lein test :unit. Am I missing something, or is this simply not supported functionality and I should look at coding it up?

The circleci.test lib is still pretty new, so it's not surprising that
there are a few unexpected quirks.

I think this would be a good addition to the lib if you want to take a
shot at implementing it.

**Comment by logosity** [comment]
@technomancy Just stumbled onto this thread for more-or-less the same reason as the others - can you point to more about (or elaborate on) clojure.test being unmaintained? Thanks!

**Comment by technomancy** [comment]
You can check the commit history yourself. I've tried a number of times to get changes in, and it may have worked once, but mostly you just get ignored.

**Comment by jac1013** [comment]
I know this is an old issue, this might help people that stumble into this these days, `circleci.test` doesn't solve the issue that @codeasone mentioned yet (the main issue this ticket was created for). I'm a beginner in Clojure and I couldn't sort it out (maybe there is a way which I cannot understand).

Ended up doing my setup and teardown in a bash script :man_shrugging:, at least this let me run `lein test` without setting up my test database.
