### ISSUE TITLE
can not set proxy when use "lein deploy clojars"

### ISSUE THREAD

**Issue by yxzhang** [technomancy/leiningen#1319]
I have tried three methods none of which can work.

(1) in ~/.lein/profiles.clj

{:user 
      {
       :jvm-opts ["-Dhttp.proxyHost=127.0.0.1" "-Dhttp.proxyPort=8087" "-Dhttps.proxyHost=127.0.0.1" "-Dhttps.proxyPort=8087"]
}} 

lein with-profile user  deploy clojars

OR

lein  deploy clojars

(2) 
export http_proxy="http://localhost:8087" 
export https_proxy="http://localhost:8087"

OR

export http_proxy="127.0.0.1:8087" 
export https_proxy="127.0.0.1:8087"

(3)
export LEIN_JVM_OPTS="-Dhttp.proxyHost=127.0.0.1  -Dhttp.proxyPort=8087  -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=8087"

**Comment by danielcompton** [comment]
One option for testing is to use [`mitmproxy`](https://mitmproxy.org/) as an http proxy on a local machine.
