### ISSUE TITLE
"can't query passphrase in batch mode" on lein deploy

### ISSUE THREAD

**Issue by sritchie** [technomancy/leiningen#1349]
Hey guys,

When I call "lein deploy" in a project with an encrypted `credentials.clj.gpg`, I get the following:

``` clojure
[sritchie@TW-MBP13-sritchie ~/code/clojure/jackknife (master)]$ lein deploy
WARNING: please set :license in project.clj.
WARNING: please set :url in project.clj.
Could not decrypt credentials from /Users/sritchie/.lein/credentials.clj.gpg
gpg: gpg-agent is not available in this session
gpg: can't query passphrase in batch mode
gpg: Invalid passphrase; please try again ...
gpg: can't query passphrase in batch mode
gpg: Invalid passphrase; please try again ...
gpg: can't query passphrase in batch mode
gpg: decryption failed: secret key not available

See `lein help gpg` for how to install gpg.
No credentials found for releases (did you mean `lein deploy clojars`?)
See `lein help deploy` for how to configure credentials.
```

If I DO have `gpg-agent` running, I get a similar error, even though I only have one secret key on my machine:

``` clojure
Could not decrypt credentials from /Users/sritchie/.lein/credentials.clj.gpg
gpg: cancelled by user
gpg: decryption failed: secret key not available

See `lein help gpg` for how to install gpg.
No credentials found for releases (did you mean `lein deploy clojars`?)
See `lein help deploy` for how to configure credentials.
```

Are these issues you guys have seen before? Am I missing something easy?

**Comment by semperos** [comment]
Mac OSX 10.9 here, already had `use-agent` in my GPG config, but continued to get "gpg-agent is not available in this session." 

I got it working by doing a hard restart of GPG and SSH agents after adding new keys, as follows:

```
killall ssh-agent gpg-agent
unset GPG_AGENT_INFO SSH_AGENT_PID SSH_AUTH_SOCK
eval $(gpg-agent --daemon --enable-ssh-support)
```

After that, the default Mac OSX graphical pinentry program appeared and my passphrase was successfully stored by gpg-agent.

**Comment by sritchie** [comment]
I can confirm that GPG Suite works for me too!

**Comment by sarnowski** [comment]
Have the exact same problems on Debian 8 with gnupg version 1.4.18.

At first, I had to enable the "use-agent" configuration in the gpg.conf, so that my agent is used at least. I can force adding the key via `gpg --batch --decrypt ~/.lein/credentials.clj.gpg` command and using that repeatedly, the agent is used. When triggering `lein release :minor`, I still get the following messages:

```
...
Could not decrypt credentials from /home/tobias/.lein/credentials.clj.gpg
gpg: gpg-agent is not available in this session
gpg: can't query passphrase in batch mode
gpg: Invalid passphrase; please try again ...
gpg: can't query passphrase in batch mode
gpg: Invalid passphrase; please try again ...
gpg: can't query passphrase in batch mode
gpg: decryption failed: secret key not available
...
```

Somehow, it refuses to use the agent.

**Comment by sarnowski** [comment]
I guess thats related to #1963

**Comment by mkno** [comment]
@sarnowski suggestion to not delete the user-agent from gpg.conf like someone above suggested did it

**Comment by worace** [comment]
I know this has been closed for a while but wanted to chime in with another fix that helped me out.

I was getting leiningen / gpg issues deploying to clojars like this:

```
gpg-agent[9378]: command get_passphrase failed: Inappropriate ioctl for device
gpg: problem with the agent: Inappropriate ioctl for device
gpg: no default secret key: Operation cancelled
gpg: signing failed: Operation cancelled
```

I was able to get around this by setting:

```
export GPG_TTY=$(tty)
```

Then leiningen would properly open the GPG passphrase prompt and let you enter your passphrase.

**Comment by lvh** [comment]
If this still doesn't work, you might be in a modern gpg2 environment whereas lein is trying to call gpg. The newer versions of gpg-agent are still compatible with gpg (1.4.x) but don't set the correct environment variables anymore by default; in particular, GPG_AGENT_INFO is now automatically set for gpg2 but gpg still wants it. You can set it yourself:

```
export GPG_AGENT_INFO="$(gpgconf --list-dirs agent-socket):0:1"
```

**Comment by xiongtx** [comment]
Make sure your `gpg` and `gpg-agent` [versions are compatible](https://askubuntu.com/a/875179).

I was on an older Fedora installation where `gpg` was still GnuPG1 and not GnuPG2, and ran into this issue.
