### ISSUE TITLE
get-dependencies-memoized memoizes side-effecting function

### ISSUE THREAD

**Issue by cursive-ide** [technomancy/leiningen#1378]
In #1162 the result of `leiningen.core.classpath/get-dependencies` was memoized. However the memoized function is not pure, it modifies the classloader in `pomegranate/add-dependencies` and if the memoized value is later used with a different classloader the result is incorrect. This will happen, for example, if Leiningen is used in-process from a client such as Cursive (or CCW/Emacs/whatever) and the current thread context classloader is non-dynamic - `leiningen.core.project/ensure-dynamic-classloader` will create a new classloader meaning that the results of previous calls to `get-dependencies-memoized` are now invalid. This leads to plugins not being loaded and all sorts of other weirdness.

**Comment by technomancy** [comment]
Let's track this in #1768 instead since it covers this.
