### ISSUE TITLE
Leiningen repl doesnt respect ~/.inputrc file

### ISSUE THREAD

**Issue by kul** [technomancy/leiningen#1390]
For a ~/.inputrc which looks like

``` bash
set editing-mode vi
set keymap vi-insert
$if mode=vi
    set keymap vi-command
    "gg": beginning-of-history
    "G": end-of-history
    "\C-l": clear-screen
    set keymap vi-insert
    "kj": vi-movement-mode
    "\C-w": backward-kill-word
    "\C-p": history-search-backward
    "\C-n": history-search-forward
    "\C-l": clear-screen
$endif
```

Leiningen sets the mode to vi correctly, but doesnt respect keymaps. A good example is of python repl which plays nicely with these settings.

**Comment by WillChilds-Klein** [comment]
i've found that [rlwrap](https://github.com/hanslub42/rlwrap) (available via homebrew) provides a viable workaround for this issue. my `~/.inputrc`:

```
set completion-ignore-case on
set editing-mode vi
$if mode=vi
    set keymap vi-command
    set keymap vi-insert
    "\C-l": "\e\C-la"
    "jk": vi-movement-mode 
$endif
```

I invoke leiningen like so:

```
$ rlwrap -a placeholder -t dumb lein repl
```

apparently, some `placeholder` argument is required for `-a` on OSX's distribution of `rlwrap`, [but not on linux's](https://www.systutorials.com/docs/linux/man/1-rlwrap/#lbAE)...

this is the only solution I've found that gives both `lein repl` and `grench repl` the keybindings specified in my inputrc, which I get for free with bash, cpython, and other readline-native interpreters.

- OSX 10.12.6
- grench 0.1.0 (per `grench -v`, although homebrew thinks it's 0.2.0)
- lein 2.7.1
- java 1.8.0_05

[the Clojure Programming wiki book's "Getting Started" section](https://en.wikibooks.org/wiki/Clojure_Programming/Getting_Started#Enhancing_Clojure_REPL_with_rlwrap) initially pointed me in this direction.

**Comment by technomancy** [comment]
Thanks for reporting this. If you could follow up with reporting this to jline2, that's the code that actually handles reading .inputrc: https://github.com/jline/jline2

**Comment by WillChilds-Klein** [comment]
it looks like the jline2 team is aware of this issue (see [here](https://github.com/jline/jline2/issues/113) and [here](https://github.com/jline/jline2/issues/133)), and claims to have fixed it in the 2.14.0 release (current version is 2.14.5).

i'm not sure where to bump the version, though, or even verify jline's current version in leiningen's dependency closure (see output of [`lein deps :tree`](https://pastebin.com/jujLWXa5)). is the actual REPL read/print ctrl logic handled by `org.clojure/tools.nrepl`?

**Comment by technomancy** [comment]
Cool; we pull it in from the reply project: https://github.com/trptcolin/reply
tools.nrepl just handles the server, not the client.

We can override the version reply uses, but it'd be better to get it
bumped there and then bump our reply version in src/leiningen/repl.clj

**Comment by WillChilds-Klein** [comment]
sounds good. i've [submitted a PR to the REPLy repo](https://github.com/trptcolin/reply/pull/174), will submit one here if/when that gets merged.
