### ISSUE TITLE
Profiles must be either fully-composite or not composite

### ISSUE THREAD

**Issue by llasram** [technomancy/leiningen#1424]
Allowing profiles to be "partially-composite" -- both incorporating other profiles and their own profile maps -- means that profiles cannot be decomposed into a collection of atomic profiles.  Such profiles make it impossible to implement e.g. `with-profile`'s profile removal consistently, at least without adding a new intermediate representation for profiles.

**Comment by glts** [comment]
Related to #2393.

**Comment by technomancy** [comment]
I agree this would be a good idea but any changes here at this point are likely to be more disruptive than the problem they're solving.
