### ISSUE TITLE
Project templates include modified EPL v1.0

### ISSUE THREAD

**Issue by S11001001** [technomancy/leiningen#1446]
I am not a lawyer.

In the last paragraph of the `COPYING` file, "New York" has been replaced with "Washington".  Each project template from `lein new` creates a `README.md` that claims to license the project under EPLv1.0 or later.  However, the license included is the modified Leiningen version.  Either the included license should be the standard "New York" variant, or it should be disclosed to the `lein new` caller that the license file the user is distributing with the new project isn't _precisely_ the EPL, but a modified version, and that there may therefore be some question as to _which_ choice-of-law clause actually holds for their project.

**Comment by timmc** [comment]
For reference, the mailing list post in question: http://librelist.com/browser//leiningen/2014/2/20/modified-epl-issue-and-its-impact/ (useful for description of how/whether to update an affected project.)
