### ISSUE TITLE
Support for getting user/password from profile when connecting to drawbridge nREPL

### ISSUE THREAD

**Issue by timmc** [technomancy/leiningen#1518]
If I use `lein repl :connect https://user:pass@example.net/repl`, then my password is hanging out in the shell history and the process table for all to see. I'd like a way to convey the userinfo portion of the URL (or the whole URL) from disk or other source not visible to all users of the machine. Presumably the `:repl-options` portion of a profile would be ideal.

(Oh, and I should probably file a separate issue for supporting detection of the `https` scheme of drawbridge as well, but I'll probably hit it at the same time if I end up working on this issue.)

**Comment by hyPiRion** [comment]
Yeah, this is implemented, but we should probably document #1651 in the `lein help repl` documentation.
