### ISSUE TITLE
lein repl incompatible with different keyboard layout

### ISSUE THREAD

**Issue by joerupen** [technomancy/leiningen#1574]
I am using a swiss-german keyboard and cannot enter the following keys in a LEIN REPL: "@", "]" (maybe there are some more keys). For the "[" key I have to stroke the key twice. When I switch the layout to US, all keys work. 

It looks to me that this problem is related to the version 2.4.2 of leiningen. It didn't occur before I upgraded to this version.
When I run `lein repl` at the command prompt, lein essentially runs this windows process:

```
java  -client  
      -Dclojure.compile.path="/target/classes"  
      -Dleiningen.original.pwd="C:\Users\joerupen"  
      -cp "C:\Users\joerupen\.lein\self-installs\leiningen-2.4.2-standalone.jar" clojure.main -m leiningen.core.main repl
```

=> In this process I can't enter the mentioned keys:

However, when I changed the lein-version to 2.3.4, then I have no problem with the keyboard.

```
java  -client  
      -Dclojure.compile.path="/target/classes"  
      -Dleiningen.original.pwd="C:\Users\joerupen"  
      -cp "C:\Users\joerupen\.lein\self-installs\leiningen-2.3.4-standalone.jar" clojure.main -m leiningen.core.main repl     
```

Environment: Windows 8.   

This might be an issue in leiningen or maybe just an issue with my windows installation, in any case the older version works for me.

**Comment by sroller** [comment]
It's seems it's not solved yet. The Scala boys recommend to go back to the former version of jline. Is there something we can in Leiningen as well? I'm on Windows 7 x64 and just starting to play around with Leiningen/Clojure. Currently I'm switching my keyboard layout when I need the \[]{}.

**Comment by joerupen** [comment]
There is a workaround that worked for me.

Jline2 supports custom mapping of keyboard keys. In your `$HOME` directory, create a file named `.inputrc`. Paste in the following config:

    set meta-flag off
    set convert-meta off
    set output-meta off
    set enable-meta-key off
    "\e[": ""
    "\e]": "]"
    "\e\\": "\\"

**Comment by hyPiRion** [comment]
@sroller, I have outlined a rough sketch on how to replace base repl dependencies in #1795.

Perhaps it's sensible to gather a new doc for all the handy tricks and tips you can do with/to fix `lein repl`.

**Comment by sroller** [comment]
thank you. the .inputrc solution works almost well. the opening [ is showing only after the next keystroke, but that's way better than before.

**Comment by leifericf** [comment]
I'm experiencing a similar issue on macOS 11.6, when using the the REPL via [iTerm2](https://iterm2.com). I'm using Leiningen 2.9.8 on Java 15.0.1. Using an Apple Magic Keyboard with Norwegian layout (QWERTY).

Square brackets are typed using Option + 8 (for `[`) and Option + 9 (for `]`). This worked fine in the REPL, until I changed my Meta key (through iTerm2 Profile settings) to `Left Option Key = Esc+`, which was necessary to get the Meta key to function properly in CIDER for Emacs. With this change, it not possible to type square brackets in the REPL.

Note that, even wth the changed Meta key, it _is_ possible to type s brackets using the _right_ Option key.

The same issue occurs with curly brackets, `{` and `}`.

I'm not sure whether this is the same issue (duplicate?) or a slightly different issue. I'm also not sure whether this is an issue with the REPL, iTerm2 or something else. Any advice would be greatly appreciated.

**Comment by timvisher** [comment]
@leifericf This shouldn't have anything at all to do with leiningen, the REPL, or the Readline implementation. The way that input works in a terminal emulator is that certain keys are 'captured' by the terminal emulator to allow you to use the keyboard to make it do things while others are passed through or augmented in some way.

In your case you changed iTerm2 to 'capture' the left option key and pass Esc+<other keys> to the underlying terminal process when pressed and so iTerm2 is no longer allowing you to use the left option key to access tho OS feature of interpreting Option+8 as an `[` insertion.

Given the prevalence of square brackets in Clojure this definitely seems like a very disruptive change. I would recommend either interacting with the REPL from an editor like VSCode/IntelliJ/Emacs/Vim or getting used to always using the right option key as your OS option key and your left option key as your 'meta' key.

Hope that helps.

**Comment by leifericf** [comment]
Thank you for taking the time to explain that, @timvisher! I appreciate your advice. I prefer using Emacs in the terminal, but I suppose I'll try the GUI version of Emacs to see if that works. I've read in the book "Clojure for the Brave and True" that "Emacs For Mac OS X" has some other issues when working with Clojure. Maybe I'll ditch macOS in favor of a PC with Linux or even Windows for Clojure development, to make my life easier.

**Comment by timvisher** [comment]
FWIW I'm a long time terminal Emacs user and my development environment has been iTerm2+tmux+emacs+CIDER for a long time and I've always been very happy. That said it's never cost me anything to turn my option keys into meta keys since I don't use a non-english keyboard layout (I'm a Dvorak user as well).

There does seem to be a _ton_ of momentum behind VSCode + Calva at the moment though. The Clojure community generally has seemed to largely steer people away from Emacs/Vim for the past several years, at least if you're not already a pro user of either of the venerable editors. There's no reason to add their learning curve to the one you're already facing with Clojure. :)
