### ISSUE TITLE
Default CONTRIBUTING.md in lein new

### ISSUE THREAD

**Issue by myguidingstar** [technomancy/leiningen#1577]
I think it's good for the community if default lein template comes with (github-compatible) CONTRIBUTING.md 
James Reeves's [article](http://www.booleanknot.com/blog/2013/09/07/pull-requests.html) is a good starting point

Opinions?

**Comment by hyPiRion** [comment]
I think it's hard to get this one "right", because of differing opinions between people. I don't want to impose any standards on people, so I'd rather prefer a meta-CONTRIBUTING.md file instead. What about making it somewhat like [doc/intro.md](https://github.com/technomancy/leiningen/blob/master/resources/leiningen/new/default/intro.md)?

**Comment by myguidingstar** [comment]
Err, I totally forgot this issue :D
a long with meta-COTRIBUTING, I think it's okay to include a short template of conventions that will be used by the project. The author will then quickly pick their preference by editing the generated file:

```md
# Conventions:
- Following [Clojure style guide](https://github.com/bbatsov/clojure-style-guide) can make your code more readable
- This project uses {tabs instead of spaces}/{spaces instead of tabs}
- This project use {clojure.test}/{midje} test framework. Make sure the tests pass and add one when relevant
```
that sounds redundant but it targets new contributors.
Btw, the Nixos guys also have really nice github issue and PR templates here https://github.com/NixOS/nixpkgs/tree/master/.github

**Comment by hyPiRion** [comment]
Thanks for the feedback, that sounds like a smart way to introduce it without too opinionated.

**Comment by yegortimoshenko** [comment]
This is actually very project-specific. And it is something that is only useful after a certain scale. Generating boilerplate won't cut it.

I remember looking through Ruby repos a few years ago, and there was that piece of boilerplate generated with Bundler that I still know by heart (see [example](https://github.com/westarete/aversion/blob/master/README.md)):

> ## Contributing
> 1. Fork it
> 2. Create your feature branch (git checkout -b my-new-feature)
> 3. Commit your changes (git commit -am 'Add some feature')
> 4. Push to the branch (git push origin my-new-feature)
> 5. Create new Pull Request

And, actually, that's about as specific as you can get, in general. And totally redundant. And sometimes even false, considering now you can make small changes via GitHub's interface.

**Comment by hyPiRion** [comment]
After thinking about this, I guess it makes sense to not add this to the default templates. There hasn't been many requests for this, and people interested in a default `CONTRIBUTING.md` could make a template themselves.
