### ISSUE TITLE
Repository problem for mixed Java and Clojure project?

### ISSUE THREAD

**Issue by kdavidson** [technomancy/leiningen#1592]
I have a project which uses Java and Clojure using a local Nexus repository for all dependencies.  Using a "mirror everything" rule in a :user profile

```
    :mirrors {#".+" {:name "ganymede" :url "http://ganymede:8081/nexus/content/groups/public/" :repo-manager true} }
```

This works fine for 
 lein deps
 lein repl
correctly retrieving my dependencies from the local nexus

However, using
 lein jar
 lein install
 lein deploy

I get a could not transfer artifact .... from/ro central (http://repo1.maven.org/maven2/) error for all the dependencies in the project.

Removing the Java code from the project makes all the lein commands resolve the dependencies from the local Nexus.

I am using version 2.4.2 of Leiningen.

My current workaround is to package the Java code in a separate project and add that as a dependency to a Clojure only project.

**Comment by technomancy** [comment]
This doesn't seem actionable without a repro case. We can reopen it if one is provided.
