### ISSUE TITLE
:eval-in :nrepl still launching a second jvm

### ISSUE THREAD

**Issue by memeplex** [technomancy/leiningen#1600]
I run `lein repl`, then `lein run` with `:eval-in :nrepl` in my project configuration. The code is indeed evaluated in the nrepl server, since I can see the results in my repl. But two jvms are launched in the process, one for lein (which is expected) and one for something else (which is unexpected, at least for me). I was of the idea that using grenchman or quick-clojure wouldn't require the launch of any additional jvm at all, once the nrepl server was running. But a jvm is still in the way to this never reached nirvana. What is the point of this jvm?

**Comment by arichiardi** [comment]
Is this working on last ```master```? I see [here](https://github.com/technomancy/leiningen/blob/e9d6d7885777537fe3b50f3308b8fec44a65c391/leiningen-core/src/leiningen/core/eval.clj#L300) that ```nrepl-port``` is slurped instead of ```.nrepl-port```...but I have just skimmed through...
