### ISSUE TITLE
Leiningen installation issue on Debian Wheezy

### ISSUE THREAD

**Issue by sakhunzai** [technomancy/leiningen#1634]
I am simply unable to install leiningen on Debian linux :

```
> lein
Downloading Leiningen to /home/debianaut/.lein/self-installs/leiningen-2.4.3-standalone.jar now...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   355  100   355    0     0    240      0  0:00:01  0:00:01 --:--:--   375
100 14.2M  100 14.2M    0     0  51565      0  0:04:48  0:04:48 --:--:-- 41059
Failed to download https://github.com/technomancy/leiningen/releases/download/2.4.3/leiningen-2.4.3-standalone.jar
It's possible your HTTP client's certificate store does not have the
correct certificate authority needed. This is often caused by an
out-of-date version of libssl. Either upgrade it or set HTTP_CLIENT
to turn off certificate checks:
  export HTTP_CLIENT="wget --no-check-certificate -O" # or
  export HTTP_CLIENT="curl --insecure -f -L -o"
It's also possible that you're behind a firewall haven't yet
set HTTP_PROXY and HTTPS_PROXY.
```

I tried with setting HTTP_CLIENT but still same error . The version I read from lein script is `2.4.3`.

**Comment by rkwofford** [comment]
Same problem here.

**Comment by acasimiro** [comment]
I am inside an enterprise network and had the same problem.

Solved downloading it manually from the browser and saving the file in the specified location:
```
mv leiningen-2.5.3-standalone.zip ~/.lein/self-installs/leiningen-2.5.3-standalone.jar
```

**Comment by mattmcd** [comment]
I had a similar problem on Ubuntu due to curl looking in a different place to the installed ca-certs.  
To fix:

    sudo mkdir /etc/pki/tls
    sudo mkdir /etc/pki/certs
    sudo ln -s /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt

**Comment by skrypka** [comment]
@mattmcd Your solution is working. Except you have a small typo. Second line: ```sudo mkdir /etc/pki/tls/certs```
Thanks!

**Comment by mattmcd** [comment]
Thanks, comment above has been corrected.

**Comment by johnstt** [comment]
I'm having this problem now with a Docker image based on [this](https://hub.docker.com/r/jupyter/scipy-notebook/), which uses some build of Debian 8. The posted answers have not made the download any faster (it hovers around 50kbps), but they _have_ made it stop failing..

Does it seem weird to anyone else that an SSL cert setup problem decides _whether something downloads quickly or slowly_ (not whether it downloads at all)?

**p.s.** if someone can point me to a Dockerfile that installs Leiningen on Debian 8 I'd really appreciate it!
