### ISSUE TITLE
`lein repl` has issues with some non-us keyboard layouts on Windows

### ISSUE THREAD

**Issue by winks** [technomancy/leiningen#1636]
I am using Windows 7 and lein 2.4.2 with a German keyboard layout.

In cmd.exe (and ConEmu32) everything works fine, but inside `lein repl` my `]` doesn't really work.

So, basically I use `AltGr + 8` for `]` and `AltGr + 9` for `]`, but most of the time (not always) I can only do `[` via `AltGr + 8 8` and `]` via `AltGr + 8 9`.

I am pretty sure this is kind of practical Windows joke, but I didn't find any meaningful results while researching and I'm not sure if it should be documented.

**Comment by adam-matic** [comment]
I have a Croatian keyboard, same problem. Try:
[ - hold Alt, press F, F
] - hold Alt, press F, G
@ - hold Alt, press F, V

**Comment by winks** [comment]
According to [this comment](https://issues.scala-lang.org/browse/SI-8759?focusedCommentId=71772&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-71772) on the scala bugtracker 2.12.1 might fix it \o/

I'll see if I can get this tested tonight

**Comment by winks** [comment]
OK, so I tested it like this:

  * cloned jline2, checked out 2.12.1, `mvn install`
  * cloned reply, `s/jline "2.12"/jline "2.12.1"/`, `lein install`
  * checked out leiningen master, built with my `reply "0.3.6-SNAPSHOT"`
  * it works.

So unless I did something totally wrong, this looks like fixed as soon as we get a new reply version.

**Comment by pirelaurent** [comment]
for info :  i have the same  problem with french keyboard and [ ] on W7.
I must strike twice to obtain a "["  - third option with char "5" and "(" : AltGr (   
I couldn't have any "]"  until i see this thread and the Winks'comment.:) 

can use this trick with french keyboard: 
Alt ((  for [   
Alt () to obtain a ] .

**Comment by hyPiRion** [comment]
This is solved by #1862, and is now out on master.
