### ISSUE TITLE
test selectors documentation

### ISSUE THREAD

**Issue by mstram** [technomancy/leiningen#1654]
The current test / selectors docs are unclear or in error.

For example,
**\* this doesn't work****

```
     lein test :only leiningen.test.test/test-default-selector
```

"only runs the specified test. A default :all test-selector is available to run all tests."

*\* 
Ran 0 tests containing 0 assertions.
0 failures, 0 errors.

*\* but this does

```
 lein test :integration
```

and

```
 lein test:noSuchTag
```

Seems to revert to an implied ":all" tag

**Comment by glts** [comment]
I’ve reviewed the documentation at `lein help test`, everything there is accurate and works.

After the merge of #2584, Leiningen now aborts when you run `lein test :noSuchTag`.

With this I think there is nothing more to do here.

**Comment by technomancy** [comment]
Yeah, throwing when the selector is missing is the right behavior. Thanks for the fix; that takes care of this too.
