### ISSUE TITLE
repl not completely reset after eroneous input?

### ISSUE THREAD

**Issue by hallyhaa** [technomancy/leiningen#1668]
user=> (^ 2 7)

IllegalArgumentException Metadata must be Symbol,Keyword,String or Map  clojure.lang.LispReader$MetaReader.invoke (LispReader.java:722)
RuntimeException Unmatched delimiter: )  clojure.lang.Util.runtimeException (Util.java:221)
user=> (* 2 7)
714
user=>

**Comment by hyPiRion** [comment]
This is an upstream issue.
