### ISSUE TITLE
lein uberjar does not work when skip-aot is true

### ISSUE THREAD

**Issue by kototama** [technomancy/leiningen#167]
lein uberjar does not compile the main class of the project when skip-aot is true, thus the JAR can not be executed and a try gives the following error:

Exception in thread "main" java.lang.NoClassDefFoundError

**Comment by gja** [comment]
If you are looking to skip :aot compilation due to bugs you found with it enabled, I have a workaround over here.

It basically just has a straight up java file, which calls clojure.main for you https://gist.github.com/gja/efa1a7beea9ecb52e906
