### ISSUE TITLE
Enforce general policy of env vars taking precedence over config files

### ISSUE THREAD

**Issue by timmc** [technomancy/leiningen#1680]
As discussed in #1676, it is probably desirable to have `$JVM_OPTS` override project settings (including `:jvm-opts`) when launching a JVM subprocess.

Since environment variables sometimes act as defaults, this may reasonably constitute a breaking change, so this is marked for 3.0. However, for a build tool with a goal of repeatability this is still a desirable change.

**Comment by technomancy** [comment]
Any changes here at this point are likely to be more disruptive than the problem they're solving.
