### ISSUE TITLE
repository replace not working since 2.4.0

### ISSUE THREAD

**Issue by iangkent** [technomancy/leiningen#1695]
We have a private Nexus Repository Manager setup that has been acting as proxy for third-party repositories. Since we upgrade from lein 2.3.4 to 2.4.x we noticed that the replace meta data no longer seems to work.

Here is the line from project.clj file:
:repositories ^:replace [["nexus" {:url "http://nexus.cenx.localnet:8081/nexus/content/groups/public"}]]

Here is the difference in project map between releases:

$ wget https://raw.githubusercontent.com/technomancy/leiningen/2.3.4/bin/lein -O /usr/local/bin/lein
$ /usr/local/bin/lein pprint :repositories

[["nexus"
  {:url "http://nexus.cenx.localnet:8081/nexus/content/groups/public"}]]

$ wget https://raw.githubusercontent.com/technomancy/leiningen/2.4.0/bin/lein -O /usr/local/bin/lein
$ /usr/local/bin/lein pprint :repositories

(["central" {:snapshots false, :url "http://repo1.maven.org/maven2/"}]
 ["clojars" {:url "https://clojars.org/repo/"}]
 ["nexus"
  {:url "http://nexus.cenx.localnet:8081/nexus/content/groups/public"}])

HOW DO WE OVERRIDE THE DEFAULT REPOSITORIES TO USE NEXUS REPOSITORY MANAGER???

**Comment by techwhizbang** [comment]
+1 on this fix not fully addressing the problem. I was running Lein 2.3.3 and upgraded today to the latest stable 2.5.1 and ran into this very problem. 

In my ~/.lein/profiles.clj I have spec'd the repositories that should be used for fetching artifacts and have included the ^:replace keyword exactly like this:

```clojure
{:user {   
        :plugins [[lein-libdir "0.1.1"],[lein-pprint "1.1.2"]],

        :repositories ^:replace [["snapshot" {:id "snapshot" :url "https://my-internal-artifactory/libs-snapshot" :username "my username" :password "my password"}]
                                 ["release"  {:id "release"  :url "https://my-internal-artifactory/libs-release" :sign-releases false :username "my username" :password "my password"}]
                                 ["central"  {:id "central"  :url "https://my-internal-artifactory/libs-release" :sign-releases false :username "my username" :password "my password"}]
                                 ["clojars"  {:id "clojars"  :url "https://my-internal-artifactory/libs-release" :sign-releases false :username "my username" :password "my password"}]]

        }
}
```

In my actual project.clj I've spec'd a number of dependencies some are 3rd party libs and some are internal libs. 

When I run

```sh
# it does the right thing and respects the repository overrides
lein deps

# it also does the right thing and respects the repository overrides
lein with-profile user do clean, test, libdir

# it stops respecting the overrides
lein jar

# anything pertaining to jar it seems to want to fetch from central (https://repo1.maven.org/maven2/) and #clojars (https://clojars.org/repo/)
lein with-profile user jar
```
