### ISSUE TITLE
lein self-install/upgrade/downgrade is broken in lein.bat (2.5.0)

### ISSUE THREAD

**Issue by nihilismus** [technomancy/leiningen#1702]
`call` [1] returns 1 [2] in case of `call wget` (`wget` is not installed) and as a consequence `ERRORLEVEL` is set to 1 which makes `if NOT ERRORLEVEL 9009` true with the following output:

```
antonio@W7U:C:\Users\antonio:$ lein upgrade
The script at C:\Users\antonio\.lein\bin\lein.bat will be upgraded to the latest stable version.
Do you want to continue (Y/N)?y
Downloading latest Leiningen batch script...
'wget' is not recognized as an internal or external command, operable program or batch file.
Failed to download https://github.com/technomancy/leiningen/raw/stable/bin/lein.bat
```

So `lein self-install/upgrade/downgrade` is broken and at the same time leiningen-win-installer [3] is affected.

As a workaround i installed wget [4] and `lein upgrade` works once again.

[1]  #1599
[2] http://stackoverflow.com/questions/6498460/batch-programming-error-handling-and-start-command 
[3] http://leiningen-win-installer.djpowell.net uses `curl`.
[4] http://gnuwin32.sourceforge.net/packages/wget.htm

**Comment by ivanpierre** [comment]
The problem is that the version 2.5.1 changes jar file into a zip file and lein.bat hjas not been changed.
The windows installer has the same problem and so chocolaty. ;)

**Comment by hyPiRion** [comment]
@ivanpierre lein.bat has been changed – see https://github.com/technomancy/leiningen/blob/stable/bin/lein.bat#L194. Does that mean the windows installer and chocolaty bundles the (presumably) old lein.bat file?
