### ISSUE TITLE
manifest broken in uberjars created usgin lein-ring

### ISSUE THREAD

**Issue by yogthos** [technomancy/leiningen#1710]
The following warning shows up when running `lein ring uberjar`:
```
Warning: The Main-Class specified does not exist within the jar. It may not be executable as expected. A gen-class directive may be missing in the namespace which contains the main method.
```

Trying to run the jar results in the following error:

```
java -jar target/myapp-0.1.0-SNAPSHOT-standalone.jar
Error: Could not find or load main class myapp.handler.main
```

I'm using the same version of the `lein-ring` plugin and it behaves correctly in the 2.4.x version.

**Comment by hyPiRion** [comment]
Is this still reproducible?

FYI, we added the ``:leaky` metadata tag, so `:uberjar` profile vectors that refers to profiles without `^:leaky` attached will be ignored. Whether that is sensible or not is another matter – see #1833.

**Comment by yogthos** [comment]
I'm not able to reproduce it with the latest lein-ring/leiningen

**Comment by hyPiRion** [comment]
Alright, then I presume it's fixed on master (We've done some fixes with manifest files, so
