### ISSUE TITLE
Path used for a plugin's profile.clj file doesn't map "-" to "_"

### ISSUE THREAD

**Issue by hugoduncan** [technomancy/leiningen#1713]
The path at which `profiles.clj` is searched for differs to that for `plugin.clj`, etc, as it does not translate "-"s to "_"s.

**Comment by glts** [comment]
The plugin `profiles.clj` file does not live in a Clojure namespace and so does not undergo namespace name mangling (`-` → `_`).

Profiles for a plugin named ‘my-plugin’ will be read as with `(io/resource "my-plugin/profiles.clj")`.

This works as documented, and for backwards compatibility reasons we should not change it.

**Comment by technomancy** [comment]
Agreed; underscore mangling is an unfortunate property of `require` and not a general-purpose rule about any file.
