### ISSUE TITLE
:uberjar-name is ignored when set in a profile 2.5.0

### ISSUE THREAD

**Issue by laczoka** [technomancy/leiningen#1718]
works fine in 2.4.3

here is how to reproduce:
(project "..."

:profiles { :sandbox { :uberjar-name "sandbox-build.jar" }})

lein with-profile sandbox uberjar 
- has no effect under 2.5.0
- works fine under 2.4.3

**Comment by gfredericks** [comment]
I think another workaround is to set the profile to `^:leaky`.
