### ISSUE TITLE
Mirror repository configured in user profile is not picked up when resolving plugins

### ISSUE THREAD

**Issue by sfnelson** [technomancy/leiningen#1722]
Using leiningen 2.5.0 mirrors are no longer used to resolve plugin dependencies when configured via the user profile. The same proxy configuration in the project.clj file is used. E.g.

```
(defproject default "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[test/dependency "1.0.0"]]
  :plugins [[test/plugin "1.0.0"]]
  :mirrors {#".*" {:name "Proxy" :url "https:///proxy/"}}
  )
```

```
$ lein deps
Could not find artifact test:plugin:jar:1.0.0 in Proxy (https:///proxy/)
Could not find artifact test:plugin:jar:1.0.0 in Proxy (https:///proxy/)
```

Now comment out the `:mirrors` declaration in the project file and add the same configuration to `.lein/profiles.clj` in the user profile:

```
$ lein deps
Could not find artifact test:plugin:jar:1.0.0 in central (https://repo1.maven.org/maven2/)
Could not find artifact test:plugin:jar:1.0.0 in clojars (https://clojars.org/repo/)
```

When the plugin is commented out and lein deps is run, the mirror is used to resolve `test:dependency`, so I'm confident that the configuration is correct, but the user profile is not being used for plugin resolution.

**Comment by cdorrat** [comment]
I can confirm the same problem on leiningen 2.5.1
We're behind a firewall & the build machines have no direct network access, adding a plugin as a dependency works correctly and is downloaded with `lein deps`, adding it to the :plugins section hangs and tries to access the external repo, not the mirror.

**Comment by anthcourtney** [comment]
+1

**Comment by martinraison** [comment]
+1

**Comment by kawas44** [comment]
+1

To have an almost clean solution to this bug you can add a plugin repository in your project.clj
```
  :plugin-repositories [["proxy" "https:///proxy/"]]
```

**Comment by thadc23** [comment]
Anything new on this front?  Because of needing to encrypt a password for access to an enterprise mirror, I cannot define a plugin repository directly in my project.clj and need to have the mirror setup in my user profile so each developer can have their own password.  It seems to still be happening for plugin repositories in 2.5.2.

**Comment by djpowell** [comment]
+1 would like to see this fix applied, else it isn't possible to use plugins from my work environment

**Comment by hanshuebner** [comment]
+1

**Comment by donniemattingly** [comment]
+1

**Comment by MarkRx** [comment]
+1

**Comment by MarkRx** [comment]
Seems to be because plugins are loaded before profiles here: https://github.com/technomancy/leiningen/blob/master/leiningen-core/src/leiningen/core/project.clj#L969

**Comment by jiacai2050** [comment]
Anyone has a PR fix this?

**Comment by glts** [comment]
The underlying problem is a bit of a vicious circle during initialisation and I don’t see an obvious solution yet.

But since Leiningen 2.8.2 this can be worked around: put a `repository-overrides.clj` file in your project root with the mirrors configuration, `{:mirrors ,,,}`. This way at least you can keep the configuration outside of `project.clj`.

**Comment by glts** [comment]
There is an open pull request #2593 that fixes this. If you want to help, you can try it out and tell us whether it works for you.
