### ISSUE TITLE
Issue with log4j when :eval-in-leiningen true set to true

### ISSUE THREAD

**Issue by Gonzih** [technomancy/leiningen#1725]
Hi, I have issue with logging from inside lein plugin. Once I set `eval-in-leiningen true` in project.clj there I don't see logging output anymore. Is it something related to lein initialization process? I tried to reset configuration for logger, set jvm options (for lein and just jvm options) to configure it without much difference.

Thanks!

**Comment by hyPiRion** [comment]
Guessing that this is a variant of #2011.

**Comment by Gonzih** [comment]
Might be. I switched to different logging approach so did not experiment with this one any more.

**Comment by hyPiRion** [comment]
In hindsight this may be because the JVM opts to lein is passed in via `LEIN_JVM_OPS`, which are the ones log4j reads when it's ran inside lein.

Since this issue is somewhat old I'll close it. Feel free to reopen if the suggestion above doesn't work.
