### ISSUE TITLE
'pom' task doesn't honor profiles

### ISSUE THREAD

**Issue by ztellman** [technomancy/leiningen#1734]
I can provide a minimal reproducing case if necessary, but `lein with-profile foo pom` doesn't appear to pay attention to the dependencies under that profile, which breaks a deploy mechanism that was previously working under `2.4.3`.  I've had to downgrade to resolve this in the interim.

**Comment by ztellman** [comment]
Okay, I've been bitten by this enough that I decided to dig a bit deeper.  This is definitely related to https://github.com/technomancy/leiningen/commit/2da05e63565a726f4d18c103017f92aa081c5315#diff-55dfa3d96e2edcfade2dd9ea8593029c, which leads me to believe that this is intended behavior.  Am I just not supposed to be able to use `with-profile` to effect the output of `pom`?  @hugoduncan , can you comment?

**Comment by instilled** [comment]
@ztellman does adding [^:leaky](https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md#profile-metadata) metadata to the profile solve your problem?

**Comment by ztellman** [comment]
Nope.

**Comment by timvisher** [comment]
@technomancy @hyPiRion Can either of you comment on whether this is the intended behavior?

**Comment by hyPiRion** [comment]
@timvisher: It's not intended behaviour, it's a bug with profile-merging logic afaik.

**Comment by timvisher** [comment]
@hyPiRion Awesome. I might try to dig into this soonish then.

**Comment by hyPiRion** [comment]
@ztellman: I am actually unable to reproduce this bug if I include `^:leaky` on 2.5.2:

```bash
# lein version:
# Leiningen 2.5.2 on Java 1.6.0_31 OpenJDK 64-Bit Server VM
lein new foobar
cd foobar
tr -d ')' < project.clj > project.clj.tmp
echo '  :profiles {:foo ^:leaky {:dependencies [[aleph "0.4.0"]]}})' >> project.clj.tmp
mv project.clj.tmp project.clj
lein pom
mv pom.xml pom-base.xml
lein with-profile foo pom
mv pom.xml pom-foo.xml
diff pom-base.xml pom-foo.xml
```

emits

```diff
61a62,66
>     <dependency>
>       <groupId>aleph</groupId>
>       <artifactId>aleph</artifactId>
>       <version>0.4.0</version>
>     </dependency>
```

Could you provide a minimal reproducing case of what you described? Perhaps I missed something obvious.

**Comment by ztellman** [comment]
Hmm, the behavior does seem different.  I was testing with `2.5.0` when I reported the issue, so maybe it's been fixed since then (I just worked around the issue shortly after reporting it).  After upgrading to `2.5.2` I'm seeing what appears to be the expected behavior.  Feel free to close the issue.

**Comment by hyPiRion** [comment]
Alright, thanks for checking it out so quickly.

I verified that it doesn't work on 2.5.0, so it's a little concerning that it was somehow magically fixed though.
