### ISSUE TITLE
new win-installer

### ISSUE THREAD

**Issue by kij** [technomancy/leiningen#1744]
the fix in fa0556d6ed1 makes a new win-installer necessary. 
@djpowell  maintains it on bitbucket, i'll contract him there.

**Comment by technomancy** [comment]
We had to move the URL since GitHub releases was being idiotic and rejecting jar files: https://github.com/technomancy/leiningen/commit/f48846ff3cce9158d2c8ec5e6b488d45d74d286d

However, the URL in the bat file is updated, so this should be fixed.
