### ISSUE TITLE
HttpWagon.getConnectionManager() does no longer exist.

### ISSUE THREAD

**Issue by xsc** [technomancy/leiningen#1746]
Since upgrading `wagon-http` (formerly version 2.4) in 15f6832813b8d234ef3b0c830e6c283e7245c786 and ba2588de28c385b96d9b8b1a9802739437770568, tests may still be passing but running e.g.

```
$ bin/lein version
```

results in an exception being thrown since `HttpWagon.getConnectionManager()` was removed in apache/maven-wagon@143efd50bfcc24e9991dba43e3a94a6316655006 but is still being used in `leiningen.core.ssl`.

---

```bash
$ git clone https://github.com/technomancy/leiningen.git lng
[...]
$ cd lng/leiningen-core && lein bootstrap && cd ..
[...]
$ bin/lein version
java.lang.IllegalArgumentException: No matching field found: getConnectionManager for class org.apache.maven.wagon.providers.http.HttpWagon
 at clojure.lang.Reflector.getInstanceField (Reflector.java:271)
    clojure.lang.Reflector.invokeNoArgInstanceMember (Reflector.java:315)
    leiningen.core.ssl/fn (ssl.clj:91)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invoke (core.clj:624)
    clojure.core$memoize$fn__5097.doInvoke (core.clj:5846)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.lang.Var.invoke (Var.java:379)
    leiningen.core.project$load_certificates.invoke (project.clj:764)
    leiningen.core.project$activate_middleware.invoke (project.clj:771)
    leiningen.core.project$init_project.invoke (project.clj:878)
    leiningen.core.project$read.invoke (project.clj:952)
    leiningen.core.project$read.invoke (project.clj:953)
    leiningen.core.main$_main$fn__1616.invoke (main.clj:381)
    leiningen.core.main$_main.doInvoke (main.clj:378)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invoke (core.clj:624)
    clojure.main$main_opt.invoke (main.clj:315)
    clojure.main$main.doInvoke (main.clj:420)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```

**Comment by aroemers** [comment]
Just a note, this issue is now released in 2.5.1, so users having `:certificates` should not upgrade yet.

**Comment by hyPiRion** [comment]
I have been trying to solve this issue for some time now, and it *seems* like we have to wait for maven http-wagon 2.9, as we need this patch applied: https://github.com/apache/maven-wagon/commit/ad1e0790420fef4382be98c3626a2052b26b777d

It seems like this just around the corner (seems like the remaining part is documentation), so I'll wait until then and fix it at that point.

It's also possible to do some private accessor reflection hacks, but I think that's a bit over the top.

**Comment by orb** [comment]
It looks like 2.9 was released in April.

**Comment by Leonidas-from-XIV** [comment]
Thank you, appreciate your work on this! I had the same issue as @xsc so I was holding onto an older version of leiningen for now.
