### ISSUE TITLE
On Windows 7 Enterprise error Could not transfer artifact clojure-complete

### ISSUE THREAD

**Issue by ArthurZ** [technomancy/leiningen#1749]
Oracle Java JDK version "1.8.0_25".
REPL fails to start with error:
Could not transfer artifact clojure-complete:clojure-complete:pom:0.2.3 from/to clojars (https://clojars.org/repo/): Connection reset
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable
REPL will start by running java -jar path/clojure<version>.jar
How to fix?

**Comment by hyPiRion** [comment]
Guessing this was a network issue. If it's still an issue, feel free to reopen.
