### ISSUE TITLE
'lein check' hangs for 60 sec for some projects -- needs (shutdown-agents) call

### ISSUE THREAD

**Issue by jafingerhut** [technomancy/leiningen#1750]
Sorry, I don't have a minimal project to reproduce this issue right now, but for example doing 'lein check' on the current latest version of the reply project does it with these versions on Mac OS X 10.9.5:

% lein version
Leiningen 2.5.0 on Java 1.7.0_45 Java HotSpot(TM) 64-Bit Server VM

I doubt the JVM and OS versions matter much here.

It does not occur for all projects.  I am guessing doing 'lein check' on reply somehow causes the compiler to eval a top-level form creating a future, or clojure.java.shell/sh, pmap, etc.

**Comment by technomancy** [comment]
We're no longer using `clojure-complete` so I think this is gone.

**Comment by traut** [comment]
I'm seeing the same behavior in my pet project:
```
$ date && LEIN_JVM_OPTS= LEIN_FAST_TRAMPOLINE=1 lein trampoline run -m tmpname.core && date
Fri Jun 10 17:17:29 CEST 2022
2022-06-10T17:17:30.869038 INFO Starting
2022-06-10T17:17:30.894683 INFO Starting document planner
2022-06-10T17:17:30.957237 INFO Document plan created
2022-06-10T17:17:31.014918 INFO Text specification created
2022-06-10T17:17:31.086618 INFO Text generated
2022-06-10T17:17:31.086750 INFO Done
Fri Jun 10 17:18:30 CEST 2022
$
```
"Done" print out is the last command, after that it's just pure wait.

**Comment by jafingerhut** [comment]
@traut I do not know if Leiningen 2.9.8 has uses of `future` in it, but if your code does, either directly or indirectly, and you are not calling `(shutdown-agents)` when your code is done, then Leiningen cannot be expected to do that for you.  See this note about Clojure's `future`, including the part about other built-in Clojure functions that call `future` internally and thus cause the same behavior, for more details: https://clojuredocs.org/clojure.core/future#example-542692c9c026201cdc326a7b

**Comment by traut** [comment]
@jafingerhut thank you! `(shutdown-agents)` does indeed fixes the issue!

Interestingly enough, my code does not use `future` in any way and I haven't had a delay like that last time I worked on this codebase 2 years ago. My setup is a bit different now - macos Monterey on m1 chip and new versions of openjdk / leiningen, but project dependencies are pinned to old versions.

**Comment by jafingerhut** [comment]
I cannot get any `lein` commands to succeed without a compilation error with a `~/.lein/profiles.clj` file that contains `venantius/ultra` as a plugin.

If I remove that from my `~/.lein/profiles.clj`, then I cannot reproduce the 60-second delay that you are experiencing.

I am running on a macOS 11.6.6 system with these versions of JDK and Leiningen:
```
$ lein version
Leiningen 2.9.8 on Java 11.0.14.1 OpenJDK 64-Bit Server VM
```

**Comment by traut** [comment]
indeed, it's `venantius/ultra` -- the delay disappears if I remove it from the user profile. Thank you very much @jafingerhut!
