### ISSUE TITLE
Mitigating the impact of "lein X auto" antipattern

### ISSUE THREAD

**Issue by si14** [technomancy/leiningen#1752]
`lein X auto` is handy at first glance, but actually it is an antipattern, as [noted by Brandon Bloom](https://twitter.com/BrandonBloom/status/523207173632196608). One of problems with this approach is an exploding amount of memory consumed by 2-3 processes needed just to compile/reload things (think `lein figwheel` + `lein garden auto` + `lein hiccup watch`, and if Clojure server is needed, one more Clojure process).

Is is possible to implement something akin to `lein do` for blocking, auto-like lein tasks? I believe it will help a bit with the memory issue.

**Comment by arrdem** [comment]
While I personally find `lein auto cloverage` to be a huge part of my personal workflow these days, I agree with @brandonbloom. Supporting this pattern fully is going to require a dependency graph between tasks to be run and potentially time delays. Consider the case of wanting to run API client tests which depend on booting a server instance and waiting for it to come online before continuing and then tearing down the server instance when done.

```Clojure
{:user
 {:tasks
  {"integration"
   [["serve" "&"] ;; creates logical child "1" as in a *nix shell
    ["sleep" 5]   ;; stop, wait for boot
    ["cloverage"] ;; run cloverage alias/task
    ["kill"  1]   ;; kill the serve "job"
    ]}}}
```

Which would make `lein auto integration` "just work", but now we have near-full BASH implementation in lein just to escape booting some extra JVMs.

**Comment by technomancy** [comment]
I don't think this will ever be handled in Leiningen itself; let's leave it to 3rd-party plugins.
