### ISSUE TITLE
Leiningen throws Clojure error `Don't know how to create ISeq`

### ISSUE THREAD

**Issue by ilyador** [technomancy/leiningen#1756]
Running `lein` in terminal causes this:

    java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Keyword
     at clojure.lang.RT.seqFrom (RT.java:505)
       clojure.lang.RT.seq (RT.java:486)
       clojure.lang.RT.keys (RT.java:514)
       clojure.core$keys.invoke (core.clj:1482)
       leiningen.core.utils$map_vals.doInvoke (utils.clj:115)
       clojure.lang.RestFn.invoke (RestFn.java:442)
       leiningen.core.user/fn (user.clj:69)
       clojure.lang.AFn.applyToHelper (AFn.java:154)
       clojure.lang.AFn.applyTo (AFn.java:144)
       clojure.core$apply.invoke (core.clj:624)
       clojure.core$memoize$fn__5097.doInvoke (core.clj:5846)
       clojure.lang.RestFn.invoke (RestFn.java:408)
       leiningen.core.user/fn (user.clj:85)
       clojure.lang.AFn.applyToHelper (AFn.java:152)
       clojure.lang.AFn.applyTo (AFn.java:144)
       clojure.core$apply.invoke (core.clj:624)
       clojure.core$memoize$fn__5097.doInvoke (core.clj:5846)
       clojure.lang.RestFn.invoke (RestFn.java:397)
       leiningen.core.user$profile_auth.invoke (user.clj:169)
       leiningen.core.classpath$add_repo_auth.invoke (classpath.clj:97)
       clojure.core$map$fn__4245.invoke (core.clj:2557)
       clojure.lang.LazySeq.sval (LazySeq.java:40)
       clojure.lang.LazySeq.seq (LazySeq.java:49)
       clojure.lang.RT.seq (RT.java:484)
       clojure.core$seq.invoke (core.clj:133)
       clojure.core$map$fn__4245.invoke (core.clj:2551)
       clojure.lang.LazySeq.sval (LazySeq.java:40)
       clojure.lang.LazySeq.seq (LazySeq.java:49)
       clojure.lang.RT.seq (RT.java:484)
       clojure.core$seq.invoke (core.clj:133)
       clojure.core$map$fn__4245.invoke (core.clj:2551)
       clojure.lang.LazySeq.sval (LazySeq.java:40)
       clojure.lang.LazySeq.seq (LazySeq.java:49)
       clojure.lang.RT.seq (RT.java:484)
       clojure.lang.LazilyPersistentVector.create (LazilyPersistentVec       java:31)
       clojure.core$vec.invoke (core.clj:354)
       cemerick.pomegranate.aether$resolve_dependencies_STAR_.doInvoke (aet       clj:712)
       clojure.lang.RestFn.applyTo (RestFn.java:137)
       clojure.core$apply.invoke (core.clj:624)
       cemerick.pomegranate.aether$resolve_dependencies.doInvoke (aet       clj:729)
       clojure.lang.RestFn.invoke (RestFn.java:2088)
       leiningen.core.classpath/fn (classpath.clj:176)
       clojure.lang.AFn.applyToHelper (AFn.java:160)
       clojure.lang.AFn.applyTo (AFn.java:144)
       clojure.core$apply.invoke (core.clj:624)
       clojure.core$memoize$fn__5097.doInvoke (core.clj:5846)
       clojure.lang.RestFn.invoke (RestFn.java:436)
       leiningen.core.classpath$get_dependencies.doInvoke (classpath.clj:306)
       clojure.lang.RestFn.invoke (RestFn.java:425)
       clojure.lang.AFn.applyToHelper (AFn.java:156)
       clojure.lang.RestFn.applyTo (RestFn.java:132)
       clojure.core$apply.invoke (core.clj:628)
       leiningen.core.classpath$resolve_dependencies.doInvoke (classp       clj:350)
       clojure.lang.RestFn.invoke (RestFn.java:425)
       leiningen.core.classpath$get_classpath.invoke (classpath.clj:405)
       leiningen.core.project$init_lein_classpath.invoke (project.clj:869)
       leiningen.core.project$init_project.invoke (project.clj:876)
       leiningen.core.project$init_project.invoke (project.clj:883)
       leiningen.core.main$_main$fn__6136.invoke (main.clj:370)
       leiningen.core.main$_main.doInvoke (main.clj:366)
       clojure.lang.RestFn.invoke (RestFn.java:408)
       clojure.lang.Var.invoke (Var.java:379)
       clojure.lang.AFn.applyToHelper (AFn.java:154)
       clojure.lang.Var.applyTo (Var.java:700)
       clojure.core$apply.invoke (core.clj:624)
       clojure.main$main_opt.invoke (main.clj:315)
       clojure.main$main.doInvoke (main.clj:420)
       clojure.lang.RestFn.invoke (RestFn.java:436)
       clojure.lang.Var.invoke (Var.java:388)
       clojure.lang.AFn.applyToHelper (AFn.java:160)
       clojure.lang.Var.applyTo (Var.java:700)
       clojure.main.main (main.java:       

java 1.8_25
lein 2.5 (latest not --devel)
osx 10.10

**Comment by hyPiRion** [comment]
With the present information, there's not much we can do to help here. Feel free to reopen with the contents in `project.clj` and/or `~/.lein/profiles.clj`, there are presumably some errors in one of those.

**Comment by AlvarTheCoder** [comment]
I encounter this issue with the exact same environment with  @ilyador

**Comment by AlvarTheCoder** [comment]
I encounter this issue with the exact same environment with  @ilyador

**Comment by david-caro** [comment]
I have the same issue on fedora 23 when running lein if the *~/lein/project.cli* has the contents (as stated on the cider-nrepl page):

```clojure
:plugins [[cider/cider-nrepl "0.10.1"]]
```
using:
```shell
$ lein -v
Leiningen 2.5.3 on Java 1.8.0_65 OpenJDK 64-Bit Server VM
```
