### ISSUE TITLE
Breaking Changes from 2.2 to 2.5 in profile handling

### ISSUE THREAD

**Issue by mobiusinversion** [technomancy/leiningen#1757]
Hi there, 

It would be awesome to have a fast simple solution to this issue.  It may be as simple as modifying my project.clj.  Right now, I have a compilation model that works with lein 2.2.  For reason of proprietary information I need to conceal the actual values, but my deploy profile looks like this 

    {:deploy {:jvm-opts ^:replace ["-Xmx1g"] :aot ^:replace [some.namespace]}

How do I make this work in Lein 2.2?  The issue is also outlined here:

http://stackoverflow.com/questions/26787816/breaking-changes-from-leiningen-2-2-2-5

Help is greatly appreciated!

**Comment by mpasdziernik** [comment]
Any news on this issue?

**Comment by hyPiRion** [comment]
I'm pretty sure 2.5.3 has this covered if you prepend the profile with `^:leaky`, like this:

```clj
:profiles
  {:deploy ^:leaky {:jvm-opts ^:replace ["-Xmx1g"] :aot ^:replace [some.namespace]}}
```

**Comment by hyPiRion** [comment]
I'm guessing this is resolved by attaching `^:leaky` to profiles you'd like to include in your uberjar.

If that's not the case, feel free to reopen. (Would also like a minimal reproducible test case too if possible)
