### ISSUE TITLE
Please promote fixed lein.bat of 2 months ago to 'stable' asap, so version on website, and pulled by Windows installer, have chance of working

### ISSUE THREAD

**Issue by Andrew-Webb** [technomancy/leiningen#1773]
Please promote https://github.com/technomancy/leiningen/blob/master/bin/lein.bat (fixed 2 months ago to detect wget, curl, PowerShell correctly) to https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat (+ whatever other files are needed) so that:-

* the version linked-to on your website might work
* the version pulled by the Windows installer might work (currently broken for me).

Once this is done, I'll re-try using the Win installer.  Thanks.

**Comment by technomancy** [comment]
Released 2.5.1.

**Comment by rtoip** [comment]
:+1:
