### ISSUE TITLE
lein sometimes builds invalid jar (or some other weird thing happening)

### ISSUE THREAD

**Issue by acthp** [technomancy/leiningen#1778]
pack200 barfs on some uberjars built by lein, throwing a "non-empty directory" exception. I haven't been able to isolate the underlying cause.

Steps to reproduce:
1. create new app project
2. add dependencies [com.h2database/h2 "1.3.175"] [com.fasterxml.jackson.core/jackson-core "2.3.1"]
3. build uberjar
4. run pack200 on uberjar

Results:
- Throws on Leiningen 2.5.0 on Java 1.7.0_51 OpenJDK 64-Bit Server VM
- Works on Leiningen 2.5.0 on Java 1.6.0_33 OpenJDK 64-Bit Server VM

In the failing case, the uberjar built by lein has this entry (shown with unzip -lv) which seems to be the problem:

```
       1  Defl:N        3 -200% 12-04-2014 09:27 32d70693  META-INF/services/
```

**Comment by hyPiRion** [comment]
I'm unable to reproduce this. Steps I used for the reproduction attempt:

```shell
lein new app foobar
# edit project.clj as described below
lein-master uberjar
pack200 packed.gz target/uberjar/foobar-0.1.0-SNAPSHOT-standalone.jar
# no errors emitted
```

Edited project.clj so it looked like this:
```clj
(defproject foobar "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [com.h2database/h2 "1.3.175"]
                 [com.fasterxml.jackson.core/jackson-core "2.3.1"]]
  :main ^:skip-aot foobar.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

Tried with master on following java versions:
- Java 1.8.0_66-internal OpenJDK 64-Bit Server VM
- Java 1.7.0_79 OpenJDK 64-Bit Server VM
- Java 1.6.0_31 OpenJDK 64-Bit Server VM

`pack200 --version` emits `com.sun.java.util.jar.pack.Driver version 1.31, 07/05/05`

**Comment by glts** [comment]
I cannot reproduce this with Leiningen 2.9.1 and Java 8, though I do get a lot of warnings – I doubt that these are related to Leiningen though.

Anyway, pack200 is deprecated since Java 11 and will be removed. I don’t think there is anything more we can do here.
