### ISSUE TITLE
New default value for :pedantic? in 2.5 breaks dependency memoization

### ISSUE THREAD

**Issue by jcrossley3** [technomancy/leiningen#1781]
In 2.4, the default for `:pedantic?` was nil, but in 2.5 it's `'ranges`. This results in a new function created for the `:repository-session-fn` option every time `classpath/get-dependencies` is invoked, effectively rendering `get-dependencies-memoized` severely misnamed.

Without the memoization, there can be a noticeable performance degradation when building certain projects.

**Comment by technomancy** [comment]
Thanks for catching this! Should make a big difference.
