### ISSUE TITLE
Failed artifact retrieval due to "Cookie rejected"

### ISSUE THREAD

**Issue by guv** [technomancy/leiningen#1796]
Consider the following project.clj.

``` clojure
(defproject gephi-demo "0.1.0-SNAPSHOT"
    :repositories [["Gephi Snapshots" "http://nexus.gephi.org/nexus/content/repositories/snapshots/"]
                          ["Gephi Releases" "http://nexus.gephi.org/nexus/content/repositories/releases/"]]
    :dependencies [[org.clojure/clojure "1.6.0"]
                   [org.gephi/gephi-toolkit "0.9-SNAPSHOT"]])
```

When retrieving dependencies there are a lot of errors of the form:

> Retrieving org/gephi/gephi-toolkit/0.9-SNAPSHOT/gephi-toolkit-0.9-20141206.190305-607.pom from Gephi Snapshots
> Jan 12, 2015 1:43:26 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies WARNING: Cookie rejected [rememberMe="deleteMe", version:0, domain:bits.netbeans.org, path:/nexus, expiry:Mon Jan 12 13:43:26 CET 2015] Illegal path attribute "/nexus". Path of origin: "/maven2/org/netbeans/modules/org-netbeans-modules-masterfs/RELEASE721/org-netbeans-modules-masterfs-RELEASE721.pom"

This results in leiningen not being able to retrieve the dependencies:

> org.sonatype.aether.resolution.DependencyResolutionException: Failed to collect dependencies

**Comment by guv** [comment]
There is an issue on the gephi tracker as well now.
https://github.com/gephi/gephi-toolkit/issues/11

**Comment by hyPiRion** [comment]
This seems to be either a problem with Aether or an issue with their nexus repo, considering Maven also barfs out on the same dependency.

**Comment by hemingwang0902** [comment]
If you are using a reverse proxy and you have different context paths on either side of it you'll need to map cookies as well.

For **Apache** you can use: *`ProxyPassReverseCookiePath /nexus /`*

For **Nexus** you can use: *`proxy_cookie_path /nexus /;`*

also, you can see: https://stackoverflow.com/questions/25755111/mule-esb-maven-build-fails-on-nexus-path-when-trying-to-deploy-mule-project-to/29136201#29136201

**Comment by glts** [comment]
In the meantime those Nexus repositories have vanished. Given that and the fact that the upstream issue was closed without resolution, I don’t know what more we can do here.

**Comment by technomancy** [comment]
We'll close it out; if more details surface we can reopen.
