### ISSUE TITLE
Can't talk to local nexus

### ISSUE THREAD

**Issue by expez** [technomancy/leiningen#1797]
When I enable `$debug` i get the following in console:

```
CLASSPATH=C:\Users\g014984\.lein\self-installs\leiningen-2.5.0-standalone.jar
jan 12, 2015 2:55:39 PM org.apache.http.impl.client.DefaultHttpClient tryExecute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:5865->http://mvn: The target server failed to respond
```

``` clj
(defproject project "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [no.gjensidige.web.ip.core "1.2.6"]]
  :mirrors {"central" {:name "Nexus"
                       :url "http://mvn/nexus/content/groups/public"
                       :repo-manager true}})
```

I'm behind a proxy, talking to a local nexus instance, on a windows machine (this couldn't get much worse :frowning:).

**Comment by hyPiRion** [comment]
I'm guessing this is the case, but for safety's sake, the local Nexus instance is listening on port 5865? If that's the case, setting the environment variable `http_no_proxy` to something like `localhost|mvn` as specified [in the FAQ](https://github.com/technomancy/leiningen/blob/9750d8e4b2a25d1c91bbe643f2d244a6cb2e1e7c/doc/FAQ.md) should be sufficient, I think.

**Comment by expez** [comment]
`http_no_proxy` seems like the right thing.  I'll reopen if that doesn't work out.  Thanks!

**Comment by expez** [comment]
`http_no_proxy` had no effect on this situation:

```
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:5865->http://mvn: The target server failed to respond
```

So `http://127.0.0.1:5865` is to get traffic to through an NTLM proxy when talking to the outside world, but the nexus instance I'm trying to talk to is inside the corporate network so going trough the proxy will cause the request to fail.  

Thus, after setting `http_no_proxy` I would expect that `http://127.0.0.1:5865` not show up at all.  Furthermore, the second part of `http://127.0.0.1:5865->http://mvn` looks a bit suspicious, shouldn't this be `http://127.0.0.1:5865->http://mvn/nexus/content/groups/public`? 

Any other ideas?  This is pretty hard to debug :frown:

I tried to see if I might get leiningen up and running so I could instrument some of the underlying functions, but I just get this:

```
>lein repl
Compilation failed: key can't be null
```

I hate windows so much lol

**Comment by hyPiRion** [comment]
I'm unsure about this being a problem with Windows, might be an issue with either how Leiningen (or some upstream dependency) handles the proxying. Or some subtle issue with how the configuration is set up. I tried to climb the dependency tree to find out if there are any obvious issues, but couldn't see any right now.

I'll have a look at it later when I have more time, probably along with a deeper inspection when I'm fixing #1746 as they may be tangentially connected.

If you're trying to "build" leiningen from master, see https://github.com/technomancy/leiningen/blob/master/CONTRIBUTING.md#bootstrapping. Essentially, the steps are (from the lein directory):

```bash
cd leiningen-core
lein bootstrap
cd ..
bin/lein compile
## Or the equivalent for Windows with bin/lein.bat used instead
```

Then putting the bin/lein version on your path.

**Comment by technomancy** [comment]
Without a repro case this does not seem actionable. I'm open to reopening if it does become actionable.
