### ISSUE TITLE
On the default value of :auto-clean

### ISSUE THREAD

**Issue by herberteuler** [technomancy/leiningen#1798]
Hello,

In the new version of leiningen, :auto-clean of a project is set to true by default.  I understand that cleaning before compiling is important for deploying build, but it might not be that good during development, especially when compiling the whole file set takes more than just a few seconds.

I am not sure why it is changed to true by default.  Is this intended?  Thanks.

Sincerely yours,
Guanpeng Xu

**Comment by hyPiRion** [comment]
The `:auto-clean` option is only checked when running the jar task (and, indirectly, uberjar, install and deploy). As far as I know, doing any of these tasks during production is quite rare.

See #1642 for more information about the rationale.

**Comment by herberteuler** [comment]
Yes that makes perfect sense.  And I just figured that my work flow needed to be fixed, which was not idiomatic.  Thank you.
