### ISSUE TITLE
Option to not sign git tags

### ISSUE THREAD

**Issue by delitescere** [technomancy/leiningen#1799]
Many projects like to sign tags (including this one itself). Many more others do not.

There has been previous discussion (http://www.raynes.me/logs/irc.freenode.net/leiningen/2014-09-03.txt) as to why the leiningen source code repository has signed tags, and those points are undisputed.

Other projects do not require tag signing. Even open-source projects with broad contribution may not desire tag signing and use a different mechanism to "sign off" contributions (cf. http://mikegerwitz.com/papers/git-horror-story).

Whatever the case, the user should have the option to either sign or not sign tags. Given the leiningen team sign by default, it may be the option is to turn off signing (even though that is the inverse of git defaults). It would be preferred if the option was set using the existing 'profiles' mechanisms (e.g. `:vcs-options {:tag-sign false}`). Preferably, the `lein vcs tag` should also take a flag to turn off signing that overrides the profile merging (e.g. `lein vcs tag --unsigned|-u`.

Given the limited degrees of freedom of `lein vcs tag` implies so-called "lightweight tags" in git (that is, `git tag` with no options).

**Comment by grahamlyons** [comment]
I'd also like this feature. I've never worked on a project before that signs git tags so having signing on by default doesn't work for me and my team.

I'd prefer to have signing off as the default but the option to turn it off would be great.

**Comment by technomancy** [comment]
If you'd like to see it implemented, the best way is to take a crack at writing it. However, the default must stay as it is. I like the description of the config and CLI options given in the issue description but am open to suggestions for alternatives.

**Comment by nberger** [comment]
Because I needed this, I implemented it as a lein plugin: https://github.com/nberger/lein-tag-no-sign

The README explains how to use it, including an example of how to override the default `release-tasks`. Hope it helps.
