### ISSUE TITLE
new and dot hgignore

### ISSUE THREAD

**Issue by zoowar** [technomancy/leiningen#1815]
It was nice to see support for dot hgignore added, but some of the rules are wrong. For example "/.lein-*" should be ".lein-*". Also, some should be rooted to avoid pruning subdirectories and files. For example, "target/**" should be in a "regexp" syntax section as "^target/".

> Neither  glob  nor regexp patterns are rooted. A glob-syntax pattern of
       the form *.c will match a file ending in .c in  any  directory,  and  a
       regexp pattern of the form \.c$ will do the same. To root a regexp pat‐
       tern, start it with ^.

Also, it would be nice to see some emacs support, for example

    syntax: glob
    *~				# emacs backup files

    syntax: regexp
    \.\#.*			# emacs cache files
    \#.*\#			# emacs autosave files

**Comment by technomancy** [comment]
Sure thing; submit a pull request and we can get that merged.
