### ISSUE TITLE
uberjar task logs about duplicate resources (2.5.1)

### ISSUE THREAD

**Issue by metametadata** [technomancy/leiningen#1824]
Using https://github.com/yogthos/edn-config I have different resource folders with config files for :dev and :uberjar profiles. I get "Warning: skipped duplicate file: config.edn" on lein uberjar.

Issue seems to be reproducible in 2.5.1, but not in 2.5.0.

**Steps:**
1) Create new project:
```
lein new app foobar
```
2) In the project root create a folder with a single file:
```
├── my-resources
│   └── baz.txt
```
3) Edit project.clj file so that it includes the new folder as a resource if uberjar profile is used:
```
(defproject foobar "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.6.0"]]
  :main ^:skip-aot foobar.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all
                               :resource-paths ["my-resources"]}})
```
4) Run uberjar task:
```
lein uberjar
```

**Actual:**
```
Compiling foobar.core
Warning: skipped duplicate file: baz.txt
Created /home/yuri/dev/foobar/target/uberjar+uberjar/foobar-0.1.0-SNAPSHOT.jar
Created /home/yuri/dev/foobar/target/uberjar/foobar-0.1.0-SNAPSHOT-standalone.jar
```

**Expected:** no warning about duplicate resource file.

**Comment by csdrane** [comment]
I wasn't able to reproduce this.

```
clojure $ lein new app temp
Generating a project called temp based on the 'app' template.
clojure $ cd temp
temp $ mkdir my-resources
temp $ touch my-resources/baz.txt
temp $ vim project.clj
temp $ lein uberjar
Compiling temp.core
Created /Users/chris/Programming/clojure/temp/target/uberjar/temp-0.1.0-SNAPSHOT.jar
Created /Users/chris/Programming/clojure/temp/target/uberjar/temp-0.1.0-SNAPSHOT-standalone.jar
temp $ 
```

**Comment by hyPiRion** [comment]
This is probably related to #2001: We may expand a single profile twice, causing `:resource-paths` et al to contain multiple entries of resources. Solving #2001 should also solve this one.
