### ISSUE TITLE
All meta data is lost on with-profiles merge for :clean-targets.

### ISSUE THREAD

**Issue by ibothwell** [technomancy/leiningen#1826]
It appears that during the with-profiles merge :clean-targets the ^{:protect false} meta-data is lost.

**Step 1: Create a new project**

```
lein new meta-project
```

**Step 2: Create a profiles.clj file with the following**

```
{:shared {:clean-targets ^{:protect false} ["resources/a.txt"]}
 :prod [:shared {:clean-targets ^{:protect false} ["resources/b.txt"]}]}
```

**Step 3: make the resources**
The following are just to make it easy to illustrate the point, which is to add a non-targets directory entity which must be cleaned on `lein with-profile prod clean`

```
> mkdir resources
> touch resources/a.txt
> touch resources/b.txt
```

**Step 4: Run lein clean**

```
lein with-profile prod clean
```

**Result**
Taking the steps outlined above the result spews out a complaint:

```
$ lein with-profile prod clean
Deleting non-target project paths ["resources/a.txt%s"] is not allowed.
Check :clean-targets or override this behavior by adding metadata ->
  :clean-targets ^{:protect false} [...targets...]
Error encountered performing task 'clean' with profile(s): 'prod'
Deleting non-target project paths ["resources/a.txt%s"] is not allowed.
Check :clean-targets or override this behavior by adding metadata ->
  :clean-targets ^{:protect false} [...targets...]
```

**Environment**

```
$ lein version
Leiningen 2.5.1 on Java 1.8.0_20 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by trimtab613** [comment]
vote

**Comment by jwhitlark** [comment]
The following seems to perform as intended.  Not sure if it's actually a bug or expected behavior.

    :clean-targets ^{:protect false :replace true}

**Comment by ai212983** [comment]
Just a note for the comment above. 

It works as intended by the docs - replacing clean-targets in main profile with new clean-targets from `profiles.clj`, not merging them, as OP wanted.
