### ISSUE TITLE
CONTRIBUTING needs clarification

### ISSUE THREAD

**Issue by winks** [technomancy/leiningen#1828]
I am talking about this paragraph:

```
## Bootstrapping

You don't need to "build" Leiningen per se, but when you're developing on a
checkout you will need to get its dependencies in place. Just use a stable
release of Leiningen to run `lein bootstrap` (an alias for `lein do install,
classpath .lein-bootstrap`) in the `leiningen-core` directory. If you want to
use or develop the `search` functionality on master, you also have to run `lein
compile` in the root (`leiningen`) directory.
```

First of all, apparently the 'If you want to
use or develop the `search` functionality' seems overly specific, don't you need this any time you're rebuilding master for an updated dependency or anything *not* in `leiningen-core`?

Second, I needed to run `./bin/lein compile` instead of my stable release one mentioned in the first sentence (and @hyPiRion also said that).

Third, is there a reason why `lein uberjar` is not included as well? That's howI just built it, then used it for testing.

In general, a paragraph of text is good and all, but wouldn't a TLDR section with code (below the detailed explanation) maybe help for those cases? Or am I alone with this problem?

I'm sorry that I can't just fix it but need feedback, but I come back to this every few months and it's complicated enough that I need to look up the order and also don't know enough to just change it :)

**Comment by hyPiRion** [comment]
Yeah, I agree that the documentation needs to be improved somewhat. I'll see what I can do later today.

**Comment by hyPiRion** [comment]
@winks, is it easier to know what to do re commands and uberjar now? I believe I have covered all steps needed to get lein up and running, with the exception of symlinking onto the path.

**Comment by winks** [comment]
Awesome, thanks, exactly what I had imagined and my understanding didn't even seem to be wrong :)

:+1:
