### ISSUE TITLE
tools.nrepl 0.2.7 for gooder middleware orderings

### ISSUE THREAD

**Issue by gfredericks** [technomancy/leiningen#1829]
Looks like `lein repl` still defaults to using tools.nrepl 0.2.6, which is subject to [NREPL-53](http://dev.clojure.org/jira/browse/NREPL-53). I don't know how these changes are tested/vetted or whatever, but wanted to mention that 0.2.7 is out now.

**Comment by hyPiRion** [comment]
Gooder middleware is now available on master.
