### ISSUE TITLE
uberjar does not resolve from profile-vector

### ISSUE THREAD

**Issue by chrisbetz** [technomancy/leiningen#1833]
Hi,

I got something like

``` clj
:profiles {:a {:dependencies [[a "1"]]}
               :b {:dependencies [[b "1"]]}
               :uberjar [:a :b]
}
```

This does not resolve correctly (classes from a and b are missing while compling my project in uberjar).

It does work if i reference the dependencies in uberjar profile directly.

**Comment by hyPiRion** [comment]
Hi,

Does this work if you make `:a` and `:b` leaky? like so 

```
:profiles {:a  ^:leaky {:dependencies [[a "1"]]}
               :b ^:leaky {:dependencies [[b "1"]]}
               :uberjar [:a :b]
}
```

**Comment by chrisbetz** [comment]
Hi,

thanks for the tip, leaky does the trick, so I'm fine for now.

However, as other tasks (like lein classpath or lein deps :tree) are working correctly without the profiles being leaky, I would suggest changing the behaviour of lein uberjar here, as it's inconsistent.

Cheers,

Chris

**Comment by hyPiRion** [comment]
Yeah, I agree that the current functionality is a bit counter-intuitive.

**Comment by glts** [comment]
In Leiningen 2.9.1, `uberjar` does seem to pick up these dependencies. With a minimal project.clj,

```clojure
(defproject repro "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.10.0"]]
  :profiles {:a {:dependencies [[clj-time "0.15.0"]]}
             :b {:dependencies [[http-kit "2.3.0"]]}
             :uberjar [:a :b]})
```

everything (clj-time, http-kit, Clojure, plus transitive deps) gets packaged into the uberjar, no `^:leaky` annotation necessary.

Suppose this got fixed somewhere along the way, else we need more info on the repro.
