### ISSUE TITLE
How to run in parallel and show both outputs?

### ISSUE THREAD

**Issue by binarykitchen** [technomancy/leiningen#1843]
Hello there

I would like to have lein run while Gulp is building / watching in parallel:

```
  :aliases
  {
    "dev"   ["do" ["shell" "gulp" "default:watch"] "run"]
  }
```

but this won't work because tasks are chained. Both are endless. How can I fix this?

Is there something else than the keyword "do"? How about "parallel" or something like that?

**Comment by hyPiRion** [comment]
There's [lein-pdo](https://github.com/Raynes/lein-pdo) which is like do, but run tasks in parallel.

**Comment by binarykitchen** [comment]
Ah, wonderful, thanks!
