### ISSUE TITLE
git implementation of leiningen.vcs/push indiscriminately pushes tags

### ISSUE THREAD

**Issue by waynr** [technomancy/leiningen#1846]
https://github.com/technomancy/leiningen/blob/master/src/leiningen/vcs.clj#L56

This is particularly problematic in CI contexts where a CI system may create CI-specific tags for use within CI "pipelines".

**Comment by waynr** [comment]
Just to be clear, in my opinion `leiningen.vcs/push` should only be pushing the tag it explicitly creates if possible.

**Comment by hyPiRion** [comment]
Yeah, I agree – no need to push all the tags you have locally. Happy to take a patch for this.

**Comment by johnwalker** [comment]
I suspect that this can be fixed by swapping git push --tags for git push --follow-tags.

**Comment by kleewho** [comment]
Now I remember why I don't like mentioning issues in commit messages
