### ISSUE TITLE
`lein deps :verify` not functioning properly due to locale issues

### ISSUE THREAD

**Issue by solicode** [technomancy/leiningen#1855]
I ran into an issue where running `lein deps :verify` was returning `bad-signature` for everything even though they were actually signed.

I eventually found the cause. gpg outputs localized messages (mine is outputting Japanese), but the checks that Leiningen is doing is assuming English [here](https://github.com/technomancy/leiningen/blob/14379a7305cb9d99eab9f63fba0ee8769b90280c/src/leiningen/deps.clj#L31-L33).

gpg looks at environment variables to determine the language. By setting the `LANGUAGE` variable to `en`, I was able to get around this issue.

I don't know how you'd like to go about solving this problem in Leiningen itself, but something like this should be fine, right?

```clojure
(shell/sh "gpg" args :env {:LANGUAGE "en"})
```

**Comment by hyPiRion** [comment]
Hi there, 

Yeah, that should be more or less correct. It just needs to be appended to the [`gpg`](https://github.com/technomancy/leiningen/blob/00e158f6f39614ce10e3d7659c399e00e41c0c7d/leiningen-core/src/leiningen/core/user.clj#L93-L99) function in `leiningen.core.user`. (Or use `shell/with-sh-env` if that seems more readable)

Do you want to do a pull request yourself to solve the issue? (I'm fine fixing it myself too, just wondering.)

**Comment by solicode** [comment]
Sure, no problem. I submitted the PR. And yeah, `shell/with-sh-env` looked cleaner.

**Comment by hyPiRion** [comment]
Closed by #1864.
