### ISSUE TITLE
Return non zero status when :pedantic? is set to true

### ISSUE THREAD

**Issue by timterry** [technomancy/leiningen#1856]
Could a non zero status be returned when pedantic is enabled  (:pedantic? true in project.clj) and lein deps :tree is executed when there are conflicting dep versions? This would make it much easier to integrate into a CI tool such as teamcity. Currently a zero status is returned what ever the result.

**Comment by pietromenna** [comment]
@timterry , try using :pedantic :abort in project.clj. This makes that in case of conflicting deep versions the return code is 1 due to (main/abort).

**Comment by hyPiRion** [comment]
I'd be happy to take a patch that makes `:pedantic? true` the same as `:pedantic? :abort`.
