### ISSUE TITLE
lein jar packs also dependencies when :aot is used

### ISSUE THREAD

**Issue by martinhynar** [technomancy/leiningen#1858]
On simple lein-based project with single dependency, running `lein jar` results in a jar that contains also compiled dependencies.

**Project structure (named `aot`):**
+ `project.clj`

```
(defproject
  aot "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.5.0"]
                 [com.cemerick/url "0.1.1"]]
  :aot [core])
```

+ `core.clj` - only source in project

```
(ns core
  (:require [cemerick.url :as u]))
```

After `lein jar` I get archive that contains also compiled dependencies (shortened)
```
unzip -l target/aot-0.1.0-SNAPSHOT.jar
Archive:  target/aot-0.1.0-SNAPSHOT.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
      119  03-17-2015 16:57   META-INF/MANIFEST.MF
     1733  03-17-2015 16:57   META-INF/maven/aot/aot/pom.xml
      145  03-17-2015 16:57   META-INF/leiningen/aot/aot/project.clj
      145  03-17-2015 16:57   project.clj
      229  03-17-2015 16:57   META-INF/leiningen/aot/aot/README.md
    11218  03-17-2015 16:57   META-INF/leiningen/aot/aot/LICENSE
        0  03-17-2015 16:57   cemerick/
     2055  03-17-2015 16:57   cemerick/url$port_str.class
     2291  03-17-2015 16:57   cemerick/url$loading__4920__auto__.class
     3577  03-17-2015 16:57   cemerick/url$fn__90.class
     1313  03-17-2015 16:57   cemerick/url$fn__67.class
        0  03-17-2015 16:57   cemerick/url/
--- cut ---
     1466  03-17-2015 16:57   core__init.class
     1293  03-17-2015 16:57   core$fn__134.class
     1819  03-17-2015 16:57   core$loading__4920__auto__.class
       44  03-17-2015 16:56   core.clj
```

As far as I understand, e.g. explanation in [Clojure Cookbook](https://github.com/clojure-cookbook/clojure-cookbook/blob/master/08_deployment-and-distribution/8-02_creating-executable-jar/8-02_creating-executable-jar.asciidoc#packaging-jars-without-their-dependencies), `lein jar` shall not pack those deps. I am not really sure how `:aot` changes the game rules, but I haven't found any description of it.

I found this behavior on `Leiningen 2.5.1 on Java 1.8.0_31 OpenJDK 64-Bit Server VM` and tried with the same result also on `2.5.0` and `2.4.3`.

**Comment by hyPiRion** [comment]
If AOT-compiled namespaces depend on other namespaces, they too have to compiled. And since most libraries out there doesn't ship with AOT-compiled namespaces, they have to be included in the jar itself.

If you, for instance, aot-compiled cemerick.url, all the non-AOT-compiled dependencies to cemerick.url would be included in the library jar. If you now depend and use cemerick.url in another AOT-compiled library (like yours), then the namespaces are already compiled in the lib and they are not included in the generated jar.

I agree that it could be convenient to specify that somewhere. I'm not entirely sure where though.

**Comment by martinhynar** [comment]
Thanks, this makes sense. If I was able to find issue like this, I would know what to expect on my lib.

**Comment by hyPiRion** [comment]
@martinhynar: I added a short explanation in the FAQ just now. In addition, this issue will be searchable, and I see you're going to add a paragraph in the Clojure Cookbook on it. Do you think this is sufficient?

**Comment by martinhynar** [comment]
@hyPiRion Yes, that works for me just fine.

**Comment by hyPiRion** [comment]
Alright, then I'll consider this one fixed.
