### ISSUE TITLE
lein test eats top level exceptions

### ISSUE THREAD

**Issue by SavageMessiah** [technomancy/leiningen#1859]
If a clojure.lang.ExceptionInfo makes it to the top level of lein test it just outputs "Tests failed." instead of printing a stacktrace or anything useful.

I'm currently running into an issue where lein test terminates with that message (and nothing else) consistently and I have no way to determine the reason for the failure except by deploying a custom build of leiningen to our CI server.

**Comment by SavageMessiah** [comment]
In particular it appears (after a somewhat cursory examination, admittedly) that if the subprocess returns a positive error code for whatever reason that fact can be swallowed up by leiningen. This is because the exception reporting subprocess failure is thrown using ex-info and https://github.com/technomancy/leiningen/blob/master/src/leiningen/test.clj#L199 
catches that and prints... nothing useful.

Everything is working for me again but improving the output in this case might save someone else some frustration in the future.

**Comment by jimbreen** [comment]
The fix for this issue (0b37859) was included in 2.9.9 and 2.9.10, but is [missing from 2.10.0](https://github.com/technomancy/leiningen/blob/2.10.0/src/leiningen/test.clj#L253-L258).
