### ISSUE TITLE
lein pom is not using :name from profile

### ISSUE THREAD

**Issue by Verneri** [technomancy/leiningen#1863]
I'm using: `Leiningen 2.5.0 on Java 1.7.0_45 Java HotSpot(TM) 64-Bit Server VM`

I have a profile that changes the name of the project

```clojure
(defproject project-name
...
:profiles {:a-profile {:name "another-name"}}
...)
```

it shows correctly on `lein with-profile +a-profile pretty-print`:
```clojure
{
...
:name "another-name",
...
}
```

and the generated jar has the correct name: another-name-VERSION.jar

but the generated pom from both `lein with-profile +a-profile pom` and `lein with-profile a-profile pom` is like this:
```xml
<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>project-name</groupId>
  <artifactId>project-name</artifactId>
  <packaging>jar</packaging>
  <version>VERSION</version>
  <name>project-name</name>
...
</project>
```

what is causing this?

Now I know I can separate the profile specific code to another project and just use dependencies, but i'd rather keep all the code in the same place.

**Comment by Verneri** [comment]
Just noticed the `^:leaky`metadata needed for this. So now it seems to work

**Comment by hyPiRion** [comment]
Alright, I'll close this then as I assume you got this figured out.
