### ISSUE TITLE
lein.bat does not propagate execution errors

### ISSUE THREAD

**Issue by gotvino** [technomancy/leiningen#1865]
You need to save %errorlevel% after calling java.exe and then use it after EOF (e.g. exit /b %errorlevel%) so you propagate errors out of the script.

**Comment by hyPiRion** [comment]
Would be happy to take a patch for this.

**Comment by winks** [comment]
That's already there, just in the wrong line? https://github.com/technomancy/leiningen/blob/master/bin/lein.bat#L398

Also,
http://blogs.msdn.com/b/oldnewthing/archive/2008/09/26/8965755.aspx

Gonna try to have a look at this.
