### ISSUE TITLE
Handling downstream pom packaged dependencies

### ISSUE THREAD

**Issue by AlBaker** [technomancy/leiningen#1866]
After applying the resolution to #1451 I still see that lein can fail on subsequent downstream dependencies that themselves may be pom packaged.  This doesn't hold true for other build tools that seem to handle it.  Overall, having to track down all downstream dependencies and root out the pom packages is not ideal for end users.

Here is an example from [stardog-clj](http://github.com/Complexible/stardog-clj)

Ideal project.clj

``` clojure
(defproject stardog-clj "3.0.0"
  :description "Stardog-clj: Clojure bindings for Stardog"
  :url "http://stardog.com"
  :license {:name "Apache License"
            :url "http://www.apache.org/licenses/LICENSE-2.0"}
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [com.complexible.stardog/client-http "3.0" :extension "pom"]  
        ]
  :repositories [["stardog" "http://maven.stardog.com"]]
  :plugins [[jonase/eastwood "0.0.2"]
            [lein-midje "3.1.3"]]
  :profiles {:dev {:dependencies [[midje "1.6.3"]]
                  :plugins [[lein-midje "3.1.3"]]}} )
```

This has a dependency down the chain to sesame, so you need to add back in:

``` clojure
(defproject stardog-clj "3.0.0"
  :description "Stardog-clj: Clojure bindings for Stardog"
  :url "http://stardog.com"
  :license {:name "Apache License"
            :url "http://www.apache.org/licenses/LICENSE-2.0"}
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [com.complexible.stardog/client-http "3.0" :extension "pom"]
                 [org.openrdf.sesame/sesame "2.7.14"]
                  ; ^^ have to add this back in to cover lein dependency resolution
        ]
  :repositories [["stardog" "http://maven.stardog.com"]]
  :plugins [[jonase/eastwood "0.0.2"]
            [lein-midje "3.1.3"]]
  :profiles {:dev {:dependencies [[midje "1.6.3"]]
                  :plugins [[lein-midje "3.1.3"]]}} )
```

**Comment by hyPiRion** [comment]
I'll label this as a bug although I'm not sure whether it technically is or not. This certainly needs some verification with how Maven and Aether works and how they are supposed to work.

**Comment by glts** [comment]
Going through the backlog … unless I misunderstand, this is no longer reproducible with Leiningen 2.9.1. With the first project.clj, `[org.openrdf.sesame/sesame "2.7.14"]` is resolved just fine, there is no need to specify it explicitly. Otherwise more detailed repro is appreciated.
