### ISSUE TITLE
lein test skips uncompilable test file

### ISSUE THREAD

**Issue by Satshabad** [technomancy/leiningen#1867]
I have a test file where the code is non-valid clojure code. Like so:

    ...
                [clojure.tools.logging :as log])
    >>>>>>> master
      (:import [com.google.common.io ByteStreams]))
    
    (deftest test-foo
    ...

This happened by accident after fixing some merge conflicts.

Anyway, when I run lein test, it just skips this test file completely without warning or error.

Is this the expected behavior?

**Comment by hyPiRion** [comment]
I am unable to reproduce this: `lein new foo`, then making either `src/foo/core.clj` or `test/foo/core_test.clj` uncompilable errors out when running `lein test`. Could you provide a minimal reproducible example?

**Comment by Satshabad** [comment]
Steps to reproduce:

    lein new foo

then

    vim test/foo/core_test.clj

paste:

    (ns com.climate.foo.server-test
      (:require [clojure.test :refer :all]
                [com.example :refer [foo
    <<<<<<< HEAD
                                                         bar]])
    =======
                                                         baz]]
                [clojure.tools.logging :as log])
    >>>>>>> master
      (:import [com.google.common.io ByteStreams]))

    (deftest a-test
      (testing "FIXME, I fail."
        (is (= 0 1))))

then

    lein test

then I see:

    -> % lein test

    lein test user

    Ran 0 tests containing 0 assertions.
    0 failures, 0 errors.

**Comment by hyPiRion** [comment]
That specific incantation fails with

```
java.lang.RuntimeException: Unmatched delimiter: ]
[stacktrace]
```

here. I am guessing you're running on an older version, so could you try to do `lein upgrade`? If it still fails after that, could you send the result of `lein version`?

**Comment by Satshabad** [comment]
You are indeed right.

Before I had 2.3.4, and after upgrading it worked fine. Thanks!
