### ISSUE TITLE
Cannot upgrade lein, because of certificate error.

### ISSUE THREAD

**Issue by GHExplorer** [technomancy/leiningen#1869]
On Windows 8.1, after trying 

   lein upgrade

, the returned error is

o you want to continue (Y/N)?y
Downloading latest Leiningen batch script...
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2015-03-29 16:33:25--  https://github.com/technomancy/leiningen/raw/stable/bin/lein.bat
Resolving github.com... 192.30.252.128
Connecting to github.com|192.30.252.128|:443... connected.
ERROR: cannot verify github.com's certificate, issued by `/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA':
  Unable to locally verify the issuer's authority.
To connect to github.com insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.
Failed to download https://github.com/technomancy/leiningen/raw/stable/bin/lein.bat

If I change the wget call in lein.bat to include the '--no-check-certificate', the upgrade process modifies the lein.bat, and removes the clause.

The lein tools are working fine as is, but it looks like it's not possible to upgrade, in the normal fashion.

**Comment by schodge** [comment]
I'm also having this problem

**Comment by shakna-israel** [comment]
I can't even use ```self-install``` to get it running before upgrade because of this same issue.

**Comment by hiredgunhouse** [comment]
Me too.
It is impossible to install lein without hacking the batch file, here's how: https://gist.github.com/286b39f910c4e5d4b5b5.git

Basically, Powershell should probably be the preffered method of downloading files via HTTP for Windows

**Comment by hyPiRion** [comment]
This is fixed on master by #1831, which will be out when 2.5.2 is out. See #1800 for the discussion on this issue.
