### ISSUE TITLE
low CPU usage during CPU-intensive tasks

### ISSUE THREAD

**Issue by martinraison** [technomancy/leiningen#1871]
When running for example `lein uberjar` on a significant codebase, the operation can take a very long time. However, the CPU usage remains quite low on average during the operation. On my machine I can see phases where CPU usage is around 20%, even longer phases where it is almost 0%, with very occasional spikes above 100% lasting about 1 second. It seems that this kind of operation should be CPU-intensive so I was expecting to see something closer to 100% all the time - or even much more if parallelism is used. Any clues as to why this could be the case?

**Comment by hyPiRion** [comment]
I haven't done any research on this, but I recall people complaining about longer runtimes on Windows compared to linux/mac. That was a long time ago though. For reference, what is the output of `lein version`?

**Comment by martinraison** [comment]
Thanks for your reply. The output of `lein version` is

    Leiningen 2.5.1 on Java 1.8.0_25 Java HotSpot(TM) 64-Bit Server VM

I'm on CentOS 6.3.

I'm aware that issue is a bit broad, but it seemed there could be a huge potential for speedup so I thought I'd bring it up.

**Comment by hyPiRion** [comment]
No worries, it's certainly something that warrants some investigation.

**Comment by martinraison** [comment]
Update: I took a thread dump during compilation, and I suspect the very long compilation times might be caused by this issue: http://dev.clojure.org/jira/browse/CLJ-703
