### ISSUE TITLE
lein overwrites jackson dependency

### ISSUE THREAD

**Issue by tobiasbayer** [technomancy/leiningen#1875]
1. create new project
2. add a dependency to jackson > 2.2 e.g. `[com.fasterxml.jackson.core/jackson-core "2.3.1"]`
3. `lein repl`
4. `user=> (clojure.java.io/resource "com/fasterxml/jackson/core/JsonFactory.class")`

Actual: the output shows that `JsonFactory` from the Leiningen jar (jackson 2.2, transitively added via cheshire) is used: 
`#<URL jar:file:/Users/tbayer/.lein/self-installs/leiningen-2.5.1-standalone.jar!/com/fasterxml/jackson/core/JsonFactory.class>`

Expected: The class from the 2.3.1 dependency is used. Otherwise e.g. the method `requiresPropertyOrdering` cannot be used, as it is `since 2.3`.

**Comment by moea** [comment]
+1, big pain.

**Comment by conormcd** [comment]
Jackson is being pulled in by cheshire, and cheshire does not appear to be used anywhere in leiningen. Could cheshire simply be removed from the project.clj?

**Comment by technomancy** [comment]
> Jackson is being pulled in by cheshire, and cheshire does not appear to be used anywhere in leiningen. Could cheshire simply be removed from the project.clj?

We had a dependency that pulled in an old version of Cheshire at one
point, so we forced an upgrade in our own project.clj. If we don't have
any dependencies that bring it in anymore, we can remove it; otherwise
we can bump it.
