### ISSUE TITLE
'lein install' removes target/*

### ISSUE THREAD

**Issue by ccfontes** [technomancy/leiningen#1877]
`lein install` removes `target/*` before doing its job.

This is a problem for me, because by having generated sources in `target`, they wont be installed because the installer itself wiped them out.

Is this the expected behavior?

**Comment by ccfontes** [comment]
Btw, Leiningen 2.5.1 installed here.

**Comment by hyPiRion** [comment]
Yes, this is intentional. This can be disabled by adding `:auto-clean false` to your project.clj, but it is more idiomatic to generate said code inside `:prep-tasks` .

**Comment by ccfontes** [comment]
@hyPiRion thanks for your advice :+1: 

Generating code with `cljx` here.

It seems `lein` 2.5.1 [breaks generation of code with cljx from :prep-tasks](https://github.com/technomancy/leiningen/issues/1878). Downgrading `lein` may solve it.

I skipped `:prep-tasks` and I'm using `:auto-clean false` successfully as is advised in this [cljx sample project fix](https://github.com/lynaghk/cljx/pull/59) and #1586.
