### ISSUE TITLE
[lein 2.5.1] breaks gen code w/ cljx from :prep-tasks

### ISSUE THREAD

**Issue by ccfontes** [technomancy/leiningen#1878]
Generating code with `cljx` from `:prep-tasks` is not possible in `lein` 2.5.1.

With this `:prep-tasks` config: `:prep-tasks [["cljx" "once"] "javac" "compile"]`, I'm getting:
```clj
Exception in thread "main" java.io.FileNotFoundException: Could not locate cljx/core__init.class or cljx/core.clj on classpath:
```
when doing `lein install`, e.g.

According to [this cursiveclojure issue](https://github.com/cursiveclojure/cursive/issues/786), `lein` 2.5.1 is breaking the code generation. Downgrading seems to solve the problem.

**Comment by hyPiRion** [comment]
Is this still an issue? Per cljx's README.md, the plugin is deprecated and as such cljc should probably be used instead.

**Comment by hyPiRion** [comment]
This issue seems to be outdated as cljc is out and (presumably) working.
