### ISSUE TITLE
Transitive dependency issue

### ISSUE THREAD

**Issue by AdamFerguson** [technomancy/leiningen#1879]
I noticed in a project that, despite specifying `[org.clojure/tools.cli "0.3.1"]` as a dependency, an older version of `tools.cli` was the only one that's available for use in the project. I think I tracked it down to the fact that the project also includes `[org.apache.storm/storm-core "0.9.4"]` as a dependency which is including an older version of `tools.cli`. This can be confirmed by looking at [this repo](https://github.com/AdamFerguson/leiningen-deps-issue-documentation). If you run the following from the repl in this project, you will see:

```
user=> (do (require 'clojure.tools.cli) (keys (ns-publics 'clojure.tools.cli)))
(cli)
user=>
```

Whereas, if the dependency on storm is commented out in the `project.clj`, then you will see:

```
user=> (do (require 'clojure.tools.cli) (keys (ns-publics 'clojure.tools.cli)))
(parse-opts summarize cli)
user=>
```

Is there an option to force the project to prefer the referenced dependency over the one included in the storm jar file?

**Comment by hyPiRion** [comment]
This is a bug where storm-core has AOT-compiled dependencies bundled inside its jar file, causing the AOT-compiled namespaces to be preferred over the non-AOT versions. Preferrably we should be able to detect and replace the AOT-compiled namespaces with newer AOT-compiled ones, but the problem itself is that one shouldn't bundle other dependencies in the first place.

I managed to crank out a workaround for now by doing as follows. Comment out storm-core and aot-compile `clojure.tools.cli`:

```clj
(defproject minimal-tools-cli "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [
                 [org.clojure/clojure "1.5.1"]
                 [org.clojure/tools.cli "0.3.1"]
;                 [org.apache.storm/storm-core "0.9.4"]                                                                                                                                                                             
                 ]
  :aot [clojure.tools.cli])
```

Now do `lein compile` and uncomment `storm-core`. Lein should now use the latest compiled aot, and doing `lein repl` with `(do (require 'clojure.tools.cli) (keys (ns-publics 'clojure.tools.cli)))` should give the expected results.

If you need to uberjar or jar, add in the key entry `:auto-clean false` to `project.clj`. And if you ever end up doing `lein clean`, repeat these steps.

(I wouldn't be surprised if there are easier ways to do this, but that was the first workaround I found.)

**Comment by AdamFerguson** [comment]
Great, thanks so much @hyPiRion!
