### ISSUE TITLE
Repeatability issue with user-specific transports

### ISSUE THREAD

**Issue by ToBeReplaced** [technomancy/leiningen#1880]
This issue was originally posed on IRC. It presents an example where leiningen's guiding principle of "projects should contain all the configuration required to successfully build" is difficult to follow.

Jack and Jill want to use a project that depends on a private s3 repository. In this case, they use https://github.com/technomancy/s3-wagon-private

Jack wants to keep his credentials in environment variables:
`:repositories [["private" {:url "s3p://mybucket/releases/" :username :env :password :env}]]`

Jill wants to keep her credentials in a credentials file:
`:repositories [["private" {:url "s3p://mybucket/releases/" :creds :gpg}]]`

How can Jack and Jill cooperate on the same project?

One possible solution is to remove configuration from `:repositories` and have it only include urls. Then, custom wagons supplied by plugins would use their own variables to provide the remaining configuration for the transport. For example, `s3-wagon-private` could read its credential information from a user's profile, like `:s3-wagon-private {:creds :gpg}`.

A similar issue presents itself when considering user-specific signing keys. How does a user say "use this signing key when deploying to this url" without defining the repository in its profile and triggering repeatability warnings?

**Comment by technomancy** [comment]
> How can Jack and Jill cooperate on the same project?

You can actually put :creds :gpg or :username ... bits into the :auth
profile in user-level config. Check out the "Full Disk Encryption"
section of GPG.md.

The :env stuff for credentials is really only intended for use in
Jenkins, etc.

> A similar issue presents itself when considering user-specific signing
> keys. How does a user say "use this signing key when deploying to this
> url" without defining the repository in its profile and triggering
> repeatability warnings?

There's no restriction for adding :deploy-repositories into user-level
config, just :repositories.

-Phil

**Comment by hyPiRion** [comment]
I'll consider this closed as Phil gave a solution to this question.
