### ISSUE TITLE
Create a lein install script

### ISSUE THREAD

**Issue by danielcompton** [technomancy/leiningen#1882]
Currently installing leiningen takes 4 steps, some of which aren't intuitive for people that are new to unix systems, e.g. working with the $PATH. Is it worth creating a `curl | sh` script for people to run who aren't comfortable with the standard setup steps?

I'm not a massive fan of this style of installation, but if the script is small and easy for people to read and trust then I'm ok with it.

I'm happy to work on this if the project maintainers would be interested in accepting it.

**Comment by technomancy** [comment]
There are a number of reasons not to do this, but the main one is that we don't have our own SSL certificate for https://leiningen.org, and adding the overhead of having to cycle that every so often doesn't seem worth the trouble. We could use a URL straight from GitHub and piggy back on their certs, but then it's not short and punchy, which I guess is supposed to be the whole point?

Also this would only work if you have a user-writeable directory on your `$PATH`, and if someone is experienced enough to have that set up, they're not likely to be confused by having to run `chmod`.

Anyway, `bin/lein` is already its own installation script, and I don't see that changing any time soon.
