### ISSUE TITLE
self-install tries to download in `/.lein/...` when run via upstart

### ISSUE THREAD

**Issue by darthdeus** [technomancy/leiningen#1884]
I'm not really sure what is causing this, but if I run `lein` from an exec directive of a upstart script, it will try to download into the root dir and fail

    Downloading Leiningen to /.lein/self-installs/leiningen-2.5.1-standalone.jar now...
    mkdir: cannot create directory '/.lein': Permission denied

the upstart script is very simple, which makes me think the problem isn't coming from there?

    start on runlevel [2345]
    stop on shutdown
    console log
    respawn
    respawn limit 10 5    
    setuid deploy
    setgid deploy

    chdir /opt/apps/my-app
    exec ./bin/lein trampoline run

The `./bin/lein` is a copy of https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein in my app's root directory.

**Comment by technomancy** [comment]
It sounds like maybe upstart is setting `$HOME` to an unexpected value or leaving it empty?

**Comment by mvitz** [comment]
Upstart scripts are run by __root__. Many linux systems use`/` as home directory for __root__. Therefore leininigen tries to install itself into `/.lein`.

**Comment by winks** [comment]
Then you should be able to tell it to spawn a login shell, if you're setting a user.
lein has a check if it's running as root, so if comes this far it means the environment of the user is not properly set.
Compare `echo $HOME` if you (as root) do `su user` versus `su - user`

**Comment by technomancy** [comment]
Yeah, going to say this is a problem in the init script rather than Leiningen.
