### ISSUE TITLE
Leiningen not using :repository-auth settings in :deploy-repositories

### ISSUE THREAD

**Issue by danielcompton** [technomancy/leiningen#1885]
## Steps to reproduce:
1. Follow the guidelines for setting up your clojars username and password using [full disk encryption](https://github.com/technomancy/leiningen/blob/master/doc/DEPLOY.md#full-disk-encryption). Your `~/.lein/profiles.clj` will have 

``` clj
:auth {:repository-auth {#"https://clojars.org/repo" {:username "user" :password "pass"}}
```
1. Run `lein deploy clojars` on a project
## Expected results

Leiningen uses the stored credentials and deploys the library
## Actual results

``` sh
$lein deploy clojars
No credentials found for clojars
See `lein help deploying` for how to configure credentials to avoid prompts.
Username:
```

leiningen prompts for username and password.
## Exploration

Running `lein pprint` prints out the full settings map. Part of the map contains

``` clj
 :deploy-repositories
 [["clojars"
   {:password :gpg,
    :username :gpg,
    :url "https://clojars.org/repo/"}]],
```

I think this is where things are going wrong, I would expect the :username and :password to be filled with my :auth details.
## Workaround

Add this to the :user section of your `profiles.clj`.

``` clj
 :deploy-repositories
 [["clojars"
   {:password "user",
    :username "pass",
    :url "https://clojars.org/repo/"}]]
```

After this, `lein deploy clojars` works as expected.

**Comment by glts** [comment]
Related to #2307.

**Comment by glts** [comment]
In Leiningen 2.9.1, the steps to reproduce seem to work fine. Username and password are picked up from the `:auth` profile, and no prompt appears. Perhaps this is fixed?

**Comment by technomancy** [comment]
We can reopen if this is still a problem; thanks.
