### ISSUE TITLE
classifiers mutate uberjar creation

### ISSUE THREAD

**Issue by kul** [technomancy/leiningen#1897]
This one is kind of surprising 

``` clojure
(defproject test2 "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.6.0"]]
  :profiles {:tests {:source-paths ^:replace ["test"]}}
  :classifiers {:tests :tests})
```

`lein uberjar` for this, causes everything to be uberjare'd but the projects own source files!
I suspect this is due to ^:replace in tests profiles.

**Comment by glts** [comment]
This is no longer reproducible with Leiningen 2.9.1.

With the given project.clj, three JARs are produced: an ordinary JAR without dependencies and a uberjar, both containing `test2/core.clj`, and a test JAR containing `test2/core_test.clj`.

**Comment by technomancy** [comment]
@glts thanks for all your work taking care of these issues.

I'm preparing a talk I'm giving next week and can't really keep up with this, but once it's finished I'm hoping to be able to spend some time responding.

**Comment by glts** [comment]
Oh please don’t feel pressured by my bout of hyperactivity! I know I’ve made a lot of comments, they can easily wait a few weeks or months. It’s just that I have a little bit of time to spend … thanks.
