### ISSUE TITLE
lein not using nrepl 0.2.7 even when latter is installed

### ISSUE THREAD

**Issue by flexibeast** [technomancy/leiningen#1900]
`lein version` reports
```
Leiningen 2.5.1 on Java 1.7.0_79 OpenJDK 64-Bit Server VM
```
My `~/.lein/profiles.clj` looks like:
```clj
{:user {:dependencies ^:replace [[org.clojure/tools.nrepl "0.2.7"]]
        :plugins [[cider/cider-nrepl "0.9.0-SNAPSHOT"]
                  [lein-pprint "1.1.1"]]}}
```
and indeed, `~/.m2/repository/org/clojure/tools.nrepl/` contains `0.2.7/tools.nrepl-0.2.7.jar` and `0.2.7/tools.nrepl-0.2.7.jar.sha1`. However, running `lein repl` from `~/` still produces:
```
nREPL server started on port 57962 on host 127.0.0.1 - nrepl://127.0.0.1:57962
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
```
i've come across this issue whilst trying to upgrade nREPL for CIDER 0.9.0snapshot. In [this SO thread about trying to upgrade to nrepl-0.2.7](http://stackoverflow.com/q/28688721), one user [says](http://stackoverflow.com/a/30139330) that the dependency is only enabled by `lein` if one is running `lein repl` from within a Clojure project. Is this the intended behaviour? Or might there be something wrong with the rest of my setup, such that the `:dependencies` vector in `~/.lein/profiles.clj` is effectively ignored?

**Comment by tonyarkles** [comment]
I'm experiencing the same problem. From my debugging so far, it looks like lein itself depends on nrepl 0.2.6 and I haven't figured out a good way to override that yet. Still experimenting.

**Comment by tonyarkles** [comment]
@flexibeast to keep things a bit more isolated, I added a `profiles.clj` alongside my `project.clj` with:

`{:dev {:dependencies [[org.clojure/tools.nrepl "0.2.10"]]}}` in it to solve it. I agree that this seems pretty broken though.

**Comment by cch1** [comment]
We're seeing the same problem.  Any suggestions on moving forward short of @tonyarkles' approach (which seems a bit hacky -and I write that with much respect)?

**Comment by joonoro** [comment]
I think this is part of the larger problem where *none* of the dependencies or plugins in `profiles.clj` are merged unless you run `lein repl` from a project (i.e., a directory with `project.clj`).
