### ISSUE TITLE
profile.cjl will be ingnored if we are not in a project.

### ISSUE THREAD

**Issue by jesse23** [technomancy/leiningen#1901]
------------------------------------------
profile.cjl:
------------------------------------------
{:user {:plugins 
        [[cider/cider-nrepl "0.9.0-SNAPSHOT" :exclusions [org.clojure/clojure]]]
        :dependencies [ [org.clojure/clojure "1.7.0-beta3"]
                        [org.clojure/tools.nrepl "0.2.10"]]}}

------------------------------------------
project.cjl
------------------------------------------
(defproject trm "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :main ^:skip-aot trm.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})

------------------------------------------
console output
------------------------------------------
D:\>lein repl
nREPL server started on port 51682 on host 127.0.0.1 - nrepl://127.0.0.1:51682
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> exit
Bye for now!
D:\>cd d:\clojure\trm

d:\clojure\trm>lein repl
nREPL server started on port 51687 on host 127.0.0.1 - nrepl://127.0.0.1:51687
REPL-y 0.3.5, nREPL 0.2.10
Clojure 1.7.0-beta3
Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

trm.core=> exit
Bye for now!
d:\clojure\trm>

------------------------------------------
expected result
------------------------------------------
profile.cjl should work for file which dose not belong to any project.

**Comment by joonoro** [comment]
I am also experiencing this:

```
$ cat .lein/profiles.clj 
{:user {:plugins [[cider/cider-nrepl "0.9.1"]]
        :dependencies [[org.clojure/clojure "1.7.0"]
                       [org.clojure/tools.nrepl "0.2.10"]
                       [org.clojure/math.combinatorics "0.1.1"]]}}
$ lein repl
nREPL server started on port 52842 on host 127.0.0.1 - nrepl://127.0.0.1:52842
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e
```

**Comment by joonoro** [comment]
After some investigating it gets even weirder: on a fresh install of Leiningen if I do `lein repl` I get nREPL 0.2.6. If I add a `project.clj` specifying nREPL 0.2.10 I *still* get 0.2.6, but if I add a `~/.lein/profiles.clj` specifying nREPL 0.2.10 I actually get nREPL 0.2.10. Specifying nREPL 0.2.10 in the profile but not the project ends up with 0.2.6. So it only works properly if both the project *and* the profile specify the dependency.
