### ISSUE TITLE
Cannot verify raw.github.com’s certificate.

### ISSUE THREAD

**Issue by huodon** [technomancy/leiningen#1902]
`lein self-install` on windows(7) throw `Cannot verify raw.github.com’s certificate` error.

I changed `lein.bat:146`  
 `call wget -O %1 %2`
 to 
`call wget -O %1 %2 --no-check-certificate`
can fix this error.

**Comment by sveri** [comment]
I have the same problem on W7 and can confirm that the proposed hack works.

However, running lein upgrade won't work like this as it replaces the lein.bat file during the upgrade process.

**Comment by emilv** [comment]
Adding `--no-check-certificate` means you won't be protected from MITM attacks. Better to find the real error.

**Comment by sveri** [comment]
@emilv I totally agree with you. Still I don't have a clue on how to fix that one for myself, so the hack is the only thing that works for me now.

**Comment by hyPiRion** [comment]
Lein 2.5.2 now ships with powershell by default, and is intended to work smoother out of the box. Could you download <https://github.com/technomancy/leiningen/blob/stable/bin/lein.bat> and check if the new lein.bat script works better for you?

**Comment by sveri** [comment]
I just downloaded the lein.bat, ran `lein upgrade` from the command line, leiningen upgraded itself and afterwards I had version 2.5.2 installed. This all in Windows 8 with the standard command.

Thanks, works for me :-)
