### ISSUE TITLE
Uberjar merging components.xml

### ISSUE THREAD

**Issue by towler73** [technomancy/leiningen#1903]
When I uberjar'ed my project I got an error parsing the merged components.xml.  Turns out one of the jars I'm using has some un-closed html tag in the description tag.  In the original jar the un-closed html is escaped, but when it is read and merged in uberjar process, it gets unescaped.

I wrote some code to fix this (below) and I thought I could add something like this to my project.clj

``` clojure
  :uberjar-merge-with {"META-INF/plexus/components.xml" 'user/components-merger}
```

but get this error

```
(leiningen.uberjar/components-merger and (quote user/components-merger) have a type mismatch merging profiles.)
```

Since components.xml is already being merged, can I override it, or does it have to be merged into leiningen code?

Thanks,
Brett

``` clojure
(defn- tree-edit [zipper editor]
  (loop [loc zipper]
    (if (zip/end? loc)
      (zip/root loc)
      (if (= :description (:tag (zip/node loc)))
        (let [new-loc (zip/edit loc editor)]
          (recur (zip/next new-loc)))
        (recur (zip/next loc))))
      )
    )

(defn- editor [node]
  (let [content (get (:content node) 0)]
    (assoc-in node [:content 0] (clojure.string/escape content {\< "&lt;" \> "&gt;" \& "&amp;"}))
    )
  )

(defn- components-write [out components]
  (binding [*out* (PrintWriter. out)]
    (xml/emit {:tag :component-set
               :content
                    [{:tag :components
                      :content components}]})
    (.flush *out*)))

(defn fix-components-xml-merge [res]
  (let [zipper (->> res xml/parse zip/xml-zip)]
    (->> (tree-edit zipper editor) zip/xml-zip zip/children
         (filter #(= (:tag %) :components))
         first :content)
    )
  )

(def components-merger [fix-components-xml-merge into components-write])
```

**Comment by technomancy** [comment]
I suspect this is just a quoting mistake.

**Comment by glts** [comment]
Indeed, this is just a quoting mistake. What you’re trying to do is supported, just omit the single quote in project.clj: `{"META-INF/plexus/components.xml" user/components-merger}`. We can close this issue.
