### ISSUE TITLE
Where does leiningen read profiles.clj from on Windows?

### ISSUE THREAD

**Issue by toolkit** [technomancy/leiningen#1910]
Hi there
I am using lein (which I installed by hand, not using the Windows installer)
This is installed under `c:\dev\lein`
I tried creating a profiles.clj under `c:\Users\xxxx\.lein`
But this didn't seem to pick up the profiles.clj
Is there a way of asking lein where it is looking?
Thanks, Neil

**Comment by hyPiRion** [comment]
`lein.bat` uses `C:\Users\{username}\.lein` (`C:\Documents and Settings\{username}\.lein` on Win XP) as directory for `profiles.clj` and the like, so it should be placed there.

Is there a `self-installs` directory in the `.lein` directory? If not, then lein uses a different directory.

**Comment by winks** [comment]
small nitpick: it uses `%USERPROFILE%` which is per default set to the above path afaik. But it's still just the current contents of the environment variable.

**Comment by toolkit** [comment]
Thanks guys. It turns out it is using c:/dev/lein/profiles.clj as opposed to any user profile based location.
