### ISSUE TITLE
[Bug] Command line arguments ignored for aliases

### ISSUE THREAD

**Issue by binarykitchen** [technomancy/leiningen#1913]
When I do a `lein redline-rpm --brand='*'`, which will call `lein build` internally whose alias will be resolved into `["shell" "npm" "run" "build"]` then I can see that the `brand` argument is missing.

I guess leiningen is not passing on any arguments to the alias when called.

Here an extract of our project.clj

```
  ; Prep-tasks are called on clojure compilation which is needed for lein run or lein jar
  :prep-tasks
  [ "build"
    "javac"
    "compile"]

  :aliases
  { "build"         ["shell" "npm" "run" "build"]
    "test"          ["shell" "npm" "run" "test"]
    "test:unit"     ["shell" "npm" "run" "test:unit"]
    "deps"          ["do" "deps" ["shell" "npm" "i"]]

  ; A trick to adjust environment before running commands, see
  ; https://github.com/hyPiRion/lein-shell/issues/17
  :shell
  {:commands
    { "npm" {:default-command "npm"}}}
```

How can I force leiningen to pass on arguments further to npm?

**Comment by binarykitchen** [comment]
thanks!

**Comment by hyPiRion** [comment]
@binarykitchen: No problem, and sorry about the delay here. I've also pushed out a fix in lein-shell, so changing lein-shell version 0.4.2 should work on any version of leiningen.
