### ISSUE TITLE
"lein release" doesn't honor with-profile

### ISSUE THREAD

**Issue by eklipse2k8** [technomancy/leiningen#1915]
This works as expected:

```
$ lein with-profile docker deploy
```

This doesn't: 

```
$ lein with-profile docker release
```

Is there a profile that lein release will use instead?

**Comment by hyPiRion** [comment]
Sorry for not answering this earlier. Have you tried to put the `^:leaky` metadata on the docker profile?

**Comment by snowell** [comment]
As a bystander who was also affected by this issue, I can confirm that adding `^:leaky` to the required profiles seems to do the trick (at least as of leiningen 2.5.0)
