### ISSUE TITLE
Issue running lein run/repl at work

### ISSUE THREAD

**Issue by jugalde** [technomancy/leiningen#1921]
I am new to lein/clojure so if I'm missing something obvious please let me know. I've tried running 

lein run core.clj

in the proper directory and

lein repl

in the project directory, but the error I get, at least for lein run is 

Could not transfer artifact org.clojure:tools.nrepl:pom:0.2.6 from/to central (https://repo1.maven.org/maven2/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Could not transfer artifact clojure-complete:clojure-complete:pom:0.2.3 from/to central (https://repo1.maven.org/maven2/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.

I've tried changing the proxies as mentioned here https://github.com/technomancy/leiningen/issues/1193
and generally have been trying to find out how to get this all to work. I am at work, so I'm not sure if there be some permissions issues. Does anyone have any idea of what may be wrong?

**Comment by hyPiRion** [comment]
This seems to be a different issue, which may be related to broken/missing root-certificates. The easiest would probably be to reinstall the JDK. (Make sure you're running the right version for your system)

If that doesn't work, feel free to comment back here and I'll see if we can figure it out.

**Comment by jugalde** [comment]
Uninstalled and reinstalled java-1.7.0-openjdk.x86_64. The same problem persists. What might be wrong with the root-certificates?

**Comment by jugalde** [comment]
Also, I'm not sure if this is relevant, but I'm using the Red Hat OS

**Comment by jugalde** [comment]
Additionally, in the script for Lein, the error get's thrown between lines 345 and 355, copied below for reference.

 export TRAMPOLINE_FILE
        "$LEIN_JAVA_CMD" \
            "${BOOTCLASSPATH[@]}" \
            -Dfile.encoding=UTF-8 \
            -Dmaven.wagon.http.ssl.easy=false \
            -Dmaven.wagon.rto=10000 \
            $LEIN_JVM_OPTS \
            -Dleiningen.original.pwd="$ORIGINAL_PWD" \
            -Dleiningen.script="$SCRIPT" \
            -classpath "$CLASSPATH" \
            clojure.main -m leiningen.core.main "$@"

**Comment by hyPiRion** [comment]
Could you output `java -version` and `lein version`?

If the java version doesn't match the installed one, you might have to run `/usr/sbin/alternatives --config java` and pick the right one. Although that shouldn't really affect this issue, might be worth an attempt.

(Only related cause I could find might be https://bugzilla.redhat.com/show_bug.cgi?id=904165, which is presumably fixed)

**Comment by jugalde** [comment]
java version "1.7.0_79"
Leiningen 2.5.1 on Java 1.7.0_79 OpenJDK 64-Bit Server VM

**Comment by hyPiRion** [comment]
Sounds very similar to #613, but it's on OpenJDK. It might be possible to use some of the workarounds there.

**Comment by hyPiRion** [comment]
Since I haven't heard any more reports related to this, I'm assuming it's similar enough in nature to #613 and/or that it may have been solved upstream.

Feel free to reopen if this is not the case.
