### ISSUE TITLE
test selector doesn't work with composed tests

### ISSUE THREAD

**Issue by xfeep** [technomancy/leiningen#1925]
``` clojure
(ns cpxtest.core-test
  (:require [clojure.test :refer :all]
            [cpxtest.core :refer :all]))

(deftest test-a
  (testing "simple"
           (println "test-a")
           (is (= 100 (+ 1 99) ))))

(deftest test-ca
  (test-a))
```

lein test is OK 

``` shell
$ lein test

lein test cpxtest.core-test
test-a
test-a

Ran 3 tests containing 2 assertions.
0 failures, 0 errors.
```

BUT test selector doesn't work

``` shell
$ lein test :only cpxtest.core-test/test-ca

lein test cpxtest.core-test

Ran 1 tests containing 0 assertions.
0 failures, 0 errors.
```

There were 0 assertions and test-a wasn't invoked.

**Comment by xfeep** [comment]
```shell
$lein version
Leiningen 2.5.1 on Java 1.7.0_45 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by shimanekb** [comment]
Calling ":only" on a function works with having the required tests for the composed function loaded from a different namespace:
`(ns example.example-test 
               (:require [example.place-of-subtest] :refer :all]))`
or 
`(ns example.example-test 
              (:use [example.place-of-subtest :only [subtest]]))`

Also in a given testing namespace you can use test-hooks to call your composed test, but not the subtests. (see test-ns-hook on https://clojure.github.io/clojure/clojure.test-api.html)

Here is also a good stack-overflow [reference](http://stackoverflow.com/questions/24970853/run-one-clojure-test-not-all-tests-in-a-namespace-with-fixtures-from-the-rep).

**Comment by shimanekb** [comment]
If you are composing test functions to address setup and teardown before each test, or once before all tests, I would look into fixtures. Here is a good reference with an example on clojure.test's fixtures http://thornydev.blogspot.com/2012/09/before-and-after-logic-in-clojuretest.html.

**Comment by technomancy** [comment]
Unfortunately I don't think there's much we can do about bugs in `clojure.test`.
