### ISSUE TITLE
windows lein.bat self install :  wget errors out

### ISSUE THREAD

**Issue by anjanb** [technomancy/leiningen#1926]
Downloaded lein.bat just now and ran the command lein.bat self-install (as an admin on windows 7 enterprise).

I got the following error

=========
c:\langTools>lein.bat self-install
Downloading Leiningen now...
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\tools\gow/etc/wgetrc
--2015-07-03 14:01:00--  https://github.com/technomancy/leiningen/releases/download/2.5.1/leiningen-2.5.1-stan
dalone.zip
Resolving web-proxy.atl.hp.com... 16.114.29.150
Connecting to web-proxy.atl.hp.com|16.114.29.150|:8080... connected.
ERROR: cannot verify github.com's certificate, issued by `/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert
 SHA2 Extended Validation Server CA':
  Unable to locally verify the issuer's authority.
To connect to github.com insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.

Failed to download https://github.com/technomancy/leiningen/releases/download/2.5.1/leiningen-2.5.1-standalone
.zip
==============

I edited the lein.bat file to add the flag "--no-check-certificate" for the wget invocation and then reran the above command.

This time it was able to download the .zip file; However, I didn't get a helpful message saying that the self-install succeeded. 

It would help to have a SUCCESS/FAILURE message at the end of running the lein.bat file.

thank you

**Comment by tommyettinger** [comment]
I get the same error with Leiningen for Windows when I first run `lein self-install`. I'll try editing lein.bat as @anjanb did.

**Comment by tommyettinger** [comment]
Changing line 146 of lein.bat to `call wget --no-check-certificate -O %1 %2` did the trick.  I don't know if this is safe to do in the long run, but since this is currently going to block installation for new users on Windows, I think I'll send a PR and discuss the one-line change there.

**Comment by hyPiRion** [comment]
This is fixed on master by #1831, which will be out when 2.5.2 is out. See #1800 for the discussion on this issue.
