### ISSUE TITLE
Consistency of tutorial.md broken at https://github.com/technomancy/leiningen/blob/stable/doc/TUTORIAL.md#uberjar

### ISSUE THREAD

**Issue by pfernandez** [technomancy/leiningen#1927]
Reaching this section in the tutorial, it says "By this point our `project.clj` file should look like this:", and then shows a file with several lines not introduced earlier in the tutorial.

Also, the directory structure of the project suddenly changes at this point from `src/my_project/` to `src/my/project/`.

**Comment by hyPiRion** [comment]
I have updated the tutorial to fix the issues you brought up, along with some other things (correct output, latest dependencies, etc). It is available at https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md and should be available on stable when 2.5.2 is out.

Does this look good to do, or is there still some possible confusion here?

**Comment by pfernandez** [comment]
Looks much better, thanks. This tutorial really helped me.

The only thing I see is that you've removed the Lucene depedency, but it's still mentioned under the [Search](https://github.com/technomancy/leiningen/blob/91117395abc5fb1fcef02781597a3206b581cbb7/doc/TUTORIAL.md#search) section. Maybe that's not an issue (I don't know anything about Lucene) but I thought I'd mention it.

**Comment by hyPiRion** [comment]
The Lucene search mention there isn't related to the dependency that was originally added to the project.clj in the tutorial. I've added a link to a link to a Lucene query syntax tutorial, although I'm pretty sure Lein doesn't support all of it.

**Comment by pfernandez** [comment]
Gotcha. Thanks!
