### ISSUE TITLE
Could not locate ring/adapter/jetty__init.class

### ISSUE THREAD

**Issue by rowhit** [technomancy/leiningen#1928]
I am new to Clojure/Leiningen. I started off to write a small webapp with luminus. I create a project and then simply started the ring server with lein but received above mentioned error. I am really not sure how to debug this.

**Comment by hyPiRion** [comment]
Hi there!

This does not seem to be related to Leiningen at all, but rather luminus-framework/luminus-template#134. In that particular thread, the author recommends using another backend server as you're probably using JDK version 6 or 7.

I'm closing this, but if you still believe it's related to Leiningen itself, feel free to reopen.
