### ISSUE TITLE
Specify dependencies for bootclasspath

### ISSUE THREAD

**Issue by sunng87** [technomancy/leiningen#1936]
This issue is similar to #1523 but one step further. Since #1523 is relatively old, I'm going to start a new one.

The idea is to allow users to put particular dependencies on bootclasspath instead of the whole. Currently, lein offers `jvm-opt` for this. But `jvm-opt` doesn't provide dependency resolution. Typically, we had to hard coded a path in `jvm-opt` which is not good way.

My idea is to change `:bootclasspath` into a vector (also keep backward-compatibility if `true` is given), users could put a vector of maven coordinates into it. Leiningen will download and resolve path for these jars. This is pretty similar to what `:java-agents` provides for now.

I would like to hear your opinion for this feature. If you think it works, I will start to working on a PR for this.

EDIT: The rationale behind this feature is I found putting the whole classpath into bootclasspath doesn't work in some scenario.

**Comment by technomancy** [comment]
I think this is a good idea, but would it be possible to implement it as
a plugin first before adding it to Leiningen itself?

For example, you could do something like this:

    $ lein bootclasspathify run -m my.ns

In this case the `bootclasspathify` plugin would inspect the
:bootclasspath-deps setting and calculate a new project map that has
:jvm-opts set appropriately. It could then hand the new project map off
to whatever task it is given as an argument, acting as a higher-order task.

**Comment by sunng87** [comment]
@technomancy Thanks! That works for me. I will start to work on a plugin for this.

**Comment by sunng87** [comment]
For anyone who is looking for such kind of plugin, please take a look at the one I just created:
https://github.com/sunng87/lein-bootclasspath-deps
