### ISSUE TITLE
Is porting this feasible?

### ISSUE THREAD

**Issue by Immortalin** [technomancy/leiningen#1938]
Hi, I am interested in porting [this](https://github.com/MinecraftForge/ForgeGradle) to the leiningen ecosystem to allow for better clojure integration as currently using clojure for Minecraft modding requires gradle which is pretty unidiomatic. Here's [some](https://github.com/setupminimal/Cljsh) [examples](https://github.com/setupminimal/standalone-clojure-mod-example/blob/master/src/main/java/io/github/setupminimal/glass/Glass.java) of what I mean. Thanks in advance!

**Comment by hyPiRion** [comment]
Hi there!

I'm not entirely sure what you ask for here. The project you link to seems portable over to Lein, so I don't think there is anything that will stop you from doing so :)
