### ISSUE TITLE
`lein test` ignores .cljc files

### ISSUE THREAD

**Issue by gfredericks** [technomancy/leiningen#1940]
To reproduce:

```
$ lein new hello
Generating a project called hello based on the 'default' template.
The default template is intended for library projects, not applications.
To see other templates (app, plugin, etc), try `lein help new`.
$ cd hello
$ lein test

lein test hello.core-test

lein test :only hello.core-test/a-test

FAIL in (a-test) (core_test.clj:7)
FIXME, I fail.
expected: (= 0 1)
  actual: (not (= 0 1))

Ran 1 tests containing 1 assertions.
1 failures, 0 errors.
Tests failed.
$ mv test/hello/core_test.clj{,c}
$ lein test

lein test user

Ran 0 tests containing 0 assertions.
0 failures, 0 errors.
```

**Comment by gfredericks** [comment]
As far as I can tell this logic is handled by bultitude, which is fixed in its newer versions.

But the newest version of bultitude also (I think) requires clojure 1.7. Leiningen is currently using clojure 1.6. Will we have to upgrade to fix this problem?

There's also an intermediate version of bultitude that finds cljc files but doesn't have the 1.7 bump.

**Comment by gfredericks** [comment]
Workaround: the `lein test ...namespaces...` call still works, so I put an alias in my project.clj:

``` clojure
:aliases {"test" ["test" "each" "of" "my" "namespaces"]}
```

Actually I only have one test namespace at the moment. Does this work with more than one? I don't know.

**Comment by hyPiRion** [comment]
Does this work with Clojure 1.7 and lein 2.5.2? Ref: #1911

**Comment by gfredericks** [comment]
Yep, upgrading fixes, thanks!
