### ISSUE TITLE
a simple note to make deploy easier

### ISSUE THREAD

**Issue by laforge49** [technomancy/leiningen#1946]
A windows user new to Clojure, deploying my first project was quite painful. And the pain was with pinentry agent.

I installed Gpg4win but gosh, the install for gpa was disabled by default and I had no idea that I needed gpa as I had not encountered any references to it, only I was looking for pinentry agent.

And then, after a lot of web searching, I noticed gpg-connect-agent. OK, I ran that and everything worked great.

A simple addition to the tutorial, me thinks, would make a world of difference. Everything else about lein has been super!

**Comment by technomancy** [comment]
That sounds good. No one on the main leiningen team has much Windows experience; if you're familiar with the topic why don't you write up what you think would be useful in a pull request and we can get it merged in?

**Comment by laforge49** [comment]
Never put together a pull request before. :-)

**Comment by laforge49** [comment]
Done!

https://github.com/technomancy/leiningen/pull/1948

**Comment by hyPiRion** [comment]
Closed by #1948.
