### ISSUE TITLE
clj-http warning with leiningen 2.5.2 and clojure 1.7.0

### ISSUE THREAD

**Issue by ducky427** [technomancy/leiningen#1949]
I get this warning with the new leiningen and clojure 2.7.0

```WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update```

I think upgrading `clj-http` to latest version v`2.0.0` should should this issue.

**Comment by hyPiRion** [comment]
Is this something you stumbled upon with the stable version of Leiningen? Or is it something that is caused on snapshot?

I'm aware of the warnings emitted by running directly from master, but I attempted to remove all of those from the stable version through AOT-compiling.

**Comment by ducky427** [comment]
I use homebrew to manage leiningen. They just upgraded to the latest version and I have been getting this warning since then. 

I don't have any dependencies in my profile.clj as well.

**Comment by hyPiRion** [comment]
Alright, thanks for the info. I'll have a look into it.

**Comment by ducky427** [comment]
I'll see if I get this warning if I were to use leiningen directly without installing it using homebrew.

**Comment by MerelyAPseudonym** [comment]
@ducky427 Do you still get the warning with all of your plugins disabled? I managed to make the error go away by removing any plugins that depend on clj-http. (In my case, I needed to comment out `[lein-ancient "0.6.7"]` from my `:user` profile’s `:plugins`.)

I don't have any suggestions on what the "correct" behavior should be, but I figured @hyPiRion would want to know if the Homebrew-installation is a [red herring](https://en.wikipedia.org/wiki/Red_herring).

**Comment by ducky427** [comment]
really sorry @hyPiRion and @MerelyAPseudonym, my bad. i had the same dependency and I though I had removed but I hadn't.

Thanks a lot @hyPiRion!

**Comment by hyPiRion** [comment]
(It is on my list to upgrade these dependencies regardless, in case anyone wonders.)
