### ISSUE TITLE
Missing section "HACKING" on README.md

### ISSUE THREAD

**Issue by pietromenna** [technomancy/leiningen#1950]
I “installed” in my local computer a snapshot version of leiningen.
It came to my attention one part of the message: 
… See the "Hacking" section of the README … This section no longer exists since commit 205c586

Anyway, maybe the message "The upgrade task is only meant for stable releases.” is enough. Can I send a PR with it?

**Comment by technomancy** [comment]
The "Hacking" section got moved to `CONTRIBUTING.md`; in particular the "Bootstrapping" section. A PR to update the message would be great.

**Comment by pietromenna** [comment]
Thanks @technomancy for the hint!
