### ISSUE TITLE
Cannot deploy to Clojars with 2.5.2

### ISSUE THREAD

**Issue by brunchboy** [technomancy/leiningen#1952]
I have had to downgrade back to Leiningen 2.5.1 because under 2.5.2, the integration with GPG on Mac OS X has broken somehow. It complains that the agent is not running and forces me to manually enter my Clojars credentials first, and then it claims that the passphrase is wrong for my own GPG key when trying to sign the JAR, but even when I manually enter the correct passphrase it fails.

Reverting to 2.5.1 allows me to publish my projects to Clojars again.

**Comment by amalloy** [comment]
Still works fine for me, with Leiningen 2.5.2 on OS X 10.10.4 and GPG keychain "Version 1.2.1 (1147)". I don't have to enter a password or anything, and just successfully deployed a jar.

**Comment by expez** [comment]
broken on arch linux using gpg 2.1.6

**Comment by brunchboy** [comment]
That is so strange, those are the exact same versions of OS X and GPG keychain that I have, and as soon as I switch to Leiningen 2.5.2, it breaks as I described, and as soon as I switch back to Leiningen 2.5.1 it works fine.

**Comment by brunchboy** [comment]
p.s. @amalloy thanks for `ring-buffer`, I use it for synchronizing metronomes either to MIDI clock or human tap-tempo buttons in [Afterglow](https://github.com/brunchboy/afterglow#afterglow). :grin:

**Comment by shimanekb** [comment]
Is this similar to issue #1963? That issue was just closed.

**Comment by brunchboy** [comment]
That does sound likely to be the same issue. Would you like me to try to pull a current master distribution and test?

**Comment by shimanekb** [comment]
Sure, if it doesn't work I will look into it.

**Comment by brunchboy** [comment]
Whoops, my naïve attempt to just use the `lein` script in the `master` branch to self-install failed:

```
➜ afterglow git:(master) ✗ ./lein ancient
Downloading Leiningen to /Users/jim/.lein/self-installs/leiningen-2.5.3-SNAPSHOT-standalone.jar now...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
Failed to download https://github.com/technomancy/leiningen/releases/download/2.5.3-SNAPSHOT/leiningen-2.5.3-SNAPSHOT-standalone.zip (exit code 22)
It's possible your HTTP client's certificate store does not have the
correct certificate authority needed. This is often caused by an
out-of-date version of libssl. It's also possible that you're behind a
firewall and haven't set HTTP_PROXY and HTTPS_PROXY.
```

Is there a quick guide for how to work from the source?

**Comment by brunchboy** [comment]
I think I found one in the Contributing section. Trying that approach…

**Comment by brunchboy** [comment]
All right, I got `2.5.3-SNAPSHOT` compiled, and can confirm that it resolves my issue as well. Thanks!

**Comment by shimanekb** [comment]
No problem : )
