### ISSUE TITLE
version divergence with cider?

### ISSUE THREAD

**Issue by rebcabin** [technomancy/leiningen#1955]
I have two emacs set ups, one adapted from "Clojure for the Brave and True" and the other from Emacs-live.  Both purport to have cider 20150814.855 installed.  My .lein/.profiles says
{:user {:plugins [[cider/cider-nrepl "0.10.0-SNAPSHOT"]]}}, and it's the same no matter which of the two emacs setups I run.  I run the brave setup by cp -r .emacs.d.brave_true/ .emacs.d, and I run the live setup by rm -rf .emacs.d, cp -r .emacs.d.live/ .emacs.d.  All emacs packages are up-to-date, leiningen is up-to-date, all homebrew stuff is up-to-date. 

When I try to "cider-jack-in" on a hello-world project, with the emacs-live setup I get, 

; CIDER 0.10.0snapshot (package: 20150814.855) (Java 1.7.0_25, Clojure 1.6.0, nREPL 0.2.10)
WARNING: The following required nREPL ops are not supported: 
inspect-start inspect-reset
Please, install (or update) cider-nrepl 0.8.1 and restart CIDER
WARNING: CIDER's version (0.8.1) does not match cider-nrepl's version (0.10.0-snapshot)
clojure-noob.core> 

but the same cider-jack-in command does work with the emacs-brave_true setup.  I can't find cider 0.8.1 anywhere in my world, I don't know whether this is an issue with leiningen, cider, emacs, emacs-live, or emacs-brave & true, but I'm taking a wild guess at leiningen because it seems to be the only thing that provides cider-nrepl.  

Of course, I want to use the emacs-live setup, but that's the one that doesn't work...

Here are copies of the two setups in case anyone would have the time to dig into this.

https://dl.dropboxusercontent.com/u/1997638/.emacs.d.brave_true.zip
https://dl.dropboxusercontent.com/u/1997638/.emacs.d.live.zip

**Comment by technomancy** [comment]
What you're describing sounds like a Cider problem. Part of the reason
this is more confusing to debug than it should is that you appear to be
using Melpa, which mangles the version numbers of the packages. If you
stop using Melpa it should at least help make it clearer which version
of cider you are using, which might help you debug the problem further.

**Comment by rebcabin** [comment]
I will try it without melpa.  Thanks!

**Comment by rebcabin** [comment]
Looks like emacs-live is out of maintenance, and it includes a version of cider that's out-of-date w.r.t. the latest.  It's not clear what happens when emacs-live's cider collides with an update from cider, either via melpa or not, but it's not a leiningen issue at all.
