### ISSUE TITLE
pprint runtime info as edn

### ISSUE THREAD

**Issue by laurentpetit** [technomancy/leiningen#1956]
Counterclockwise needs to synchronize the Eclipse project classpath with leiningen so that dependencies, source dependencies, native dependencies are correctly set.

At least for 2 purposes:
- leveraging as much as possible from the IDE in terms of static code introspection (suggesting java / javadoc from the listed dependencies and dependencies source jars)
- easy / quick startup of a REPL with all the dependencies (including native dependencies) without involving leiningen (works well in 80% cases and is the preferred way by many because startup time is faster)

Currently, what has been suggesting for "calling leiningen and get runtime information" is the following ( http://librelist.com/browser//leiningen/2015/8/14/getting-leiningen-classpath/ ):

```
lein update-in : assoc :eval-in :pprint -- run -m clojure.main
```

This works, but has at least 2 problems:
- Problem 1: what is output is not readable as edn. The first part looks like
      `
  Java: java
  Classpath: -classpath /Users/laurentpetit/tmp test/tutorial/test:/Users/laurentpetit/tmp test/tutorial/src:/Users/laurentpetit/tmp test/tutorial/dev-resources:/Users/laurentpetit/tmp test/tutorial/resources:/Users/laurentpetit/tmp test/tutorial/target/classes:/Users/laurentpetit/.m2/repository/clojure-complete/clojure-complete/0.2.3/clojure-complete-0.2.3.jar:/Users/laurentpetit/.m2/repository/overtone/scsynth-extras/3.5.7.0/scsynth-extras-3.5.7.0.jar:/Users/laurentpetit/.m2/repository/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar:/Users/laurentpetit/.m2/repository/overtone/at-at/1.2.0/at-at-1.2.0.jar:/Users/laurentpetit/.m2/repository/overtone/byte-spec/0.3.1/byte-spec-0.3.1.jar:/Users/laurentpetit/.m2/repository/overtone/osc-clj/0.9.0/osc-clj-0.9.0.jar:/Users/laurentpetit/.m2/repository/overtone/libs.handlers/0.2.0/libs.handlers-0.2.0.jar:/Users/laurentpetit/.m2/repository/overtone/scsynth/3.5.7.0/scsynth-3.5.7.0.jar:/Users/laurentpetit/.m2/repository/commons-net/commons-net/3.0.1/commons-net-3.0.1.jar:/Users/laurentpetit/.m2/repository/javax/jmdns/jmdns/3.4.1/jmdns-3.4.1.jar:/Users/laurentpetit/.m2/repository/clj-glob/clj-glob/1.0.0/clj-glob-1.0.0.jar:/Users/laurentpetit/.m2/repository/org/clojure/clojure/1.6.0/clojure-1.6.0.jar:/Users/laurentpetit/.m2/repository/overtone/overtone/0.9.1/overtone-0.9.1.jar:/Users/laurentpetit/.m2/repository/overtone/midi-clj/0.5.0/midi-clj-0.5.0.jar:/Users/laurentpetit/.m2/repository/org/clojure/tools.nrepl/0.2.10/tools.nrepl-0.2.10.jar:/Users/laurentpetit/.m2/repository/org/clojure/data.json/0.2.3/data.json-0.2.3.jar:/Users/laurentpetit/.m2/repository/clj-native/clj-native/0.9.3/clj-native-0.9.3.jar
  JVM args: -Dfile.encoding=UTF-8 -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:-OmitStackTraceInFastThrow -Dclojure.compile.path=/Users/laurentpetit/tmp test/tutorial/target/classes -Dtutorial.version=0.1.0-SNAPSHOT -Dclojure.debug=false -Djava.library.path=/Users/laurentpetit/tmp test/tutorial/target/native/macosx/x86_64
  ``
  Spot the problem? Yes, there's a space in the project directory name. Having to try to reconcile things by parsing plain text is hard to get right.
- Problem 2: just an aesthetic problem, I guess. CCW doesn't care at all about the pprint form (here, `clojure.main`). It's there just to make the `:eval-in :pprint` happy so that it does not either display the hel page (if nothing provided), or do too much (most built-in leiningen tasks). It just appears that the `run -m clojure.main` task is the most innocuous one getting the runtime information in addition to the pprinted form.

I have done a quick fork of leiningen which adds a `:pprint-edn` version of `:eval-in` which is similar to `:pprint` but prints a map before the form, and not plain text. I will submit the PR very soon so you can react on it. I still don't like that having this map feels like runtime information is "second-line citizen".

**Comment by technomancy** [comment]
> I still don't like that having this map feels like runtime information is "second-line citizen".

Emitting two forms is a bit strange. What if the first map were emitted as metadata on the code form instead?

I could see an argument for doing this in the existing :pprint instead of adding a new defmethod; essentially it is turning something that was originally only designed for human consumption into a form that is both human-readable and machine-readable.

The only question is whether there are any existing automated tools which rely on the current ad-hoc jvm args printing. Seems unlikely but possible.

**Comment by laurentpetit** [comment]
I'm not opposed to your ideas, just want to share thoughts yet:

Le dimanche 16 août 2015, Phil Hagelberg <notifications@github.com> a
écrit :

> > I still don't like that having this map feels like runtime information
> is "second-line citizen".
>
> Emitting two forms is a bit strange. What if the first map were emitted as
> metadata on the code form instead?


I haven't thought too much about the fact that the second form is
guaranteed to be read-able in all cases. Will there be some times where it
wouldn't read if some tag reader is not installed in the reading jvm?
Having 2 forms guarantees that the first read will always only get runtime
info and not the command.

>
> I could see an argument for doing this in the existing :pprint instead of
> adding a new defmethod; essentially it is turning something that was
> originally only designed for human consumption into a form that is both
> human-readable and machine-readable.


The refactoring in my PR duplicates almost no code. The edn version takes a
lot more spaces and visual clutter for the human reading.
Also, if one wants to start enhancing the edn version with relevant but yet
missing information, making human (more concise, not necessarily exhaustive
summary) and edn version the same output will always bring necessary
compromises to the design choice.

For instance there are other requirements coming, I didn't want to bring
everything to the table in one pass: source jars. I don't known if their
resolution should be done in this :pprint call. It could totally be done in
another new task. I have no strong idea about it yet.

Another thought while we're at it: there would be an argument to have
everything related to aether (jar dependencies, source dependencies) be
output to stdout as top level forms each: aether generally takes a long
time to process, and being able, in the consuming side, to read classpath
elements as they come, without having to wait for the whole internet to be
downloaded could enhance the user experience.
Edn explicitly makes this possible over xml. Thus the :pprint-edn would
become something like
{:java-args "...."}
{:classpath-arg ["one classpath element"]}
{:classpath-arg ["second classpath element"]}
The end would be marked just by closing of the stream. So someone just
wanting the whole info at once could just merge the top level forms with
conj
I understand this would be more work since it would probably require
implementing additional listener hooks into aether/pomegranate.
Just talking about it right now because it should probably be a design
choice of the :pprint-edn to be made early if we don't want to break things
later.

>
> The only question is whether there are any existing automated tools which
> rely on the current ad-hoc jvm args printing. Seems unlikely but possible.


I can start asking the usual suspect about it and also try a github search
though it may return a lot of false positives.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/technomancy/leiningen/issues/1956#issuecomment-131481305>
> .
>


-- 
Laurent Petit

**Comment by technomancy** [comment]
This is fixed in master.
