### ISSUE TITLE
2.5.2 producing incorrect classpath?

### ISSUE THREAD

**Issue by tdavis** [technomancy/leiningen#1960]
After upgrading to 2.5.2 from 2.5.1, lein can no longer compile my application; many java and clojure packages cannot be found. The output of `lein classpath` differs greatly between the two versions, and also between 2.5.2 release and a 2.5.2 snapshot I have available (4ab6de9b9c0fca5561a5edc58263bda82e1069f3).

Here are a couple examples where the classpaths differ significantly. Overall, there are 165 more entries in the correct classpath than the one 2.5.2 is reporting and none of the classes are in an exotic location, just ~/.m2/repository.

```
$ lein-2.5.2 classpath | tr : \\n | grep trapperkeeper
~/.m2/repository/puppetlabs/trapperkeeper/1.1.1/trapperkeeper-1.1.1-test.jar

$ lein-2.5.2-snapshot classpath | tr : \\n | grep trapperkeeper
~/.m2/repository/puppetlabs/trapperkeeper/1.1.1/trapperkeeper-1.1.1-test.jar
~/.m2/repository/puppetlabs/trapperkeeper/1.1.1/trapperkeeper-1.1.1.jar
~/.m2/repository/puppetlabs/trapperkeeper-webserver-jetty9/1.3.1/trapperkeeper-webserver-jetty9-1.3.1.jar

$ lein-2.5.2 classpath | tr : \\n | grep bouncycastle

$ lein-2.5.2-snapshot classpath | tr : \\n | grep bouncycastle
~/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.52/bcpkix-jdk15on-1.52.jar
~/.m2/repository/org/bouncycastle/bcpg-jdk15on/1.52/bcpg-jdk15on-1.52.jar
~/.m2/repository/org/bouncycastle/bcmail-jdk15on/1.52/bcmail-jdk15on-1.52.jar
~/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.52/bcprov-jdk15on-1.52.jar
```

I have tried `lein clean` but I have to assume I'm just doing something wrong as it relates to upgrading.

**Comment by hyPiRion** [comment]
This is strange, as I am unable to reproduce this on the projects I have tested this on. Do you have a minimal repro case? It may be related to profile merging issues.

**Comment by hyPiRion** [comment]
I haven't heard of anyone else having this issue, so I presume it's resolved. If this still is a problem, feel free to reopen. I'd like a reproducible test case if that's the case though, as I'm unable to produce this bug myself.

**Comment by arohner** [comment]
I have the same issue, though I haven't narrowed down the minimal test case:

```
$ lein-2.5.1 classpath | tr ":" "\n" | wc -l
     403
$ lein-2.5.2 classpath | tr ":" "\n" | wc -l
      27
```

**Comment by hyPiRion** [comment]
I'll keep this open, but I'll be unable to do any work without a reproducible case. Although I'd prefer a minimal test case, anything that spits out an erroneous classpath will do.

**Comment by arohner** [comment]
I have a few ideas I'll try soon.

**Comment by arohner** [comment]
Found it, I think. My project contained the following line:

```clojure
:profiles {:base {:dependencies ^:replace [[clojure-complete "0.2.3" :exclusions [org.clojure/clojure]]]...}
```

I don't recall why I added that, or what purpose it served, but the behavior is obviously different:

```
$ lein-2.5.2 classpath | tr ":" "\n" | wc -l
     409
```

My strong suspicion is that I added that line as a workaround for a previous bug. Feel free to mark this User Error, but the difference may be useful for you.

**Comment by hyPiRion** [comment]
Thanks! That's a good starting point.

I'd like to dig into this to at least just provide some valuable feedback to users struggling with the same thing, and figure out how they can resolve it.

**Comment by glts** [comment]
Going through the backlog … the profiles documentation says:

> The `:base` profile provides dependencies necessary for basic repl functionality … It is part of Leiningen itself; you shouldn't need to change it.

That seems quite clear to me; I wonder if there is anything more to do here.

**Comment by technomancy** [comment]
I think we're good here.
