### ISSUE TITLE
If git tag fails, lein silently ignores

### ISSUE THREAD

**Issue by timvisher** [technomancy/leiningen#1968]
Is this intentional behavior? Or could it be fixed/a pr made to the effect that if the tag fails to be created, the build fails.

Should be as simple as checking the return code of this call, I think. https://github.com/technomancy/leiningen/blob/9c5192e6520fb96aa625313a468e0143001f54ca/src/leiningen/vcs.clj#L67

**Comment by hyPiRion** [comment]
Oh yeah, that's not intentional. That's not specific to the tag command though, but to all of them.

If anyone want to have a stab at this, then I'd be happy if they fixed all of the cases, so that no exit code is ignored (unless it's sensible to do so).

**Comment by timvisher** [comment]
@hyPiRion Want to pick up that :pr:?

**Comment by timvisher** [comment]
@hyPiRion any chance of a patch release for this?

**Comment by timvisher** [comment]
@hyPiRion ping :)

**Comment by hyPiRion** [comment]
@timvisher: Whoops, it seems like I forgot to hit the send button.

I'd like to finish off a bit more of https://github.com/technomancy/leiningen/milestones/2.5.3 before that happens. I can see if I can speed up my PR reviews, so that the only outstanding issue is #1734.
