### ISSUE TITLE
No instruction for building leiningen 

### ISSUE THREAD

**Issue by johnbendi** [technomancy/leiningen#1971]
There is no instruction for building leiningen on the readme and I believe it should be there. Instructions for building all variants and a note on any special dependencies building may require.

**Comment by hyPiRion** [comment]
The building information is in contributing.md, but yeah, it should definitely be linked to in the readme.

**Comment by hyPiRion** [comment]
Is the link I've added in ee6d34e sufficient, or do you think we should make it even more visible? Now you can at least search for "building" and it will pop up.

**Comment by danielcompton** [comment]
A "Developers" section in the README might be more visible, and is what most projects do here.

**Comment by hyPiRion** [comment]
Right. I'm happy to take a PR for this then, if anyone's up to it.
