### ISSUE TITLE
Question: lein connecting to 188.93.79.52:80

### ISSUE THREAD

**Issue by zoowar** [technomancy/leiningen#1973]
I'm using lein-2.5.1. Today I it became extremely slow and I noticed it is trying to connect to 188.93.79.52:80 which is not responding and doesn't have a dns entry. Can someone shed some light on why lein is connecting to 188.93.79.52:80?

**Comment by technomancy** [comment]
This must be due to one of your plugins or profiles. Hard to say more without knowing how you've configured it.

**Comment by zoowar** [comment]
Thanks. Looks like it's [lein-cljsbuild "1.0.4"]. This was working a couple of days ago. I updated to the latest version [lein-cljsbuild "1.1.0"] and still see the issue. I'll follow up with them.
