### ISSUE TITLE
Leiningen hangs, doesn't exit

### ISSUE THREAD

**Issue by Immortalin** [technomancy/leiningen#1983]
Hi, when I am doing java interop using [this](https://github.com/mohaps/xtractor), leiningen hangs at both compile and uberjar and sometimes uses up increasing amounts of memory, causing the computer to hang. The problem seems to lie with the interop. Without utilizing any java code, the code compiles perfectly. This is my code(it has been reduced to its simplest form i.e. only the interop):

```clojure
(ns scraper.core
  (:gen-class)
  (:import [com.mohaps.xtractor Extractor]
           [com.mohaps.fetch Fetcher]
           [de.jetwick.snacktory SHelper])
           )

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println "Hello, World!"))

(Fetcher.) ;; removing this line fixes everything.
```

Here's my project.clj:

```clojure
(defproject scraper "0.1.0-SNAPSHOT"
  :description "A Web Scraper"
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [com.mohaps/xtractor "1.0-SNAPSHOT"]
                 [dk.ative/docjure "1.9.0"]
                 [de.jetwick/snacktory "1.1" :exclusions [log4j]]]
  :repositories [["karussell_releases" "https://github.com/karussell/mvnrepo/raw/master/releases/"]]
  ;; :java-source-path "../web-scraper/.lein-git-deps/xtractor/src/main/java"
  :main scraper.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}}
  )
```

When using lein run, leiningen prints the hello world but doesn't exit.

The java library is installed locally by cloning it and then running mvn install. 
Leiningen also sometimes doesn't cleanly exit when running other commands and has to be ended via Ctrl-C. Drip is enabled.

**Comment by technomancy** [comment]
Something in your dependencies is starting a background thread or threadpool; this doesn't really have anything to do with Leiningen.
