### ISSUE TITLE
Releases 2.5.1 and 2.5.2 no longer publish a standalone jar

### ISSUE THREAD

**Issue by RickMoynihan** [technomancy/leiningen#1987]
Hi,

Technomancy used to publish standalone leiningen jar releases, yet the newer releases no longer seem to do this.

It would be awesome if these could be re-instated on the releases page, as these builds are really useful in some environments; e.g. when using the jenkins leiningen plugin:

https://github.com/technomancy/leiningen/releases

**Comment by RickMoynihan** [comment]
Just realized I was being stupid - the zip is the jar; is there any reason the file extension changed?

**Comment by hyPiRion** [comment]
I think the commit message in f48846ff3cce9158d2c8ec5e6b488d45d74d286d explains it pretty well.

It's just because GitHub doesn't allow us to upload jars.

**Comment by RickMoynihan** [comment]
Strange why they'd do that... Thanks for the reply though! :-)

**Comment by hyPiRion** [comment]
It's weird, because a jar is pretty much just a zip with a different file name =/
