### ISSUE TITLE
[Enhancement] Template source saving

### ISSUE THREAD

**Issue by ClashTheBunny** [technomancy/leiningen#1995]
I have been learning Clojure for a while and one little nit I have is that I can't go look up what template I used to create a project.  And it's usually fairly far into working with a template that I want to either open a bug or check if there is a new version with better usability.  This is specifically with the 8 million different react-figwheel options out there that all do very similar things but have subtle differences and features.

I would like that when I do a `lein new template-name project-name +option1 +option2` I end up with a project.clj with information about the version, name, options, and git-repo or clojars path of the template.  This way I can check if there are updates and where I would look for them.

I know the big problem with this is that lein is so flexible that it can't guarantee that there will even be a project.clj.  Would a plugin be possible that checks any new project's project.clj or boot.build for this metadata and warns you that it's missing?  How do we get the culture change in the Clojure community that helps users with this traceability?  The simplest possibility would be a dumb plugin that just spits out the command just used to create the project in a random file, like `.lein-create-command`

Thanks!

**Comment by hyPiRion** [comment]
Templates are, well, templates, and should in general work out of the box.

If the template has a lot of options and you want to add in recent changes in the template to a project that uses it, then I believe this is a symptom of a bigger issue. Either the functionality provided by the template should be in a plugin or dependency which you can bump, and/or the template may be trying to do more than it should. Adding this functionality would only defer us from solving the "real" problem.

That being said, there's no problem asking the owners of bigger templates to add in this information in a file/`project.clj`, or make a plugin that does this for you.

Perhaps one of the issues is that plugin developers aren't aware of the fact that [plugins can contain profiles](https://github.com/technomancy/leiningen/blob/master/doc/PLUGINS.md#profiles). I guess that many of these problems could be resolved by this. Another option would be to find an idiomatic way to let plugins generate (repeatable) profiles for you.

Perhaps it's more sensible to look at the bigger plugins and ask them to do something like this instead?

**Comment by technomancy** [comment]
I don't think there's a general-purpose solution for this within Leiningen itself since we can't make any assumptions about the structure of the output of a template.
