### ISSUE TITLE
Correct way to use `[:repl-options :init]` for composability?

### ISSUE THREAD

**Issue by gfredericks** [technomancy/leiningen#1997]
I'm currently trying to decide how to deal with the way [this](https://github.com/greglook/whidbey/blob/eff232c960be8ed933e7f6e35d04d9c6a0e32155/src/whidbey/plugin.clj#L26) bit of code composes with my own `[:repl-options :init]`. The two relevant forms look something like:

``` clojure
(do a b)

(do c d)
```

I assume leiningen is combining them with `into`, obtaining the result:

``` clojure
(do a b do c d)
```

which rightly complains about `do` not resolving.

I'm thinking that if all `[:repl-options :init]` everywhere were wrapped in a vector, this would work okay. Then `[(do a b)]` and `[(do c d)]` would become `[(do a b) (do c d)]`. I think this might break certain uses where earlier expressions in the `do` need to be executed before later expressions can be compiled.

Is there anything else I'm missing? Should I recommend that the linked project wrap its expression in a vector?

**Comment by hyPiRion** [comment]
Lein combines them with `concat` (unless I'm overlooking something), so the result would be `((do a b) (do c d))`.

I guess the best thing to do is to wrap them in `(list ...)`. Combining `(list (do a b))` with `(list (do c d))` would at least not cause the merging to fail, although it won't help if one block depends on another.

See also #878.

**Comment by gfredericks** [comment]
Wouldn't concat give `(do a b do c d)`, with essentially the same problem? Otherwise I'm not sure what's causing the behavior I'm seeing.

**Comment by hyPiRion** [comment]
Oh, I was talking about the forms `[(do a b)]` and `[(do c d)]`.

**Comment by hyPiRion** [comment]
@gfredericks: Has this been answered, or is this still an issue?

If you do a concatenation of `(list (do a b c))` and `(list (do d e f))`, you end up with `(list  (do a b c) list (do d e f))`, which (although hacky) should work.

**Comment by gfredericks** [comment]
Sorry, I'm bad at following up on this. Am swamped by conj prep at the moment, don't mind if you want to close the issue to get it out of the way. I'm sure I'll figure something out ☺.

**Comment by hyPiRion** [comment]
Oh, no worries. I'm in no need of closing issues if it's not actually resolved :)

**Comment by hyPiRion** [comment]
@gfredericks: Pinging you one last time before I decide to close this =) Does the workaround I've mentioned above work for the case you have?

**Comment by gfredericks** [comment]
AAAUUUGHHH!!!
