### ISSUE TITLE
"Active profiles" in %s not consistent with actually active profiles

### ISSUE THREAD

**Issue by curtosis** [technomancy/leiningen#2001]
Given the following:
```
:target-path "target/%s/"
:profiles
{:prod      [:profiles/production :uberjar]
 :uberjar  {:omit-source true :env {:foo ... } ...}
 :beta-ui  {:env {:beta-ui true}}}
```

Calling `lein with-profile prod,beta-ui ring uberwar` gives the target path `target/production+uberjar+uberjar`.

That is, `:uberjar` is included twice (the uberwar task loads it, plus the explicit mention in the composite `:prod`), while the explicit `:beta-ui` is ignored.

Deleting the explicit `:uberjar` composite mention gives `target/production+uberjar`, with `:beta-ui` still missing. (`lein pprint` does show that the specified profiles are being merged as expected.)

The `%s` expansion also ignores `:project/dev` and `:profiles/dev` when run without explicit profiles -- presumably because they're pulled in by `:default`? 

The end result is that it is not at all clear why a particular profile name does or does not get merged into the `%s` spec.

`

**Comment by hyPiRion** [comment]
It's a bit unexpected that uberjar shows up twice, but the rest is intentional. 

uberjar and pom will filter away all non-leaky profiles. That is, all profiles that has the metadata `^:leaky` attached to it, along with `:uberjar` and `:default`. See the [profile metadata](https://github.com/technomancy/leiningen/blob/stable/doc/PROFILES.md#profile-metadata) in the profiles documentation for more information.

**Comment by curtosis** [comment]
Ah, that's helpful! I've spent a lot of time on that page, but glossed over that, since it didn't seem immediately relevant.

(Though I'm not sure yet what it means for a profile to be stripped out, in general. I think get it for pom and uberjar, where you don't want everything blindly dumped into the pom or web.xml, but it's a little fuzzy what the rest of the implications are.)

**Comment by curtosis** [comment]
More data points, after additional testing:
- `^:leaky` **does** get passed through to the `uberjar` task.
    - `:uberjar` gets listed twice under the `uberjar` task.
- `^:leaky` profiles do *not* get passed through to `ring uberwar` and `ring uberjar`.
    - `:uberjar` gets listed once under the `ring uberwar` task
    - `:uberjar` gets listed three and **seven** (!) times under the `ring uberjar` task (`ring uberjar` builds two `target/%s/` directories).

I've done a little digging into the `lein ring` handoff, but haven't gotten very far yet.

**Comment by hyPiRion** [comment]
how ring uberwar/-jar works is independent of how lein's own uberjar works. We can't control how the ring plugin sets up the profiles, that is up to them.

**Comment by andrew-nguyen** [comment]
@hyPiRion I'm not sure if this is related (working on isolating the issue for a new issue) but I am running into a problem where the `uberjar` profile is being included twice (thus causing problems with cljsbuild since it's seeing duplicates).  I am not using `lein ring/uberwar`
