### ISSUE TITLE
Can't use S3 Wagon Private when :eval-in-project is set

### ISSUE THREAD

**Issue by danielcompton** [technomancy/leiningen#2011]
I'm trying to deploy a Leiningen plugin to a private repository using S3 wagon private. However when `:eval-in-leiningen true` is set, Leiningen isn't able to find the S3 wagon, and it's not able to deploy to the private repo. It seems like the plugin isn't being run at the right point. Is this an inherent limitation of Leiningen or is there a way around it?

**Comment by hyPiRion** [comment]
It might be a bug with S3 wagon, but it might be a bug in Lein as well. Have you put up an issue in their issue tracker?

**Comment by technomancy** [comment]
This happens because there is a circular dependency during project initialization between the plugins and the dependencies themselves when leiningen is run with `:eval-in :leiningen`. Unfortunately I don't believe there's a way to solve this without creating other more serious problems.
