### ISSUE TITLE
install lein error

### ISSUE THREAD

**Issue by zhenghub** [technomancy/leiningen#2012]
I ran this command to install:

> wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein && chmod u+x lein && ./lein

And it failed:
> Downloading Leiningen to /home/zhenghu/.lein/self-installs/leiningen-2.5.3-standalone.jar now...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
Failed to download https://github.com/technomancy/leiningen/releases/download/2.5.3/leiningen-2.5.3-standalone.zip (exit code 77)
It's possible your HTTP client's certificate store does not have the
correct certificate authority needed. This is often caused by an
out-of-date version of libssl. It's also possible that you're behind a
firewall and haven't set HTTP_PROXY and HTTPS_PROXY.

However I can easily download https://github.com/technomancy/leiningen/releases/download/2.5.3/leiningen-2.5.3-standalone.zip using wget:
>wget https://github.com/technomancy/leiningen/releases/download/2.5.3/leiningen-2.5.3-standalone.zip

**Comment by hyPiRion** [comment]
I am unable to reproduce this, but it seems to be an issue with CURL and lack of certificates. If you are running linux, installing the ca-certificates should resolve this issue. For OS X, it seems like http://apple.stackexchange.com/questions/95538/how-to-fix-curl-throwing-error-setting-certificate-verify-locations has some pointers to solve the issue.

As a workaround, running `HTTP_CLIENT="wget -O" ./lein` should work fine. Repeated lein commands should work fine (but _may_ break if you lack certificates). When you need to upgrade lein itself, you would need to call `HTTP_CLIENT="wget -O" ./lein upgrade`.

**Comment by zhenghub** [comment]
My os is debian 8 and the first plan didn't work because I have ca-certificates already installed.
Plan B works though it needs root authority.

**Comment by hyPiRion** [comment]
@zhenghub, alright, could you try this?

```shell
sudo mkdir -p /etc/pki/tls/certs
sudo cp /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt
```

**Comment by zhenghub** [comment]
@hyPiRion 
It works!
Thank you very much!

**Comment by hyPiRion** [comment]
No problem :)
