### ISSUE TITLE
lein can't find java on Cygwin under Windows10?

### ISSUE THREAD

**Issue by crunch3** [technomancy/leiningen#2013]
$ lein
/d/Users/Mike/.lein/bin/lein: line 359: D:\Programs\Java\jdk1.7.0_25\bin\java.exe: command not found

My account has a variable LEIN_JAVA_CMD = D:\Programs\Java\jdk1.7.0_25\bin\java.exe
and java IS there (sh runs it without complaint)

$ echo $LEIN_JAVA_CMD
D:\Programs\Java\jdk1.7.0_25\bin\java.exe

$ which java
/d/Programs/Java/jdk1.7.0_25/bin/java

$ java -version
java version "1.7.0_25"
Java(TM) SE Runtime Environment (build 1.7.0_25-b16)
Java HotSpot(TM) 64-Bit Server VM (build 23.25-b01, mixed mode)

what am I missing?

**Comment by hyPiRion** [comment]
What happens if you unset the `LEIN_JAVA_CMD`, or set it to `/d/Programs/Java/jdk1.7.0_25/bin/java`?

**Comment by crunch3** [comment]
$ unset LIEN_JAVA_CMD
$ lein
/d/Users/Mike/.lein/bin/lein: line 359: D:\Programs\Java\jdk1.7.0_25\bin\java.exe: command not found

**Comment by crunch3** [comment]
$ unset LEIN_JAVA_CMD
$ echo $LEIN_JAVA_CMD
$ lein
Leiningen is a tool for working with Clojure projects.
Several tasks are available:
....

cool, thanks.  Any idea why?

**Comment by juergenhoetzel** [comment]
@crunch3 You have to use Cygwin/Unix paths. See https://cygwin.com/cygwin-ug-net/using.html#cygdrive

In your case: `export LEIN_JAVA_CMD=$(cygpath.exe -u "D:\Programs\Java\jdk1.7.0_25\bin\java.exe")`

**Comment by hyPiRion** [comment]
Closing this as this seems to be resolved. Feel free to reopen if you still have issues.
