### ISSUE TITLE
Allow disabling user profiles warning via project map

### ISSUE THREAD

**Issue by glenjamin** [technomancy/leiningen#2016]
Would you accept a PR that allows silencing this warning via a `profiles.clj` setting, rather than just the environment variable?

https://github.com/technomancy/leiningen/blob/master/leiningen-core/src/leiningen/core/project.clj#L614

I've read the docs on https://github.com/technomancy/leiningen/wiki/Repeatability, and while I agree in principle - I'd rather keep the location of our corporate repository outside of `project.clj`.

**Comment by hyPiRion** [comment]
I'm not entirely sure why you'd like to keep the location outside of `project.clj`, could you elaborate? I don't have big issues with a PR for this, just curious to know what the rationale is.

**Comment by technomancy** [comment]
You can put something like this at the top of your `project.clj` file to suppress the warnings:

```clj
(alter-var-root #'leiningen.core.project/warn-user-repos (constantly constantly))
```

It's a bit clearer that you're working against the recommendations of Leiningen, and you don't have to go around making sure that all the machines have the env var set.

**Comment by technomancy** [comment]
Oh, except that apparently this already exists: `LEIN_SUPPRESS_USER_LEVEL_REPO_WARNINGS`, cool.

**Comment by glenjamin** [comment]
@hyPiRion I had a bunch of use-cases, but I've just spotted https://github.com/technomancy/leiningen/blob/master/sample.project.clj#L113 - and that covers all of them.
