### ISSUE TITLE
Allow custom git commit release message when releasing

### ISSUE THREAD

**Issue by saulshanabrook** [technomancy/leiningen#2018]
I would love to be able to set a custom commit message when using the `["vcs" "commit"]` release task.

It [looks like currently](https://github.com/technomancy/leiningen/blob/d701275464c185f4f22be58450b1af4b94a79836/src/leiningen/vcs.clj#L68) it just does `Version <version number>`. I would love to be able to add `[skip ci]` to the commit message. 

Would you accept a pull request that adds that feature? I see it as similar to `git tag` where you can just a prefix to each commit. So then I could do `["vcs" "commit" "[skip ci] "]` which change the commit message to `[skip ci] Version <version number>`.

We could add more flexibility, to add any sort of string, but a prefix or suffix would suffice for my purposes.

**Comment by hyPiRion** [comment]
This is somewhat related to #1992.

**Comment by hyPiRion** [comment]
@saulshanabrook: To answer your question: I'd be fine with adding a `:vcs-commit-string` option, where `"Version %s"` is the default if not found. The `%s` argument should be the project's `:version` value.

This should be backwards compatible with other VCS implementations (hg and so forth), and then we could see if there is a better way to do this for 3.0.0.

**Comment by hyPiRion** [comment]
@saulshanabrook, I guess this would be of interest to you: I released [ein-shell](https://github.com/hyPiRion/lein-shell) 0.5.0 yesterday, which gives you the option to do `["shell" "git" "commit" "-m" "[skip ci] Version ${:version}"]` in the :release-tasks vector.

Still happy to have this implemented as I previously outlined though.

**Comment by saulshanabrook** [comment]
@hyPiRion That worked great for my purposes, so I am going to close this since I know longer need this feature. Thank you so much! I just [wrote up a blog post](http://www.saulshanabrook.com/tests-docs-and-deploys-for-clojure/) on getting this whole process working, including using that feature.

**Comment by hyPiRion** [comment]
Glad to hear that it worked out! :)
