### ISSUE TITLE
Support Windows "Take Command" alternative shell in lein.bat

### ISSUE THREAD

**Issue by m9aertner** [technomancy/leiningen#2019]
I'm using an alternative Windows Shell named "Take Command", not plain CMD.EXE. See [https://jpsoft.com/] (the TCC/LE variant can be downloaded/used free of charge).

I find that two minor amendments are required to make this work _cleanly_ with `lein.bat`
1. One delete command does not redirect stdout, unlike other similar existing uses in `lein.bat`.
2. The classpath does not get set in TCC, simply re-ordering the condition helps.

I'll provide a pull request. Note that these amendments are compatible with CMD.EXE.

**Comment by hyPiRion** [comment]
Hi there,

Thanks for looking into this – I would obviously have no issues with a pull request fixing this :)

**Comment by m9aertner** [comment]
Let me do some more testing, by following the CONTRIBUTING.md instructions...

**Comment by hyPiRion** [comment]
Just a heads up, #1899 tells that there may be some issues building the uberjar on Windows – that may also be an issue for testing lein itself. Since this is a modification of `lein.bat` though, you could try it out on a copy of the `lein.bat` you use in day-to-day work.

**Comment by m9aertner** [comment]
Solved as part of #1899, see PR #2023
