### ISSUE TITLE
why lein not -path parameter

### ISSUE THREAD

**Issue by xingzhefeng** [technomancy/leiningen#2029]
example:
cd /home/one  
nohup lein ring server > /dev/null >my.log 2>&1& echo $! > run.pid

I want   Remove cd steps . 
like nohup lein -path '/home/one' ring server > /dev/null >my.log 2>&1& echo $! > run.pid

**Comment by hyPiRion** [comment]
Is there any specific reason you'd like to remove the cd steps?

**Comment by xingzhefeng** [comment]
I want system start up the commond start

**Comment by hyPiRion** [comment]
So I assume you can do that in a script or directly via `cd foo && nohup lein ...; cd -`, right?

Just wondering whether this is an actual limitation or a convenience for users.
