### ISSUE TITLE
Launching a REPL (in an empty directory) is really slow

### ISSUE THREAD

**Issue by wolverian** [technomancy/leiningen#2031]
Compare the launch time in an empty directory:

```
$ ls -a
.   ..
$ time echo '(+ 1 2)' | lein real                                                                                                                        
[cut]
    0m6.22s real     0m11.94s user     0m0.66s system
```

vs

```
$ time echo '(+ 1 2)' | java -cp /Users/iv/.m2/repository/org/clojure/clojure/1.7.0/clojure-1.7.0.jar clojure.main                                       
[cut]
    0m1.13s real     0m2.00s user     0m0.13s system
```

That's a slowdown of 600%, which I think is a bug.

Environment:

```
$ uname -a                                                                                                                                               
Darwin dune.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
$ lein version
Leiningen 2.5.3 on Java 1.8.0_65 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by wolverian** [comment]
This is with an empty `profiles.clj`

**Comment by hyPiRion** [comment]
If you're interested in benchmarking the actual `clojure.main` function, then I'd suggest you call `clojure.main` from lein itself. `lein repl` is not equivalent to `clojure.main`:

```
$ time lein run -m clojure.main/main -e '(+ 1 2)'
3
lein run -m clojure.main/main -e '(+ 1 2)'  1.60s user 0.04s system 141% cpu 1.158 total
$ time java -cp ~/.m2/repository/org/clojure/clojure/1.7.0/clojure-1.7.0.jar clojure.main -e '(+ 1 2)'
3
java -cp ~/.m2/repository/org/clojure/clojure/1.7.0/clojure-1.7.0.jar  -e '(+ 1 2)'  1.72s user 0.02s system 191% cpu 0.909 total
```

(Your mileage may vary, obviously)

Regardless of this, Leiningen has to spin up another JVM for itself, which is the cause of this slowdown. 

If this is a problem, you usually have two options: 

- Change the workflow to be more REPL-oriented – most people spin up a repl when they start developing (usually through Cursive/CIDER), and only restart it when they have to
- Using [Grenchman](https://github.com/technomancy/grenchman)

**Comment by technomancy** [comment]
Though more specific suggestions are welcome, I don't think there's anything actionable here.
