### ISSUE TITLE
Plugin middleware :injections poorly documented

### ISSUE THREAD

**Issue by mvitz** [technomancy/leiningen#2033]
I created a sample plugin with the code from https://github.com/technomancy/leiningen/blob/master/doc/PLUGINS.md#project-middleware

However when I use this plugin the file is never written.

**Comment by mvitz** [comment]
I tried all leiningen versions from 2.5.x and 2.4.x (unfortunately 2.3.x can not be installed automagically by lein because the S3 Bucket changed). None of these works. If this is intended maybe you just can answer how the current best practice is for generating files when leiningen is run.

I'm also confused by the feature to create src,test and resources directories if they do not exist. Creating folders that the user doesn't want seems to be a bad practice for me ;-)

**Comment by hyPiRion** [comment]
I'm guessing this is bad documentation, I will have a better look later today.

The "feature" that creates directories is actually a bug; see #2010.

**Comment by hyPiRion** [comment]
Yeah, that documentation is a bit unclear. Happy to take a patch that improves the documentation.

To get you on your merry way for now: Say you have a plugin named `foobar` (which you have created by typing in `lein new plugin foobar`), then the source file for activating middleware should be in the location `src/foobar/plugin.clj`, and it should contain the following:

```clj
(ns foobar.plugin)

(defn middleware [project]
  (update-in project [:injections] concat
             `[(spit "resources/project.clj" ~(prn-str project))]))
```

If the version of foobar is `"0.1.0-SNAPSHOT"`, then you do `lein install` in the plugin project's root and depend on it in another project via `[foobar "0.1.0-SNAPSHOT"]`. Running `lein repl` in the project that depends on this plugin should now yield a copy of project.clj in the resources directory.

**Comment by mvitz** [comment]
Thanks this works. The key point was calling `lein repl` instead of `lein jar` or `lein uberjar`.

What I want is to generate a file on each build. Is there any way to accomplish that? It seams injections are only evaluated under special circumstances.

**Comment by hyPiRion** [comment]
https://github.com/technomancy/leiningen/blob/e9efb0e279ed41800e025f3da5607db710bc6059/sample.project.clj#L243-L245 describes injections succinctly. It is probably better explained in the link provided, http://technomancy.us/143.

**Comment by mvitz** [comment]
Thanks.

In the meantime can you answer my question (and primary problem):
How to generate a file on each build with leiningen. This file should be generated regardless of what task I call.

**Comment by hyPiRion** [comment]
I'd recommend to put those things in `:prep-tasks`. For example, if you want to invoke `make` (via lein-shell) before any task that runs, then you can add this to your project.clj:

```clj
;; (defproject ... 
    :prep-tasks [["shell" "make"] "javac" "compile"]
;; ...
```

**Comment by hyPiRion** [comment]
I have added some pointers on how to read project map, removed the poorly thought-out example of how to create middleware and added a note that `:injections` does not apply to jars or uberjars.

That being said, I guess what you wanted was some guide to the`:prep-tasks` option. I am guessing this doesn't make it easier to find it, but at least you won't be tricked into assuming the middleware or :injections can help you with it.

If you have any thoughts on how we can make it a bit easier to find, I'm all ears and would love some input on it.
