### ISSUE TITLE
Add a way to get the project version in release tasks

### ISSUE THREAD

**Issue by danielcompton** [technomancy/leiningen#2034]
In my release tasks I want to be able to copy files to a path with the lein-shell plugin, but that path needs to include the project's version number. Without going through complex machinations sub shelling and running more scripts, it's not clear to me how to get the project version.

Does something like this exist when running release tasks? I'm not sure if this is belongs in Leiningen's domain or lein-shell, apologies if it's in the wrong spot.

**Comment by hyPiRion** [comment]
I have created hyPiRion/lein-shell#21 for that specific issue. Not sure if this helps, but :project/foo inside call vectors will expand to the project parameter foo: `["shell" "cowsay" :project/version]` would for example emit the version you're on.

**Comment by technomancy** [comment]
I think `:project/version` mentioned here is exactly the thing. Feel free to reopen with more details if that isn't enough.
