### ISSUE TITLE
leiningen forces the creation of unneeded directories

### ISSUE THREAD

**Issue by hiredman** [technomancy/leiningen#2040]
You can see my comment on the commit https://github.com/technomancy/leiningen/commit/e9d6d7885777537fe3b50f3308b8fec44a65c391

**Comment by hiredman** [comment]
The best way to solve the issue in the original pr is likely to have lein new create whatever directories, and then don't re-create the directories whenever lein runs so I can still delete them and they stay deleted.

**Comment by hyPiRion** [comment]
Duplicate of #2010.
