### ISSUE TITLE
Manifest not getting populated with "lein with-profile foo ring uberwar" in 2.5.3

### ISSUE THREAD

**Issue by fgiasson** [technomancy/leiningen#2041]
I have to add some build information (from Jenkins) into a WAR generated by Leiningen. What I will describe below was working with version `2.5.1` but is not with `2.5.3`.

I added that property to the `tomcat` profile:

```clojure
  :profiles {:tomcat {:manifest {"Build-Number" #=(eval (System/getenv "BUILD_NUMBER"))}}}
```

When I was deploying my application using:

```
lein with-profile tomcat ring uberwar
```

That information is not added to the manifest file. However, it was working in lein `2.5.1`. This `:manifest` option is also available in the global scope of my `defproject` such that it works with `uberjar` (`uberjar` work as expected).

What I am wondering is if this is a new bug or if there is a new way to define that `:manifest` property.

**Comment by hyPiRion** [comment]
Could you see if adding `^:leaky` onto the profile, like 

```
 :profiles {:tomcat ^:leaky {:manifest {"Build-Number" #=(eval (System/getenv "BUILD_NUMBER"))}}}
```

works?

**Comment by fgiasson** [comment]
Hi @hyPiRion,

No, same behavior. By the way, what `^:leaky` is supposed to do?

**Comment by hyPiRion** [comment]
If you mark your profile with ^:leaky metadata, then the profile will not be stripped out when the pom and jar files are created. Apparently this doesn't seem to work the same way with lein-ring's uberwar.

I checked lein-ring's issue list, and I couldn't find anything that seems like the issue. The closest I could see was weavejester/lein-ring#163. If that's the issue, then this should be resolved on master.

**Comment by fgiasson** [comment]
Hi @hyPiRion,

Ok great, didn't thought about looking into `lein ring` for that. Let me try that tomorrow, and I will comment on what I find then.

Thanks!

**Comment by fgiasson** [comment]
@hyPiRion thanks for the hint, this solved my issue! So upgrading to the latest `lein ring` made it.
