### ISSUE TITLE
Add ':build' version number to release task, to support 4-digit version numbers

### ISSUE THREAD

**Issue by cprice404** [technomancy/leiningen#2049]
Currently the 'change' part of the lein release task supports 3 version number levels: `:major`, `:minor`, and `:patch`.

Some of our projects use a 4th digit to represent the build version.

Would you be amenable to a PR that add support for a value of `:build` being passed in for the `change` level?

**Comment by hyPiRion** [comment]
I am happy to take a patch for this if this is backwards compatible and well documented.

**Comment by cprice404** [comment]
Awesome, thanks.

**Comment by cprice404** [comment]
Started poking at this today and it seems like it would be easy to implement and write tests for; the one question / concern that I have is that the comments in the code repeatedly refer to the SemVer specification from http://semver.org, and that spec does not allow a 4th digit in the version number.  It seems to recommend putting a build number in the qualifier string after the hyphen, e.g. `1.0.0-25`.

Maven's version number scheme sounds like, while it will technically support 4-digit version numbers, it will probably screw up any tooling that attempts to do version number comparisons:

https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN400

Meanwhile, both RPM and DEB package versioning rules seem to support an arbitrary number of dot-separated numerics, and do not allow hyphens.  So, yay for standards and practices.  :(

We automatically build RPMs and DEBs from our projects, so conforming to their versioning rules is really what was inspiring this feature request, but it seems like it probably makes more sense to keep leiningen in compliance with the way that maven wants to version things... so I'm waffling on whether or not this is a good idea for an official leiningen patch or not.

**Comment by cprice404** [comment]
I decided that it might make more sense to do the 4digit-version thing as a separate lein plugin.  I did my best to make it backward-compatible with the built-in release/change stuff.

Code is here:

https://github.com/puppetlabs/lein-release-4digit-version

Hoping to do a clojars release soon and then will probably add that to the plugins wiki page and close out this issue.

**Comment by hyPiRion** [comment]
Thanks for looking into this! Based on the points brought up here, I'll guess that this is something we will never end up supporting officially, because we'd like to be compatible with the general JAR/Maven scheme used.

I have added lein-release-4digit-version to the deployment section on the Plugins wiki page though, which should be sufficient for those in need: https://github.com/technomancy/leiningen/wiki/Plugins#deployment

**Comment by cprice404** [comment]
Great, thanks.  I'm trying to validate that that plugin will work properly with both the existing versions of lein and the next release (when #2050 ships).  Hoping to release the plugin to clojars sometime this week.

**Comment by cprice404** [comment]
Just to tie off the thread here:

0.1.0 is released to clojars: https://clojars.org/lein-release-4digit-version
