### ISSUE TITLE
Add a debug-do command

### ISSUE THREAD

**Issue by johnwalker** [technomancy/leiningen#2051]
Would it be possible to have a command that runs a plugin sort of like lein-try, but sandboxed and totally isolated from the users profile.clj / project.clj?

```
Usage:

lein debug-do [lein-plz "0.1.0"] plz add thing

lein debug-do [[lein-plz "0.1.0"], ...] plz add thing

lein debug-do [plugins] command command-arguments
```

Most of the issues I receive for lein-plz are related to the way dependencies of different plugins interfere with one another, and I assume it's the same for other plugins. The debugging cycle starts by asking users to write their project.clj, and then I guess whether there is interference or ask them to write lein deps :tree. It'd be nice just to see if things work without telling users to comment out other dependencies or any of that stuff.

**Comment by hyPiRion** [comment]
That should be doable as a plugin without any dependencies, not sure if that defeats the purpose or not.

I'm not sure I'd like to introduce a task into Lein proper, whose only purpose is to run completely isolated. On the other hand, I'd like to help out with debuggability, so thoughts here are welcome.

How often do people end up with dependency issues in plugins? Maybe it's worth looking at better isolation for plugin tasks as well, if need be.

**Comment by technomancy** [comment]
Echoing the sentiment that this belongs in a plugin first; once it is proven and stabilized we can discuss inclusion in Leiningen proper.
