### ISSUE TITLE
How to save the REPL code into file?

### ISSUE THREAD

**Issue by netroby** [technomancy/leiningen#2052]
I am runnig lein repl to start a REPL shell. then i wrote lot's of code. 
Now i want to save them into file. how can i do it?

**Comment by hyPiRion** [comment]
The REPL that comes with Leiningen does not provide functionality to save what you've written. I don't think REPLs in general provide this as it usually doesn't make sense. It's better to just use CIDER/Cursive or any other tool that gives you tools to evaluate pieces of a file in a (lein) repl instead.

The closest would probably be the file `~/.lein/repl-history`, but it doesn't separate REPL sessions.

**Comment by xiongtx** [comment]
This would be a really nice feature. Java 9's [JShell](http://openjdk.java.net/jeps/222) has `/save` and `/open` options that save / load REPL commands, which is really 😎 .

**Comment by netroby** [comment]
@hypirion so how do you rethink this? any new idea?

**Comment by netroby** [comment]
ping @technomancy

**Comment by technomancy** [comment]
This could either be done as an nrepl middleware or as a new feature in https://github.com/trptcolin/reply which is the CLI repl client that Leiningen uses. If you do it as a middleware then you can use that feature no matter what client you use.

**Comment by netroby** [comment]
I mean the `lein repl` can support this ?

**Comment by technomancy** [comment]
> I mean the lein repl can support this ?

You can add middleware to lein repl which can support all kinds of
amazing features that no one has thought of yet. But you have to write
the middleware first if it doesn't exist, and I don't think this one does.

**Comment by xiongtx** [comment]
> You can add middleware to lein repl

This is nREPL middleware, right? It's not specific to Lein?

Also, [are inputs stored in the REPL session](https://clojurians.slack.com/archives/C0AB48493/p1513739354000009)? CIDER [keeps track of its own REPL input history](https://github.com/clojure-emacs/cider/blob/master/cider-repl-history.el), so I'm guessing the answer is no?

**Comment by technomancy** [comment]
> This is nREPL middleware, right? It's not specific to Lein?

Yeah.

> Also, are inputs stored in the REPL session? CIDER keeps track of its
> own REPL input history, so I'm guessing the answer is no?

You'd need to track it yourself, but it shouldn't be difficult since you
need to intercept input anyway in order to watch for commands, I think.

-Phil
