### ISSUE TITLE
Problem with install script on Ubuntu 

### ISSUE THREAD

**Issue by petegrif** [technomancy/leiningen#2053]
Have successfully installed on Macs but having problems on Ubuntu.
When I execute lein I get the following error:

Could not transfer artifact cider:cider-nreply:pom:0.8.1 from/to central (https://repo1.maven.org/maven2/): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.

Any help appreciated.

**Comment by hyPiRion** [comment]
This is usually because Java doesn't have the certificates (cacerts) where it expects them to be.

The fix for that is usually

```shell
sudo update-ca-certificates -f
```

if that doesn't work, try

```shell
sudo apt-get install --reinstall ca-certificates-java
```

**Comment by petegrif** [comment]
@hyPiRion - no luck I'm afraid.  Could it be to do with the version of java I have installed?

"openJDK version "1.8.0_66-internal"
"openJDK Runtime Environment (build 1.8.0-66-internal-b17)"
"openJDK 64-bit Server VM (build 25.66.b17, mixed mode"

**Comment by petegrif** [comment]
Reverted to 1.7
still got problems but suspect it may be due to clojars.org being down.
anyone have any helpful information on this?

**Comment by petegrif** [comment]
Got it
there was a spelling mistake in the dependency in profiles.clj

cider/cider-nreply0.8.1

should read 

cider/cider-nrepl0.8.1

Be good to fix it and save some other poor newbie.  :)

**Comment by hyPiRion** [comment]
Oh dangit.

Although `This could be due to a typo`-message is pretty clear on what one should check, I'd keep this open for some time as the error message is very misleading. If it's possible to make it slightly less confusing without removing the exception, I'd be happy to take a patch for that.

**Comment by petegrif** [comment]
Whilst the message is reasonably clear in retrospect, a newbie like me had absolutely no idea where I should check for a possible "typo in :dependences".  I had to do a lot of digging to better understand the whole structure of the installation before I managed to track it down (with the problem being compounded by intermittent inability to access clojars.org throwing up other errors) even though the error was indeed trivial.

But all's well that ends well and I have a lot better understanding now. :)  Thanks again.

**Comment by pietromenna** [comment]
Is this still an issue?

**Comment by pepijndevos** [comment]
I have the same issue after a fresh `apt-get install leiningen`, `lein new blah`, `lein deps`. I tried the CA commands, to no avail. The project.clj is unchanged, and only contains `[org.clojure/clojure "1.8.0"]` as a dependency. I'm also not behind a proxy. I'm on Ubuntu 18.04

```
Could not transfer artifact org.clojure:clojure:jar:1.8.0 from/to central (https://repo1.maven.org/maven2/): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
Could not transfer artifact org.clojure:clojure:jar:1.8.0 from/to clojars (https://repo.clojars.org/): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
Could not transfer artifact org.clojure:tools.nrepl:jar:0.2.12 from/to central (https://repo1.maven.org/maven2/): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
Could not transfer artifact org.clojure:tools.nrepl:jar:0.2.12 from/to clojars (https://repo.clojars.org/): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
Could not transfer artifact clojure-complete:clojure-complete:jar:0.2.4 from/to central (https://repo1.maven.org/maven2/): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
Could not transfer artifact clojure-complete:clojure-complete:jar:0.2.4 from/to clojars (https://repo.clojars.org/): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
Could not transfer artifact org.clojure:clojure:pom:1.8.0 from/to central (https://repo1.maven.org/maven2/): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
Could not transfer artifact org.clojure:tools.nrepl:pom:0.2.12 from/to central (https://repo1.maven.org/maven2/): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
Could not transfer artifact clojure-complete:clojure-complete:pom:0.2.4 from/to central (https://repo1.maven.org/maven2/): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.

```

**Comment by geryxyz** [comment]
yes

**Comment by vspinu** [comment]
On a clean install of Ubuntu 18.04 with OpenJDK 10 I am getting

```
Could not transfer artifact org.clojure:clojurescript:jar:0.0-3308 from/to central (https://repo1.maven.org/maven2/): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

**Comment by vspinu** [comment]
This helped:

```sh
sudo apt purge openjdk-11-jdk java-common
sudo apt install openjdk-11-jdk
``` 

So not lein issue.

**Comment by ehashman** [comment]
@vspinu this was reported as well as #2428. Seems to have been an issue with the latest openjdk in Ubuntu 18.04. The details were shared on this [StackOverflow question](https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty/50103533#50103533) and the bug appears to have been fixed a couple weeks ago.

**Comment by ehashman** [comment]
Note: relevant upstream bugs affect the entire Java toolchain:

- Ubuntu: https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1739631
- Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894979

In the future, please report bugs directly to Debian or Ubuntu and I will respond much faster :)

**Comment by glts** [comment]
I am using Leiningen on Ubuntu 18.04 without issues. I take it this has been resolved?

**Comment by technomancy** [comment]
According to the trackers linked above this has been fixed upstream.
