### ISSUE TITLE
lein commands should work when a source is down

### ISSUE THREAD

**Issue by philc** [technomancy/leiningen#2054]
clojars.org is down right now. As a result, running lein stalls (seemingly forever) with this output:

$ lein repl
Jan 01, 2016 12:57:57 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.NoRouteToHostException) caught when processing request to {s}->https://clojars.org:443: No route to host
Jan 01, 2016 12:57:57 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://clojars.org:443
Jan 01, 2016 12:59:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.NoRouteToHostException) caught when processing request to {s}->https://clojars.org:443: No route to host
Jan 01, 2016 12:59:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://clojars.org:443
Jan 01, 2016 1:00:28 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.NoRouteToHostException) caught when processing request to {s}->https://clojars.org:443: No route to host
...

A workaround is to use LEIN_OFFLINE=1:

```
LEIN_OFFLINE=1 lein ...
```

This is poor developer usability. This shouldn't be necessary if all dependencies are fetched already, and it's harder / less obvious how to set this env variable from within editors like Vim and Emacs for Fireplace and Cider workflows.

**Comment by cespare** [comment]
After reading #1216, it seems like maybe all that's needed is to check for `NoRouteToHostException` in addition to `UnknownHostException` for automatically enabling offline mode. (Or maybe there is a more general class of exceptions that should be allowed here.)

**Comment by jasonjckn** [comment]
+1

**Comment by tmxkwkfgka** [comment]
revive again now

**Comment by tmxkwkfgka** [comment]
It revive just before. I can connect clojars.org
