### ISSUE TITLE
LEIN_OFFLINE doesn't work for plugins

### ISSUE THREAD

**Issue by arohner** [technomancy/leiningen#2055]
Another issue turned up by the clojars.org issues. I have a project with :plugins. I run

`LEIN_OFFLINE=true lein repl ...`
and see

`$ LEIN_OFFLINE=true lein repl :start :port 6005
The repository system is offline but the artifact lein-cljsbuild:lein-cljsbuild:jar:1.0.6 is not available in the local repository.
The repository system is offline but the artifact lein-environ:lein-environ:jar:1.0.0 is not available in the local repository.
....`

lein-cljsbuild clearly is in my local repo, and this project loaded successfully two days ago, and I haven't updated deps since then. 

After commenting out the top-level :plugins in project.clj, the project bootup progresses farther (though I still haven't gotten to a repl).

**Comment by yegortimoshenko** [comment]
Any updates on this? This breaks reproducible builds of lein-cljsbuild projects on NixOS.

**Comment by technomancy** [comment]
I can't reproduce as described it with 2.8.0-RC1 but if you have a more specific repro case I can look further.

**Comment by yegortimoshenko** [comment]
Sure. Assume this `project.clj`:

```
(defproject example "TODO"
  :dependencies [[org.clojure/clojurescript "1.9.908"]]
  :plugins [[lein-cljsbuild "1.1.3"]]
  :cljsbuild {:builds []})
```

Then:

```
$ HOME=/tmp/deps _JAVA_OPTIONS=-Duser.home=/tmp/deps lein deps
Picked up _JAVA_OPTIONS: -Duser.home=/tmp/deps
Retrieving lein-cljsbuild/lein-cljsbuild/1.1.3/lein-cljsbuild-1.1.3.pom from clojars
Retrieving fs/fs/1.1.2/fs-1.1.2.pom from clojars
Retrieving org/clojure/clojure/1.3.0/clojure-1.3.0.pom from central
[...]
Retrieving clojure-complete/clojure-complete/0.2.4/clojure-complete-0.2.4.jar from clojars
$ sudo rfkill block wlan
$ ping google.com
ping: google.com: Name or service not known
$ HOME=/tmp/deps _JAVA_OPTIONS=-Duser.home=/tmp/deps LEIN_OFFLINE=true lein cljsbuild once
Picked up _JAVA_OPTIONS: -Duser.home=/tmp/deps
Compiling ClojureScript...
Could not transfer artifact org.clojure:clojure:jar:1.5.1 from/to central (https://repo1.maven.org/maven2/): repo1.maven.org
Could not transfer artifact org.clojure:clojure:jar:1.5.1 from/to clojars (https://clojars.org/repo/): clojars.org
Could not transfer artifact cljsbuild:cljsbuild:pom:1.1.3 from/to central (https://repo1.maven.org/maven2/): repo1.maven.org: Name or service not known
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

Or wipe `~/.m2` and drop `HOME` and `_JAVA_OPTIONS` environment variable overrides.

I get a bit different text from last command in my `nix-build` chroot (starts from "The repository system is offline..."), but the steps are identical.

I can reproduce it both with 2.7.1 and 2.8.0-RC1. I've found another issue with the latter, I'll open another ticket.

**Comment by technomancy** [comment]
I think this is a problem specific to cljsbuild. If you actually declare your dependencies then `lein deps` will pick them up. The problem is cljsbuild "magically" injects them in a way that makes it impossible for any other task to know anything about. If you run `LEIN_OFFLINE=y lein repl` it works fine.

**Comment by yegortimoshenko** [comment]
And yet, all jars that `LEIN_OFFLINE=true lein cljsbuild once` claimed were missing are actually there in `/tmp/deps`...

**Comment by yegortimoshenko** [comment]
[cljsbuild "1.1.3"] is missing. Anyway, thanks for helping me figuring it out, @technomancy. I can't reproduce this issue as well, both on 2.7.1 and 2.8.0, so it probably can be closed.
