### ISSUE TITLE
:plugin-repositories in :user profile ignored for plugin resolution within project scope

### ISSUE THREAD

**Issue by tobias** [technomancy/leiningen#2059]
If I specify:

``` clojure
:plugin-repositories ^:replace
  [["central" {:url "http://repo1.maven.org/maven2" :snapshots false}]
  ["clojars" {:url "https://clojars-mirror.tcrawley.org/repo/"}]]
```

in my `:user` profile of `~/.lein/profiles.clj`, then specify a plugin within `project.clj`, the `:user` `:plugin-repositories` are ignored. They are, however, honored for any plugins specified in the `:user` profile itself, and honored for template lookup for the `lein new` task.

**Comment by jiacai2050** [comment]
anyone working on this?

**Comment by glts** [comment]
@jiacai2050 There is an open pull request #2593 that should fix this. Please try it out if you can, that should certainly help pushing it forward.
