### ISSUE TITLE
`:pom-additions` concatenates instead of merges xml

### ISSUE THREAD

**Issue by roytruelove** [technomancy/leiningen#2061]
For instance if I have the following in my `project.clj`:

`:pom-addition [:build [:testResources [:testResource foo]]]`

I'd expect the testResource to be nested inside any testResource that already exists.  Instead it creates a 2nd `build` element that's appended to the end of the project, resulting in two `build` elements.

_(BTW I know there are standard ways of adding test resources, this is just an example)_

**Comment by hyPiRion** [comment]
This a specific instance of #878, and so unfortunately won't get fixed before 3.0.

**Comment by technomancy** [comment]
Seems like a duplicate.
