### ISSUE TITLE
GPG credentials decrypting results in a NullPointerException

### ISSUE THREAD

**Issue by arichiardi** [technomancy/leiningen#2062]
I have noticed that I cannot execute a `lein deploy clojars` with a standard `credentials.clj.gpg` anymore on master. I have investigated and tracked the error to https://github.com/technomancy/leiningen/commit/fb876c7d49201e4e1253e271abe4b4086a20439d.

Basically what happens now is that in case of `gpg` program succeeding, the decrypted `edn` is printed in the terminal (at least here) and [`out`](https://github.com/technomancy/leiningen/commit/fb876c7d49201e4e1253e271abe4b4086a20439d#diff-ad66867b6d37245a7ff05811484b4624R143) results in a nil with consequent `NullPointerException`.
I don't think the employed `waitFor` returns more than the exit code and therefore [the following destructuring is not accurate](https://github.com/technomancy/leiningen/commit/fb876c7d49201e4e1253e271abe4b4086a20439d#diff-ad66867b6d37245a7ff05811484b4624R136).

I was able to solve it by modifyging `gpg` as follows, but of course I might be missing the reason why `Pipe` was introduced in the first place.

```
(defn gpg
  "Shells out to (gpg-program) with the given arguments"
  [& args]
  (try
    (println "GPG program" (gpg-program))
    (let [proc-env (as-env-strings (get-english-env))
          proc-args (into-array String (concat [(gpg-program)] args))
          proc (.exec (Runtime/getRuntime) proc-args proc-env)]
      (.addShutdownHook (Runtime/getRuntime)
                        (Thread. (fn [] (.destroy proc))))
      (with-open [out (.getInputStream proc)
                  err (.getErrorStream proc)]
        (let [#_pump-out #_(doto (Pipe. out System/out) .start) <-- commented out
              pump-err (doto (Pipe. err System/err) .start)]
          #_(.join pump-out)                                    <-- commented out
          (.join pump-err)
          (let [exit-code (.waitFor proc)]
            {:exit exit-code :out (slurp (InputStreamReader. out))})))) <- out slurped and sent as `:out`
    (catch java.io.IOException e
      {:exit 1 :err (.getMessage e)})))
```

I am willing to complete this task with a little more background and for this reason I am pinging @hyPiRion :smiley:

**Comment by arichiardi** [comment]
Given #1904, It might make sense to just pipe `err` and leave `out` pass through but again, I am not very sure of how this was handled in the first place. I can work on the solution though.

**Comment by hyPiRion** [comment]
Oh darn, that's what I get for not being thorough.

The main issue I was trying to solve there was to get better feedback when one had not specified a 
`credentials.clj.gpg` file. Considering this has been working just fine until now, I am guessing removing the pump-out and doing the slurping step, just as you've done, would work fine. Happy to take a PR for this.

**Comment by arichiardi** [comment]
Will do
