### ISSUE TITLE
Using a pure Java project in checkouts?

### ISSUE THREAD

**Issue by kephale** [technomancy/leiningen#2065]
Howdy all!

Is there an existing way to use a Java project within checkouts/ (let's assume the Java project is mavenized with a pom.xml)?

I see: https://gist.github.com/thickey/1990327 which can convert a pom.xml to a project.clj

At which point it would be... trivial? to use it in checkouts/, which would tempt me to suggest the checkouts mechanism first checking for a project.clj as per usual, then to check for a pom.xml and make a project.clj on-the-fly.

~Kyle

**Comment by hyPiRion** [comment]
The checkout implementation is in general a bit ad-hoc'y implemented and, from what I know of it, isn't as robust as I'd like to be. I would love to have checkouts implemented better, but I'm not sure I'd focus on pom.xml-projects. Preferably, projects containing a `project.clj` should load just fine.

That shouldn't be a problem for Java projects though – most poms I have worked with can be converted into project.clj.

**Comment by kephale** [comment]
Thanks for the reply. Checkouts has worked quite well with projects that have a project.clj for me so far. I just wanted to point out/make some record that it might not be too much effort to do something like port that pom2proj code into lein to enable checkouts for maven/Java projects as well. That being said, I'm running into some poms that require more sophisticated parsing for a proper conversion (i.e. things like <properties>... that contain version number variables that are used later). 

Cheers!

**Comment by technomancy** [comment]
This seems like a better fit for a plugin.
