### ISSUE TITLE
Document difference between lein repl and the Clojure 1.8 socket repl

### ISSUE THREAD

**Issue by winks** [technomancy/leiningen#2068]
People on the #clojure irc channel keep asking for the new REPL and so maybe we should document _some_thing, if only the differences/drawbacks or support is planned/not needed.

**Comment by hyPiRion** [comment]
That sounds reasonable. I'm not sure which document to put it in though. Perhaps the FAQ if the answer is small enough?

**Comment by technomancy** [comment]
I think this belongs in the documentation of nrepl, not Leiningen.
