### ISSUE TITLE
Check if 2.6.0 works with Clojure 1.8

### ISSUE THREAD

**Issue by winks** [technomancy/leiningen#2069]
verify that nothing breaks by changing 1.7.0 to 1.8.0

**Comment by hyPiRion** [comment]
I have already changed lein over to 1.8.0, so to check this, one only has to do `lein bootstrap` in the leiningen-core directory, then play around with `lein-head`/`lein-master` for your usual projects.

**Comment by winks** [comment]
Awesome!
So probably mentioning the supported clojure (major) versions in NEWS.md would be a good addition?

I quickly checked it, but there was no mention when 1.7/1.6 were initially being "officially supported" - I'd suggest putting a notice for 1.8 in the next release notes - or is that not needed?

**Comment by hyPiRion** [comment]
Yeah, it's reasonable to add in that the project-less repl, templates and lein itself runs on 1.8.

**Comment by hyPiRion** [comment]
Seems to work fine. No big changes according to the changelog.

This is also added to NEWS.md, so I guess this is resolved.
