### ISSUE TITLE
Leiningen hangs if repo is not available

### ISSUE THREAD

**Issue by Jarzka** [technomancy/leiningen#2085]
Hi

Today I noticed that if I have defined a repository in project.clj file and that repository does not respond, leiningen does not inform about this but just hangs if you try to clean or compile your project. This can be confusing.

**Comment by hyPiRion** [comment]
Yeah, this is just bad UX.

**Comment by technomancy** [comment]
Sorry, are you saying that there are no HTTP connection timeouts? If so this would be a bug in the underlying HTTP wagon, and we should probably report it upstream.

**Comment by glts** [comment]
With a little bit of patience, Leiningen does report the timeout:

```
$ time lein deps
Could not transfer artifact org.clojure:clojure:jar:1.10.0 from/to central (https://repo1.maven.org/maven2/): Read timed out
Could not transfer artifact org.clojure:clojure:jar:1.10.0 from/to clojars (https://repo.clojars.org/): Read timed out
Could not transfer artifact org.clojure:clojure:pom:1.10.0 from/to central (https://repo1.maven.org/maven2/): Read timed out
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.

real    0m41.905s
user    0m2.350s
sys     0m0.206s
```

Leiningen 2.9.1, OpenJDK 1.8.0_212 on Ubuntu 18.04.

**Comment by technomancy** [comment]
Thanks.
