### ISSUE TITLE
lein.bat doesn't correctly handle whitespace in the standalone.jar file path

### ISSUE THREAD

**Issue by VoltaicAge8838** [technomancy/leiningen#2086]
Running the lein batch file results in the message
`Error: Could not find or load main class Lastname\.lein\self-installs\leiningen-2.6.1-standalone.jar`
Since the full path is "C:\Users\Firstname Lastname\.lein\self-installs\leiningen-2.6.1-standalone.jar" it looks like the space in the path is throwing it off.
Putting quotes around `%CLASSPATH%` on line 380 seems to solve the issue. However, these quotes were taken out [in this commit](https://github.com/technomancy/leiningen/commit/927b9bf26c63be553a52f27281eb5185f382e78a) to fix another issue.

**Comment by igoroctaviano** [comment]
The same here, Error: Could not find or load main class User\.lein\self-installs\leiningen-2.6.1-standalone.jar
