### ISSUE TITLE
Add support for the XDG Base Directory Specification

### ISSUE THREAD

**Issue by severen** [technomancy/leiningen#2087]
You can find the specification [here](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

This [blog post](https://ploum.net/207-modify-your-application-to-use-xdg-folders/) lists the advantages of using the XDG Base Directory Specification as follows:
- `$HOME` is a lot less cluttered.
- Backups are a lot more safer and easier (you know that creating a backup of your `$XDG_DATA_HOME` along with your files is enough).
- A lot easier to reset a default configuration if you want/need it (and without any risk of loosing information).
- Avoid some strange bugs that happen because you had a old version of some configuration file.
- It is a lot more flexible and portable because no paths are hard-coded. You can use the XDG library that does the job for you _or_, if you don’t want the dependency, implementing the XDG specification is only a few lines of code.

**Comment by hyPiRion** [comment]
This seems like something we should investigate, but adding it right now for profiles would break backwards compatibility (unless we add an override enviroment variable, in which case you could just use `LEIN_HOME`).

There's also the aspect of usability: People tend to write `~/.lein/profiles.clj` manually, as Leiningen is a CLI. I'm guessing the recommendation there is mostly for GUI applications with a settings interface – digging into `~/.config/lein/profiles.clj` isn't that much harder, but it's slightly more effort than just `~/.lein/profiles.clj` and it's much more invisible (for better or worse).

That said, I'll happily look further into this for the future. Thanks for the pointers!

**Comment by SShrike** [comment]
Thanks for looking into this! :+1: 

IMO, support should either be default with a warning shown when the legacy directory is detected _or_ it should be able to be enabled with an environment variable such as `$LEIN_XDG_ENABLE` (simply using `$LEIN_HOME` would not cut it as the XDG Spec consists of three directories with the intention of splitting out caches, data and configuration).

**Comment by SShrike** [comment]
I've realised that I've made no mention of Windows or OS X in my post, a possible extension of this issue could be using the proper directories for all OSes. (E.g. something like %APPDATA% on Windows and `~/Library` on OS X)

**Comment by hyPiRion** [comment]
Yeah – when we decide to go for something like this, we should use best practices all over.

**Comment by technomancy** [comment]
Sorry for the very long delay here.

I think this is a good idea, but I'm still thinking thru the details of how to do this in a way that's backwards-compatible. Obviously an explicit `$LEIN_HOME` takes precedence, but otherwise if the `~/.lein` directory exists, we should use it. But if `~/.config/leiningen` exists and `~/.lein` does not, we should use that instead, for config files like `profiles.clj`. And if `~/.local/share/leiningen` exists, we should probably put self-installs there and look for self-installs there, if they haven't already been put in `~/.lein`.

The question is what do we do when neither one exists? I would prefer to use the XDG location in this case, but I'm concerned that might be a breaking change.

Also, should self-install uberjars be downloaded to `$XDG_DATA_HOME` or `$XDG_CACHE_HOME`?

**Comment by aisamu** [comment]
> Also, should self-install uberjars be downloaded to $XDG_DATA_HOME or $XDG_CACHE_HOME?

IIUC, `$XDG_CACHE_HOME` (as in, "files that I could wipe on every boot and things would still work 'identically', minus the time taken to transparently recreate/re-fetch them").
If repopulating a missed cache is not transparent (e.g. requires manually re-running an installer script), perhaps `$XDG_STATE_HOME`?

**Comment by technomancy** [comment]
You're right; I think `$XDG_CACHE_HOME` is better for self-installs.

I was going to have it prefer the XDG location for self-installs even if it didn't exist, but then I realized that would make it so on a fresh install, if you ran a lein command, it would self-install into the XDG location, and then if you went to go create a `~/.lein/profiles.clj` file *after* self-install, it would switch to thinking that `~/.lein/` was the right place, and then it would have to self-install again. So I think it's safer to only use the XDG one if an actual `$XDG_CACHE_HOME/leiningen` directory already exists.

I think we're all set here then.

**Comment by offsetcyan** [comment]
Was this completed or not planned?

**Comment by technomancy** [comment]
We support using `$XDG_CACHE_HOME/leiningen` if it exists. Is that what you mean, or are you talking about something else?
