### ISSUE TITLE
settings such as `local-repo` and `mirrors` from user profile not honored when `javac` is called by `jar`

### ISSUE THREAD

**Issue by cprice404** [technomancy/leiningen#2089]
We noticed an unusual thing in our CI jobs recently;  all of our CI jobs have a `~/.lein/profiles.clj`, which contains a `user` profile, which provides values for `:local-repo` and `:mirrors`.  We use `:local-repo` to keep the artifacts localized to the specific CI job (rather than system-wide), and we use `:mirrors` to cause all of the jobs to use our local nexus mirror rather than hammering on clojars and maven central every time they run.

However, we noticed from watching the logs of these jobs that they were often downloading all of the dependency artifacts twice(!); once from our nexus mirror (and storing them in `:local-repo`), and then a second time (from clojars / maven central, bypassing our nexus mirror, and storing the artifacts in ~/.m2).

After some poking I determined that this was happening on projects that contained Java sources.  It happens when the `jar` task is setting up the `eval-in-subprocess` call for `javac`.  `jar` calls `javac` via some "prep tasks" stuff, and passes a project map that has the `user` profile set up to be excluded.  Then the `javac` code does some manipulation to the project related to profiles, which involves "un-merging" the excluded profiles (including user):

https://github.com/technomancy/leiningen/blob/2ca63f0084091d7799482ebe97cb60b8f17d76c9/src/leiningen/javac.clj#L120

At that point, settings like `:local-repo` and `:mirrors` that were defined in the `user` profile are no longer in the project map.  Then, in preparing a shell command to run javac in, we hit a line of code that ends up doing classpath resolution:

https://github.com/technomancy/leiningen/blob/2ca63f0084091d7799482ebe97cb60b8f17d76c9/leiningen-core/src/leiningen/core/eval.clj#L252

This causes all of the dependencies to be resolved again without respecting the `:local-repo` and `:mirrors` settings from the `user` profile.

**Comment by cprice404** [comment]
Here's a failing test that illustrates the issue:

https://github.com/cprice404/leiningen/commit/cadf5ea2f75624f2054b52eab0b9f179d4f18c2a

**Comment by cprice404** [comment]
In the `jar` task itself, there is some code about "whitelisted" settings that seems intended to address this issue.  It seems like that logic just needs to be extended to the `javac` task:

https://github.com/technomancy/leiningen/blob/2ca63f0084091d7799482ebe97cb60b8f17d76c9/src/leiningen/jar.clj#L274

**Comment by cprice404** [comment]
@waynr you may be interested in this because I think it is involved in some of the wackiness we've been seeing in CI recently.  If this gets merged and released we'll probably want to upgrade all of the CI servers to the latest release.

**Comment by hyPiRion** [comment]
Thank you for taking the time for looking into this; seems like a nasty rabbit hole to dig into. Will happily accept #2090 when it's been fixed and I've gotten time to review it.
