### ISSUE TITLE
Is there a command `leinw`，like `gradlew`?

### ISSUE THREAD

**Issue by QinAIns** [technomancy/leiningen#2102]
Is there a command `leinw`，like `gradlew`? So that I don't need to install the lein command.I just add `leinw` in my project.

**Comment by hyPiRion** [comment]
The [`lein script`](https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein) should, as far as I know, also work as a "gradlew" script.

**Comment by QinAIns** [comment]
Thanks! I just add the lein/lein.bat to my root project.
If I run in the Linux OS, run this command:
`./lein run'
It solve.
