### ISSUE TITLE
Multiproject build with different source & binary repositories?

### ISSUE THREAD

**Issue by jerger** [technomancy/leiningen#2103]
Hi,

I've a multiproject consisting of some thenth of modules bound together ...
Each module is used standalone and has its own releas & version.
Is there a way to e.g. build/release/deploy them all together using some kind of lein masterbuild?

Best Regards

**Comment by hyPiRion** [comment]
Hi there!

Leiningen doesn't support this directly, but there might be [plugins](https://github.com/technomancy/leiningen/wiki/Plugins) that could do this.

**Comment by technomancy** [comment]
The plugin should cover this use case.
