### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by winks** [technomancy/leiningen#2105]
While investigating #2104 I did this (Windows, but maybe unrelated):

```
cd code\leiningen
git pull --rebase upstream master
# this is lein.bat 2.6.1, not the one in the repo
c:\apps\bin\lein.bat version
```

Could not find artifact leiningen-core:leiningen-core:jar:2.6.2-SNAPSHOT in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
- So yes, I am in a HEAD checkout of leiningen
- I am running `lein.bat version` with _another_ lein.bat as I usually do
- the `leiningen-core` dependency from ./project.clj seems to be checked

I'm probably wrong, but I never noticed this and it feels incorrect.
Especially because it works after I did `lein bootstrap` inside `./leiningen-core` and (correctly) outputs 2.6.1 (because 2.6.2-SNAPSHOT was found locally)

**Comment by technomancy** [comment]
Sorry, I think this is expected behavior. Running `lein bootstrap` inside the `leiningen-core/` dir is the required procedure.
