### ISSUE TITLE
Files from :source-path are not recompiled on lein run if previous action's profile used different ones 

### ISSUE THREAD

**Issue by agnivalent** [technomancy/leiningen#2108]
After executing a command, that uses different `:source-paths`, than in the env of `lein run` (e.g. `lein uberjar`), classes for sources in `:source-paths` are not being recompilled. Touching sources used by `lein run`, and `lein clean` get rid of the problem. Other options from the profiles seem to work just fine.

Is it intended behaviour?

```
➜  lein run
...
-=[project-name started successfully using the development profile]=-
...
➜  lein uberjar
...
➜  lein run
...
-=[project-name started successfully]=-
...
➜  touch env/dev/clj/project_name/config.clj
➜  lein run
...
-=[project-name started successfully using the development profile]=-
...
```

project.clj:
```
(defproject project-name "0.1.0-SNAPSHOT"
...
  :profiles
  {:uberjar {
...
             :source-paths ["env/prod/clj"]
...}
   :dev           [:project/dev :profiles/dev]
   :project/dev  {
...
                  :source-paths ["env/dev/clj"]
                  ...
```

in env/dev/clj/project-name/config.clj:
```
     (log/info "\n-=[misabogados-workflow started successfully using the development profile]=-")
```

in env/prod/clj/project-name/config.clj:
```
     (log/info "\n-=[misabogados-workflow started successfully]=-")
```

Version:
```
➜  lein -v
Leiningen 2.6.1 on Java 1.8.0_72 OpenJDK 64-Bit Server VM
```

**Comment by hyPiRion** [comment]
Hi there,

What is the value of the `:target-path`-entry in `project.clj`, if it set?

I am guessing it's possible to make Leiningen confused if `:target-path` does not contain `%s`, and if there are multiple files in different `:source-paths` that represent the same namespace.

Regardless of that: Do you have the configuration in a namespace that differ based on what profiles you've ran/build it with? Speaking from experience, it's preferable to contain configuration in input files or environment variables, and not based on what file is loaded on startup. Something like [environ](https://github.com/weavejester/environ) or just reading EDN from a file might be worth looking at.

**Comment by agnivalent** [comment]
Hi,

Thank you for your answer!

`:target-path` was not set, so I guess it was `target/` by default. Setting it as `target/%s/` fixed the problem. 

Regarding config: different config sources in `env/<<profile>>/clj` have the same namespace, and contain a set of ring middlewares, so those can be listed in environ or in some other config file, thank you for suggestion.

The setup I'm using is from [luminus-template](https://github.com/luminus-framework/luminus-template), so I'll suggest a change there.
