### ISSUE TITLE
lein hangs forever on Mac OSX El Capiton

### ISSUE THREAD

**Issue by leandromoreira** [technomancy/leiningen#2110]
# Context:

*  OS: Mac OSX El Capiton 10.11.3
*  Lein Version: 2.6.1 
*  Java Version: 1.8.0_31 Java HotSpot(TM) 64-Bit Server VM

# Steps to reproduce the issue:

```shell
lein new chestnut test
cd test
DEBUG=true lein run -m test.server
```

**I was expecting the server up but it just hangs:**

> Leiningen's classpath: :/usr/local/Cellar/leiningen/2.6.1/libexec/leiningen-2.6.1-standalone.jar
> Applying task run to [-m test.server]
> Applying task javac to nil
> Running javac with [@/var/folders/jv/0yvqn2hd015g5b0cgz6b5d_m0000gp/T/.leiningen-cmdline1007249025131972264.tmp]
> Applying task compile to nil
> All namespaces already AOT compiled.

**Comment by hyPiRion** [comment]
I'm unable to reproduce this on 2.6.1, but it took a very long time before the server started, and when it finally started it did not produce any terminal output.

Could you try to verify that the server actually starts by changing the `-main` function in  `src/clj/test/server.clj` from

```clj
(defn -main [& [port]]
  (let [port (Integer. (or port (env :port) 10555))]
    (run-jetty http-handler {:port port :join? false})))
```

to

```clj
(defn -main [& [port]]
  (let [port (Integer. (or port (env :port) 10555))]
    (println "Starting server on port" port)
    (run-jetty http-handler {:port port :join? false})))
```

and verify that it doesn't produce any output, even if you wait, say, 3-4 minutes?

**Comment by leandromoreira** [comment]
@hyPiRion you're right it just doesn't output anything, thanks a lot.
