### ISSUE TITLE
plugin-additions should not be converted to a hash-map

### ISSUE THREAD

**Issue by Malabarba** [technomancy/leiningen#2113]

**Comment by Malabarba** [comment]
In this line: https://github.com/technomancy/leiningen/blob/master/src/leiningen/pom.clj#L251
pluggin additions is converted to a hash-map, but that forces it to have an even number of entries. However, some keys might have multiple values associated with them.

For instance, using the `:pom-addition` notation, I was adding a plugin like this:

    :pom-addition [:build
                   [:plugins
                    [:plugin
                     [:groupId com.theoryinpractise]
                     [:artifactId clojure-maven-plugin]
                     [:version "1.3.23"]
                     [:extensions true]
                     [:configuration
                      [:vmargs "some args"]
                      [:warnOnReflection true]]]]]

Using the `:pom-plugins` notation, I would have to add it like this:

    :pom-plugins [[com.theoryinpractise/clojure-maven-plugin "1.3.23"
                   [:extensions true
                    :configuration [:vmargs "some args"] [:warnOnReflection true]]]]
    
However this doesn't work because `:configuration` has 2 values associated with it, and the code tries to convert it to a hash-map.

**Comment by glts** [comment]
In this case you would the map syntax:

```clojure
:pom-plugins [[com.theoryinpractise/clojure-maven-plugin "1.3.23"
               {:extensions true
                :configuration ([:vmargs "some args"]
                                [:warnOnReflection true])}]]
```

This produces the expected result in Leiningen 2.9.1.

[sample.project.clj](https://github.com/technomancy/leiningen/blob/0f1058d3bdb0ace8a516a8e3e26bc34acd0885ce/sample.project.clj#L467-L480) shows the different supported notations. See also #2489.

**Comment by Malabarba** [comment]
Thanks for the reply. 
I don't have this issue anymore so I'll just close it since it has an answer.
