### ISSUE TITLE
Request: warning for clojure version dependency mismatch?

### ISSUE THREAD

**Issue by paultopia** [technomancy/leiningen#2115]
Recently I came across an interesting bit of minor unfriendliness in Leiningen.  The default project.clj created with lein new set clojure 1.6.0 as a dependency.  I was trying to use core.matrix, and it appears (see note on [this issue](https://github.com/mikera/core.matrix/issues/278) on core.matrix) that library requires clojure 1.7.0 or above (actually, it looks like the current core.matrix project.clj calls for 1.8.0). 

Not noticing this, I fired up the REPL.  As usual Leiningen went and fetched the dependencies, including core.matrix, from clojars, without complaint and it landed in my .m2 and on the classpath as appropriate.  However, when I tried to use the namespace that required core.matrix, the REPL threw the following error:

CompilerException` java.io.FileNotFoundException: Could not locate clojure/core/matrix__init.class or clojure/core/matrix.clj on classpath

This led, naturally, to hours of trying to figure out what wrong before discovering a simple dependency mismatch.  Itseems like it would be lots more friendly if Leiningen could catch these issues from the start, and maybe throw up a giant red/all-caps warning when it pulls dependencies with these kinds of conflicts from clojars.  Just a thought...

**Comment by paultopia** [comment]
(incidentally, I'm a bit of a noob, but I'm happy to try to implement this myself if someone can point me to the relevant part of the codebase I'm happy to try to implement this... probably just by something simple like keeping an vector of dependencies, dependencies of dependencies, etc. and then appending a warning message to the end of the build process if anything further down the chain is different from anything higher up.)

**Comment by technomancy** [comment]
It looks like what you're describing is adding `:pedantic? :warn` to your `project.clj` file. It's not on by default, but it should catch situations like this.

**Comment by paultopia** [comment]
Cool, thanks!
