### ISSUE TITLE
Merging of composite profiles should not alter collection type

### ISSUE THREAD

**Issue by amacdougall** [technomancy/leiningen#2119]
Given a project.clj containing this:
```clojure
:profiles
{:dev [:project/dev :profiles/dev]
 :project/dev
 {:cljsbuild {:builds [...vec of builds...]}}
 :profile/dev {...some more settings, to be clobbered by profiles.clj}
```
The resulting project map, according to an error message from `doo` and confirmed by `configleaf`, has:
```clojure
:cljsbuild
{:builds (...list of builds...)}
```
Most core library functions can cope equally well with lists and vectors, but Clojure still considers them fundamentally different; this can lead to breakage in plugins which are expecting a vector.

To put it another way, profile merging should avoid changing the type of a value.

**Comment by hyPiRion** [comment]
I'd rather not support this before Lein 3, as this will break a lot of plugins. (I've already tried this, you see.)

Rather, plugins should accept sequences instead of vectors.

**Comment by amacdougall** [comment]
Thanks for the response. I realize that it's a gray area—I've also made a PR against the particular plugin that was giving me trouble.

**Comment by hyPiRion** [comment]
Yeah, no problem. =) I see the rationale and I agree in principle, but the easiest backward compatible fix for now is to fix it in plugins instead of possibly breaking a lot of existing ones

**Comment by amacdougall** [comment]
Cool. I'll close this issue.
