### ISSUE TITLE
Mirror standalone files

### ISSUE THREAD

**Issue by Heliosmaster** [technomancy/leiningen#2124]
Is it possible to provide some sort of redundancy other than github, for releases / downloading the standalone files?

We are somewhat free from GitHub in our development environment and the (ongoing) outage is hitting us because i can't downgrade my version of leiningen...

**Comment by winks** [comment]
pro:
  * GitHub is the SPOF here
  * we could probably get some LE cert and a mirror rotation going

contra:
  * given any homemade mirror solution, GitHub will probably come out on top in terms of reliability
  * who administers the mirror(s) [depending on tradffic I could maybe offer one in Germany]

Maybe one officially blessed backup download url is good enough (and I would support this idea), but I think that's for @hyPiRion and/or @technomancy to decide.

**Comment by hyPiRion** [comment]
I could administer a mirror without too much hassle, but I would probably need some help on handling multiple sources for the bat script. Patches that would support this feature in both scripts are very welcome.

**Comment by technomancy** [comment]
The reason we didn't host anything on leiningen.org was that originally it didn't have https, but now I have a Let's Encrypt cert on it. It's an option for uberjars.

**Comment by winks** [comment]
I like the idea on hosting on a custom domain, but if it's 'just one box' I'm not sure making the availability a lot worse is worth it.

**Comment by technomancy** [comment]
Yeah, to be honest if your goal is just to work around GitHub downtime I would recommend an internal mirror. I don't think leiningen.org's uptime will beat GitHub's static file download uptime. Perhaps some kind of fallback scheme would help, but my gut instinct is that it would just complicate things.

**Comment by winks** [comment]
yeah,. I'll keep thinking about this.
maybe jsut something like a hardcoded "lein self-install --mirror" or, if possible automatic retry on failure.

**Comment by Heliosmaster** [comment]
Well, the whole point would be to eliminate the SPOF. Github + something else would be already really good. The chance of both going down at the same time is tinier than what it is.

**Comment by hyPiRion** [comment]
I think it depends on how much effort it is to support this in the scripts. If it's easy to do "oh, unable to fetch from github, let's try this other link", then I think it's at least worthy to consider.

That being said, considering this is the first time (?) this has been considered problematic since summer 2014, it's probably not that important.

**Comment by technomancy** [comment]
What if we allowed the self-install URL to be overridden by an environment variable? Then the retry logic could just be pushed out to whatever script is automating the installation of lein in the first place.

    lein self-install || LEIN_UBERJAR_LOCATION=... lein self-install

**Comment by winks** [comment]
that's an easy fix we could easily land in the next version, yes

**Comment by hyPiRion** [comment]
After some thought, it feels like this would just cause more trouble than it's worth. Closing this, and will reconsider it if GitHub's uptime decreases significantly.
