### ISSUE TITLE
Running uberjar with multiple profiles and autocleaning

### ISSUE THREAD

**Issue by Heliosmaster** [technomancy/leiningen#2125]
On our build system we were running version 2.4.2 until recently, because we create multiple jars with different profiles:

Our `project.clj` looks like this

```
...
  :profiles {:bob {:uberjar-name "bob.jar"
                  :main buildtest.bob}
            :tim {:uberjar-name "tim.jar"
                  :main buildtest.tim}}
...
```

and we ran `lein with-profile bob:tim uberjars`

In recent version of leiningen (2.5.0+), will make
1. create `bob.jar`
2. clean the target folder
3. create `tim.jar`

We "solved" this issue momentarily, by putting `:auto-clean false` in the `project.clj`. I wonder if there is something better that you can do. I find it a bit confusing that you can run uberjars with multiple profiles, but without any extra configuration it does not yield what you expect.

**Comment by hyPiRion** [comment]
Sorry for the delayed response here.

Yeah, I agree that this is a bit counterintuitive. I guess the easiest solution is to keep using `:auto-clean false`. Uou could also use plugins to move the file out of the `:target` directory, but I guess that would require more effort.

**Comment by technomancy** [comment]
Not sure this is actionable as-is, but if you have a suggestion we can reopen it.
