### ISSUE TITLE
leiningen.vcs/uses-vcs fails when not in git root

### ISSUE THREAD

**Issue by voj** [technomancy/leiningen#2128]
If a project is not in the git root directory, it is possible to specify

```
:scm {:dir ".."}
```

to point leiningen to the git root. However, this setting is ignored in `leiningen.vcs`. 

When detecting which VCS is used, `uses-vcs` looks for the file `.git` in the project's `:root`. However, git will actually store this file in the directory specified by `:scm :dir`.

Example impact:

```
$ lein release
Unknown VCS detected for 'vcs assert-committed'
```

A workaround for this is to specify 

```
:vcs :git
```

**Comment by hyPiRion** [comment]
Yeah, that looks very much like a bug. Happy for patches on this.
