### ISSUE TITLE
Typo in tutorial

### ISSUE THREAD

**Issue by marionzualo** [technomancy/leiningen#2130]
In the Uberjar section of the [tutorial](https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md). There are these instructions:

-------
By this point, our `project.clj` file
should look like this:

```clj
(defproject my-stuff "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [clj-http "2.0.0"]]
  :profiles {:dev {:dependencies [[ring/ring-devel "1.4.0"]]}}
  :main my.stuff
  :aot [my.stuff])
```
---
Those instructions are followed by

---------
Let's try
something easy in `src/my_stuff.clj`:

```clj
(ns my.stuff
  (:gen-class))

(defn -main [& args]
  (println "Welcome to my project! These are your args:" args))
```
-----------------

When running `lein uberjar` as suggested I get an error:

```
› lein uberjar
Compiling my.stuff
Could not locate my/stuff__init.class or my/stuff.clj on classpath.
```

I fixed the error by using the source file `src/my/stuff.clj` (as opposed to the `src/my_stuff.clj` recommended by the tutorial). Should the typo in the tutorial be fixed? Or am I missing something?

Thanks.

**Comment by hyPiRion** [comment]
Yeah, that was indeed a bug in the documentation. Thanks for pointing it out!

I thought it was more sensible to add in the default namespace that the `lein new app my-stuff`-template generates to avoid confusion, so I changed it into `my-stuff.core` instead.
