### ISSUE TITLE
exclusions ignored in plugins in profiles?

### ISSUE THREAD

**Issue by tvaughan** [technomancy/leiningen#2131]
If I do something like:

``` clojure
  :dependencies [[compojure "1.5.0"]]
  :profiles {:ultra
             {:plugins [[venantius/ultra "0.4.1" :exclusions [instaparse]]]}}
```

I still get complaints from `lein deps :tree` and `:pedantic? :abort` that I need to exclude instaparse from ultra.

**Comment by nzey** [comment]
Same situation here, running `Leiningen 2.6.1 on Java 1.8.0_65 Java HotSpot(TM) 64-Bit Server VM`

**Comment by metametadata** [comment]
I've just stumbled upon the similar problem:

```
Possibly confusing dependencies found:
[buddy/buddy-auth "1.4.1"] -> [clout "2.1.2"] -> [instaparse "1.4.0" :exclusions [org.clojure/clojure]]
 overrides
[venantius/ultra "0.5.1"] -> [venantius/glow "0.1.4" :exclusions [hiccup garden]] -> [instaparse "1.4.1"]

Consider using these exclusions:
[venantius/ultra "0.5.1" :exclusions [instaparse]]

Aborting due to :pedantic? :abort
```

Excluding `instaparse` doesn't help:

```
:dependencies [[buddy/buddy-auth "1.4.1"]]
:pedantic? :abort
:plugins [[venantius/ultra "0.5.1" :exclusions [instaparse org.clojure/clojure]]]
```

**Comment by technomancy** [comment]
Does it work if you add `venantius/glow` as a direct dependency and put the `instaparse` exclusion in that?

**Comment by metametadata** [comment]
These combinations fail with the same error as in my original comment:

1) provide `glow` with excluded `instaparse` explicitly:

```clj
:dependencies [[buddy/buddy-auth "1.4.1"]
               [venantius/glow "0.1.4" :exclusions [instaparse]]]

:plugins [[venantius/ultra "0.5.1" :exclusions [org.clojure/clojure]]]
```

2) and also exclude `glow` from `ultra`:

```clj
:dependencies [[buddy/buddy-auth "1.4.1"]
               [venantius/glow "0.1.4" :exclusions [instaparse]]]

:plugins [[venantius/ultra "0.5.1" :exclusions [venantius/glow org.clojure/clojure]]]
```

**BUT** everything works if I provide `glow` explicitly without any exclusions:

```clj
:dependencies [[buddy/buddy-auth "1.4.1"]
               [venantius/glow "0.1.4"]]

:plugins [[venantius/ultra "0.5.1" :exclusions [org.clojure/clojure]]]
```

Thank you for the tip, I think I'll use this workaround until the issue is fixed.

**Comment by glts** [comment]
This seems to be a problem in Ultra, not Leiningen.

Ultra applies middleware that rewrites the project map. They have to take care to preserve exclusions, and generally to only do transformations that make sense within the framework of Leiningen middleware. I don’t think we can do anything here.

**Comment by technomancy** [comment]
Yeah it's really easy for plugin middleware to mess things up like this.
