### ISSUE TITLE
Lein check crashes ungracefully when a file has malformed lisp in it.

### ISSUE THREAD

**Issue by phillord** [technomancy/leiningen#2133]
To reproduce create a new project with lein new, replace the entire contents
of core.clj (including namespace) with a single character "{", type lein check
-- this error results.

```
java.lang.RuntimeException: EOF while reading
 at clojure.lang.Util.runtimeException (Util.java:221)
    clojure.lang.LispReader.readDelimitedList (LispReader.java:1204)
    clojure.lang.LispReader$MapReader.invoke (LispReader.java:1158)
    clojure.lang.LispReader.read (LispReader.java:263)
    clojure.lang.LispReader.read (LispReader.java:196)
   clojure.lang.LispReader.read (LispReader.java:185)
```

This happens with both the current release and trunk. It's possible to get a
variety of other errors from the lisp reader depending on the exact contents
of the file. In no case is there anything informative about the cause of the
error, which can make it hard to track down for a project with lots of
namespaces.

The crash stems from here:

```
     nses (b/namespaces-on-classpath :classpath source-files
                                     :ignore-unreadable? false)
```

If ":ignore-unreadable?" is changed to true the problem goes away, although
this also stops lein check from checking syntax which it is supposed to be
doing. Unfortunately, bultitude doesn't have a
":tell-me-if-its-unreadable-but-dont-crash" option, so I suspect the fix is
needed there.

**Comment by hyPiRion** [comment]
Yeah, I agree that this is terrible UX. Happy to get this fixed or improved in some way, because this can easily be confusing.

**Comment by TimoFreiberg** [comment]
We can do something about this: https://github.com/TimoFreiberg/bultitude/issues/5
I've never done anything in leiningen, so if anyone can tell me how a nice bultitude API would look for leiningen it would help me a lot :)

**Comment by technomancy** [comment]
I think this should be fixed with the new bultitude.
