### ISSUE TITLE
lein repl crashes after running seesaw function

### ISSUE THREAD

**Issue by Allaman** [technomancy/leiningen#2134]
Hello,

see below for a small sample project using seesaw. After starting the function in the repl with `lein repl` and closing the application window the repl throws following error:
```
SocketException The transport's socket appears to have lost its connection to the nREPL server
        clojure.tools.nrepl.transport/bencode/fn--10128/fn--10129 (transport.clj:95)
        clojure.tools.nrepl.transport/bencode/fn--10128 (transport.clj:95)
        clojure.tools.nrepl.transport/fn-transport/fn--10100 (transport.clj:42)
        clojure.core/binding-conveyor-fn/fn--4676 (core.clj:1938)
        java.util.concurrent.FutureTask.run (FutureTask.java:266)
        java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
        java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
        java.lang.Thread.run (Thread.java:745)
Bye for now!
```
Leiningen 2.6.1 on Java 1.8.0_77 Java HotSpot(TM) 64-Bit Server VM

project.clj
```
(defproject test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "foobar"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [seesaw "1.4.5"]])
```
core.clj
```
(ns test.core
  (:use seesaw.core))

(defn gui [& args]
  (invoke-later
   (-> (frame :title "Hello",
              :content "Hello, Seesaw",
              :on-close :exit)
       pack!
       show!)))
```

**Comment by hyPiRion** [comment]
Hi!

If you remove `:on-close :exit` as arguments to the frame function, this should work fine.

**Comment by Allaman** [comment]
@hyPiRion You are right! Without `:on-close :exit` the repl is not crashing anymore! Thanks!
Do you know why? I mean this is the example from seesaw's github page that I would expect to run ;)

**Comment by hyPiRion** [comment]
I am guessing `:on-close :exit` runs something à la `(System/exit 0)` or similar, stopping the JVM process. That would make the connection via Leiningen dead, which causes that error.

The example in the readme seems to mention `lein run -m` instead of `lein repl`, but yeah, I'd expect to have something which could be run in the repl from a readme. Perhaps you should ask how one would do idiomatic repl development with seesaw in their issue tracker?
