### ISSUE TITLE
lein.bat cannot download standalone jar: 403 forbidden

### ISSUE THREAD

**Issue by vermiculus** [technomancy/leiningen#2136]
[`bin/lein.bat`](https://github.com/technomancy/leiningen/blob/master/bin/lein.bat) fails with 403-Forbidden:

```
C:\windows\system32>lein self-install
Downloading Leiningen now...
Exception calling "DownloadFile" with "2" argument(s): "The remote server
returned an error: (403) Forbidden."
At line:1 char:17
+ & {param($a,$f) (new-object System.Net.WebClient).DownloadFile($a, $f)}
"https:/ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

The system cannot find the file specified.
C:\windows\system32>
```

Also reproducible with chocolatey which downloads/runs `https://raw.github.com/technomancy/leiningen/2.2.0/bin/lein.bat`.

**Comment by winks** [comment]
Hi,
you're trying to use the `lein.bat` from Github's master branch - there is no release JAR for this version. Please use [stable/lein.bat](https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat) - this should work.

And for the other one.. 2.2.0 is very old, I'll see who we have to poke there to get a newer version into chocolatey.

**Comment by vermiculus** [comment]
Ah, thanks a ton!

And yeah -- wow. Chocolatey does need to be updated... such is life on Windows, I suppose.

**Comment by winks** [comment]
Filed a bug, trying to keep track: https://github.com/Iristyle/ChocolateyPackages/issues/58
