### ISSUE TITLE
Exceptions thrown by fixtures can cause lein test to hang

### ISSUE THREAD

**Issue by alexhall** [technomancy/leiningen#2137]
When test fixtures throw exceptions, they are uncaught by both `clojure.test` and the testing form generated by `lein test`. This causes the main thread in the test process to terminate, but if agents are in use then the agent executor service (or anything else that spawns a non-daemon thread) prevents the test process from terminating, thus causing `lein test` to hang forever.

See https://github.com/alexhall/fixture-failure for a demo of this issue, along with a workaround that can be applied in the project itself.

**Comment by hyPiRion** [comment]
Fixed by #2138.
