### ISSUE TITLE
403 denied for `lein self-install`

### ISSUE THREAD

**Issue by howdoicomputer** [technomancy/leiningen#2139]
```
C:\Users\drfra\workspace
λ lein self-install
Downloading Leiningen now...
Powershell
Found
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."
At line:1 char:17
+ ... aram($a,$f) (new-object System.Net.WebClient).DownloadFile($a, $f)} " ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

The system cannot find the file specified.
```

Windows 10

**Comment by winks** [comment]
@howdoicomputer which `lein.bat` version did you download and run?

**Comment by howdoicomputer** [comment]
@winks I ended up solving my problem. I was using the version packaged in the [Chocolatey 'repository'](https://chocolatey.org/packages/Lein).

I solved it by curling the batch script from the `2.6.1` release, setting my `HTTP_CLIENT` variable, and running self-install.

**Comment by howdoicomputer** [comment]
I'll close this issue since I'm pretty sure it's a duplicate. Odd that I didn't find it in the search. I also see you're pursuing avenues for dealing with the outdated package on Chocolatey. I was looking into that as well. Sorry that I created noise.

**Comment by winks** [comment]
No worries, thanks for  following up.
