### ISSUE TITLE
with-profile not honouring excluded plugins

### ISSUE THREAD

**Issue by marknsikora** [technomancy/leiningen#2141]
The `with-profile` command is not honouring the plugins part of a profile when the profile is excluded. Simple test example, lein-protobuf compiles a local copy of the protobuf compiler so it outputs the compile process when included.

``` clojure
(defproject bad-with-profile "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]]
  :main ^:skip-aot bad-with-profile.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}
             :dev {:plugins [[lein-protobuf "0.4.1"]]}})
```

The dep tree indicates that it is not used.

```
$ lein deps :plugin-tree 
 [lein-protobuf "0.4.1"]
   [conch "0.2.0"]
   [fs "1.2.0"]
     [org.apache.commons/commons-compress "1.3"]
     [org.clojure/clojure "1.4.0"]
   [leinjacker "0.4.0"]
     [org.clojure/core.contracts "0.0.1"]
       [org.clojure/core.unify "0.5.3"]
$ lein with-profile -dev deps :plugin-tree

```

But if a test or run is performed then plugin is installed.

```
$ lein with-profile -dev test 
Configuring protoc
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
...
```

**Comment by 3duard0** [comment]
I was checking this bug today and here is what I found out so far:
- lein-protobuf adds a hook to `javac`.
- Before leiningen starts to run the task `with-profile` it loads the profile, which in this moment still has dev profile included, and adds the hook from lein-protobuf.
- Then leiningen excludes the dev profile and runs the `test` task, but the hook is still there. As the task `javac` is triggered as a dependency from `test` the hook of protobuf is called.

I'm not sure of the best way of fixing this without changing the behavior of leiningen. Two alternatives came to mind:
- Maybe if `with-profile` removed all the hooks of functions different than `#'with-profile`.
- Not loading any hooks if the task being called is `with-profile`.

Ps: This bug may also involves `middleware` functions.

If any of these alternatives seems fine, I would be happy to implement and submit a solution.

**Comment by technomancy** [comment]
> Maybe if with-profile removed all the hooks of functions different than #'with-profile.

We don't track what hooks are added; there's not really a good way to know what you would need to remove.

> Not loading any hooks if the task being called is with-profile.

I'm pretty sure this would break a lot of existing workflows.

Unfortunately I don't really see a way around this; IMO it's a good example of why we started recommending against using hooks in plugins. They just do not compose well with other features.

I can reopen if there are other suggestions to address this, but I think it's somewhat fundamental. Initializing the project loads the plugins; the plugins can do whatever they want at that stage and Leiningen can't really control it.
