### ISSUE TITLE
JVM_OPTS parsing incorrectly adds trailing spaces to arguments

### ISSUE THREAD

**Issue by sfnelson** [technomancy/leiningen#2145]
When the `JVM_OPTS` shell variable includes multiple spaces between arguments, the `get-jvm-opts-from-env` function incorrectly adds trailing spaces to the previous argument. For example:

```
JVM_OPTS="-Djavax.net.ssl.keyStore=/path/to/file.p12 \
          -Djavax.net.ssl.keyStoreType=pkcs12"
```

After parsing:

```
["-Djavax.net.ssl.keyStore=/path/to/file.p12         " "-Djavax.net.ssl.keyStoreType=pkcs12"]
```

This is obviously incorrect, and unfortunately very confusing (trailing whitespace is very hard to see in exceptions). The issue is caused by incorrect parameter accumulation in the `join-broken-arg` function, whitespace is added even if the given token is empty (i.e. the gap between two spaces).

**Comment by hyPiRion** [comment]
Looks good, thanks! =)
