### ISSUE TITLE
entries in ~/.lein/profiles are ignored

### ISSUE THREAD

**Issue by techwhizbang** [technomancy/leiningen#2147]
I have a ~/.lein/profiles.clj file locally as well on my CI servers. 

I just upgraded to Leiningen 2.6.1 and was previously using 2.3.3. The :manifest section of ~/.lein/profiles.clj file adds some basic info to the manifest section of the jar. 

``` clojure
{:user {:manifest {"BLAH" "HALLLO"}}}
```

The manifest is ignored and does not appear in the unzipped version of the application jar META-INF/MANIFEST.MF

This is reproducible with a vanilla new project via `lein new foo` and then calling `lein with-profile user do clean, jar`

**Comment by techwhizbang** [comment]
Actually this is not limited to the :manifest key, it seems to affect :target-path, :compile-path, :mirrors, :repositories, etc. I've also tried several incantations of these entries with and without the ^:replace and ^:leaky meta to no avail.

**Comment by techwhizbang** [comment]
Unless of course there is some new way to make these changes to take effect that isn't documented according to what is here: https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md

**Comment by techwhizbang** [comment]
As I scan the list of other open issues there seems to be quite a pile up of similar issues.

#2057 
#2058
#2059

**Comment by fractaloop** [comment]
This bug is a blocker for me as well. :+1:

**Comment by benalbrecht** [comment]
i'm having the same issue with the :local-repo key
version 2.5.3 seems to work fine

**Comment by hyPiRion** [comment]
Yeah, this is annoying and could be the cause of the other issues you mentioned.

**Comment by aadrian** [comment]
IMHO this bug is critical.
 
It makes this newly published book: https://pragprog.com/book/dswdcloj2/web-development-with-clojure-second-edition useless for new users, as in order to be able follow along, the user need to change in the profile to a specific version (e.g. Page 4).

**Comment by cprice404** [comment]
@aadrian can you be more specific about what the example in the book shows?  It doesn't seem like page 4 is visible via that link?

**Comment by aadrian** [comment]
> can you be more specific about what the example in the book shows? 

It should not be relevant, since this bug seems to affect all entries that can be made in that file.

The example in the book is setting a specific version on the Luminus template, so that the snippets in the book to correspond to what the user is experiencing.

**Comment by cprice404** [comment]
I was just trying to come up with a reproducer that was a little simpler than the MANIFEST one above, and make sure that it actually covered all of the issues that people have linked to this one.

In any case, I was able to repro with the `MANIFEST.MF` example, and did a git bisect tracing it back to this commit: ca32d3e28a0f2480ea67658d08106cd84c6a90b9

**Comment by aadrian** [comment]
> I was just trying to come up with a reproducer that was a little simpler than the MANIFEST one 

``` {:user {:plugins [[luminus/lein-template "2.9.10.74"]]}}```

**Comment by cprice404** [comment]
@aadrian and then run what command?  because I can run `lein new luminus foo` without specifying that plugin anywhere, even with 2.6.x.

**Comment by aadrian** [comment]
>  can run lein new luminus foo without specifying that plugin anywhere,

Of course you can, but without that profile setting, lein will use the **latest** template available, not the one used throughout the entire book, thus having different libraries and/or versions.

The whole point of it is "wysiwyg" :) : for the user get what it's seeing in the book when it executes commands specified in that book. 

Because many Clojure libraries don't seem to value backward compatibility very much, versions are even more important since allot snippets in most Clojure books are already obsolete :(.

**Comment by cprice404** [comment]
@aadrian all I am asking is if you can give me an example of a command that would succeed with that version and fail with the latest version...

**Comment by techwhizbang** [comment]
The simplest way that I've been able to see the bug occurring aside from the MANIFEST example I provided above but I didn't want to confuse the situation with an external Lein plugin is to add whatever keys you want in the ~/.lein/profiles.clj and then use lein-pprint to see the result via `lein pprint`. 

Looking at that bisect and the timeframe of commit aligns approximately to the Leiningen versions this stopped working properly.

**Comment by cprice404** [comment]
Another clue: this seems to be something special about the `:user` profile.  If you create a profile with a different name in your `~/.lein/profiles.clj`, e.g. `:foo`, and then try to do the `MANIFEST.MF` repro with `with-profile foo do`, the manifest gets the value as one would expect.

Also I was hacking on the source code and effectively reverted the change from ca32d3e28a0f2480ea67658d08106cd84c6a90b9 from the current master branch (by changing the `expand-profiles` function to be a no-op), but the reproducer still reproduces with that change.  This implies that there have been other commits since then that also influence the behavior of this.

**Comment by cprice404** [comment]
[This commit](https://github.com/cprice404/leiningen/commit/def03d9999c70c9b161145d8d8d1ba88cddc33d9) fixes the `MANIFEST.MF` reproducer, but I don't know how to tell if it would break other things.  It doesn't cause any test failures.

However, this patch is just inside the `jar` code, so it wouldn't make any difference whatsoever on the related tickets such as #2058.  So, either these bugs aren't actually related, or perhaps there is a better place for a fix than what I did in that patch.

**Comment by technomancy** [comment]
> It should not be relevant, since this bug seems to affect all entries that can be made in that file.

The `jar` task specifically excludes things from the `:user` profile in order to keep builds deterministic and prevent "works on my machine" issues. It does not affect declarations of plugins, so readers of the book should be able to follow the instructions and have it work.
