### ISSUE TITLE
cannot run install script

### ISSUE THREAD

**Issue by njiang8** [technomancy/leiningen#2148]
So I got this issue when trying to install lein
```
Downloading Leiningen to /Users/nanjiangjiang/.lein/self-installs/leiningen-2.6.1-standalone.jar now...
curl: (1) Protocol "https" not supported or disabled in libcurl
Failed to download https://github.com/technomancy/leiningen/releases/download/2.6.1/leiningen-2.6.1-standalone.zip (exit code 1)
It's possible your HTTP client's certificate store does not have the
correct certificate authority needed. This is often caused by an
out-of-date version of libssl. It's also possible that you're behind a
firewall and haven't set HTTP_PROXY and HTTPS_PROXY.
```

I've looked at all the related problems with this error message but still have no clue... I tried manually download the zip file and put it in `~/.lein` but the prolem still exists
Thanks in advance

**Comment by winks** [comment]
Have you tried to put the zip in the folder `/Users/nanjiangjiang/.lein/self-installs/` but use `leiningen-2.6.1-standalone.jar` as the filename?

(It's a Github limitation as far as I know, we download a .zip and then rename it to. jar)

**Comment by njiang8** [comment]
That works! Thanks
