### ISSUE TITLE
LEIN_HOME not used to resolve .m2 dir for plugins

### ISSUE THREAD

**Issue by lambda-ai** [technomancy/leiningen#2158]
Hi,

when building on our CI server, the process can't write in the user's home directory, which was no problem for the build up to now, since I set LEIN_HOME to a location that could be written to. However, when adding the environ plugin, I again got the same issue, and I can't see any variable to set to avoid this.

[EDITED:]
I initially thought the local-repo mechanism was working, but that's not true. In fact I don't have any way to run the build.

Thanks,
-Mathias

**Comment by hyPiRion** [comment]
Hi there!

I think I need some more information here: Do you think you could pinpoint what the exact issue is? Is the issue itself that `LEIN_HOME` doesn't work properly, or that leiningen somehow decides to write in the user's home directory regardless?

**Comment by mathiasdw** [comment]
Hi!

I tried to find the code where the mvn cache is resolved, but no luck. Maybe it's in one of the dependencies? Anyway, LEIN_HOME works fine for normal dependencies. It's just that the plugins (for me it was lein-environ) ignore it, and try to write to the user home dir.

**Comment by hyPiRion** [comment]
Ah right, that's probably the issue: It's stored in `$HOME/.m2`. It should in theory be overridden with `:local-repo`, as you said. For example, if you have this in `$LEIN_HOME/profiles.clj`:

```clj
{:user {:local-repo "/my/path/here"}}
```

then that should place the dependencies in `"/my/path/here"` (That works at least on my machine)

**Comment by mathiasdw** [comment]
Hi,
yes, I tried that as well, and again that worked for the normal dependencies, but not for the plugin.

**Comment by hyPiRion** [comment]
alright, then it seems like the plugin dependencies doesn't honor the :local-repo key.

**Comment by carrete** [comment]
See also https://github.com/technomancy/leiningen/issues/2111 and possibly related https://github.com/technomancy/leiningen/issues/2131

**Comment by jeaye** [comment]
This is blocking me, currently, when trying to build an uberjar on NixOS. My Nix builder doesn't have a writeable `HOME`, yet specifying a custom `HOME`, `LEIN_HOME`, `M2_HOME`, and `MAVEN_HOME` won't do the trick; lein still tries to write to the Nix builder's home instead.

**Comment by gentoor** [comment]
move :plugins from project.clj to ~/.lein/profiles.clj. i think this is a bug, and didn't find how to fix it!

**Comment by zerg000000** [comment]
I tried. if the `:local-repo` is defined directly in `project.clj` plugin could be resolved from the path instead of downloading every times.

```{clojure}
(defn init-project
  "Initializes a project by loading certificates, plugins, middleware, etc.
Also merges default profiles."
  ([project default-profiles]
     (-> (project-with-profiles (doto project
                                  (load-certificates)
                                  (init-lein-classpath)
                                  (load-plugins)))
         (init-profiles default-profiles)
         (load-plugins)
         (activate-middleware)))
  ([project] (init-project project [:default])))
```

The suspect is the `load-plugins` call after `init-lein-classpath`. The first call of `load-plugins` is before loading the `project-with-profiles` or `init-profiles`, so the plugins will be loaded without knowing the `:local-repo` in `~/.lein/profiles.clj`.

**Comment by glts** [comment]
@zerg000000 I believe we cannot simply remove the first `load-plugins` call because plugins may include profiles themselves https://github.com/technomancy/leiningen/blob/master/doc/PLUGINS.md#profiles

**Comment by yegortimoshenko** [comment]
Hope this gets resolved soon. Here's a workaround I've used for NixOS builds:

```_JAVA_OPTIONS=-Duser.home=maven lein cljsbuild once```

**Comment by technomancy** [comment]
@gits is correct here; we must load plugins before profiles are loaded because the plugins themselves can contain profiles. I don't see a way around the issue described here without breaking that feature.
