### ISSUE TITLE
Could not find artifact leiningen-core:leiningen-core:jar:2.6.2-SNAPSHOT in clojars 

### ISSUE THREAD

**Issue by jiacai2050** [technomancy/leiningen#2160]
Could not find artifact leiningen-core:leiningen-core:jar:2.6.2-SNAPSHOT in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.

It seems there is no this version in [clojars](https://clojars.org/repo/leiningen-core/leiningen-core/)

**Comment by winks** [comment]
Could it be that you are using `lein`/`lein.bat` from git HEAD?

Please try using the released version: [lein](https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein) / [lein.bat](https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat)

**Comment by jiacai2050** [comment]
Yes, I tried to build leiningen from git HEAD, I want to know how leiningen is developed, to be exactly, the workflow  leiningen dev team  used

**Comment by winks** [comment]
Ok, sorry, in that case you should look at [CONTRIBUTING](https://github.com/technomancy/leiningen/blob/master/CONTRIBUTING.md#bootstrapping)

Basically you need to build leiningen-core first, then leiningen

**Comment by jiacai2050** [comment]
Thanks, I didn't find it at first.
