### ISSUE TITLE
lein deploy doesn't support :classifier parameter

### ISSUE THREAD

**Issue by rationalism** [technomancy/leiningen#2161]
From lein help, the arguments for lein deploy are:

Arguments: ([] [repository] [repository identifier version & files])

It looks like there's no way to deploy a package with both a version and a :classifier keyword, as in this example from https://github.com/technomancy/leiningen/blob/master/sample.project.clj:

:dependencies [[org.jclouds/jclouds "1.0" :classifier "jdk15"]]

I worked around this by deploying with mvn, but it would be more convenient to just use lein deploy.

**Comment by rymndhng** [comment]
Would definitely like this as well. I'm currently using maven to work around this, but would love the ability to infer the classifier from parsing the generated filename.
