### ISSUE TITLE
Building LightTable fails with lein error: "Could not transfer artifact..." on armhf

### ISSUE THREAD

**Issue by nonnymoose** [technomancy/leiningen#2167]
I am trying to compile [LightTable](https://github.com/LightTable), which uses the `lein cljsbuild once app` command to build their project. Lein returns the following error:

```
OpenJDK Zero VM warning: TieredCompilation is disabled in this release.
Could not transfer artifact lein-cljsbuild:lein-cljsbuild:pom:1.0.1 from/to central (https://repo1.maven.org/maven2/): java.lang.IllegalStateException
Could not transfer artifact lein-codox:lein-codox:pom:0.9.0 from/to central (https://repo1.maven.org/maven2/): java.lang.IllegalStateException
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

As far as I can tell, I am _not_ behind a proxy, and I have tried it more than once.
@kenny-evitt says:

> @nonnymoose I can't reproduce this. I also just noticed that, according to the output in your comment, the build is attempting to download lein-cljsbuild and lein-codox from Maven ("central") instead of Clojars. I'm guessing your Leiningen configuration is not the same as mine.

Any help would be appreciated, and I would be happy to modify my configuration myself if necessary.
The related issue in LightTable is LightTable/LightTable#2224

**Comment by beniwtv** [comment]
Seeing the same problem here when trying to build PuppetDB:

```
OpenJDK Zero VM warning: TieredCompilation is disabled in this release.
Could not transfer artifact lein-release:lein-release:pom:1.0.5 from/to central (https://repo1.maven.org/maven2/): java.lang.IllegalStateException
Could not transfer artifact lein-cloverage:lein-cloverage:pom:1.0.6 from/to central (https://repo1.maven.org/maven2/): java.lang.IllegalStateException
Could not transfer artifact puppetlabs:i18n:pom:0.2.2 from/to central (https://repo1.maven.org/maven2/): java.lang.IllegalStateException
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

This is on an ARM v7 machine running Ubuntu 16.04 LTS.

**Comment by scgilardi** [comment]
the info here looks relevant: http://stackoverflow.com/questions/37167189/illegalstateexception-thrown-by-maven-ssl-related-when-downloading-project-de

**Comment by technomancy** [comment]
This looks an awful lot like a bug in the packaging of the JVM for that platform.
