### ISSUE TITLE
Tests failing related to clojars-ssl-cert

### ISSUE THREAD

**Issue by cprice404** [technomancy/leiningen#2170]
After the most recently merged PR, [travis is failing](https://travis-ci.org/technomancy/leiningen/jobs/144248991) with the following error:

```
lein test :only leiningen.test.keys/clojars-ssl-cert

FAIL in (clojars-ssl-cert) (keys.clj:13)
If this fails, yell at _ato to get a new SSL cert.
expected: (< (System/currentTimeMillis) (.getTime month-before-cert-expiry))
  actual: (not (< 1468349427928 1468281600000))
```

That sounds like the clojars server cert may be expired?  Which could theoretically explain some of the other SSL-related issues people have been running into lately?

I will attempt to look into it further but if anyone knows more about this error than I do, info would be appreciated!

**Comment by hyPiRion** [comment]
As discussed on IRC:

```
21:25|  cprice404| so, it seems like there are 2 steps here maybe:
21:25|  cprice404| 1. find the new clojars.pem and replace the old one with it, and
21:26|  cprice404| 2. possibly remove that date check test if the coverage it provides is happening in clojars already?  Though it seems like it might still be worth keeping that 
                   test around to highlight when the clojars.pem needs to be replaced for use in the lein production code?
```

**Comment by cprice404** [comment]
The FAQ indicates that leiningen packages the clojars cert for use as a client cert, so we opted to keep the test around as a reminder that that cert will need to be updated periodically.
