### ISSUE TITLE
Leiningen test hooks clash with test.check 0.9.0

### ISSUE THREAD

**Issue by gaverhae** [technomancy/leiningen#2173]
Minimal (or at least small) reproducing example, `project.clj`:

``` clojure
(defproject t "0"
  :dependencies [[org.clojure/clojure "1.9.0-alpha10"]
                 [org.clojure/test.check "0.9.0"]])
```

`test/t/core_test.clj`

``` clojure
(ns t.core-test
  (:require [clojure.spec :as spec]
            [clojure.spec.test :as spec.test]
            [clojure.test :refer :all]))

(defn dummy [i] (inc i))

(deftest fails
  (is (true?
        (->
          (spec.test/check-fn
            dummy
            (spec/fspec
              :args (spec/tuple int?)
              :ret integer?
              :fn #(= (-> % :ret) (-> % :args first inc))))
          :clojure.spec.test.check/ret :result))))
```

I would expect that test to pass. Running the `check-fn` in the REPL works fine. When running `lein test`, however, I get:

```
ERROR in (fails) (Compiler.java:7410)
expected: (true? (-> (spec.test/check-fn dummy (spec/fspec :args (spec/tuple int?) :ret integer? :fn (fn* [p1__485#] (= (-> p1__485# :ret) (-> p1__485# :args first inc))))) :clojure.spec.test.check/ret :result))
  actual: clojure.lang.Compiler$CompilerException: java.lang.ClassCastException: clojure.lang.AFunction$1 cannot be cast to clojure.lang.MultiFn, compiling:(clojure/test/check/clojure_test.cljc:95:1)
```

That [test.check line 95](https://github.com/clojure/test.check/blob/f8b1c969fe0ae85870a9fb17ee88d0ec5176c3f6/src/main/clojure/clojure/test/check/clojure_test.cljc#L95) is trying to call `get-method` on `clojure.test/report`, which is [defined as a multimethod in `clojure.test`](https://github.com/clojure/clojure/blob/clojure-1.9.0-alpha10/src/clj/clojure/test.clj#L324).

Running the above tests with `tools.trace` enabled, I got:

```
TRACE t493: (clojure.core/alter-var-root #'clojure.test/report #object[leiningen.core.injected$prepare_for_hooks$fn__34 0x55795845 "leiningen.core.injected$prepare_for_hooks$fn__34@55795845"])
TRACE t493: => #object[clojure.lang.AFunction$1 0x5b970f7 "clojure.lang.AFunction$1@5b970f7"]
```

which leads me to believe that the source of the problem is [somewhere around here](https://github.com/technomancy/leiningen/blob/2.6.1/src/leiningen/test.clj#L76), though I am definitely not familiar enough with that code to understand the implications. Should this be filed against robert-hooke to keep the "multi" nature of a redefined fn?

**Comment by puredanger** [comment]
One workaround for this problem is to turn off lein monkey-patching of clojure.test in your project.clj:

`:monkeypatch-clojure-test false` 

Also, I believe test.check has a change that avoids this in master for the next version.

**Comment by puredanger** [comment]
Also see http://dev.clojure.org/jira/browse/TCHECK-113

**Comment by otfrom** [comment]
I bumped into this problem on 19 Sept. Adding `:monkeypatch-clojure-test false` worked, but it failed as above without it.

**Comment by technomancy** [comment]
I don't think there's much we can do about this; `clojure.test` is notoriously inflexible, and my efforts to improve it upstream have historically had a very poor success rate; otherwise we never would have resorted to this unfortunate monkeypatching.

If I had to do it over again I would have made `lein test` use a fork of `clojure.test` so that we could improve it as needed, but there's no way to give up on the monkeypatching now without breaking existing features.

**Comment by didibus** [comment]
Another workaround is to add `(run-tests)` at the end of you test namespace. It has the unfortunate effect of having lein run the tests twice, but it appears to fix this issue at the same time.

**Comment by conan** [comment]
I've encountered this without depending on `test.check` directly, but instead pulling it in via `clojure.spec.test.alpha`.  `:monkeypatch-clojure-test false` in the `project.clj` makes it work.
