### ISSUE TITLE
2.7.0 release date?

### ISSUE THREAD

**Issue by cprice404** [technomancy/leiningen#2177]
Does anyone have any idea when we might be able to do a 2.7.0 release?  Or if there are any must-have issues that need to be addressed prior to that release?

**Comment by hyPiRion** [comment]
I've been in the mountains for a week now, so I haven't seen through the issue list. If nothing very important has come up, I'd like to review and merge in #2112 before we publish 2.7.0, but apart from that, there's nothing specific.

Generally happy for more pull requests merged in or reviewed, but nothing critical.

**Comment by cprice404** [comment]
Thanks!  Hope I didn't bother you during your holiday.

I can try to find some time to look over #2112.

**Comment by cprice404** [comment]
I spent some time reviewing #2112 last week but haven't heard back from the author yet.  It has some merge conflicts and IMO there are probably a few design ideas that should be discussed before it should be considered for merge.  Perhaps that one could land in 2.8.0?  Version numbers are cheap, right?  :P

**Comment by hyPiRion** [comment]
@cprice404: Yeah, I've looked on #2112 as well, and think we can do without it. I'll be looking at some of the smaller PRs and then push out a release after that.

**Comment by cprice404** [comment]
@hyPiRion that's great news, please let me know if there is anything I can do to help.

**Comment by cprice404** [comment]
@hyPiRion any particular small PRs you'd like help reviewing?

**Comment by hyPiRion** [comment]
@cprice404: I did a couple of PRs yesterday, would like to get #2169, #2174 and #2180 in as well, if they're mergeable. I'll start on them in ~10-12 hrs time, but feel free to review and merge if you got time/have a Windows machine nearby.

**Comment by cprice404** [comment]
@hyPiRion I took care of that first one.  Started to look into the other two by grabbing a VMWare windows VM at the office, but quickly realized that I have no idea how to Windows.  :)  Ran out of time.  May be able to try again tomorrow if you haven't already taken care of them.  Thanks!

**Comment by hyPiRion** [comment]
@cprice404 : Thanks for looking into #2169 :)

And yeah, I too ran out of time today after trying to install the JDK 8 on a Windows VM.

**Comment by cprice404** [comment]
FWIW my more windows-savvy co-workers turned me on to using 'chocolatey' to install git and the JDK.  That makes it as simple as:

```
net install git
net install jdk8
```

Will let you know if I have time to get any farther on it today.

**Comment by cprice404** [comment]
@hyPiRion I spent some more time trying to play with the powershell PR on a win10 vm today; I can't seem to figure out how to bootstrap lein from source on windows.  It keeps telling me that the jar doesn't exist in the "self-install" dir, but it explodes if I try to run `self-install`.  I tried using a released version of lein to do an `uberjar` and then I was going to copy that file into place, but that just ended with a StackOverflowError.

If you still need help poking at that PR and can give me any clues about how to bootstrap on Windows, I can try again tomorrow.

**Comment by hyPiRion** [comment]
Oh, no worries, I think I got it under control.

The most important thing is not really that it bootstraps properly – although it would make it easier for newcomers – but that it works with the jar files. So I just replaced "2.6.2-SNAPSHOT" with "2.6.1" and checked if it worked.

**Comment by cprice404** [comment]
@hyPiRion hooray!  Thanks for all of your work getting the release out.  I will try to help keep an eye out for any bug reports with 2.7.0, but also feel free to ping me in IRC or whatever if you need a hand with anything!
