### ISSUE TITLE
lein repl: Windows 10 error

### ISSUE THREAD

**Issue by okant** [technomancy/leiningen#2178]
I have installed leiningen via installer. 

When I try to run "lein repl" command I get this error.

In such situation, what should I do?

![repl error](https://cloud.githubusercontent.com/assets/20689415/17189708/65d3c93e-544b-11e6-8c3a-6235371cb365.png)

If this issue is an unappropriated one, sorry for disturbing

**Comment by winks** [comment]
ouch, this might a problem with the path and escaping.

Could you please try to run in "c:\users" or any other path without spaces? (If my theory of the "ve" coming from your username is correct)

**Comment by lopalghost** [comment]
I ran into this problem--it was indeed due to spaces in the path name. For a temporary fix, you can edit lein.bat and change

`set CLASSPATH=%LEIN_JAR%`
to
`set CLASSPATH="%LEIN_JAR%"` (with quotes)

It seems the quotes were removed at some point, I assume because they caused another issue?

**Comment by bcalco** [comment]
I moreover recommend adding %CLASSPATH%, thusly:

     set CLASSPATH="%LEIN_JAR%;%CLASSPATH%"

**Comment by hyPiRion** [comment]
This was fixed in 2.7.0.
