### ISSUE TITLE
Typo in tutorial jar file name

### ISSUE THREAD

**Issue by webappzero** [technomancy/leiningen#2183]
The name of jar file on line 579 of doc/TUTORIAL.md doesn't match either name generated in lines 572 or 573.

579:     my-stuff-0.1.0-standalone.jar

572:     my-stuff-0.1.0-SNAPSHOT.jar
573:     my-stuff-0.1.0-SNAPSHOT-standalone.jar

**Comment by cprice404** [comment]
Closed via #2184
