### ISSUE TITLE
`lein repl` hangs in Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by whitecoop** [technomancy/leiningen#2185]
Java starts and holds about 30% of my CPU, but nothing happens. I've tried `lein repl` inside a Leiningen project and outside. `Cntl + c` won't kill it once it hangs.

![repl-hangs](https://cloud.githubusercontent.com/assets/10946864/17413530/631f7e40-5a36-11e6-90cb-709bc3cc96cb.PNG)

Since other `lein` commands work, I thought the issue might be with Leiningen rather than Bash on Windows, but I wouldn't rule it out (it is still in beta).

It's pictured above, but here's the `lein -version` output: `Leiningen 2.6.1 on Java 1.7.0_101 OpenJDK 64-Bit Server VM`

Also, while I was typing this up, the process finally gave up and offered this:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (safepoint.cpp:325), pid=60, tid=140237077153536
#  guarantee(PageArmed == 0) failed: invariant
#
[thread 140237058672384 also had an error]
# JRE version: OpenJDK Runtime Environment (7.0_101) (build 1.7.0_101-b00)
# Java VM: OpenJDK 64-Bit Server VM (24.95-b01 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 2.6.6
# Distribution: Ubuntu 14.04 LTS, package 7u101-2.6.6-0ubuntu0.14.04.1
# Core dump written. Default location: /home/whitecoop/core or core.60
#
# An error report file with more information is saved as:
# /home/whitecoop/hs_err_pid60.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
#
/usr/bin/lein: line 396:    60 Aborted                 (core dumped) "$LEIN_JAVA_CMD" "${BOOTCLASSPATH[@]}" -Dfile.encoding=UTF-8 -Dmaven.wagon.http.ssl.easy=false -Dmaven.wagon.rto=10000 $LEIN_JVM_OPTS -Dleiningen.original.pwd="$ORIGINAL_PWD" -Dleiningen.script="$SCRIPT" -classpath "$CLASSPATH" clojure.main -m leiningen.core.main "$@"
```

**Comment by kumarshantanu** [comment]
Given that even the `java -version` command (for Oracle 1.8 JDK) hangs on my Ubuntu/Windows10/WSL setup, I guess WSL is not quite ready to run Java yet.

**Comment by conan** [comment]
`java -version` works fine for me if java is acquired using `sudo apt-get install default-jdk`.  Details over on the referenced issue above.

**Comment by whitecoop** [comment]
Adding this for others reference. This is where the real issue(s) are: [https://github.com/Microsoft/BashOnWindows/issues/541](https://github.com/Microsoft/BashOnWindows/issues/541)

**Comment by technomancy** [comment]
The referenced issue has been closed; does this still happen?

**Comment by whitecoop** [comment]
@technomancy unfortunately I don't have a windows machine anymore, so I can't test it... I do recall a while ago now (likely this happened since I opened this issue) there was a substantial release of WSL (v2, maybe?) that addressed a number of more deeply nested challenges (running Java bumped into them sometimes), but it's been a long time since I was reading about / following those developments and I no longer follow that space. Feel free to close this issue if you like.

**Comment by technomancy** [comment]
OK no problem. We can reopen if we get reports of it still happening.
