### ISSUE TITLE
Ability to pin lein to a specific version

### ISSUE THREAD

**Issue by raags** [technomancy/leiningen#2186]
I see that the script exports LEIN_VERSION right at the top; can we source a file say ~/$LEIN_HOME/lein-version and use that instead? Use case would be to pin lein to a specific version, and upgrade when needed/tested.

**Comment by hyPiRion** [comment]
I don't think that's necessary – first and foremost, we have `lein upgrade vsn` and `lein downgrade vsn`, so if you wanted to change to version 2.4.0 for example, you could just do `lein downgrade 2.4.0`.

The scripts are also standalone, so I tend to just copy the lein file when a new release comes out; You can e.g. copy the lein script to `lein-2.4.0` and then do `lein-2.4.0 downgrade 2.4.0` if you want it to refer to 2.4.0.

**Comment by technomancy** [comment]
If you want all users to be on the same version of Leiningen, I recommend copying `bin/lein` into the project repo itself and using that.

I would accept a patch to warn or abort on a mismatch, but it won't do any good for versions that already exist.
