### ISSUE TITLE
lein test - Support clojure.test.junit

### ISSUE THREAD

**Issue by urzds** [technomancy/leiningen#2188]
[`clojure.test.junit`](https://clojure.github.io/clojure/clojure.test-api.html#clojure.test.junit) is a "clojure.test extension for JUnit-compatible XML output". A call to `clojure.test.junit/with-junit-output` needs to wrap the call to `clojure.test/run-tests` to produce XML output. It would be great if `lein test` could support this, e.g. through a `--with-xunit` commandline parameter, like some [other](http://nose.readthedocs.io/en/latest/plugins/xunit.html) [tools](http://doc.pytest.org/en/latest/usage.html) do.

**Comment by hyPiRion** [comment]
I'm not sure if this is easy to do or not – we already do a lot of monkeypatching inside `lein test`, and I'd prefer to not add more in there for now. If this is really easy to add support for then I wouldn't mind, but if this turns out to be nasty, then I'd prefer that this functionality is included via a plugin (unless that's impossible).

**Comment by tlrobinson** [comment]
@urzds Have you found any other way to get junit output? I tried https://github.com/ruedigergad/test2junit but just get `Ran 0 tests containing 0 assertions`

**Comment by SevereOverfl0w** [comment]
Given that almost anything can wrap around `clojure.test/report` function (including JUnit and TAP) it would be better if this takes a reference to a function that will wrap the tests.

This allows per-project reporters.

**Comment by devurandom** [comment]
@tlrobinson I used Midje until now. Its JUnit output is not perfect, but it mostly works.

@SevereOverfl0w You mean instead of
```clj
(with-junit-output
  (run-tests 'my.cool.library))
```
the following should be used?
```clj
(defn junit-report [&args]
  (clojure.test.junit/with-junit-output
    (apply clojure.test/report args)))
(binding [clojure.test/report junit-report]
  (clojure.test/run-tests 'my.cool.library))
```

What exactly would be the benefit?

**Comment by SevereOverfl0w** [comment]
@devurandom Sorry, no. I mean that I should be able to do `lein test :reporter clojure.test.junit/with-junit-output` instead of `lein test :reporter {junit,tap}`, to ensure that future reporters are compatible with leiningen, we shouldn't hardcode the two options that are available in core.

**Comment by kenrestivo-stem** [comment]
I had no problems by doing this:

```clojure
  :aliases {"junit" ["with-profile" "test" "do" "test-out" "junit" "junit.xml"]
          ....
:plugins [[lein-test-out "0.3.1"]
              ...


Then I could just run 

```sh
lein junit
```

And got what I wanted.

**Comment by technomancy** [comment]
The built-in support for junit in `clojure.test` is not suitable for general-purpose use because it swallows all normal error/failure output. We already monkeypatch `clojure.test` pretty hard, so I am much more inclined to point people to a third-party test runner than to try to mangle `clojure.test` even harder.

**Comment by kenrestivo-stem** [comment]
True, I had to do a 

```clojure
(log/set-level! :error)
```
At the top of my core.clj file in order to get valid junit.xml output.

What test runner do you recommend for outputting junit.xml (for use in, sorry about this, Jenkins) from clojure.test tests?

**Comment by technomancy** [comment]
> What test runner do you recommend for outputting junit.xml (for use in, sorry about this, Jenkins) from clojure.test tests?

I have been looking into this and haven't found one I can recommend yet.

**Comment by danielcompton** [comment]
I use https://github.com/ruedigergad/test2junit with CircleCI successfully.

**Comment by technomancy** [comment]
I'm going to close this out since it shouldn't be handled as part of Leiningen, but I would accept a documentation patch recommending plugin alternatives.
