### ISSUE TITLE
JAVA_OPTS are not correctly handled

### ISSUE THREAD

**Issue by munk** [technomancy/leiningen#2190]
```
❯ JAVA_OPTS="-Xms256m -Xmx8192m -XX:+HeapDumpOnOutOfMemoryError" lein test; lein version
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Error occurred during initialization of VM
Initial heap size set to a larger value than the maximum heap size
Tests failed.
Leiningen 2.6.1 on Java 1.8.0_25 Java HotSpot(TM) 64-Bit Server VM
```

When running this with my project, I get an initialization error. The initial heap size is not larger than the max heap size, so something wonky is going on. I would expect that this configuration would build correctly instead of throwing an error. Maybe the options are not being parsed correctly?

**Comment by hyPiRion** [comment]
I'm unable to reproduce this issue.

Inside a project, the `:jvm-opts` inside project.clj  will be spliced in as arguments before `JAVA_OPTS`, which may cause issues if you're attempting to override the default project.clj options. Could this be the issue here?

**Comment by munk** [comment]
This was happening on my local CI server and it seems to have resolved itself. I suspect it was some versioning problem somewhere. If I reencounter it I'll try to make this more reproducible and open a new issue.
