### ISSUE TITLE
Change leiningen downloader

### ISSUE THREAD

**Issue by danceasarxx** [technomancy/leiningen#2191]
Is there a way to change the application leiningen uses to refresh packages, or even download packages

**Comment by winks** [comment]
Can you elaborate? Is something not working?

**Comment by danceasarxx** [comment]
I have been waiting for about an hour to update search index....it's still at `42%`

**Comment by danceasarxx** [comment]
I just checked the download size, **over** `200MB`. Hope I wont have to download this again.

**Comment by winks** [comment]
The search functionality is kind of a sore point. I'd suggest just using web search to find the packages you need on central or clojars.

I did suggest to use web search by default in the past but I'm sure someone had a good reason why we still have this.

**Comment by hyPiRion** [comment]
Yeah, `lein search` isn't the best thing in the world, and we're planning to take it out of Lein proper sometime. I'd suggest using clojars/github/[The Clojure Toolbox](http://www.clojure-toolbox.com/) when searching for libraries as of now.

The index is only used for `lein search`, so fortunately no other tasks will attempt to download it.

**Comment by danceasarxx** [comment]
Thanks....makes sense
