### ISSUE TITLE
managed dependencies: look into supporting `:exclusions`, etc., without requiring explicit `nil` for version number

### ISSUE THREAD

**Issue by cprice404** [technomancy/leiningen#2195]
As discussed in #2194 , the syntax for using managed dependencies in cases where you need additional modifiers for a dependency (e.g. `:classifier`, `:exclusions`) is not entirely intuitive.

If you don't need any such modifiers, you can use managed dependencies by just omitting the version string from your declared dependency:

```clj
:dependencies [[clj-time]]
```

You can also explicitly specify a `nil` for the version string, which has the same effect but is not entirely intuitive:

```clj
:dependencies [[clj-time nil]]
```

If you do need modifiers, then only the latter syntax works:

```clj
:dependencies [[clj-time nil :exclusions [foo]]
```

This syntax, which is probably more intuitive to users, does *not* currently work:

```clj
:dependencies [[clj-time :exclusions [foo]]
```

It would definitely be nice to be able to support this last syntax.  My recollection was that doing so was going to require some more intrusive changes to the lein dependency code, so I didn't try to bite that off in the first pass, but it is probably worth revisiting.

If my memory serves, this would probably also require some changes to the upstream `pomegranate` library.

**Comment by hyPiRion** [comment]
Any reason why we can't massage the vectors before passing them to pomegranate? That seems doable to me, but perhaps you hit on something when you implemented this.

**Comment by cprice404** [comment]
You're probably right about that, good point.
