### ISSUE TITLE
Updating GPG documentation for GPG2 on Homebrew

### ISSUE THREAD

**Issue by danielcompton** [technomancy/leiningen#2200]
Homebrew has [started](https://github.com/Homebrew/homebrew-core/commit/912329f6c9fff00d88086e295d25ee2aceadb7da#diff-4915eb70a37408b4ffd6432f88db943c) installing gnupg 1 with the `1` suffix, which means that Leiningen signing will break if users update their (currently working) gpg through Homebrew. There's at least these options available:

* Update the docs to tell homebrew users to install `brew install gnupg2`. I did this, and everything seemed to work ok.
* Update Leiningen to look for `gpg1` if `gpg` is not found
* Tell users to use the `gpgbin` workaround described in the caveats for the formula.

**Comment by hyPiRion** [comment]
If this works fine with gnupg2 and there's no big reason to not install it, then I don't think it's important to support gpg1 out of the box – we already have `LEIN_GPG` which can be used to refer to GPG in case it has a different name. Happy to get this documented better though.
