### ISSUE TITLE
Improve the Windows situation for sdkman builds

### ISSUE THREAD

**Issue by hypirion** [technomancy/leiningen#2210]
The current SDKMAN deploys only consists of the bat script where you have to call self-install manually. It should preferably be a PowerShell script instead, and it should refer to  the jar file in /lib/.

Relates to #2192 and #2193.

**Comment by technomancy** [comment]
Honestly I'm not sure how downstream packaging scripts ended up in the lein repo; they should be maintained by the downstream packagers instead.

**Comment by winks** [comment]
I'm not even sure we're using `bin/lein-sdkman` anymore for https://github.com/leiningen/leiningen-sdkman

Making a note here to doublecheck, but we can probably delete it in the main repo.

**Comment by technomancy** [comment]
I went ahead and removed the script from our repo so if you need to grab a copy for the downstream, just look a few revisions back.
