### ISSUE TITLE
Bump cheshire again

### ISSUE THREAD

**Issue by mhjort** [technomancy/leiningen#2215]
Many people are working on AWS related plugins. AWS SDK nowadays requires 2.6.x version of Jackson library. Bumping Cheshire dependency in Leiningen would fix the issue.

**Comment by hyPiRion** [comment]
Thanks for mentioning this, this is now bumped on master. (I'm guessing jackson 2.7.x works fine as well)

**Comment by mrmcc3** [comment]
I've run into this AWS/Cheshire/Jackson version mismatch several times when developing plugins. It's extremely frustrating and hard to track down. I see this is fixed on master but I fear this issues will reappear again if/when Jackson makes breaking changes that AWS adopts before leiningen. From what I can see the only place cheshire is used is in `leiningen.search`. Would it be better if we just used clojure/data.json and eliminate these future dependency mismatches

**Comment by technomancy** [comment]
The search task is the only direct dependency, but we also pull it in via reply, the nrepl client.

**Comment by mrmcc3** [comment]
Ahh right makes sense

**Comment by technomancy** [comment]
Leiningen no longer depends on Cheshire: https://github.com/technomancy/leiningen/commit/f27dff2a07c9ee0d0c6ece10332488b89c03c7dd
