### ISSUE TITLE
Allow specifying javac command path

### ISSUE THREAD

**Issue by Meidan** [technomancy/leiningen#2222]
If a machine has more than 1 jdk installed, allow using the non-default one by specifying a path for the javac command, for tasks such as lein uberjar.

**Comment by winks** [comment]
does setting `JAVA_CMD` help?

https://github.com/technomancy/leiningen/blob/master/bin/lein#L225

**Comment by Meidan** [comment]
I tried `java-cmd`, it didn't help. An equivalent for javac would probably will.

**Comment by winks** [comment]
When I run lein 2.7.0 like this:
```
JAVA_CMD=/some/path/to/another/java lein uberjar
```

and then extract it via `jar xf foo.jar` then I see the correct JDK version in the in the `META-INF/MANIFEST.MF` file

**Comment by Meidan** [comment]
Cool, that works! (I was trying to get `:java-cmd` to work at the project level which would be more elegant, that I completely missed your reference)

**Comment by winks** [comment]
Awesome, closing this then :)
