### ISSUE TITLE
Very vague warning message if you use sudo lein.

### ISSUE THREAD

**Issue by rjb25** [technomancy/leiningen#2230]
The final line of this warning `Set LEIN_ROOT to disable this warning` is what is not very clear.
It does not specify where or anything related to how to do this. A file name or even type would make this message a lot more helpful.
```
WARNING: You're currently running as root; probably by accident.
Press control-C to abort or Enter to continue as root.
Set LEIN_ROOT to disable this warning.
```

**Comment by hyPiRion** [comment]
Yeah, happy to add a patch with information that this is an environment variable. Do you think `Set the environment variable LEIN_ROOT to disable this warning` would be sufficient?

**Comment by rjb25** [comment]
Yes. That gives enough to let me or anyone know where to start looking. Thanks!

**Comment by rjb25** [comment]
In case anyone else is wondering what an environment variable is, [this](https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps) should help.

**Comment by rjb25** [comment]
Is there a reason the following still throws the same warning?
```text
$ export LEIN_ROOT=true
$ sudo lein
WARNING:...
```

**Comment by hyPiRion** [comment]
`sudo` does not preserve environment variables unless you pass `-E` to it; try

```shell
$ sudo -E lein
```

Also, may I ask why you're using `sudo lein` here? There's usually no need to use lein as a root user, unless you lack ownership for some of the files lein operates on.

**Comment by rjb25** [comment]
I think I am falling into that 'unless' case. Here is the first line of the error I get when I execute
`lein run`.
```
java.io.FileNotFoundException: /var/www/codelifeblog.com/target/classes/META-INF/maven/cryogen/cryogen/pom.properties (Permission denied)
```
