### ISSUE TITLE
Could not transfer artifact.... access denied

### ISSUE THREAD

**Issue by michaellindon** [technomancy/leiningen#2240]
I have the following project
https://github.com/michaellindon/sss4clj
https://clojars.org/sss4clj
which I am trying to set up travis for.

My build always fails on travis-ci with the following error message

> Could not transfer artifact org.clojure:clojure:pom:1.3.0-alpha2 from/to clojure (http://build.clojure.org/releases): Access denied to: http://build.clojure.org/releases/org/clojure/clojure/1.3.0-alpha2/clojure-1.3.0-alpha2.pom , ReasonPhrase:Forbidden.
> 
> This could be due to a typo in :dependencies or network issues.
> 
> If you are behind a proxy, try setting the 'http_proxy' environment variable.

I have attached the full build log from travis in log.txt
[log.txt](https://github.com/technomancy/leiningen/files/737769/log.txt)

I had the same issue when performing lein deps on my personal computer. On my office computer everything worked fine, but fails on my laptop, so this is not unique to travis. I was able to run it on my laptop by copying the downloaded files off of my work computer, yet this solution is not possible for travis or users who may want to use this package.

My project.clj file at the current time looks like 

```
(defproject sss4clj "0.1.0-SNAPSHOT"
  :description "Shotgun Stochastic Search Algorithm"
  :url "https://github.com/michaellindon/sss4clj"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [incanter "1.9.1"]
                 [net.mikera/core.matrix "0.57.0"]
                 [net.mikera/vectorz-clj "0.45.0"]
                 [org.clojure/test.check "0.9.0"]
                 [org.clojure/data.priority-map "0.0.7"]])

```
Can someone please help?

**Comment by danielcompton** [comment]
It seems slightly surprising that your system is reaching out to build.clojure.org. I'm not quite sure why it would be doing that, as I assumed that your dependencies `:repositories` wouldn't be searched. You could try adding `:exclusions [org.clojure/clojure]` to all of the dependencies to stop it from downloading it, e.g.: `[net.mikera/core.matrix "0.57.0" :exclusions [org.clojure/clojure]`, and running `lein deps :tree` to find out which library is pulling that version in.

Also, do you have anything in your ~/.lein/profiles.clj which could be causing this?

**Comment by michaellindon** [comment]
The following worked for me:
Rather than importing all of incanter I changed the dependency 
from
[incanter "1.9.1"]
to
[incanter/incanter-core "1.9.1"]

so that stuff I didn't need is ignored. Moreover in my .travis.yml I added

jdk:
  - oraclejdk8

and now it works

**Comment by yochannah** [comment]
I had the same issue, and fixed it with the incanter fix detailed above. @michaellindon Thanks for posting your solution!!

**Comment by Hendekagon** [comment]
or [incanter "1.9.1" :exclusions [org.clojure/clojure]]

**Comment by technomancy** [comment]
Sounds like this is a problem with certain dependencies, not Leiningen.

**Comment by puredanger** [comment]
I just happened to walk across this issue while searching for something else but I can shed some light on the question about looking at build.clojure.org. Originally, there was a static Maven repo on build.clojure.org that hosted very old versions of clojure and clojure-contrib and some people had it listed as a repository in their pom. 

When we updated our build boxes in Nov 2016 (and did not move the static repo over), I discovered this as we had an internal build break. Most of the artifacts already existed in Maven Central, but I did find a few that existed nowhere else and in particular I published clojure/clojure-contrib 1.0.0 and 1.1.0 out there, which is where I've seen people run into this. There were also a slew of builds that came out of an interim version of contrib between the original clojure-contrib and the current version - I did not bother pushing those up anywhere, but I do have a copy of everything in that original repo just in case.

**Comment by technomancy** [comment]
@puredanger Good to know; thanks for following up.

**Comment by anantbhargatiya** [comment]
I also faced similar issue (access denied/forbidden) and for me the problem was password issue in settings.xml and security-settings.xml.... mvn has two commands for password encryption mvn -emp <password> which goes to security-settings.xml and another one is mvn -ep <password> which goes to settings.xml. make sure you use correct command and update passwords in both files correctly.
