### ISSUE TITLE
Leiningen can't install maven artifacts whose names are invalid symbols

### ISSUE THREAD

**Issue by cap10morgan** [technomancy/leiningen#2241]
For example: Specifying `net.3scale/3scale-api` in the dependencies causes lein to throw an invalid token exception when it tries to load the `project.clj`.

**Comment by cap10morgan** [comment]
Specifying this dep like this is a workaround: `[~(symbol "net.3scale" "3scale-api") "3.0.2"]`. So if that's the official / best way to do it, I'm happy to close this.

**Comment by hyPiRion** [comment]
It's currently the best – if not the only – way to do it, yeah.

I think this would happen so infrequently (symbol name must start with digit) that I myself wouldn't look into making this more convenient than it currently is. That being said, I wouldn't mind a patch which allows us to use `"net.3scale/3scale-api"` if it doesn't require too big changes in leiningen core.

**Comment by cap10morgan** [comment]
@hyPiRion Let me know what you think of this PR: #2242.

**Comment by hyPiRion** [comment]
Looks good, thanks! :)
