### ISSUE TITLE
Add docker deployment to .travis.yml

### ISSUE THREAD

**Issue by johnmcconnell** [technomancy/leiningen#2245]
Currently, there is no "official" docker image for leiningen. Perhaps, we can add one.

**Comment by technomancy** [comment]
Is this something people would use? I would think people would be more concerned about having control over their OS choice and then just doing the lein install on top of that than using an image that locked them into whatever OS/JDK choices that the official lein image had.

**Comment by johnmcconnell** [comment]
It's a good question. Right now, I would like because of my current automated deploy setup.

That app stated above is a ring application which runs as an uberjar. I would like to bundle the app into a docker image. I would also like the docker image to run database migrations.

Because the docker images runs the server as an uberjar and needs to handle running db migrations, it is easier to include leiningen in the docker image. If there is a better way, I am all ears.

**Comment by johnmcconnell** [comment]
Link to dockerfile mentioned above: https://github.com/optly/api/blob/37-create-docker-build/Dockerfile

**Comment by johnmcconnell** [comment]
Also, the os and jdk can be parameterized as part of the build matrix if you like.

**Comment by technomancy** [comment]
> Because the docker images runs the server as an uberjar and needs to
> handle running db migrations, it is easier to include leiningen in the
> docker image.

I'm not sure I understand. Migrations should be run without Leiningen.

I think there's use cases when you would want to use Leiningen with
docker in CI, but it would need to be on the OS of your choosing, so I
think it makes more sense to focus on getting it into system package
managers like apt and yum.

**Comment by johnmcconnell** [comment]
Totally, getting into the apt and yum repos has a bigger impact. This is more for a very specific use case I am working on.

The application server uses the leiningen plugin, called `drift` and runs via: `lein migrate`

The current docker deployment for the application works like the following:
1. a thing starts a postgresql host
2. a thing runs: `docker run <docker-image> lein migrate` to get the postgres db up to date
3. a thing runs: `docker run -d <docker-image> java -jar target/uberjar/path-to-uberjar.jar` to start the application server

I understand that some init handler could take care of this.

If you are wondering about impact, here are the current images for lein: https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=lein&starCount=0

According to those stats, at best this helps like 2k people.

**Comment by winks** [comment]
Hmm, I'm not sure a generic docker image would help.
While I see no harm in providing one or more official ones, wouldn't it boil down to exactly these steps per distro?

  1. take distro specific base file
  1. install correct java (might be merged with the above)
  1. grab lein script (via wget?), make executable
  1. run lein self-install

or am I missing something?

**Comment by johnmcconnell** [comment]
Right. I didn't think of a generic up to date image and using `lein upgrade`. I think that is the best way to handle it. Do you still want to support an official docker image? I can change the PR.

Containers are useful in that it skips the resolve dependencies stage of deployment.

For example:
* I want service A needs to run.
* host B can run it
* I need to install all of services A dependencies (openssl, glibc, file permissions, etc...) on host A. However, because I am using a docker image these dependencies are packaged up for me and my deployment system "doesn't need to worry about it".
* I can now run service A on host B (assuming docker is on host B).

I wasn't sold on docker at first, but ehh... its a tool

**Comment by winks** [comment]
Yes, I see your point - it makes sense to prepare docker images for certain tools you want in your container. I just think if "smallish" applications like leiningen can be installed with a oneliner and have no config then it's easier if you use any of your docker base images and just create a new snapshot with lein installed. We can't guess who would use which base image, so even a reasonable amount of base images would be useless to 90% of users I guess.

**Comment by johnmcconnell** [comment]
Yeah, it may not be worth the effort. Anyways, I solved my problem with: https://github.com/johnmcconnell/docker-lein, but I should have used: `lein upgrade`. I'm fine closing this, but I'll leave that to you.

**Comment by technomancy** [comment]
Upon further thought I think the main reason I feel uncomfortable with this is that besides being unnecessarily specific, declaring an "official Leiningen image" would imply that we have made a commitment to keep that image up-to-date with security patches. I don't want to be burdened with that for something I don't use myself.

**Comment by technomancy** [comment]
For anyone interested, there are "official" Clojure images on Docker Hub that include Leiningen: https://hub.docker.com/_/clojure/ (They are not actually official in any way other than being marked by Docker as such.)
