### ISSUE TITLE
Middleware and hooks should take into account plugin group

### ISSUE THREAD

**Issue by weavejester** [technomancy/leiningen#2248]
Currently middleware and hooks are automatically loaded from the `plugin-name.plugin` namespace. Unfortunately this does not account for the group name, so a project called something like `foo/lein-plugin` would result in the ambiguous namespace `lein-plugin.plugin`.

Ideally, if the group name is different to the artifact name, the group name should also be used. So `foo/lein-plugin` would result in a namespace `foo.lein-plugin.plugin`.

**Comment by glts** [comment]
This looks like a duplicate of #1274.
