### ISSUE TITLE
Warn when vulnerable JARs are on the classpath?

### ISSUE THREAD

**Issue by danielcompton** [technomancy/leiningen#2253]
AFAIK, Leiningen doesn't have any way of detecting whether JARs with security vulnerabilities are on the classpath. After reading https://opensource.googleblog.com/2017/03/operation-rosehub.html (and remembering the incident last year), I wondered whether it would make sense for Leiningen to maintain a list of JARs that are known to have security vulnerabilities and to warn users when they are on the classpath?

This raises a bunch of questions about how this list is distributed, in some ways similar to [CRL](https://en.wikipedia.org/wiki/Certificate_revocation_list) distribution, but before we go down that path, is this something that Leiningen wants to provide?

**Comment by winks** [comment]
Sounds useful, but in plugin form. While it makes sense to integrate this into ones build workflow I don't think this should be a core functionality or even enabled by default - not even thinking deeper about the problems of keeping the list up to date.

Related tools:

  * https://security.sensiolabs.org/check (PHP composer dependencies)
  * https://hakiri.io/facets (Ruby gems)
  * and many more

But I see none of these integrated into the build tool.

**Comment by hyPiRion** [comment]
I think supporting this in some way would be a great idea, but I hope this could begin as a plugin.

Also, I wish the repositories like maven central/clojars et al would be able to provide some kind of revocation in the future, although I understand that it won't happen immediately. Perhaps it makes sense to speak with other JVM-based languages and make a service for this?

**Comment by danielcompton** [comment]
> Also, I wish the repositories like maven central/clojars et al would be able to provide some kind of revocation in the future, although I understand that it won't happen immediately.

Yeah, I started thinking about showing this on Clojars when I started writing this issue. The downside of relying on Clojars solely, is that many people don't visit it to check out project versions. Revocation is a bit more thorny, as people's build can start breaking.

>  Perhaps it makes sense to speak with other JVM-based languages and make a service for this?

Just to clarify, are you talking about making a service that any JVM based tool can use to check if JARs are safe? That sounds promising, although I'm not sure how it would work from a business perspective, as Sonatype also sells this as part of [Nexus Lifecycle](https://www.sonatype.com/nexus-lifecycle).

I think making a plugin is a good first step to investigate this further. If the plugin proves useful, and lein maintainers agree, I think it could be good to bring it into Leiningen core. Opt-in security would provide protections to the entire lein community, rather than just the few that notice and can be bothered to install the plugin.

**Comment by technomancy** [comment]
I think this should be a 3rd-party service which can follow the Clojars feed. It would be great to create a plugin which could use the service to scan a local project, but since it inherently needs a frequently-updated list I think the canonical source needs to be a service, not a plugin. A service could even open GitHub issues for projects which depend on bad libs.

**Comment by hyPiRion** [comment]
> Revocation is a bit more thorny, as people's build can start breaking.

Yeah, I guess I used revoke incorrectly here. I meant some functionality that could warn users about security issues, but not break their build.

**Comment by zloster** [comment]
My two cents (about the JAR from Java world) Recently I've found out about:

- https://github.com/jeremylong/DependencyCheck - this one seems more sophisticated
- https://github.com/victims/victims-enforcer from http://www.victi.ms/ - this one is only for JARs

At least they will give you some ideas about what and how to be implemented.

**Comment by technomancy** [comment]
Leaving a note for myself if I come back to this issue for later: the source for the DependencyCheck Maven plugin that would need to be ported is at https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-maven/src/main/java/org/owasp/dependencycheck/maven/CheckMojo.java

**Comment by glts** [comment]
Nowadays https://github.com/rm-hull/lein-nvd does this well.

**Comment by technomancy** [comment]
Yeah, I think keeping this in a separate plugin is the way to go.
