### ISSUE TITLE
Release uberjar to clojars

### ISSUE THREAD

**Issue by johnmcconnell** [technomancy/leiningen#2259]
I currently have a use case where my CI infrastructure downloads leiningen and bundles it up with the application. I believe the lein self install uses an AWS endpoint. Can we release leiningen to mvnrepository or clojars?

**Comment by technomancy** [comment]
I don't think they'll accept uploads of uberjars; they have pretty strict requirements on uploads.

**Comment by johnmcconnell** [comment]
Okay thanks!

**Comment by danielcompton** [comment]
Just to follow up on this, there's a 25MB limit on uploads, so Lein's uberjar won't fit.

**Comment by johnmcconnell** [comment]
Thanks daniel
