### ISSUE TITLE
lein uberjar in osx terminal interferes with shell commands

### ISSUE THREAD

**Issue by agoldhammer** [technomancy/leiningen#2260]
After running lein uberjar in osx terminal (or iterm2), ls command no longer shows files. cd command restores functionality of ls. Very weird behavior.

**Comment by technomancy** [comment]
If you can provide a repro case that would be helpful; this does not happen on most projects and is much more likely to be a problem with the project in question than with Leiningen.

**Comment by agoldhammer** [comment]
Here is the project.clj:
(defproject statcounter "0.1.1-SNAPSHOT"
  :description "Query statcounter api"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/core.async "0.3.442"]
                 [org.clojure/data.json "0.2.6"]
                 [net.apribase/clj-dns "0.1.0"]
                 [intervox/clj-progress "0.2.1"]
                 [pandect "0.6.1"]
                 [clj-http "2.0.0"]]
  :main statcounter.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})

core.clj is minimal repro case:
(ns statcounter.core
  (:gen-class))

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println "Hello, World!"))

Following sequence of commands in iterm2 on Mac OSX Sierra 10.2.3 demonstrates problem:
macpro:target agold$ lein compile
macpro:target agold$ lein uberjar
Compiling statcounter.core
Created /Users/agold/Prog/sandbox/statcounter/target/uberjar/statcounter-0.1.1-SNAPSHOT.jar
Created /Users/agold/Prog/sandbox/statcounter/target/uberjar/statcounter-0.1.1-SNAPSHOT-standalone.jar
macpro:target agold$ ls
macpro:target agold$ cd uberjar
macpro:uberjar agold$ ls
classes/
stale/
statcounter-0.1.1-SNAPSHOT-standalone.jar
statcounter-0.1.1-SNAPSHOT.jar
macpro:uberjar agold$

Note that after "lein uberjar" command is run in target directory, ls command produces no output, as if the uberjar directory had disappeared. but "cd uberjar"  changes into that directory, and ls now reveals the existence of files there.

**Comment by technomancy** [comment]
OK, if you're starting *inside* the `target/` directory here then it's just that the directory is deleted during the uberjar process, so your shell is trying to list the files of a non-existent directory; you have to `cd` to a real directory before `ls` will work again. This doesn't really have anything to do with Leiningen, it's just a confusing behavior of your shell.

**Comment by agoldhammer** [comment]
OK, thanks.
