### ISSUE TITLE
Unclear how to provide Wagon Proxy settings

### ISSUE THREAD

**Issue by Zintinio** [technomancy/leiningen#2264]
I wasn't sure where to post this, but I have been having an issue with proxies and leiningen / wagons. Specifically, in `project.clj` the user _should_ be able to pass proxy settings to the underlying network connector for wagon plugins, but I don't see this documented anywhere for either leiningen or the example plugins (s3, etc). A [docstring within Pomegranate](https://github.com/cemerick/pomegranate/blob/master/src/main/clojure/cemerick/pomegranate/aether.clj#L541) specifies a `:proxy` key that should be passed. This should be made clearer to the user.

**Comment by Zintinio** [comment]
I'm still not certain if this actually works, as I've not seen it used anywhere.

**Comment by Zintinio** [comment]
This suddenly works for me, no tweaking necessary. Either something changed with the proxy or an underlying library.

**Comment by glts** [comment]
Hiya, been looking at the proxy stuff … currently Leiningen does not
actually have any knobs to customise the proxy config of the Wagon
directly. Pomegranate of course does understand a map with proxy
settings, but this is an internal implementation detail of Leiningen. It
is not currently exposed in any way, and hence indeed not documented.

As explained in the
[FAQ](https://github.com/technomancy/leiningen/blob/2.7.1/doc/FAQ.md)
and in the [sample
project](https://github.com/technomancy/leiningen/blob/2.7.1/sample.project.clj#L516-L517),
you need to set the usual environment variables `http(s)_proxy` to make
Leiningen use the proxy.

Hope this helps.

**Comment by Zintinio** [comment]
David,

     At the time I posted, leiningen wasn't respecting the aforementioned
variables when using the wagon plugin. After a few updates and possibly
changed to the proxy that we don't control, it started working for us. Hard
to find the root cause, I would close the issue with "can't reproduce".

**Comment by technomancy** [comment]
Feel free to reopen if you've got some concrete suggestions about what could be improved here, but it sounds like the original problem is taken care of.
