### ISSUE TITLE
Documentation for :test-selectors

### ISSUE THREAD

**Issue by Rovanion** [technomancy/leiningen#2265]
In `sample.project.clj` it's mentioned that one should "See `lein help tutorial` for more information." However the output of `lein help tutorial` never mentions the key `:test-selectors` and is therefore of little help on the subject.

Where can one find help on `:test-selectors`? I can't find it mentioned in `doc/`.

**Comment by technomancy** [comment]
I think this is likely to just be a typo; it should say `lein help test`.
