### ISSUE TITLE
Tutorial example url breaks with Oracle JDK due to security cert

### ISSUE THREAD

**Issue by szurcher** [technomancy/leiningen#2268]
A security exception is thrown instead of receiving an http response object when following the tutorial because http://leiningen.org now automatically redirects to https://leiningen.org, and the site's security certificate is from Let's Encrypt which Oracle does not yet have default trust for in their JDK.

For tutorial purposes, it's easily fixed by providing an example url that either does not redirect to https, or to a site with a certificate from an older recognized authority.  On the user/Oracle end it should be possible to import the necessary certificate, though that's an awkward step to take in the middle of a basic tutorial.

The tutorial lines in question:
```
user=> (require '[clj-http.client :as http])
nil
user=> (def response (http/get "http://leiningen.org"))
```

Expected:
```clj
#'user/response
```

Got:
```
CompilerException sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, compiling:(form-init8948635733661338426.clj:1:15)
```

Current Oracle JDK version:
```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
Working alternative examples:
1) `user=> (def response (http/get "http://www.google.com"))`
2) `user=> (def response (http/get "https://www.google.com"))`

**Comment by technomancy** [comment]
This was fixed a while ago.
