### ISSUE TITLE
Sample project.clj points to README.md for documentation on checkout dependencies, but there is none there

### ISSUE THREAD

**Issue by Rovanion** [technomancy/leiningen#2270]
In the sample.project.clj I read

>   ;; Paths to include on the classpath from each project in the                                           
>   ;; checkouts/ directory. (See the FAQ in the Readme for more details                                    
>   ;; about checkout dependencies.) Set this to be a vector of                                             
>   ;; functions that take the target project as argument. Defaults to                                      
>   ;; [:source-paths :compile-path :resource-paths], but you could use                                     
>   ;; the following to share code from the test suite:  

but I find no mention of checkout dependencies in the README. If you could point me towards the documentation I'll correct the sample.project.clj.

**Comment by technomancy** [comment]
Oops; that should say the tutorial instead.
