### ISSUE TITLE
When using `:scm {:name "git"}` pom task doesn't auto-populate the scm/tag node

### ISSUE THREAD

**Issue by nberger** [technomancy/leiningen#2274]
From [a question in the clojars mailing list](https://groups.google.com/forum/#!topic/clojars-maintainers/GWm8tbGp6E4) I realized that the reason why some projects point to `HEAD` as the release commit in clojars (the "with this commit" link) is because they have something like the following in their project.clj: `{:scm {:name "git" :url "https://github.com..."}}`.

The `:name "git"` makes the pom task to not auto-populate the :tag and other nodes in the resulting pom, instead taking those values from the :scm map in the project.clj. But it's common for projects to only have `:name` and `:url` in that map, so `:tag` is not present in their poms, resulting in clojars pointing that link to HEAD (because that's what maven-model's `getTag` returns when it can't find an scm/tag node).

See for example [this lein-ring release](https://clojars.org/lein-ring/versions/0.12.0) where the "with this commit" link points to https://github.com/weavejester/lein-ring/commit/HEAD. Other projects where I've seen this happening are [lein-figwheel](https://clojars.org/lein-figwheel/versions/0.5.10) and [devcards](https://clojars.org/devcards/versions/0.2.3).

Even though [the sample.project.clj explains this behavior](https://github.com/technomancy/leiningen/blob/e829c12d5147ad9b5f1f50032ac1d763e20932e1/sample.project.clj#L469-L471), it seems it takes users by surprise, and also it's not clear what the implications are without a deep knowledge of multiple things.

I'm not sure what's the best way to "fix" this, but here are 2 ideas:

1. Add better documentation about the implications of having `{:scm {:name "git"}}`

All I was able to find about `:scm` in the docs (apart from the comment in sample.project.clj) is the following in DEPLOY.md (and it doesn't help much):

```
4. Conform to Sonatype OSS' requirements for uploaded artifacts' `pom.xml` files;
all you need to do is make sure the following slots are populated
properly in your `project.clj`:

  :description
  :url
  :license
  :scm
  :pom-addition
```

2. Auto-populate from git what's not defined under `:scm`

The pom task could do something like the following in [write-scm-tag](https://github.com/technomancy/leiningen/blob/e829c12d5147ad9b5f1f50032ac1d763e20932e1/src/leiningen/pom.clj#L130) when `(= "git" scm)`:

```clojure
(merge (make-git-scm ...)
       (select-keys (:scm project) ...))
```

This way projects that define any of `[:tag :url :connection :developerConnection]` would keep having those in the generated pom, those who don't will have it populated automatically, like when the `:scm` entry is not present or when it has `:name "auto"`.

Even though the change is not backwards compatible, it doesn't seem to me like it would impact negatively in many projects or any at all.

**Comment by technomancy** [comment]
Sorry for the delay on this; I believe the second option you suggested is the right way to go here. We could allow folks to add `^:replace` metadata when they don't want the auto-detected values to get merged in, similar to how profiles work.

**Comment by nberger** [comment]
No problem!

I agree, the `^:replace` metadata is a good idea. Do you want me to send a PR with this change?

**Comment by technomancy** [comment]
> I agree, the ^:replace metadata is a good idea. Do you want me to send a PR with this change?

Sure; if you're up for it I would take it.

**Comment by nberger** [comment]
@technomancy: I sent #2315 with a possible solution to this. But I didn't implement the `^:replace` part because after thinking more about it, I'm not sure whether it's needed/desired. I added more info about it in the PR. I'd like to hear your opinion, you know more about leiningen conventions and what users would expect.

There's some refactoring in the PR, let me know if you prefer me to remove that and keep the diff as small as possible.
