### ISSUE TITLE
Task-not-found hook?

### ISSUE THREAD

**Issue by bfontaine** [technomancy/leiningen#2275]
Hello,
I’m trying to understand if there’s a way to have a hook that fires when a task is not found. I read PLUGINS.md and it appears we can only wrap functionality around *existing* commands.
I see that `leiningen.core/resolve-task` accepts an optional `not-found` function as its second parameter but I’m not sure how my plugin could change how `apply-task` calls that function and inject its own handler.
Any idea?

**Comment by technomancy** [comment]
There's currently no way to override this behavior. I would be open to taking a patch for this if it functioned similarly to `leiningen.core.project/plugin-hooks` but am unlikely to implement it myself.

**Comment by bfontaine** [comment]
Thanks!
