### ISSUE TITLE
Insecure HTTP exception

### ISSUE THREAD

**Issue by arichiardi** [technomancy/leiningen#2277]
Hello @technomancy,
I get the exception: `java.lang.Exception: Tried to use insecure HTTP repository` for the below dependency. I know that this is due to the new `pomegranate` but I decided to try it out with a clean `lambdacd` project in order to understand and report where it breaks. This is also relevant for https://github.com/boot-clj/boot/pull/612.

```
org.ecCould not find artifact org.ow2.proactive:process-tree-killer:jar:1.0.0 in central (https://repo1.maven.org/maven2/)
Could not find artifact org.ow2.proactive:process-tree-killer:jar:1.0.0 in clojars (https://repo.clojars.org/)
Could not transfer artifact org.ow2.proactive:process-tree-killer:jar:1.0.0 from/to activeon (http://repository.activeeon.com/content/repositories/releases/): Cannot access http://repository.activeeon.com/content/repositories/releases/ with type default using the available connector factories: BasicRepositoryConnectorFactory
Could not transfer artifact org.ow2.proactive:process-tree-killer:pom:1.0.0 from/to activeon (http://repository.activeeon.com/content/repositories/releases/): Cannot access http://repository.activeeon.com/content/repositories/releases/ with type default using the available connector factories: BasicRepositoryConnectorFactory
```

Any good workaround or solution for this?

Thanks a lot for bumping Aether btw :+1:

**Comment by technomancy** [comment]
Thanks for reminding me; I meant to add a FAQ entry about this. I just pushed it; hope that helps clear things up.

**Comment by free-variation** [comment]
Is there a way to find out which dependency is triggering this failure?  Our project has loads of dependencies, including many indirect ones.

**Comment by technomancy** [comment]
> Is there a way to find out which dependency is triggering this failure?

Unfortunately the dependency resolution mechanism we use doesn't give us
a lot of context; I suggest a binary search by removing half your
dependencies at a time.

**Comment by binarykitchen** [comment]
tried the cemerick workaround mentioned in the faq by putting that code on top of project.clj but it didn't make any difference. still seeing the same warning as above.

```clj
;; never do this
(require 'cemerick.pomegranate.aether)
(cemerick.pomegranate.aether/register-wagon-factory!
 "http" #(org.apache.maven.wagon.providers.http.HttpWagon.))
```

on top of project.clj doesnt help. and btw, it's dangerous indeed. it is going to permit other insecure repositories silently ...

is there a known trick to configure a single repository URL to redirect it to plain HTTP on a private network?

**Comment by technomancy** [comment]
> is there a known trick to configure a single repository URL to redirect it to plain HTTP on a private network?

There is no declarative way to do this; unfortunately you would have to construct your own Wagon implementation which only allowed whitelisted URLs thru.

**Comment by binarykitchen** [comment]
@technomancy yep, will try that now, constructing my own Wagon implementation. but don't know where to start. do you have any good examples for that?

**Comment by technomancy** [comment]
I haven't written a wagon, so I'm not a good authority on that.

But on reflection, I don't believe that a whitelisted-HTTP wagon would do any good; if someone can intercept a connection to a single repository or a connection to every repository, it makes no difference.

**Comment by binarykitchen** [comment]
@technomancy we're on a private network, so it's fine. 

we just do not want to allow third-party insecure repos to slip through. with your workaround it's a global change which will let everything go through.

just want to filter this for our private repo only ...

**Comment by technomancy** [comment]
Ah, like a wagon which could refuse to function unless it was able to confirm you're on the same network as the repo itself? I guess that would work, but it seems like more work than just adding TLS to the repo.

**Comment by binarykitchen** [comment]
Something like that but not sure how to code/subclass wagon for this.

**Comment by theBlackDragon** [comment]
I just wanted to point out this also affects the :mirror declaration in profiles, I'm not sure if this was intended (the example project.clj still uses http for mirror declarations) but forcing people to set up SSL for an internal mirror seems a bit drastic.

If there's no way around this then could someone kindly tell me what I need to do to disable this warning on a per-profile basis?
