### ISSUE TITLE
New version of Aether/pomegranate breaks s3-wagon-private

### ISSUE THREAD

**Issue by technomancy** [technomancy/leiningen#2278]

**Comment by technomancy** [comment]
The weird thing about this is that the tests for pomegranate show that registering a custom wagon works fine under some circumstances: https://github.com/cemerick/pomegranate/blob/master/src/test/clojure/cemerick/pomegranate/aether_test.clj#L591

For some reason the S3 wagon is different. We register it here: https://github.com/cemerick/pomegranate/blob/master/src/main/clojure/cemerick/pomegranate/aether.clj#L114

The old implementation which works with the S3 wagon is here: https://github.com/cemerick/pomegranate/blob/pomegranate-0.3.1/src/main/clojure/cemerick/pomegranate/aether.clj#L109

**Comment by ghadishayban** [comment]
I couldn't reproduce this on a bare project that used lein 2.7.2-SNAPSHOT compiled this morning.  I was able to successfully push and pull a dep from a private s3 repo

**Comment by technomancy** [comment]
@ghadishayban could you let me know what version of s3-wagon-private you used? Seems I get different results with 1.2.0 and 1.3.0 (though both failures). The wagon is registered correctly, but the auth info (passphrase) isn't propagated correctly, leading to "Secret key cannot be null" errors.

**Comment by technomancy** [comment]
I believe what's happening is that the authentication settings are set (I've confirmed that Pomegranate calls `setAuthentication` the same way it used to) but that the new version of Aether ignores this authentication data. Perhaps it provides another way to set the credentials in a way that they would actually be used, but since there is no documentation published it's difficult to tell; I believe this would require a deep-dive into the source by someone who is very familiar with reading Java code.

**Comment by glts** [comment]
With the help of @technomancy I managed to find the cause of this,
thankfully not buried very deeply.

Commit cemerick/pomegranate@b71ad6f0e3e88003c1ee28458af1f94bd319f6a6
contains the relevant diff:

```diff
 (defn- set-authentication
   "Calls the setAuthentication method on obj"
   [obj {:keys [username password passphrase private-key-file] :as settings}]
   (if (or username password private-key-file passphrase)
-    (.setAuthentication obj (Authentication. username password private-key-file passphrase))
+    (doto obj
+      (.setAuthentication
+       (.build
+        (doto (AuthenticationBuilder.)
+          (.addUsername username)
+          (.addPassword password)
+          (.addPrivateKey private-key-file passphrase)))))
     obj))
```

The old `Authentication` constructor API allowed any argument to be
`null`. The new `AuthenticationBuilder.addPrivateKey` method also allows
args to be `null`, but silently ignores the passphrase if the private
key file path is `null`:

```java
public AuthenticationBuilder addPrivateKey( String pathname, String passphrase )
{
    if ( pathname != null )
    {
        addString( AuthenticationContext.PRIVATE_KEY_PATH, pathname );
        addSecret( AuthenticationContext.PRIVATE_KEY_PASSPHRASE, passphrase );
    }
    return this;
}
```

The workaround is specifying any path (any non-null value?) for
`:private-key-file`.

```clojure
:repositories {"releases"
               {:url "s3p://my-private-leiningen-repo/"
                :username "username"
                :private-key-file "/tmp/.empty"
                :passphrase "passphrase"}}
```

I haven’t thought about the proper fix or if we're using the private key
API correctly …

**Comment by technomancy** [comment]
Wow, nice find! I missed that this was part of the new API.

I would say that this is definitely a bug in the wagon then. We could add a workaround when we detect that the problematic wagon is being used, or just document the workaround of using a dummy file, but this is super helpful; thanks so much for taking a look.
