### ISSUE TITLE
Add support for specifying root destination path for jar :filespecs

### ISSUE THREAD

**Issue by cemerick** [technomancy/leiningen#2280]
I often want to include some resources in jars or uberjars, but have them relocated within the jar to a different path, e.g. include `some/directory` in the jar, but under the path `other/directory`. I've often worked around this with symlinks and/or auxillary build steps outside leiningen, but a current project makes doing this more cumbersome than I'd like.

Implementing this as a local `project.clj` hack is pretty straightforward:

```clojure
(require 'leiningen.jar)
(in-ns 'leiningen.jar)
; dupe of :path dispatch, plus the stuff supporting a destination root
(defmethod copy-to-jar :rooted-path [project jar-os acc spec]
  (let [root-file (io/file (:path spec))
        root-dir-path (unix-path (dir-string root-file))
        destination-root (some-> (:root spec) (str "/"))
        paths (for [child (file-seq root-file)
                    :let [path (relativize-path
                                 (full-path child (unix-path (str child)))
                                 root-dir-path)]]
                (when-not (or (skip-file? child path root-file
                                (:jar-exclusions project))
                            (added-file? child path acc))
                  (put-jar-entry! jar-os child (str destination-root path))
                  path))]
    (into acc paths)))
(in-ns 'leiningen.core.project)
```

With this, I can include:

```clojure
:filespecs [{:type :rooted-path :path "source/directory" :root "destination/directory"}]
```

Is this sort of enhancement desirable? A PR would add this option to `:path` and `:paths` filespec support; it doesn't make sense for the others.

**Comment by technomancy** [comment]
I like it! Much nicer than using symlinks.

**Comment by technomancy** [comment]
Going to close this out since it seems unlikely anything will come from it, but if someone wants to make it happen happy to reopen.
