### ISSUE TITLE
Eliminate common cause of "skipped duplicate file" warnings when [uber]jarring

### ISSUE THREAD

**Issue by cemerick** [technomancy/leiningen#2281]
In my experience, a common/easy trap to fall into is to have duplicate `:resource-paths` entries, either duplicating `"resources"`, or other entries in multiple active profiles. Because `:resource-paths` is just a sequence (vector?), the [uber]jar task processes any duplicate entries blindly, leading to some potentially very noisy build output.

It seems like making `:resource-paths` a set upon profile merging would solve this, or barring that, changing `leiningen.jar` to work over a `distinct` sequence of resource paths instead of the sequence from the project map that often will contain duplicate entries.

**Comment by technomancy** [comment]
Distinct would be better than a set, because this is one place where order can be pretty important.

**Comment by cemerick** [comment]
Wait, really? Isn't the order of `:resource-paths` entirely dependent upon the order of profile merging, and thus effectively undefined?

**Comment by technomancy** [comment]
Hm; why do you think profile merge order is undefined? It can also be chosen deliberately when necessary.

**Comment by cemerick** [comment]
I guess I mean that since profiles are provided by the user via `with-profile`, and so there's (at best) a tenuous connection between user intent at that level and the ordering of entries in :resources-path or any of the other components of e.g. classpaths?

Or, are people really relying upon entries from each mentioned profile (and their dependents) flowing into e.g. `:resource-paths` and classpaths matching the profile ordering?

**Comment by technomancy** [comment]
> Or, are people really relying upon entries from each mentioned profile
> (and their dependents) flowing into e.g. :resource-paths and
> classpaths matching the profile ordering?

The intent is that there's a clear and consistent pattern around priority order for profiles, yeah.

**Comment by cemerick** [comment]
In that case, I either really don't understand what's supposed to happen, or there's a bug.

Given a project.clj (pushed the sample project up [here](https://github.com/cemerick/lein-resources-ordering)):

```clojure
(defproject lein-resources-ordering "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]]
  :profiles {:a {:resource-paths ["a"]}
             :b {:resource-paths ["b"]}})
```

```
$ lein with-profiles a,b pprint :resource-paths
Picked up _JAVA_OPTIONS: -Duser.home=/mnt/g/
("/mnt/g/dev/vendor/lein-resources-ordering/b"
 "/mnt/g/dev/vendor/lein-resources-ordering/a"
 "/mnt/g/dev/vendor/lein-resources-ordering/resources")
```

Given that ordering, the result isn't surprising:

```
$ lein do clean, with-profiles a,b jar
Picked up _JAVA_OPTIONS: -Duser.home=/mnt/g/
Warning: skipped duplicate file: foo.txt
Created /mnt/g/dev/vendor/lein-resources-ordering/target/lein-resources-ordering-0.1.0-SNAPSHOT.jar
$ jar xf target/lein-resources-ordering-0.1.0-SNAPSHOT.jar foo.txt; cat foo.txt
Picked up _JAVA_OPTIONS: -Duser.home=/mnt/g/
b
```

I know I'm basically OT at this point, but it seems like an important detail, and I think one I've tripped on before without realizing it.

**Comment by technomancy** [comment]
My recollection is that with-profiles acts like clojure.core/merge in that it's supposed to be "last map wins".

This could probably be clearer in the documentation, but it should at least be consistent.

**Comment by cemerick** [comment]
Okay; It's weird when applied to nested things that are fundamentally sequential on both ends, but I can see how and why that would be the choice that was made, thanks. 

I'll toss up a PR soon.
