### ISSUE TITLE
Recursive checkouts are slow and inefficient

### ISSUE THREAD

**Issue by sfnelson** [technomancy/leiningen#2284]
The function `checkout-deps-paths` is recursively called because it's included in `:checkout-deps-shares` for the default project profiles. This allows leiningen to recursively build a checkouts classpath by traversing all projects reachable from checkouts, and their checkouts (etc).

In practice, it's pretty reasonably to assume that checkouts will be a directed-acyclic-graph, rather than a tree, so this form of recursion results in the DAG being fully expanded into a tree, creating a lot of duplication. In our project we have 11 projects with a total of 37 checkouts. Calling `lein cp` on the root project takes 13 seconds and creates over 1000 classpath entries for 75 unique directories. This is not only unacceptably slow for starting leiningen, but results in an unwieldy classpath that causes poor class resolution performance for Java.

I think `checkout-deps-paths` needs to be graph-aware – it should use a recursion mechanism that eliminates projects that it has already seen, and it should use `getCanonicalFile` to remove symlinks from classpath entries.

**Comment by technomancy** [comment]
Interesting. I've never seen a project that used more than 2 or 3 checkouts.

I think your idea of de-duplicating based on .getCanonicalFile is sound.
Would be happy to merge a PR that did this.
