### ISSUE TITLE
Update URL of Google’s Maven central mirror

### ISSUE THREAD

**Issue by glts** [technomancy/leiningen#2299]
Finally got around to checking the continuing build failures here and in
Pomegranate. These seem to be caused by a relocation of the
HTTPS-enabled Google mirror of Maven central.

The best info I have been able to find is here:
https://storage-download.googleapis.com/maven-central/index.html

So a simple search-and-replace of
`https://maven-central.storage.googleapis.com` with one of the three new
options will fix the build.

**Comment by technomancy** [comment]
Good catch; thanks!
