### ISSUE TITLE
doctoc comments are showing when running "lein help faq", etc

### ISSUE THREAD

**Issue by technomancy** [technomancy/leiningen#2302]

**Comment by technomancy** [comment]
```
~ $ lein help faq
<!-- START doctoc generated TOC please keep comment here to allow auto update -->
<!-- DON'T EDIT THIS SECTION, INSTEAD RE-RUN doctoc TO UPDATE -->
**Table of Contents**  *generated with [DocToc](https://github.com/thlorenz/doctoc)*

- [FAQ](#faq)

<!-- END doctoc generated TOC please keep comment here to allow auto update -->

# FAQ

**Q:** How do you pronounce Leiningen?  
**A:** It's LINE-ing-en. ['laɪnɪŋən]
...
```

^ This is pretty silly!

Before printing any static help text in `src/leiningen/help.clj`, we should check to see if the output includes `<!-- END doctoc generated TOC please keep comment here to allow auto update -->` and remove everything up to and including that before printing it.

**Comment by irinarenteria** [comment]
@technomancy, I'd be happy to pick this up. I'll likely have questions for you or @ehashman, since I'm still quite fresh at Clojure.

**Comment by technomancy** [comment]
@irinarenteria Great! Let me know if you have any questions; I'm also available in the `#leiningen` or `#clojure` channel on freenode. Thanks.

**Comment by technomancy** [comment]
I'm hoping to cut a release candidate soon; if you think you could do this by the end of the week that would be great, but if not that's fine; I can fix it myself. Thanks!

**Comment by ehashman** [comment]
I'm going to try to help @irinarenteria with this today!

**Comment by irinarenteria** [comment]
Sorry, @technomancy, barely got around to this today (and for some reason I didn't get a notification for your comment). Will have something up by the end of this week! Spending some time with @ehashman today making sure my setup is ok.
