### ISSUE TITLE
Set JVM flags to respect cgroups limits

### ISSUE THREAD

**Issue by technomancy** [technomancy/leiningen#2304]
Ensure these don't cause problems with earlier builds of the JVM; if not we should definitely set the memory flags described here: https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits

**Comment by technomancy** [comment]
Unfortunately but unsurprisingly this will cause launch failures on older JVMs which don't support the flag: https://gist.github.com/amalloy/5e9f30f0455b1e0e44fa678dcec8fbac

If we check within Leiningen's own JVM to see that it's running a new enough revision, we can enable it. This will break in the case that Leiningen is being run with a newer JVM and someone sets `:java-cmd` to an older rev; but that is very unlikely.

**Comment by winks** [comment]
The linked gist is "1.7.0_51" while this seems to work:

```
Leiningen 2.7.2-SNAPSHOT on Java 1.7.0_131 OpenJDK 64-Bit Server VM
```

**Comment by technomancy** [comment]
Cool; I've bumped it to use the flags for updates 131 and newer on 1.7 and 1.8, leave it out for 1.6, and always do it for all other revs. Should work fine unless someone tries to run under 1.5. =)

**Comment by danielcompton** [comment]
For those interested, here is some [discussion](https://groups.google.com/d/msg/mechanical-sympathy/Qodan28zYUo/8KKgbGGkAAAJ) on this flag from the mechanical sympathy mailing list.

**Comment by technomancy** [comment]
> My view is that -XX:+UseCGroupMemoryLimitForHeap is *currently* a "somewhat meaningless" flag, and will remain so until it is on by default (at which point it will have a true beneficial effect, so lets hope it gets out the experimental phase soon).

I agree with this in the context of direct invocations of the `java` command, but this ignores the fact that tooling can introduce this setting and effectively make it default before the OpenJDK devs get around to it, which is basically what we're doing with this patch.

**Comment by danielcompton** [comment]
> that tooling can introduce this setting and effectively make it default

Absolutely, I agree.
