### ISSUE TITLE
Revert self-install deprecation

### ISSUE THREAD

**Issue by akahl-owl** [technomancy/leiningen#2309]
`self-install` should be un-deprecated because there is a valid use case for it: Installing Leiningen into Docker images. Without this, every new Docker build would have to fetch the same jar file again. During the build of the Docker image itself, there is no meaningful, other command that can be run which doesn't have other side effects.

Should `self-install` be removed, a workaround would have to be established which essentially emulates the removed feature.

**Comment by hyPiRion** [comment]
I think `lein version` should do what you desire without any considerable side effects. The only "issue" with it is that you now need to install a JDK before you've downloaded Leiningen. However, I'd be very surprised if you install a JDK after Leiningen.

**Comment by technomancy** [comment]
I agree; using `lein version` for this makes sense.
