### ISSUE TITLE
Auto-resolved current namespace map syntax not working

### ISSUE THREAD

**Issue by heptahedron** [technomancy/leiningen#2310]
Opening a repl with `lein repl` and evaluating `#::{:foo :bar}` results in the following error:

```
RuntimeException EOF while reading, starting at line 1  clojure.lang.Util.runtimeException (Util.java:221)

RuntimeException Unmatched delimiter: }  clojure.lang.Util.runtimeException (Util.java:221)
```

@technomancy has suggested this is a bug in the version of repl-y currently being used.

Version:

REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.9.0-alpha19
Java HotSpot(TM) 64-Bit Server VM 1.8.0_144-b01

**Comment by technomancy** [comment]
Since this can't be fixed in Leiningen I'm not going to consider it a blocker for 2.8.0.

**Comment by technomancy** [comment]
Currently blocked on https://github.com/cgrand/sjacket/issues/27

**Comment by technomancy** [comment]
Looks like I was wrong; this didn't actually get fixed in reply.
