### ISSUE TITLE
Problem with locally deployed resources

### ISSUE THREAD

**Issue by ghaskins** [technomancy/leiningen#2311]
# Summary 

I am seeing an issue where I am trying to cache resources into a :local-repo for the purposes of supporting an effectively offline build (e.g. inside a docker-build environment).

# Background
Use case is: library project (mylibrary) and app project (myapp).  myapp depends on mylibrary.  Gist of flow is standard dep("lein install") -> .m2 -> consumer("lein deps"), except the docker environment will not have access to the .m2 repo.  To mitigate this, trying to use a combination of "lein deploy" to a "file:" repo and :local-repo to pull mylibrary into the local-repo, and thus docker, without using .m2.

# Expectation
This should yield an effectively accessible cache of artifacts that may be used in an offline-type environment, such as a docker-build

# Result
myapp fails to recognize the cached mylibrary within :local-deps

# Notes
I do observe that the "lein deploy" results in sane looking artifacts/metadata pushed, including .sha1 checksums.  I also observe that the online "lein deps" does cache mylibrary in :local-repo.  However, I also note that the .sha1/.md5 checksums are missing.  I also note that the offline variant of the build fails to find any sources of mylibrary, despite it being present in the cache.

# Test Case
[lein-issue.zip](https://github.com/technomancy/leiningen/files/1288826/lein-issue.zip)

Unzip and run ./build.sh.  This will yield:

```
++ lein with-profile +offline jar
The repository system is offline but the artifact mylibrary:mylibrary:jar:0.1.0 is not available in the local repository.
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Error encountered performing task 'jar' with profile(s): 'base,system,user,provided,dev,offline'
Could not resolve dependencies
```

**Comment by ghaskins** [comment]
Should also add:

# Version info: 
```
$ lein version
Leiningen 2.7.1 on Java 1.8.0_131 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by glts** [comment]
I’ve looked at this with Leiningen 2.9.1 and I think it’s simply a configuration mistake.

Maven records which repository a dependency was originally downloaded from.

1. `lein with-profile +online deps` ‘downloads’ mylibrary from myrepo.
2. `lein with-profile +offline jar` looks for the mylibrary artefact, but because no :repositories are specified for this profile it tries to look for that artefact in the default repositories, Maven Central and Clojars. The artefact is not available in offline mode, and so it fails.

You need to extract myrepo out of the profile as a top-level setting. Then it works.

    :profiles {:online {:repositories {"myrepo" "file:///tmp/myrepo"}}
               :offline {:offline? true}}

becomes

    :repositories {"myrepo" "file:///tmp/myrepo"}

**Comment by technomancy** [comment]
I think the root issue here is that `:offline?` means "you can't check repositories" while you want it to mean "you can't check non-`file://` repositories. Unfortunately this behavior comes from the underlying Maven libraries and isn't in scope to be fixed within Leiningen. But there are workarounds, as noted.
