### ISSUE TITLE
conda-forge package for leiningen

### ISSUE THREAD

**Issue by abhi18av** [technomancy/leiningen#2317]
Hi guys,

I've been working on the [`conda-forge`](https://conda-forge.org/) package for `leiningen` in this [PR](https://github.com/conda-forge/staged-recipes/pull/4036) 

I'm running into issues, could you help me get `leiningen` into the `conda` management space ?

**Comment by danielcompton** [comment]
Can you explain a bit more on the PR about the issues you’re running into?

**Comment by abhi18av** [comment]
Actually, I'd like to get `clojure` into the community-driven effort for  `Data Science`

`Clojure` is often used in `Data Science` and so is `Python` , `Julia`, `Java` and `R`. So, instead of treating each language as an island there's a language-agnostic and platform-agnostic package manager called [`conda`](https://conda.io/docs/) which is an initiative from [`Anaconda`](https://www.anaconda.com/what-is-anaconda/).

Think of `brew` but completely cross platform and it creates isolated environments for installed software which can't interfere with each other.

The main advantage is that it's result of push towards reproducible research and analysis. I think that `clojure` community would greatly benefit from `conda`. `conda-forge`, like `bio-conda` is an entirely community driven effort towards this goal.

Trouble is, I need help regarding setting up the package once.

Here's the current error 

```python
TypeError: 'NoneType' object is not callable

```

**Comment by technomancy** [comment]
The error you're showing is from Python, not from Clojure. If you have Leiningen-specific questions we may be able to help.

**Comment by technomancy** [comment]
Going to close this as it's not a Leiningen problem, but feel free to ping me on any relevant PRs if you have lein-specific questions.
