### ISSUE TITLE
lein 2.8.0 produces warnings for illegal reflective access jdk 9.0.1 Win10

### ISSUE THREAD

**Issue by gregoryo** [technomancy/leiningen#2331]
seeing reflective access warnings with leiningen on Windows 10 
jdk 9.0.1
leiningen-2.8.0-standalone.jar
lein commands all seem to work, they simply display the warning
```
.\bin\lein.bat  -v
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by dynapath.defaults$eval380$fn__381 to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of dynapath.defaults$eval380$fn__381
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Leiningen 2.8.0 on Java 9.0.1 Java HotSpot(TM) 64-Bit Server VM
```
also mentions
-  on #2325 of same behavior on macOS
- slack channel last month https://clojurians-log.clojureverse.org/leiningen/2017-09-22.html

**Comment by technomancy** [comment]
Looks like this problem is coming from Pomegranate.

**Comment by technomancy** [comment]
Dang I had no idea there was a Leiningen channel on slack. I wonder if someone could update the topic to suggest trying IRC since that's where they can get help from the maintainers.

**Comment by danielcompton** [comment]
>  I wonder if someone could update the topic to suggest trying IRC since that's where they can get help from the maintainers.

I've just done this.

<img width="913" alt="screenshot of google chrome 22-10-17 1-00-41 pm" src="https://user-images.githubusercontent.com/811954/31856846-04c313ba-b729-11e7-8b36-632c2d47a2f1.png">

**Comment by technomancy** [comment]
Thanks!

**Comment by technomancy** [comment]
My reading of this issue is that we can no longer rely on the classloader we get from the JVM; we'll need to install our own that we know can have things added to it without breaking in a future JDK release.

**Comment by gregoryo** [comment]
thank you.

**Comment by technomancy** [comment]
Sorry; I put "might fix" in my commit message and GitHub interpreted it as "does fix". I haven't confirmed the issue is gone.

**Comment by glts** [comment]
The warnings are still there for me on current master (cb8abd7). Bumping
dynapath to 1.0.0 fixes this completely though:

```diff
--- a/leiningen-core/project.clj
+++ b/leiningen-core/project.clj
@@ -11,7 +11,7 @@
                  [com.cemerick/pomegranate "0.4.0"
                   :exclusions [org.tcrawley/dynapath
                                org.codehaus.plexus/plexus-utils]]
-                 [org.tcrawley/dynapath "0.2.5"]
+                 [org.tcrawley/dynapath "1.0.0"]
                  [org.apache.maven.wagon/wagon-http "2.12"
                   :exclusions [org.apache.maven.wagon/wagon-provider-api]]
                  [com.hypirion/io "0.3.1"]

```

Thank you!
