### ISSUE TITLE
Lock exact leiningen version

### ISSUE THREAD

**Issue by binarykitchen** [technomancy/leiningen#2339]
Like you can do for yarn or npm in a package.json - this to ensure every developer of the same project will have the same leiningen version.

Not `min-lein-version` but something like `lein-version` ... or a combination of `min-lein-version` and `max-lein-version`, grins.

**Comment by technomancy** [comment]
I would recommend copying the `bin/lein` script into your repository's repo and updating the CI scripts, readme, etc to use that.

There is a `:min-lein-version` key you can set in `project.clj` but no `:exact-lein-version`. I would be happy to take a patch for that.

**Comment by avfonarev** [comment]
I'm happy to implement this one. However, there seems to be a design decision involved. Namely, do you want to have equality of the version numbers or allow something like `:required-lein-version "2.8.*"`? Also, do I assume that the actual leiningen version is always semantic?

**Comment by technomancy** [comment]
Thanks. I would honestly prefer a feature which only supported exact version matches and didn't do any fuzzy matches at all.

Semantic versioning is a goal we have, but our tools shouldn't encode an assumption that we achieve it consistently.
