### ISSUE TITLE
Don't store downstream bin/lein-sdkman files in our repo

### ISSUE THREAD

**Issue by technomancy** [technomancy/leiningen#2346]
We have a file for downstream packagers already (`bin/lein-pkg`); it should be the responsibility of downstream packagers to decide how to patch that appropriately instead of storing it in the Leiningen repo.

**Comment by marc0der** [comment]
Sdkman does not patch any files, it only takes the existing binary zip, explodes it and adds the bin folder to your path. Nothing special should be required for lein to work on sdkman.

**Comment by hypirion** [comment]
The binary script for skdman works a little differently, as the location of the Leiningen jar itself is located in a different folder (and you end up with an inconsistent state if you can upgrade Leiningen by doing `lein upgrade`). But it's not very different, no.

**Comment by technomancy** [comment]
> Sdkman does not patch any files

That's what I mean; it doesn't patch bin/lein, but it should. The diff
between the main bin/lein and the bin/lein that sdkman uses should be
stored in a patch that is external to this repository, like it is with
Debian, nix, homebrew, etc.

**Comment by marc0der** [comment]
Cool thanks, I get it.
