### ISSUE TITLE
Cannot download leiningen-2.8.2-SNAPSHOT-standalone.zip

### ISSUE THREAD

**Issue by iongion** [technomancy/leiningen#2347]
I have installed lein from master and I am getting this when trying to use it:
```
$ lein
Downloading Leiningen to /home/istoica/.lein/self-installs/leiningen-2.8.2-SNAPSHOT-standalone.jar now...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Failed to download https://github.com/technomancy/leiningen/releases/download/2.8.2-SNAPSHOT/leiningen-2.8.2-SNAPSHOT-standalone.zip (exit code 22)
It's possible your HTTP client's certificate store does not have the
correct certificate authority needed. This is often caused by an
out-of-date version of libssl. It's also possible that you're behind a
firewall and haven't set HTTP_PROXY and HTTPS_PROXY.
```

**Comment by hypirion** [comment]
If you want to use Leiningen from master, I would recommend to follow the steps specified in the [Bootstrapping](https://github.com/technomancy/leiningen/blob/master/CONTRIBUTING.md#bootstrapping) section of the Contribution documentation. If you want to use a uberjar from master, see [uberjar from master](https://github.com/technomancy/leiningen/blob/master/CONTRIBUTING.md#uberjar-from-master).

If the goal is to just run Leiningen, not to work on it, I'd recommend to install lein 2.8.1. With the script you have, you can do that easily by doing `lein upgrade 2.8.1`.
