### ISSUE TITLE
It would be nice if the default template had a value for `:repl-options {:init-ns }`

### ISSUE THREAD

**Issue by slipset** [technomancy/leiningen#2350]
I generally do `lein new foo` whenever I start a new project. A subsequent `lein repl` puts me in 
the default ns instead of `foo.core`

**Comment by technomancy** [comment]
Perhaps you'd be more happy with `lein new app foo` instead? The default
template is intended for libraries, which don't have an entry point.

-Phil

**Comment by slipset** [comment]
Yeah, I’m aware of ‘new app’, but I tend to forget. And, for some reason, clj.user is almost never where I want to be when I develop my stuff. 

But feel free to close :)

**Comment by technomancy** [comment]
Yeah, `:main` is definitely wrong for a template designed for libraries, but `:repl-options {:init-ns foo.bar}` might be a better fit for what you're looking for anyway, since it doesn't imply "entry point" but just "where the repl should start".
