### ISSUE TITLE
2.8.x regression with nested lein invocations (INPUT_CHECKSUM leak)

### ISSUE THREAD

**Issue by darwin** [technomancy/leiningen#2351]
I noticed that my pretty complex lein tasks started silently failing when upgrading lein from 2.7.1 to 2.8.0 (2.8.1 is affected as well).

My project is using [lein-shell](https://github.com/hypirion/lein-shell) plugin to invoke arbitrary shell scripts. And those shell script may decide to invoke lein tasks and so on. This could lead to nested lein calls. Imagine following nesting:
```
lein task1
  some-script.sh
    lein task2
```

The problem is that newly `lein task2` is trying to exec a trampoline file (something like `/tmp/lein-trampoline-v2q1LpQQMhnQI`) which exists but is empty. This problem was present in 2.7.1 but after some poking (and without further understanding) I was able to work-around it with https://github.com/binaryage/dirac/commit/1bc88edb043c2d248cc3d8314ae1330f8b5c600b. Newly in 2.8.0 this workaround does not cut it anymore - probably due some changes in trampoline logic.

I went ahead to determine real cause of the trouble and I discovered that the problem is that the `bin/lein` shell script is not "hygienic". In my case it exports `INPUT_CHECKSUM` which confuses nested lein tasks. 

Specifically, imagine `lein task1` to hit this line https://github.com/technomancy/leiningen/blob/b8cf7a0d497911302885aafbfb8baaddfd81a549/bin/lein#L327 which exports `INPUT_CHECKSUM` and then later in a nested (inherited) shell environment `lein task2` is executed with deliberately empty `LEIN_FAST_TRAMPOLINE`. In this case empty trampoline file is created here: https://github.com/technomancy/leiningen/blob/b8cf7a0d497911302885aafbfb8baaddfd81a549/bin/lein#L331-L336 and `INPUT_CHECKSUM` is inherited from `lein task1`, the shell script then takes this route: https://github.com/technomancy/leiningen/blob/b8cf7a0d497911302885aafbfb8baaddfd81a549/bin/lein#L348 which leads to `exec` of an empty bash script, which is a silent operation with success.

I'm able to work around the issue by `unset INPUT_CHECKSUM` before this line:
https://github.com/technomancy/leiningen/blob/b8cf7a0d497911302885aafbfb8baaddfd81a549/bin/lein#L331

But I think someone with "whole picture" should review the shell script and make it hygienic. I would recommend not exporting the env vars but instead passing them directly into java command via `-Dxxx` or by some other direct mean which would not leak into inherited shell environment(s). If you really need to export the env vars, I would recommend to give them LEININGEN_ prefix, to prevent possible unexpected clashes with some other env vars and properly handle vars like `INPUT_CHECKSUM` which should not get inherited.

Thanks for considering this.

**Comment by technomancy** [comment]
That should do the trick; thanks.

**Comment by darwin** [comment]
Thanks, LGTM.
