### ISSUE TITLE
Uberjar fails with duplicate entry error

### ISSUE THREAD

**Issue by chrisdavies** [technomancy/leiningen#2355]
I'm running Leiningen 2.7.1 and Java 1.8.0_144 in a docker container.

When I try to build under a profile, it bombs: `lein with-profile ruzsys uberjar`

```
Uberjar aborting because jar failed: duplicate entry: clojure/java/jdbc$query$fn__2283.class
Error encountered performing task 'uberjar' with profile(s): 'ruzsys'
Uberjar aborting because jar failed: duplicate entry: clojure/java/jdbc$query$fn__2283.class
```

Any idea what might cause such an error, and what workarounds there might be?

It seems to have something to do with the migratus library. The odd thing is, this same build appears to work outside of my docker container (e.g. on my dev machine). But I'm running a different version of Java on my dev machine (1.8.0_51).

```clj
; project.clj
(defproject ringapi "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.9.0-beta4"]
                 [org.clojure/java.jdbc "0.7.3"]
                 [org.postgresql/postgresql "42.1.4.jre7"]
                 [com.layerware/hugsql "0.4.8"]
                 [ring "1.6.3"]
                 [cheshire "5.8.0"]
                 [com.rpl/specter "1.0.4"]
                 [metosin/reitit "0.1.0-SNAPSHOT"]
                 [migratus "1.0.0"]
                 [environ "1.1.0"]
                 [hikari-cp "1.8.1"]
                 [org.clojure/core.async "0.3.443"]
                 [com.taoensso/timbre "4.10.0"]
                 [timbre-ns-pattern-level "0.1.2"]
                 [com.fzakaria/slf4j-timbre "0.3.7"]]
  :plugins [[lein-ring "0.12.1"]]
  :ring {:handler ringapi.core/app}
  :aliases {"db-migrate"  ["run" "-m" "ruzsys.migrations/migrate"]
            "db-rollback" ["run" "-m" "ruzsys.migrations/rollback"]
            "db-new-migration" ["run" "-m" "ruzsys.migrations/new-migration"]}
  :profiles {:ruzsys {:main ruzsys.migrations
                      :aot [ruzsys.migrations]
                      :uberjar-name "ruzsys.jar"}})
```

**Comment by chrisdavies** [comment]
Following up here...

`lein ring uberjar` works. So, I dug into that project, and modified my `ruzsys.migrations` code. I put the main entry point for that into `ruzsys/core.clj` which looks like this:

```clj
(ns ruzsys.core
  (:gen-class))

; main takes a single, url-like argument
; which tells it which function to run
(defn -main [& args]
  (let [cmd (first args)]
    (require '[ruzsys.migrations])
    ((resolve 'ruzsys.migrations/run) cmd)))
```

So, basically, if I don't do any aot other than main, and main doesn't explicitly refer to outside files, thinks work. But when I do any aot, I get an error about duplicates.

**Comment by chrisdavies** [comment]
Ah. Interesting. Thanks!

That makes sense. For now, I'm not AOTing because this project is really just an investigation into whether or not to use Clojure and what cloud provider to use for some microservices we're spinning up.

**Comment by technomancy** [comment]
Cool. I would still recommend reporting a bug with whatever library it is that contains the class files if you can.

**Comment by chrisdavies** [comment]
Actually, following up on this, why does AOT work on Mac, but not on Linux (or more precisely, not on Docker)? This would suggest the issue isn't with the dependencies but with Lein (or maybe with the Clojure compiler).

**Comment by chrisdavies** [comment]
Also, I can add you to a sample repo, that reproduces the issue, if you want.

**Comment by technomancy** [comment]
> Actually, following up on this, why does AOT work on Mac, but not on Linux (or more precisely, not on Docker)? This would suggest the issue isn't with the dependencies but with Lein (or maybe with the Clojure compiler).

This typically means that you need a case-sensitive filesystem to trigger the problem.

I would say it's a bug in whichever of your dependencies is including .class files in their jar.

**Comment by chrisdavies** [comment]
Makes total sense. OK. Thanks. I'll dig into it and log a bug on the offending dep(s).
