### ISSUE TITLE
Deploying to clojars without signing

### ISSUE THREAD

**Issue by mattiasw2** [technomancy/leiningen#2359]
Using windows and would like to deploy to clojars. Do not want to mess with GPG right now. Added this to project.clj. Just upgraded lein.

```
  :deploy-repositories [[:clojars {:url "[https://clojars.org/mattiasw/](https://clojars.org/mattiasw/)" 
                                      :sign-releases false}]]
```

Tried different versions of above, for example replacing :clojars by "clojars".

But, lein anyway try to start gpg

**Comment by danielcompton** [comment]
Here's a working example: https://github.com/Day8/re-frame/blob/c451e00cff9e52ed52d9ba21554d3baab61776b6/project.clj#L31-L32. Your Clojars URL won't include your username.

**Comment by mattiasw2** [comment]
Thank you! Solved the gpg problem, but still not working. Instead I get

     Could not transfer artifact hashdb:hashdb:jar:0.1.4 from/to releases (https://clojars.org/mattiasw): Access denied to: https://clojars.org/mattiasw/hashdb/hashdb/0.1.4/hashdb-0.1.4.jar, ReasonPhrase: Forbidden.

I am going to revisit this later.

**Comment by danielcompton** [comment]
@mattiasw2 the repository URL should be `https://clojars.org`. You don't need to include your username.

**Comment by mattiasw2** [comment]
Changed to 
```
  :deploy-repositories [["releases"  {:sign-releases false :url "https://clojars.org"}]
                        ["snapshots" {:sign-releases false :url "https://clojars.org"}]]
```
This is the project I have been experimenting with

https://github.com/mattiasw2/hashdb/blob/master/project.clj
