### ISSUE TITLE
`lein upgrade` with bash script throws accidental warning about $CLASSPATH

### ISSUE THREAD

**Issue by ehashman** [technomancy/leiningen#2361]
@cswl reports via IRC that when a user runs `lein upgrade`, they encounter a warning:

```
WARNING: You have $CLASSPATH set, probably by accident.
It is strongly recommended to unset this before proceeding.
```

This appears to be because we `exec` the new script once downloaded:

https://github.com/technomancy/leiningen/blob/4169f26ca83e0ed70c70a415e45d673acade3c4d/bin/lein#L281-L288

Since we have already exported the classpath within the currently running lein script, we still use the same environment with classpath to `exec` the new script, hence the warning. Perhaps we could unset the CLASSPATH variable before `exec`ing the newly downloaded script to avoid this.

**Comment by winks** [comment]
Seems to be safe on Windows.
```
C:\Users\Florian
λ lein version

C:\Users\Florian\.lein\self-installs\leiningen-2.7.1-standalone.jar can not be found.
You can try running "lein self-install"
or change LEIN_JAR environment variable
or edit lein.bat to set appropriate LEIN_JAR path.


C:\Users\Florian
λ lein self-install
Downloading Leiningen now...

C:\Users\Florian
λ lein version
Leiningen 2.7.1 on Java 1.8.0_144 Java HotSpot(TM) 64-Bit Server VM
C:\Users\Florian
λ lein upgrade
The script at C:\Users\Florian\lein.bat will be upgraded to the latest stable version.
Do you want to continue (Y/N)?y
Downloading latest Leiningen batch script...

Upgrading...
Downloading Leiningen now...

C:\Users\Florian
λ lein version
Leiningen 2.8.1 on Java 1.8.0_144 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by cswl** [comment]
@winks That's probably because Windows uses the `lein.bat` and not the shell script `lein`

**Comment by winks** [comment]
@cswl Yes, but there are at times intentions to make those 2 do similar things :) (Which is not so easy, given 2 different scripting languages).

I didn't really expect to find the same "bug" - but didn't hurt to doublecheck.

**Comment by cswl** [comment]
Ah, didn't thought of that.
Would be intresting to see why this doesn't happen on Windows :3

**Comment by winks** [comment]
Well for one the check if the classpath is set is missing.
So it probably makes sense to add it to `lein.bat` as well - sadly *I* don't know why the warning is there in the first place, I suppose @technomancy can shed some light on this.

**Comment by ehashman** [comment]
The reason that we're running into this issue with the shell script is that `exec` will execute lein sharing the same environment as the current running script. It appears from your example that `lein upgrade` on Windows (using the batch script) does not call `lein version` once upgraded, so this wouldn't be an issue:

https://github.com/technomancy/leiningen/blob/db531846bf663db54f9dab5301d2b4e007772910/bin/lein.bat#L303-L312

**Comment by winks** [comment]
@technomancy Sorry to be nagging - but did you see the last few comments?

Should we sync lein.bat to also call `lein version` at the end and investigate if this fix then needs porting or just let them behave differently?

**Comment by technomancy** [comment]
> sadly I don't know why the warning is there in the first place, I suppose @technomancy can shed some light on this.

This is because while we allow Leiningien's classpath to be affected by the `$CLASSPATH` env var for backwards compatibility reasons, 90% of the time when people do this it's an accident, because they set `$CLASSPATH` three years ago trying to get Hadoop working or something and forgot to remove it from their config when they gave up on Hadoop, and now we've got an ancient version of Apache HTTP Client or whatever.

I don't know if this is a common problem on Windows, but my first instinct would be to add the check.
