### ISSUE TITLE
Leiningen-core can no longer run on it's own

### ISSUE THREAD

**Issue by SevereOverfl0w** [technomancy/leiningen#2369]
This is due to https://github.com/technomancy/leiningen/blob/0720e0ea8a4a1f1e4005fad377118606b7318e32/leiningen-core/src/leiningen/core/classpath.clj#L407-L408

Which depends on a resource file, which is not present if you only depend on leiningen-core. The cider-nrepl project has this dependency in order to develop the leiningen plugin.

**Comment by SevereOverfl0w** [comment]
Sorry, I hit enter prematurely. I've updated the description with information.

**Comment by technomancy** [comment]
Thanks for catching this. In the mean time you can just put a file containing an empty map on the classpath in that location, since if you aren't running in Leiningen's own process then the bootclasspath probably doesn't apply.
