### ISSUE TITLE
lein repl :connect via http fails on version 2.8.1 but not on 2.7.1

### ISSUE THREAD

**Issue by jconti** [technomancy/leiningen#2370]
Running leiningen 2.8.1 I get the following stack trace.  I get a normal remote repl via drawbridge under 2.7.1.

System is Windows 10, running Java 1.8.0_152 Java HotSpot(TM) 64-Bit Server VM.

At least one other person has seen the same behavior from reading [this stackoverflow question](https://stackoverflow.com/questions/47144567/leiningen-nrepl-connect-to-remote-repl-with-drawbridge).

```
c:\code> lein repl :connect @.replurl
java.io.FileNotFoundException: Could not locate cemerick/drawbridge/client__init.class or cemerick/drawbridge/client.clj on classpath.
 at clojure.lang.RT.load (RT.java:456)
 clojure.lang.RT.load (RT.java:419)
 clojure.core$load$fn__5677.invoke (core.clj:5893)
 clojure.core$load.invokeStatic (core.clj:5892)
 clojure.core$load.doInvoke (core.clj:5876)
 ....
 clojure.lang.AFn.applyToHelper (AFn.java:171)
 clojure.lang.Var.applyTo (Var.java:700)
 clojure.main.main (main.java:37)
```

**Comment by technomancy** [comment]
This was dropped because distributing it with Leiningen made it impossible to upgrade the version due to bootclasspath issues. Unfortunately it looks like we forgot to document the removal; sorry about that.

You can add it back in with `[com.cemerick/drawbridge "0.0.7"]` in `:plugins`.
