### ISSUE TITLE
Leiningen doesn't use `:certificates` while fetching `:plugins` specified in ~/.lein/profiles.clj

### ISSUE THREAD

**Issue by sergeyminaev** [technomancy/leiningen#2371]
Hello,

It seems Leiningen doesn't use `:certificates` while fetching `:plugins` specified in ~/.lein/profiles.clj. 

Contents of my ~/.lein/profiles.clj:

    {:user {:mirrors {"central" {:name "central"
                                 :url "https://artifactory.local/artifactory/repo1/"}
                      "clojars" {:name "clojars"
                                 :url "https://artifactory.local/artifactory/clojars/"}}
            :certificates ["/home/user/.lein/artifactory.local.crt"]
            :plugins [[lein-ancient "0.6.14"]]
            }}

When I run any lein command (for example `lein version`) it fails:

    $ lein version
    Could not transfer artifact lein-ancient:lein-ancient:jar:0.6.14 from/to central (https://artifactory.local/artifactory/repo1/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    Could not transfer artifact lein-ancient:lein-ancient:jar:0.6.14 from/to clojars (https://artifactory.local/artifactory/clojars/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    Could not transfer artifact lein-ancient:lein-ancient:pom:0.6.14 from/to central (https://artifactory.local/artifactory/repo1/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    This could be due to a typo in :dependencies, file system permissions, or network issues.
    If you are behind a proxy, try setting the 'http_proxy' environment variable.

Dependencies from project.clj fetched from artifactory.local successfully.

Problem seems to be here (leiningen-core/src/leiningen/core/project.clj):

    (defn init-project
      "Initializes a project by loading certificates, plugins, middleware, etc.
    Also merges default profiles."
      ([project default-profiles]
         (-> (project-with-profiles (doto project
                                      (load-certificates)
                                      (init-lein-classpath)
                                      (load-plugins)))
             (init-profiles default-profiles)
             (load-plugins)
             (activate-middleware)))
      ([project] (init-project project [:default])))
    
Here `(load-certificates)` executes before `(init-profiles default-profiles)` and `:certifiactes` is `nil` at this moment. If rewrite the function to change the order of this calls it works fine in my case but impact on other things is unknown for me.

**Comment by technomancy** [comment]
The problem is we have to load the certificates before loading the plugins that are found in `project.clj` because otherwise we might not be able to download the plugins.

We have to load the plugins before loading the profiles because plugins can contain profiles.

So we can't just change the order. It might be possible to just call `load-certificates` twice though.

**Comment by tow8ie** [comment]
Any progress on this? I have the same issue and I don’t fully understand the proposed solution to fix it myself.

**Comment by mulkamanov** [comment]
The issue is still relevant. I have the same problem.

**Comment by glts** [comment]
In #2454 a (project-specific) repository overrides mechanism was added, that should at least provide a work-around outside of the project.clj for now.

**Comment by mulkamanov** [comment]
> In #2454 a (project-specific) repository overrides mechanism was added, that should at least provide a work-around outside of the project.clj for now.

Would it be a good idea to add support for a global "repository-overrides.clj"?

**Comment by glts** [comment]
@mulkamanov I think so. This was originally part of the plan (#2454), but was not implemented in the end:

> The current implementation only supports projectdir based overrides, but support for other profile locations such as ~/.lein can be added in the future.

I would support overrides within ~/.lein.

**Comment by glts** [comment]
There is an open pull request #2593 that fixes this. If you want to help, you can try it out and tell us whether it works for you.
