### ISSUE TITLE
Finding dependencies that are insecure

### ISSUE THREAD

**Issue by tetriscode** [technomancy/leiningen#2372]
Is there a way for Leiningen 2.8.1 to know which dependency it is fetching is insecure so that it can be rehosted? Travis CI just updated to 2.8.1 and my CI is now breaking.

**Comment by ism-ssw** [comment]
May be of no help to you but I started getting it with the update and the offending library was sandbar

**Comment by technomancy** [comment]
The underlying libraries we use unfortunately don't seem to offer a way to support this, so your best bet is a binary search.
