### ISSUE TITLE
Use Clojure 1.9.0 is the default new template version

### ISSUE THREAD

**Issue by puredanger** [technomancy/leiningen#2373]
Now that 1.9.0 is out, should probably update the default Clojure version to 1.9.0 in `/resources/leiningen/new/{app,default}/project.clj`. I know 1.8.0 is used out there in other places as well (docs, tests, etc), but I'm not sure how much of that to change, so just filing this as a ticket.

**Comment by technomancy** [comment]
Yeah, makes sense. Just the app and default templates need this, I think.

**Comment by jimmyhmiller** [comment]
Since there hasn't been a new version release since this change, is there anyway to change this locally?

**Comment by technomancy** [comment]
Sure; you can install the updated templates under another name: https://github.com/technomancy/leiningen/blob/master/doc/TEMPLATES.md
