### ISSUE TITLE
2.8.0 breaks ^:displace

### ISSUE THREAD

**Issue by bostonaholic** [technomancy/leiningen#2374]
It seems that upgrading from 2.7.1 -> 2.8.0 breaks the use of `^:displace` in the `:repl` profile.

```
~ cat .lein/profiles.clj
{:repl {:dependencies [^:displace [org.clojure/clojure "1.9.0"]]}}
~ lein -v
Leiningen 2.7.1 on Java 1.8.0_152 Java HotSpot(TM) 64-Bit Server VM
~ lein repl
user=> *clojure-version*
{:major 1, :minor 9, :incremental 0, :qualifier nil}
user=> exit
Bye for now!
~ lein upgrade 2.8.0
Leiningen 2.8.0 on Java 1.8.0_152 Java HotSpot(TM) 64-Bit Server VM
~ lein -v
Leiningen 2.8.0 on Java 1.8.0_152 Java HotSpot(TM) 64-Bit Server VM
~ lein repl
user=> *clojure-version*
{:major 1, :minor 8, :incremental 0, :qualifier nil}
```

**Comment by technomancy** [comment]
This is actually a bug in 2.7.x that made it impossible to run a repl outside a project; in 2.8.x the original behavior is restored: running outside a project means you get Leiningen's version of Clojure.

**Comment by stardiviner** [comment]
@technomancy 
> running outside a project means you get Leiningen's version of Clojure.
Does this mean Leiningen will use built-in Clojure version?
I'm using Leiningen 2.8.1, Java 9, I start `lein repl` got Clojure 1.8 too.

**Comment by technomancy** [comment]
@stardiviner that's correct.
