### ISSUE TITLE
Unable to find valid certification path to requested target. Any fixes ?

### ISSUE THREAD

**Issue by SambitKumarPanda** [technomancy/leiningen#2375]
`Could not transfer artifact com.project from/to clojars repo (http://clojars): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target `

Any fix ?

**Comment by danielcompton** [comment]
Dupe of #2371? Also, you should use the new Clojars repo at https://repo.clojars.org.

**Comment by danielcompton** [comment]
This looks like an incorrect URL if it is just `http://clojars`. Closing for now but can reopen if there is more info.

**Comment by tadwhitaker** [comment]
Yeah, same issue. Not sure how to resolve this certificate issue.

**Comment by danielcompton** [comment]
Hmm, I have a suspicion that a dependency has incorrectly defined their repository dependencies. Can you try bisecting the dependencies in your project to see which one triggers it?
