### ISSUE TITLE
Deps via insecure HTTP

### ISSUE THREAD

**Issue by lgrapenthin** [technomancy/leiningen#2376]
This issue https://github.com/technomancy/leiningen/issues/2277 is closed, but the issue has not been resolved.

The current breaking behavior is not acceptable. Having to apply a workaround by patching every project.clj is also not acceptable. I know exactly what I am doing when I am using HTTP and Leiningen shouldn't try to know any better.

Thank you for Leiningen, please reconsider.

**Comment by technomancy** [comment]
Leiningen supports loading "wagons" which add external support for dependency resolution transports. The best way to support this would be with an external wagon.

I would take a documentation patch to point people to such an tool.

**Comment by lgrapenthin** [comment]
It worked without wagons before. This is clearly a backwards incompatible change. Why do I have to learn about "wagons" now?
