### ISSUE TITLE
pom task doesn't include updatePolicy or checksumPolicy

### ISSUE THREAD

**Issue by samwagg** [technomancy/leiningen#2377]
If not, is there a reason it doesn't, or is this just a feature that hasn't yet been implemented?

e.g. 
```
  <repositories>
    <repository>
      <releases>
        <enabled>false</enabled>
        <updatePolicy>always</updatePolicy>
        <checksumPolicy>warn</checksumPolicy>
      </releases>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>never</updatePolicy>
        <checksumPolicy>fail</checksumPolicy>
      </snapshots>
      <id>codehausSnapshots</id>
      <name>Codehaus Snapshots</name>
      <url>http://snapshots.maven.codehaus.org/maven2</url>
      <layout>default</layout>
    </repository>
```

**Comment by technomancy** [comment]
You should be able to put :update :always/:never in your :repositories entries, yeah.

**Comment by samwagg** [comment]
Thank you, this is working for me. The only thing that's happening that's unexpected is the generated pom.xml does not have <updatePolicy>. I also tested with :checksum and the generated pom did not have that field either. Is that expected?

**Comment by technomancy** [comment]
> Thank you, this is working for me. The only thing that's happening that's unexpected is the generated pom.xml does not have . I also tested with :checksum and the generated pom did not have that field either. Is that expected?

I see; looks like an oversight. Happy to take a patch for that.

**Comment by samwagg** [comment]
https://github.com/technomancy/leiningen/issues/2377
