### ISSUE TITLE
Print a warning for `lein new figwheel`  when the template name is "cljs"

### ISSUE THREAD

**Issue by ahmedelgabri** [technomancy/leiningen#2382]
I wanted to try ClojureScript & I made a very typical n00b mistake & spent some time trying to wrap my head around why `lein new figwheel cljs` was not working. Thanks to @roman01la for pointing out the problem to me https://twitter.com/roman01la/status/945056087904014337

<img width="1792" alt="screen shot 2017-12-24 at 22 51 27" src="https://user-images.githubusercontent.com/63876/34329578-567ea8ae-e906-11e7-8dc8-2505addd3ab9.png">

So I want to propose to print a warning in the terminal to help beginners avoid doing the same mistake & I'd like also to open a PR for that (but I will need help 😊). If I'm not mistaken the change should affect these files https://github.com/technomancy/leiningen/blob/c73d4557c21aac5955b3996f2c190a1425b02853/src/leiningen/new/template.clj#L5-L23

https://github.com/technomancy/leiningen/blob/c73d4557c21aac5955b3996f2c190a1425b02853/src/leiningen/new/default.clj#L8-L34

https://github.com/technomancy/leiningen/blob/c73d4557c21aac5955b3996f2c190a1425b02853/src/leiningen/new/app.clj#L8-L30

**Comment by technomancy** [comment]
Leiningen will refuse to create a project named "clojure" for this exact same reason on the JVM. If anyone familiar with cljs could confirm that it would be a good idea to do the same thing with that, we could check for both.

**Comment by roman01la** [comment]
I don’t see any reasons why this shouldn’t be implemented, especially if it’s already done for “clojure” 👍
