### ISSUE TITLE
Checked out dependencies still resolved against Maven

### ISSUE THREAD

**Issue by arrdem** [technomancy/leiningen#2384]
At work we have a single repo which encompasses several Clojure applications, and shared libraries which support them. We're using lein-modules to help us automate this pattern, which works pretty well for the most part. In the context of a monorepo however, sub-artifacts such as our shared library aren't particularly meaningful. The goal of a monorepo is to provide build repeatability by lock-stepping everything in the repo. Everything should build against the source copy of the shared library at all times.

At present, checkout dependencies seem to be implemented by detecting `project.clj` files and partially evaluating them to sub-project maps whose classpaths are then concatenated with that of the current project, or at least that's my reading of [core.classpath](https://github.com/technomancy/leiningen/blob/da695d4104f1df567e4cd3421dc193f906f27ae6/leiningen-core/src/leiningen/core/classpath.clj#L573). This behavior leaves the `:dependencies` listings for checked-out dependencies intact which means that Leiningen will attempt to resolve artifacts it already has against Maven.

For our shared library, this means that as a workaround we have to generate and install at least locally a package version so that the Maven dependency resolution step succeeds.

The desired behavior would be that, when resolving dependencies, Leiningen does not do a Maven search for any dependency it already has available as a checkout. This would better match the intention of checkouts -- that they supersede Maven dependencies. Would you accept a patch to implement this behavior?

**Comment by arrdem** [comment]
This may relate to #686, not sure what the intended behavior is here.

**Comment by technomancy** [comment]
The behavior you're describing is the intended design of checkouts. They
are not meant to replace dependencies, just as a way of avoiding the
"install, switch projects, restart the repl" cycle you would otherwise
have when developing two projects in parallel.

It sounds like you're interested in adding another kind of dependency
type that doesn't work in terms of artifacts, but it would be a distinct
feature from checkouts.

Have you considered just adding things to :source-paths instead of :dependencies?

**Comment by arrdem** [comment]
Okay. That's good to know.

Part of our desire is to be able to incrementally factor our applications from monolithic source trees towards artifacts that can be stabilized and promoted to their own repositories. Being able to have the niceties of a Lein project such as being able to run a repl or tests on a constrained fileset defined by something that looks and behaves like a project and having packaged dependencies independent from other projects which may share that fileset and those dependencies would be nice. `:source-paths` and leveraging profiles extensively don't buy us that particularly nicely.

As this is a different set of dependency semantics than what checkouts are intended to provide, what would you consider the most appropriate vehicle for achieving them? A plugin that does dependency rewriting, or would you be interested in some tools.deps style resolver plugin system.

**Comment by technomancy** [comment]
Reid D McKenzie <notifications@github.com> writes:

> As this is a different set of dependency semantics than what checkouts
> are intended to provide, what would you consider the most appropriate
> vehicle for achieving them?

I guess I don't understand the use case.

In my mind if you're trying to keep things all in one repo, then
dependencies across multiple projects in one repo amounts to basically
just "put more directories on the classpath" in the end, right? So
are you saying you would like a higher-level way to configure the same
end result of "more directories on the classpath" or that "more
directories on the classpath" isn't the desired end result?

-Phil

**Comment by arrdem** [comment]
"more directories on the classpath" is definitely the desired result here in general, but part of the desire is to be able to still be precise about only grabbing one project and its dependencies rather than grabbing the entire repo.

**Comment by technomancy** [comment]
Now I'm even more confused; originally this issue was that you didn't want the transitive dependencies resolved, but now you do?

**Comment by technomancy** [comment]
This doesn't seem actionable as-is. We can reopen if there's something specific to do.
