### ISSUE TITLE
Use of aot

### ISSUE THREAD

**Issue by r-custodio** [technomancy/leiningen#2388]
I honestly have a question about this

Some developers from community keeps saying that is bad to use AOT, what do you from lein recommend? I never had a problem with it, but what is the disadvantage about AOT? What bugs can it do?

**Comment by technomancy** [comment]
I would say it's bad to have AOT during development. It won't usually
cause problems unless you use protocols or records (or use libraries
which have protocols or records) but when you do it can cause problems
that are very difficult to debug. Mostly it manifests as reloads being
ignored.

Doing AOT as the final step of your deploy process is usually safe, as
long as you do it on an isolated checkout and the .class files don't
leak into your dev environment.

**Comment by r-custodio** [comment]
Thanks!!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
