### ISSUE TITLE
Shell bug?

### ISSUE THREAD

**Issue by junyitian** [technomancy/leiningen#2389]
Hello,
        Is it shell bug?  LEIN_VERSION="2.8.1"
if [[ "$CLASSPATH" != "" ]]; then
    echo "WARNING: You have \$CLASSPATH set, probably by accident."
    echo "It is strongly recommended to unset this before proceeding."
fi

**Comment by technomancy** [comment]
Can you be more specific about which part might be a bug?

There is no good reason to set $CLASSPATH at this time, but we still support it for backwards-compatibility reasons.

**Comment by junyitian** [comment]
The meaning of the Shell above is to check the CLASSPATH is not empty, or do not need to set the CLASSPATH?

**Comment by technomancy** [comment]
The code warns people who may have accidentally set `$CLASSPATH` and encourages them not to do that.
