### ISSUE TITLE
How to run `lein repl` with nailgun?

### ISSUE THREAD

**Issue by abo-abo** [technomancy/leiningen#2390]
I installed [nailgun](https://github.com/facebook/nailgun) and it works fine for `clojure.main`.

Start server:
```shell
java com.martiansoftware.nailgun.NGServer
```

Run REPL:
```shell
ng clojure.main
```

However, trying `lein repl`:

```shell
export JAVA_CMD=ng
lein repl
```

results in an error:

    INFO: Server unexpectedly exited with unhandled exception
    java.lang.ClassNotFoundException: -Xbootclasspath/a:/home/oleh/.lein/self-installs/leiningen-2.7.1-standalone.jar
    	at java.lang.Class.forName0(Native Method)
    	at java.lang.Class.forName(Class.java:348)
    	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:271)

I tried adding that jar to CLASSPATH, and also starting the server like this:

    java -cp "$(lein classpath):$CLASSPATH" com.martiansoftware.nailgun.NGServer

Still, the same error. Has anyone had success with something like this?

**Comment by technomancy** [comment]
I don't think nailgun will work for this. You could try `grench` instead which is designed to work with Leiningen and serves the same purpose: https://leiningen.org/grench.html

**Comment by abo-abo** [comment]
Thanks, I'll check it out.
