### ISSUE TITLE
Composite profiles expansion may cause inconsistent profile merge/unmerge behavior

### ISSUE THREAD

**Issue by mrrodriguez** [technomancy/leiningen#2393]
If I have a project written in two slightly different ways that utilizes "composite profiles", eg.

```clj

;; CASE 1

(defproject my.test/test "1-SNAPSHOT"
  :profiles {:top {:foo :bar}
             :dev [:top {}]    ;; <---- HERE is the difference
             :uberjar [:top
                       {:hello :world}]})

;; CASE 2

(defproject my.test/test "1-SNAPSHOT"
  :profiles {:top {:foo :bar}
             :dev [:top]       ;; <---- HERE is the difference
             :uberjar [:top
                       {:hello :world}]})

```

I ran into a few issues with some broader behaviors that I am leaving out for now. I can add those on if needed.

The issues stem form the fact that the `leiningen.core.project/expand-profiles` behavior is different for the CASE 1 and 2 projects before. To demonstrate that assume the `defproject` is in a path "/home/case1/project.clj" and "/home/case2/project.clj"

```clj

(require 'leiningen.core.project)
(in-ns 'leiningen.core.project)

;; CASE 1

(def case1 (read "/home/case1/project.clj"))

(expand-profiles case1 [:default])
;;= (:base :system :user :provided :dev) ;; <---- notice :dev


;; CASE 2

(def case2 (read "/home/case2/project.clj"))

(expand-profiles case2 [:default])
;;= (:base :system :user :provided :top) ;; <---- :top instead of :dev above


```

The profile `:dev [:top {}]` is not recursively expanded through to `:top` in CASE 1. The profile `:dev [:top]` is fully-recursively expanded in CASE 2.

`leiningen.core.project/expand-profiles` is used by `leiningen.core.project/merge-profiles` and `leiningen.core.project/unmerge-profiles` among other things. Due to the different expansion behavior here, I've had scenarios where the `:default` profile may merge/unmerge different profiles depending on whether or not the empty map from CASE 1 was there or not.

This issue seems to come from [the function leiningen.core.project/expand-profile*](https://github.com/technomancy/leiningen/blob/2.8.1/leiningen-core/src/leiningen/core/project.clj#L630-L642)

It actually explicitly distinguishes between the `sequential?` with some `map?` case vs just `sequential?`. I also have noticed a comment in the code on recent versions of Lein v2x in `leiningen.core.project/expand-profile*`

> ;; TODO: drop "support" for partially-composite profiles in 3.0

I'm not sure what that is referring to though and how that will affect this behavior.

**Comment by glts** [comment]
I am currently reviewing the profiles code, thank you for writing up this detailed analysis.

I believe this is intentionally designed this way, though; see the test [`test-profiles-in-group`](https://github.com/technomancy/leiningen/blob/2.9.1/test/leiningen/test/with_profile.clj#L30-L32), where `:foo` does not get expanded to `:bar` because it points to a mixed composite profile. Usually this seems not to be a problem, because full recursive ‘expansion’ is also done later via `lookup-profile*`.

I’d be interested if you have a repro for a user-visible problem caused by this.

**Comment by mrrodriguez** [comment]
@glts it's been a long time since I wrote this and can't recall an explicit case that caused me trouble. However, I know this was the source of a build problem I had. The difference in final profiles affecting something later in the profile merging I believe, so things were missing that I expected to be there when the profile wasn't recursively expanded.

**Comment by technomancy** [comment]
At this point, I think changes here are more likely to cause more problems than they solve. We do specifically recommend against the use of mixed keyword/map composite profiles in the documentation so the best we can do is get people to avoid it.
