### ISSUE TITLE
Friendlier Leiningen watches for issues and warns

### ISSUE THREAD

**Issue by gitshub** [technomancy/leiningen#2394]
A programmer gets an unexpected result and spends hours trying to find out why.  The computer could save this time by keeping a list of known issues and watching for them (when not too much programming effor, or too big performance hit is involved).  As an example, below I describe a "gotcha" listed in the documentation but easy to overlook.  I think it is similar to:

    "I see  you are trying to increment 7. Sorry, but  the documentation states that this trick doesn't currently work with 7 and 43. You will receive the value hard-coded into the version of Leiningen which you downloaded. See references..."

Here is the actual "gotcha": 

I'm issuing the command "(lein repl)" to bring up a REPL.  If I am just using it to learn Clojure, and not working on a project, I may choose to issue the command _above_ the root directory of any "project.clj" file, so Leiningen will not use any such file. 

  Leiningen documentation (https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md) says "
-------------------
 By default, the repl task will use the version of Clojure, tools.nrepl and clojure-complete that ships with the Leiningen. These can be overridden in projects, but this doesn't change the repl's behaviour outside of those projects. To do that, you should put a :repl profile in your ~/.lein/profiles.clj file. ...

   If you want to specify the default Clojure version outside of projects, you can do so by ^:displace-ing it in the :repl profile:
    
    {:repl {:dependencies [^:displace [org.clojure/clojure "1.8.0-alpha3"]]}}
    
    This version will only be used outside of Clojure projects. Note that this ^:displace trick will not work with tools.nrepl or clojure-complete."
----------------   
So "tools.nrepl" and "clojure-complete" are like the  7 and 43 in my initial example.

Of course, an easy workaround is just to learn Clojure after changing to a project directory, but why can't the computer watch for known issues and give warning?  How hard would it be for Leiningen to detect that the "~/.lein/profiles.clj" (or other relevant profile files) specify a different Clojure version from the one hard coded into Leiningen, and that the user is calling "nREPL"?

If this is done with several issues, the effort spent might save users tons of time and increase Clojure/Leiningen 's popularity a lot, in my humble opinion.

Thanks for your consideration.

References:

1. "this ^:displace trick will not work with tools.nrepl or clojure-complete." https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md

2.  "Updating ~/.lein/profiles.clj to {:repl {:dependencies [^:displace [org.clojure/clojure "1.9.0"]]}} does not seem to work. – Petrus Theron Jan 10 2018 at 9:05" https://stackoverflow.com/questions/24094597/how-do-you-change-clojure-version-in-leiningen-and-lighttable

3. "I asked technomancy on IRC just now. He said: "REPL's outside projects are hard coded to lein's version of clojure". – David J. Feb 24 '14 at 19:52" https://stackoverflow.com/questions/15170388/how-to-change-clojure-or-leins-clojure-default-version

4. https://stackoverflow.com/questions/28688721/how-to-upgrade-nrepl-version-of-leiningen

**Comment by danielcompton** [comment]
I've read this issue and are not 100% sure on exactly what you're asking for here? Is this a further change to documentation or making leiningen detect if there are clojure-complete and tool.nrepl dependencies in the `:repl` profile?

**Comment by technomancy** [comment]
This is a good question. We actually have mechanisms in place to warn
when you attempt to load a version of a library in Leiningen's own
process that can't be loaded:

https://github.com/technomancy/leiningen/blob/master/leiningen-core/src/leiningen/core/classpath.clj#L412

This allows the user to spot potential conflicts when a plugin requests
a version of a library that can't be loaded.

However, we specifically do not warn for mismatches of Clojure
itself. This is because basically every plugin with dependencies will
end up with a conflict! So you would see a warning every time, and 99%
of the time, it's not actually a problem. Emitting a warning in this
case would lead to "warning fatigue" which just trains people to ignore
them.

Technically speaking there is no difference when running outside a
project between :dependencies and :plugins. However, the intent is
different, so maybe it makes sense to treat them differently in terms of
how we emit warnings?

**Comment by gitshub** [comment]
@https://github.com/technomancy -- Whatever you say, I'm just a beginner!

@https://github.com/danielcompton Making leiningen detect (and warn) if there are clojure-complete and tool.nrepl dependencies in the :repl profile which request
a version of software (Clojure itself in this case) that can't be loaded.  The user might try to request  Clojure "1.8.0-alpha3" by using the above line in "~/.lein/profiles.clj" file, because he wants (for some reason) to issue the command "(lein repl)" _outside of_ a project directory and get Clojure "1.8.0-alpha3", not the version hard-coded into his Leiningen software (which is what he will unknowingly wind up with).
