### ISSUE TITLE
Updating project's Clojure dep to 1.9.0 breaks lein repl

### ISSUE THREAD

**Issue by leblowl** [technomancy/leiningen#2395]
Just a heads up. With a new leiningen base template (`lein new datomic-test`), upgrading the clojure dep to 1.9.0 broke `lein repl` for me:
```bash
lucas@debian:~/Code/leblowl/datomic-test$ lein --version
Leiningen 2.8.1 on Java 1.8.0_151 OpenJDK 64-Bit Server VM
lucas@debian:~/Code/leblowl/datomic-test$ cat project.clj
(defproject datomic-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [com.datomic/client-pro "0.8.14"]])
lucas@debian:~/Code/leblowl/datomic-test$ lein repl
Error loading cider.nrepl.middleware.test: java.lang.RuntimeException: Invalid token: ::clojure.test/once-fixtures, compiling:(cider/nrepl/middleware/test.clj:98:57)
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cider.nrepl.middleware.test/wrap-test in this context, compiling:(/tmp/form-init5652515655827990377.clj:1:5189)
```

Adding `:plugins [[cider/cider-nrepl "0.16.0"]]` to the `project.clj` file fixed it for me.

**Comment by technomancy** [comment]
Thanks, but this is a bug in cider, not Leiningen.

**Comment by leblowl** [comment]
Okay, well I guess I am confused, so sorry for my ignorance. But I ran the
command 'lein repl' ... and I didn't include any cider dependency that I
was aware of. It was a fresh leiningen project template. So do you know
where this cider dependency is coming from and how it got included? Thanks
for your help! I appreciate you.

**Comment by technomancy** [comment]
Sure; no problem. If I had to guess I'd say it was probably installed in `~/.lein/profiles.clj` maybe? I don't see anything within `project.clj` itself that could trigger it.

**Comment by leblowl** [comment]
Awesome, thanks @technomancy. It was the user's `profiles.clj` file:
```bash
lucas@debian:~/Code/leblowl/datomic-test$ cat ~/.lein/profiles.clj 
{:user {:plugins [[cider/cider-nrepl "0.8.1"]]}}
```
That's a good "gotcha".

**Comment by dineshbhardwaj** [comment]
thanks
