### ISSUE TITLE
Test for $CLASSPATH producing false positives. Fix included.

### ISSUE THREAD

**Issue by cdrasmussen** [technomancy/leiningen#2396]
Test for CLASSPATH settings in lein.sh is producing false positives.

Test for CLASSPATH in lein.sh should read:
if [ -n "$CLASSPATH" ] ; then
    echo "WARNING: You have \$CLASSPATH set, probably by accident."

This was tested in Ubuntu 16.04.3 LTS Xenial Xerus

**Comment by technomancy** [comment]
Thanks; this should already be fixed by #2362.

**Comment by cdrasmussen** [comment]
Oops. Sorry for the duplicate.

+CDR
