### ISSUE TITLE
Unable to pull dependencies from central/clojars

### ISSUE THREAD

**Issue by deepakjangid123** [technomancy/leiningen#2401]
Hi all,

My project.clj file looks like -
```
(defproject somename "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.apache.kafka/kafka-clients "0.11.0.2"]]
  :main somename.core
  :target-path "target/%s"
  :profiles {:dev {:dependencies [[lein-light-nrepl "0.3.3"]
                                  [enlive "1.1.6"]
                                  [cheshire "5.8.0"]
                                  [criterium "0.4.4"]]}}
  :repl-options {:nrepl-middleware [lighttable.nrepl.handler/lighttable-ops]})

```

`lein repl` is working fine, out of the project directory.
```
$ lein repl
nREPL server started on port 34420 on host 127.0.0.1 - nrepl://127.0.0.1:34420
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_161-b12
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> 
```
But, for this project when I am doing `lein deps`, It is unable to pull dependencies. 
I am getting an error like-

> Could not transfer artifact org.apache.kafka:kafka-clients:pom:0.11.0.2 from/to central (https://repo1.maven.org/maven2/): Connect to  [localhost/127.0.0.1] failed: Connection refused (Connection refused)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.

```
$ lein version
Leiningen 2.7.1 on Java 1.8.0_161 Java HotSpot(TM) 64-Bit Server VM

$ java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```
Please help me with this.

**Comment by technomancy** [comment]
>  Could not transfer artifact org.apache.kafka:kafka-clients:pom:0.11.0.2 from/to central (https://repo1.maven.org/maven2/): Connect to [localhost/127.0.0.1] failed:

You need to find out why your computer is resolving "repo1.maven.org" to 127.0.0.1, because that's just not right.

**Comment by deepakjangid123** [comment]
Thanks for your help,
I was quite unable to figure it out. So reinstall the OS. Now it is working fine.
