### ISSUE TITLE
lein repl in project with checkouts opens in checkouts' user.clj namespace

### ISSUE THREAD

**Issue by anler** [technomancy/leiningen#2407]
Hello! I'm running into this issue that I'm not sure if it's a bug or not, but for me is a bit surprising its behavior.

I have created [two projects](https://github.com/anler/lein-test) one of which is a checkout dependency (lib-project) of the other (app-project). The problem is if I try to run `lein repl` in the app-project, it tries to open the repl in the `user.clj` namespace of the lib-project but fails to do so since that namespace is using dependencies declared in dev profile of lib-project.

If indeed is a bug, I can try to help in its resolution.

Thanks!

**Comment by technomancy** [comment]
Unfortunately auto-loading of `user.clj` is a feature of Clojure that we can't turn off; it is not controlled by Leiningen.

I don't think there's anything we can do about this.
