### ISSUE TITLE
uberjar-merge-with and transitive dependencies

### ISSUE THREAD

**Issue by lambder** [technomancy/leiningen#2408]
Looks like `:uberjar-merge-with` option merges only files from direct dependencies ignoring the transitive ones.

Is there a way to merge files from all the dependencies?

if my `:dependencies` doesn't include `[org.flatland/ordered "1.5.4"]` the resulting `data_readers.clj` is :

```
{sql/call honeysql.types/read-sql-call,
 sql/param honeysql.types/read-sql-param,
 sql/regularize honeysql.format/regularize,
 sql/array honeysql.types/read-sql-array,
 linked/map linked.map/->linked-map,
 linked/set linked.set/->linked-set,
 ordered/set flatland.ordered.set/into-ordered-set,
 ordered/map flatland.ordered.map/ordered-map,
 sql/raw honeysql.types/read-sql-raw}
```

if I include `[org.flatland/ordered "1.5.4"]` the resulting `data_readers.clj` is :

```
{sql/call honeysql.types/read-sql-call,
 sql/raw honeysql.types/read-sql-raw,
 sql/param honeysql.types/read-sql-param,
 sql/array honeysql.types/read-sql-array,
 sql/regularize honeysql.format/regularize,
 linked/map linked.map/->linked-map,
 linked/set linked.set/->linked-set}
```

**Comment by technomancy** [comment]
I can't reproduce this on master. I added a test in 94e06b1, and the behavior you want seems to work already. (The new dependency adds an indirect dep on `org.flatland/ordered`.

If you can provide a repro case I can look into this further but it looks like it may be fixed already.

**Comment by glts** [comment]
I have tried to reproduce this with Leiningen 2.9.1. Given the project.clj

```clojure
(defproject pork "0.1.0-SNAPSHOT"
  :dependencies [[porcupine "0.0.4"]])
```

after running `lein uberjar`, the uberjar contains `{ordered/set flatland.ordered.set/into-ordered-set, ordered/map flatland.ordered.map/ordered-map}` in `data_readers.clj`.

So the problem as stated here is no longer reproducible.

**Comment by technomancy** [comment]
Yeah, I think we got this with one of our fixes in the past couple years.
