### ISSUE TITLE
Installing Leiningen

### ISSUE THREAD

**Issue by Danimal66** [technomancy/leiningen#2416]
Hello, I am a programmer wanting to learn Clojure. I am using Windows 10 and am not quite sure how to properly install Leiningen. I saved the .bat file and added the folder it's stored in to my path in environment variables but when I go to command prompt to try and do a lein self-install it tells me that it doesn't recognize the command "lein". I was wondering if you could provide me with more assistance. I have tried to look up videos or articles explaining what to do, but I can't figure out what I am doing incorrectly. Thank you for your time!

**Comment by Danimal66** [comment]
Thank you for the quick response! When I ran the .bat file and restarted it got rid of the error where it doesn't recognize "lein" but it now it pops up a long list of errors that "is not recognized as an internal or external command, operable program or batch file." I think I am at the part of the installation where it tells me to make it executable. But I'm confused by the wording. Am I supposed to make the .bat file into a .exe now?

**Comment by winks** [comment]
No, that's only for the `lein` shell script under Linux/UN*X.
If you are using `cmd` then just running `lein` should work.

If you are using `PowerShell` and are in the same dir, then `.\lein.bat` or `.\lein` should work.
If you are using `PowerShell` and are not in the same dir, then just `lein` should suffice.

**Comment by stevechae** [comment]
Also note that Windows install (via `lein.bat`) seems to be broken at the moment. The fix is outlined here: https://github.com/technomancy/leiningen/issues/2412

**Comment by Danimal66** [comment]
I get a different error than they're receiving in the fix you provided, I am probably doing something wrong, but this is the error message I get currently:

C:\Users\danam>lein

C:\Users\danam>#!/usr/bin/env bash
'#!' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\danam># Ensure this file is executable via `chmod a+x lein`, then place it
'#' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\danam># somewhere on your $PATH, like ~/bin. The rest of Leiningen will be
'#' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\danam># installed upon first run into the ~/.lein/self-installs directory.
'#' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\danam>export LEIN_VERSION="2.8.1"
'export' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\danam>case $LEIN_VERSION in
'case' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\danam>*SNAPSHOT) SNAPSHOT="YES" ;;
'*SNAPSHOT)' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\danam>*) SNAPSHOT="NO" ;;
'*)' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\danam>esac
'esac' is not recognized as an internal or external command,
operable program or batch file.
"$CLASSPATH" was unexpected at this time.
C:\Users\danam>if [[ "$CLASSPATH" != "" ]]; then

**Comment by stevechae** [comment]
It looks like you are trying to run the Linux/Unix version of the installation script. You should run the **Windows version** instead which can be found [here](https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat).

Since you are on Windows 10, you may still encounter an issue trying to run Windows installations script. For that, see https://github.com/technomancy/leiningen/issues/2412 for a fix.

**Comment by winks** [comment]
Closing this for now, please see #2412 if you run into any of the described problems and further info.
