### ISSUE TITLE
Which profile should contain "convenience tooling" dependencies.

### ISSUE THREAD

**Issue by samwagg** [technomancy/leiningen#2420]
> The :dev profile is used to specify project specific development tooling. Put things here if they are required for builds or tests, rather than just convenience tooling.
-- From the [profiles doc](https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md)

Where should such dependencies go? E.g. I want a linter plugin (eastwood) to be available to all contributors when they clone my repo.

**Comment by samwagg** [comment]
I realized I was conflating things. To clarify, my example is of a plugin rather than I dependency, which I suppose is fine at the top level in project.clj. 

But I think my question still stands in general, and possibly indicates an enhancement opportunity for the doc. I am confused about where I should put such "convenience tooling", which I guess (but am not sure) refers to libraries to be used by the developer in the REPL but not actually required by the project.

**Comment by technomancy** [comment]
I'm using "convenience tooling" here to mean things that aren't needed
to make the build pass. If your build won't pass without running the
linter then it should be in the main `project.clj` file.

If your project doesn't require linting to pass, then I'd consider it a
user convenience tool that would be better off in the `:user` profile.

Maybe the docs could make that wording clearer; if you have a suggested
change feel free to submit it.
