### ISSUE TITLE
Local .m2 considered insecure HTTP repository

### ISSUE THREAD

**Issue by mobiusinversion** [technomancy/leiningen#2422]
Hello,

I am building a lein project locally, and I have a SNAPSHOT of one of the dependencies I wrote in Java, in my local .m2.  However `lein` refuses to see this and instead issues me the famous

    Tried to use insecure HTTP repository without TLS.
    This is almost certainly a mistake; however in rare cases where it's
    intentional please see `lein help faq` for details.

I know the workaround, but thats ugly just to use a local dependency.  How do I use a local dependency without the insecure HTTP wagon?

**Comment by technomancy** [comment]
There's no problem in using a local dependency in and of itself; the
problem here is likely that the local dependency itself depends on
another library that it is instructing Leiningen to fetch insecurely
over http. You can override this with a mirror setting that redirects it
to an https URL. Can you link to the pom.xml file of the Java dep?

**Comment by mobiusinversion** [comment]
Thanks, I will have a look.
