### ISSUE TITLE
Centos dont run lein

### ISSUE THREAD

**Issue by WanXinTao** [technomancy/leiningen#2424]
I performed the final step according to your steps, but when the lein is executed, it shows that the file or directory cannot be found.
Chmod a+x lein is executable

**Comment by WanXinTao** [comment]
Centos  yum can not install leiningen，So I can only install it manually, but I can't run it

**Comment by winks** [comment]
Could you maybe paste the exact error and commands you executed, please?

**Comment by technomancy** [comment]
There's nothing we can do without details about the problem here; feel free to reopen if you have a more specific question.
