### ISSUE TITLE
Update default target path to be "target/%s/"

### ISSUE THREAD

**Issue by danielcompton** [technomancy/leiningen#2425]
Would it make sense for the default target path in Leiningen to be updated to `:target-path "target/%s/"`? This seems like a better default for projects. I guess it would be a breaking change which is why you might not want to change the default behaviour, but it could be good for 3.0.0?

**Comment by puredanger** [comment]
This seems likely to break anything that consumed leiningen output (like tools, custom scripts, etc).

👎

**Comment by technomancy** [comment]
I think we already have a TODO for this in the source, but yes it's not the kind of thing we can do without bumping to 3.0.

**Comment by danielcompton** [comment]
Yeah, as I was writing the issue, I thought that it would be a breaking change for tools and scripts that consume Lein output.

**Comment by RickMoynihan** [comment]
Would it be a breaking change to include it in the default `lein new` template though, that way new projects could get the better behaviour out of the box.

**Comment by technomancy** [comment]
It wouldn't be a breaking change.

In fact, it wouldn't be a change at all: https://github.com/technomancy/leiningen/blob/master/resources/leiningen/new/app/project.clj#L8

**Comment by jconti** [comment]
Your succinctness has helped my thought process, thank you!  I would like to restate my (potentially ignorant) claim:

> That a user cannot expect `:target-path "target/%s"` to work with [pre-compile](https://github.com/technomancy/leiningen/blob/master/doc/MIXED_PROJECTS.md#interleaving-compilation-steps) is a bug.  Must users regard all builds requiring pre-compilation (2+ profiles) as inevitably buggy?  Those builds need `:target-path` more than most.

I suspect I have missed something very obvious.  If you could point it out I would be very appreciative.

**Comment by technomancy** [comment]
Well, the whole point of a precompile profile is to produce output intended for another profile. So the whole idea of "profiles should have their outputs isolated" is impossible for such a profile. The two concepts are by definition mutually exclusive.

The best we could do is mention in the documentation for precompile profiles that it's a good idea to specify the `:target-path` for its output in a way that does not include `%s`.
