### ISSUE TITLE
Support Clojure 1.9 in plugins.

### ISSUE THREAD

**Issue by DLaps** [technomancy/leiningen#2433]
The current release depends on Clojure 1.8. I think there is no possibility to use new built-in functionality in plugins like clojure.spec.alpha, which is only part of Clojure 1.9.

A new release of leiningen, which supports Clojure 1.9 in plugins, would be nice.

**Comment by PsukheDelos** [comment]
Just putting our interest into this out there as it's making building our application increasingly difficult. Is there any traction on when this might be possible / is it in the pipeline at all? Really love Leiningen by the way, keep up the good work! -G

**Comment by technomancy** [comment]
The likelihood of plugin breakage is too high for this to be included in Leiningen 2.8.2, but I'll merge it once that one is released so it can be part of the following version.

**Comment by technomancy** [comment]
Sure, I'm hoping to get 2.8.2 out in a few weeks; the only open blockers are listed at https://github.com/technomancy/leiningen/milestone/26

Beyond that I don't have any concrete plans, but hopefully you can test your changes on the master branch at that point and we can get some wider testing on it to get a feel for what kind of potential plugin incompatibility it might introduce.

**Comment by PsukheDelos** [comment]
Legend! Thanks so much @technomancy! -G

**Comment by danielcompton** [comment]
There is an open PR for this at https://github.com/technomancy/leiningen/pull/2449, although it doesn't look like it is in a mergeable state.

**Comment by technomancy** [comment]
Done in 9699fd7.
