### ISSUE TITLE
Support non-directly-linked Clojure

### ISSUE THREAD

**Issue by vemv** [technomancy/leiningen#2437]
Hi there!

I am finding that it is not trivial to use a Clojure 1.8+ (the language) artifact that hasn't been direct-linked.

From the official side, the issue isn't getting much attention https://dev.clojure.org/jira/browse/CLJ-1862

The reason I would want to turn if off is for dev-env-only facilities, such as spec instrumenting -not supported for e.g. `+`-, stacktrace improvements and other stuff that could be considered 'monkey patching'.

From what I see, building Clojure with DL turned off is as easy as setting a single [flag](https://github.com/clojure/clojure/blob/4ef4b1ed7a2e8bb0aaaacfb0942729252c2c3091/build.xml#L31). However:

* I'd have to host the artifact myself (easy)
* I'd have to convince peers (e.g. adopters of a library of mine depending on my custom Clojure) that my Clojure distribution is clean / malware-free (hard)
* I'd have to tackle the fact that all Clojure libraries depend on `org.clojure/clojure` with my own distribution called e.g. `vemv/clojure`. I reckon it would be hard to do in a clean manner.

For those reasons, it would seem to me that this is something Leiningen could fix behind the scenes.

Let's say my project.clj says

`^:non-directly-linked [org.clojure/clojure "1.9.0"]`

. Then, leiningen could replace that .jar for one compiled/distributed by the Leiningen community (e.g. `leiningen/clojure "1.9.0"`), in a way that is transparent to other libraries.

Does it sound like a good idea?

Btw I might give a shot to the implementation myself.

Victor

**Comment by technomancy** [comment]
We have existing methods to exclude a dependency you don't want, and you
can introduce your own replacement. But right now (outside the context
of plugins) Clojure is treated as just another dependency with no
special handling, and I would like to keep it that way.

**Comment by vemv** [comment]
Hey Phil,

I understand your stance but OTOH this makes it hard to author/distribute libraries that patch clojure.core (which certainly can be done in a clean/minimal/responsible manner).

Essentially I'd have to instruct users to use a random Clojure build, which would be a no-go for most people.
