### ISSUE TITLE
Non-JAR dependencies are not used in CLASSPATH

### ISSUE THREAD

**Issue by kumarshantanu** [technomancy/leiningen#244]
Leiningen, like Maven, supports :type and :classifier in artifact names. However, dependency artifacts whose :type is not JAR are not included on the CLASSPATH. For example, the artifacts of :type "zip" on the URL below are not available to the application:

http://wiki.docbook.org/Maven

```
<dependency>
  <groupId>net.sf.docbook</groupId>
  <artifactId>docbook-xsl</artifactId>
  <version>1.75.1</version>
  <type>zip</type>
  <classifier>ns-resources</classifier>
</dependency>
```

When I manually copy the .ZIP file as .JAR in 'lib' or 'lib/dev' directory then it is included in the CLASSPATH and is available to the application.

**Comment by michael-o** [comment]
To whom it may concern: https://issues.apache.org/jira/browse/MNG-5567
