### ISSUE TITLE
lein script no longer available from project homepage

### ISSUE THREAD

**Issue by DasEarl** [technomancy/leiningen#2440]
The 'Download the lein script' url links to https://raw.githubusercontent.com/technomancy/leiningen/preview/bin/lein which is no longer available since the preview branch is gone.

Also the standalone.zip ist also no longer available from https://github.com/technomancy/leiningen/releases/download/2.8.2-SNAPSHOT/leiningen-2.8.2-SNAPSHOT-standalone.zip

**Comment by technomancy** [comment]
Can you be more specific about where you saw this broken link? I can't find it anywhere.

**Comment by DasEarl** [comment]
It seems to be working now. The lein script from https://leiningen.org/ now links to https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein

The other broken link comes from the lein script from the master branch.
