### ISSUE TITLE
lein run does not pass arguments to -main that begin with a hash character.

### ISSUE THREAD

**Issue by mxtetrachord** [technomancy/leiningen#2441]
steps to repro:

`$ cd some-dir`
`$ lein new app foo && cd foo`

edit src/colors/core.clj:
```clojure
(defn -main [& args]
  (println args))
```

`$ lein run 123456`
`(123456)`

`$ lein run #123456`
`nil`

<img width="580" alt="screen shot 2018-06-19 at 8 15 50 am" src="https://user-images.githubusercontent.com/13964123/41606680-153c3230-7399-11e8-9323-315f73b70a63.png">

**Comment by technomancy** [comment]
This is actually a feature of your shell; you're running `lein run` with a comment after it that says 123456. To avoid having your shell treat it as a comment, either wrap it in quotation marks or put a backslash in front of it.
