### ISSUE TITLE
Checkouts documentation question

### ISSUE THREAD

**Issue by matanster** [technomancy/leiningen#2445]
The documentation section for [checkouts](https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#checkout-dependencies) could be improved. Why not say upfront that:

- One must have at least once made their dependency available in their m2 repo or maven central. Why hide that as a troubleshooting note saying `Run lein install in the suchwow directory`? it should be said upfront to avoid lots of confusion. Or did I misunderstand and that's actually not a requirement?

IMHO.

**Comment by technomancy** [comment]
Sure; I'd take a patch for that.

**Comment by zendevil** [comment]
Is there a way for not having to lein install in a checkout repo with each edit? Can the edits be made in the checked-out repo and then used without the need to lein install again, when running a repl in the root project?
