### ISSUE TITLE
Add lein-codeindex to list of plugins

### ISSUE THREAD

**Issue by sanel** [technomancy/leiningen#2446]
I'm sporadically working on plugin that does code indexing, correctly pulling out all dependencies. The plugin is called [lein-codeindex](https://github.com/sanel/lein-codeindex).

It would be nice if it coule be part of [Plugins](https://github.com/technomancy/leiningen/wiki/Plugins) page.

Thanks!

**Comment by technomancy** [comment]
Sure; that page is a wiki, so feel free to add your plugin.

**Comment by sanel** [comment]
Ah, though it was md file. Thanks! :)
