### ISSUE TITLE
Misleading "Insecure HTTP repository without TLS" error due to insufficient disk space

### ISSUE THREAD

**Issue by daveliepmann** [technomancy/leiningen#2460]
I got an "insecure HTTP repository without TLS" error while retrieving dependencies during `lein run` not due to a TLS error, but because the disk was full:

>Tried to use insecure HTTP repository without TLS.
This is almost certainly a mistake; however in rare cases where it's
intentional please see `lein help faq` for details.

I must apologize because I don't have an easy environment in which to replicate the error. However I am relatively confident in my suspicion that disk space was the culprit because the error occurred several times, but stopped after clearing several gigabytes of disk space. Furthermore, the error occurred in a Docker container (therefore under mostly-identical conditions) but was not reproducible on other machines with more disk space. Finally, I don't pretend to understand leiningen's use of [`insecure-http-abort`](https://github.com/technomancy/leiningen/blob/master/leiningen-core/src/leiningen/core/main.clj#L418) or pomegranate/aether, but it looks like that "Tried to use insecure HTTP repository without TLS." message could be returned on any `abort` of the Wagon object.

**Comment by danielcompton** [comment]
Looking at https://github.com/technomancy/leiningen/blob/master/leiningen-core/src/leiningen/core/main.clj#L441, it seems like this error should only apply if you were retrieving something from an http repo, otherwise I can't see how this code path would be hit?

**Comment by technomancy** [comment]
I'm going to close this since there's nothing we can do without a repro case, but if you have any more details we can reopen.
