### ISSUE TITLE
Warnings when starting repl

### ISSUE THREAD

**Issue by emlyn** [technomancy/leiningen#2465]
When I create a new project and then start a repl, I see a number of warnings printed:
```
> lein new empty
Generating a project called empty based on the 'default' template.
The default template is intended for library projects, not applications.
To see other templates (app, plugin, etc), try `lein help new`.
> cd empty
> lein repl
nREPL server started on port 54376 on host 127.0.0.1 - nrepl://127.0.0.1:54376
Exception No namespace: reply.eval-modes.nrepl found  clojure.core/the-ns (core.clj:4128)
CompilerException java.lang.ClassNotFoundException: clojure.tools.nrepl, compiling:(/private/var/folders/gk/ddnj_fdj49bfldn4zz73mj6w0000gn/T/form-init6348983630051496943.clj:1:82)
#object[clojure.lang.Namespace 0x22d4314b "user"]
Error loading namespace; falling back to user
nil
user=>
```

**Comment by erikthorselius** [comment]
I have the same problem and it looks like this is fixed on master. How far away is a release?

**Comment by technomancy** [comment]
I've listed all the candidates for 2.8.2 in a milestone: https://github.com/technomancy/leiningen/milestone/26 (not all of them will end up being in the release; everything in that list just needs further attention to determine whether or not they should be in the release)

I don't have an ETA but if you want to help track down some of those it would help get it out sooner.

**Comment by erikthorselius** [comment]
Thanks! I will have a look on the milestone place and see if anything is small enough for a newbie like me. 

And some kudos because I use lein a lot!

**Comment by kohr-h** [comment]
I'm using a `2.8.2-SNAPSHOT`` version from Git master (I've followed the instructions [here](https://github.com/technomancy/leiningen/blob/stable/CONTRIBUTING.md#bootstrapping), including the uberjaring part, hope I got them right). I get a similar but not exactly the same message:
```
$ lein repl
nREPL server started on port 36481 on host 127.0.0.1 - nrepl://127.0.0.1:36481
Exception No namespace: reply.eval-modes.nrepl found  clojure.core/the-ns (core.clj:4128)
REPL-y 0.4.1, nREPL 0.4.3
Clojure 1.9.0
OpenJDK 64-Bit Server VM 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

empty.core=>
```
Here's `lein -version`:
```
Leiningen 2.8.2-SNAPSHOT on Java 1.8.0_181 OpenJDK 64-Bit Server VM
```

**Comment by technomancy** [comment]
You're right; this still happens on master.
