### ISSUE TITLE
Unable to run lein on Ubuntu on ARMv8 machine 

### ISSUE THREAD

**Issue by abhi18av** [technomancy/leiningen#2467]
Hi @technomancy 

I installed `leiningen` using `apt install leiningen` in my `Ubuntu-18.04` server which is running on the `ARMv8` architecture.

I installed `java` using the following commands

```
# JAVA
add-apt-repository ppa:webupd8team/java
apt-get update
apt-get install oracle-java8-installer

# ENVIRONMENT 

JAVA_HOME="/usr/lib/jvm/java-8-oracle"

```

However, when I try to run `lein -version` it throws the following error 

```
root@cub:~# lein -version
/usr/bin/lein: line 125: /usr/lib/jvm/java-8-openjdk-arm64/bin/java: No such file or directory
```

I don't quite know what to do here, please help me out a bit :)

**Comment by winks** [comment]
first you should check if the jvm is correctly installed.
I'd suggest something like `find /usr/lib/jvm -type f -name java`  `find /usr -type f -name java` as the error clearly says it looks for a `java` binary but can't find one.

maybe even `which java` already tells you the correct path if `java -version` shows the correct jvm

**Comment by abhi18av** [comment]
Hi @winks ,

As I installed `oracle-jdk` for me it prints out the following 
```sh
root@cub:~# find /usr/lib/jvm -type f -name java
/usr/lib/jvm/java-8-oracle/jre/bin/java
/usr/lib/jvm/java-8-oracle/bin/java
```

And here's the output of other `find` snippet 
```sh
root@cub:~# find /usr -type f -name java
/usr/share/bash-completion/completions/java
/usr/lib/jvm/java-8-oracle/jre/bin/java
/usr/lib/jvm/java-8-oracle/bin/java
```

**Comment by winks** [comment]
I think lein *expects* your java binary in `/usr/lib/jvm/java-8-openjdk-arm64/bin/java` but it's actually in `/usr/lib/jvm/java-8-oracle/bin/java`

What I had overlooked yesterday is your `JAVA_HOME` line - you need to set that either per run or globally.

so to try it out:
```
export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
lein version
```

If you want to have that permanently you need to export that `export` line to your `~/.bashrc`, `~/.zshrc` or `~/.profile` depending on your shell and specific setup

**Comment by abhi18av** [comment]
Hmm, perfect!

Thanks @winks  :+1:

**Comment by tribbloid** [comment]
strange, why it doesn't work for me?

```
$ echo $JAVA_HOME 
/usr/lib/jvm/java-8-oracle
$ export JAVA_HOME="/usr/lib/jvm/java-8-oracle" | lein version

```

**Comment by winks** [comment]
@tribbloid 
Sorry, the above posts don't really make sense without context, also I wrote some wrong things (which weren't the OP's problem it seems)
a) you need `JAVA_CMD` and not `JAVA_HOME`
so, this should work:
```
$ export JAVA_CMD='/usr/lib/jvm/java-8-oracle/bin/java'
$ lein version
```
b) you either can use inline variables (valid for the current line) via
```
$ JAVA_CMD='/usr/lib/jvm/java-8-oracle/bin/java' lein version
$ echo $JAVA_CMD
# empty...
```
or you can export = make them available for the whole session, e.g.
```
$ export JAVA_CMD='/usr/lib/jvm/java-8-oracle/bin/java'
$ echo $JAVA_CMD
/usr/lib/jvm/java-8-oracle/bin/java
```

**Comment by abhi18av** [comment]
@winks , this is the permanent solution thanks 👍
