### ISSUE TITLE
Fix/Remove non-working link to installer for Windows from README

### ISSUE THREAD

**Issue by OyvindSabo** [technomancy/leiningen#2469]
The website to which http://leiningen-win-installer.djpowell.net/ links to, is no longer available. If there are no other Windows installers available, I suggest that the link be removed, but if there are other installers for Windows, it would be nice to link to those:)

**Comment by technomancy** [comment]
Thanks for the heads-up. I've removed the link and just pointed people to the batch file and powershell version since I don't know of any other options for Windows.
