### ISSUE TITLE
pom task ignores dependencies expressed in custom profiles

### ISSUE THREAD

**Issue by pmonks** [technomancy/leiningen#2473]
The pom task ignores dependencies that are expressed in custom profiles.

**Steps to reproduce:**
Given the following minimal `project.clj`:

```clojure
(defproject org.clojars.pmonks/pom-test "0.1.0-SNAPSHOT"
  :min-lein-version "2.8.1"
  :dependencies     [[org.clojure/clojure "1.9.0"]]
  :profiles         {:http {:dependencies [[clj-http "3.9.1"]]}})
```

The command `lein pom` should _not_ include the `clj-http` dependency in the emitted `pom.xml` file.  Leiningen does indeed do this correctly.

In contrast, the command `lein with-profile +http pom` _should_ include the `clj-http` dependency in the emitted `pom.xml`.  Leiningen does **not** do this correctly - that dependency is completely missing from `pom.xml`.

Note: what's strange is that dependencies expressed in a "well known" profile (such as `:dev`) _do_ get included in the generated `pom.xml` file, so the pom task does appear to perform partial profile merging.

**Comment by mrrodriguez** [comment]
Just an FYI here, I think that the `:leaky` metadata on a profile may work. However, I'm not sure if that is always what is expected in these types of tasks that seem to strip out non-leaky profiles by default (typically task that make final artifacts I believe).

**Comment by pmonks** [comment]
Thanks for the pointer @mrrodriguez - checking that now.

**Comment by pmonks** [comment]
Yep that worked - thanks for the tip!

I'll close this bug and if someone wants to mark it "invalid", I'd appreciate it!
