### ISSUE TITLE
Exceptions thrown in user namespace initialisation in Clojure 1.10.0-beta5 are missing full stack

### ISSUE THREAD

**Issue by danielcompton** [technomancy/leiningen#2476]
I was trying out Clojure 1.10.0-beta5 and found what seems to be a significant workflow regression with stack traces, at least with Leiningen.

### Context

I was refactoring some code and moving it from a server application into a library. I tried to run the tests and got this error:

```console
$ lein test
Exception in thread "main" java.lang.ExceptionInInitializerError
        at clojure.main.<clinit>(main.java:20)
Tests failed.
```

There is not a lot of information in this stack trace to debug what is going on. I downgraded my Clojure dependency to 1.9 and reran the tests and got this stack trace:

```console
$ lein test
Exception in thread "main" java.lang.ExceptionInInitializerError
        at clojure.main.<clinit>(main.java:20)
Caused by: java.io.FileNotFoundException: Could not locate myapp/api/postgres__init.class or myapp/api/postgres.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name., compiling:(myapp/api/system.clj:1:1)
   ... (stack elided by Daniel)
Caused by: java.io.FileNotFoundException: Could not locate myapp/api/postgres__init.class or myapp/api/postgres.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
   ... (stack elided by Daniel)
Tests failed.
```

You can see both stack traces at https://gist.github.com/danielcompton/f3130559c233e1d49cabdae4a599856b (slightly anonymised).

With the 1.9 stacktrace, I can see that there is a file (`maypp.api.postgres`) missing when trying to load a particular namespace (`myapp.api.system`). It looks like the new 1.10 changes to stack traces are only printing the first exception, and not any of the nested exception causes.

### Tracking down the issue

I tried this with lein 2.8.1 with no ~/.lein/profile.clj to make sure I didn't have anything interfering with the stack. I tried to make a similar error scenario on https://github.com/puredanger/demo-deps using the clj command line tool, and it gave me a full stack trace showing the problem.

After that, I realised that the issue **only** shows up when I have my `user` namespace included as the `:init-ns`, i.e.

```clj
:profiles {:dev
           {:source-paths ["dev"]
            :repl-options {:init-ns user}}
```

The `user` namespace is requiring `myapp.api.system` which is triggering the exception before Leiningen has finished loading the `user` namespace.

Adding this to `src/user.clj` to the demo-deps project also triggers the same problem:

```
(ns user
  (:require [missing.ns]))

(println "Loaded user")
```

It appears as if the issue is that the full stack is swallowed when exceptions are thrown during initialisation of the `user` namespace.

I'm not sure if there is anything Leiningen can/should do here to make the errors friendlier here, or if it is all upstream. I've posted this upstream as [CLJ-2427](https://dev.clojure.org/jira/browse/CLJ-2427), but I thought it could be useful to have this issue here as people (like myself) may falsely attribute it to Leiningen. Happy to close it if there's nothing that we'd like to about it here.

**Comment by danielcompton** [comment]
I think I'll close this for now, as it's really an upstream issue, but can reopen if 1.10 is released without a fix.

**Comment by technomancy** [comment]
Thanks for tracking this down. I think you're right that it needs to be fixed elsewhere, but it's good to have this noted for future reference.
