### ISSUE TITLE
jar created through uberjar cannot be executed by jexec

### ISSUE THREAD

**Issue by randomizedthinking** [technomancy/leiningen#2478]
I would like to use ran a jar file without `java -jar`. On the Debian I use,  `binfmt-support` is installed. 

> \> cat /proc/sys/fs/binfmt_misc/jar
> enabled
> interpreter /usr/bin/jexec
> flags:
> offset 0
> magic 504b0304

Support `sample-uberjar.jar` is the final output of `lein uberjar`. Any project would work. The symptoms I have are:

- jar can be executed by `java -jar sample-uberjar.jar`;
- yet `jexec` cannot execute the file. The error message is: `invalid file (bad magic number): Exec format error`.

A relevant post I found is at: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6401361. The evaluation of the bug states one possibilyt is: "0xcafe" tag is not set for the jar file. Not sure it is the case for the lein uberjar here.

**Comment by glts** [comment]
Researched this quickly: rtyley/bfg-repo-cleaner#279 has good info, this looks like it’s not a Leiningen issue. Also note that jexec may be going away: https://bugs.openjdk.java.net/browse/JDK-8176066.
