### ISSUE TITLE
lein repl does not respect Clojure version specified in :repl profile in ~/.lein/profiles.clj

### ISSUE THREAD

**Issue by vheuken** [technomancy/leiningen#2480]
**REPRO:**
1. Create a `~/.lein/profiles.clj` file with `{:repl {:dependencies [^:displace [org.clojure/clojure "1.10.0-beta5"]]}}`
2. Run `lein repl` outside of a project folder

**EXPECTED:**
The repl should use Clojure `1.10.0-beta5` 

**ACTUAL:**
The repl uses Clojure 1.8.0

**NOTES:**
This was found following the instructions in the docs: https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md#replacing-default-repl-dependencies

**Comment by seancorfield** [comment]
This worked back in 2.7.1.

**Comment by technomancy** [comment]
Thanks for bringing this to my attention. The docs are inaccurate.

This worked in version 2.7.1 due to a mistake that caused a major performance regression. Since that performance regression was fixed, it stopped working, but the docs weren't updated.

**Comment by vheuken** [comment]
Does this mean the ability to specify a Clojure version for the repl profile is no longer supported, or just that the method displayed in the docs is outdated?

**Comment by technomancy** [comment]
Running a repl outside a project gives you the same process that Leiningen runs in, which means it can't have the Clojure version changed.

Changing the version of Clojure requires running Leiningen in a project; that's what project.clj files are for.
