### ISSUE TITLE
lein uberwar fails to load repositories both from user profile and local repository

### ISSUE THREAD

**Issue by slowcod** [technomancy/leiningen#2483]
the same as in issue #2098 but for uberwar task. Removing the _maven.remote file made it work as expected.  Leiningen 2.8.1

**Comment by technomancy** [comment]
The `uberwar` task is not part of Leiningen but part of the `lein-ring` plugin; perhaps this should be tracked there?

**Comment by technomancy** [comment]
Going to close this out as it seems to be a problem with a 3rd-party plugin.
