### ISSUE TITLE
lein ancient generates: "An illegal reflective access operation has occurred" w/OpenJDK 11.0.1, Clojure 1.10.0-RC1 for lein 2.8.1

### ISSUE THREAD

**Issue by billrobertson42** [technomancy/leiningen#2484]
I noticed this when starting a new project today. I frequently just copy entries from old projects and then run `lein ancient` to figure out which versions I need to update.

The repl seems to start OK. I haven't gotten the opportunity to test to see if everything else works or not yet though.

    $ java -version
    openjdk version "11.0.1" 2018-10-16
    OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
    OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
    
    $ lein ancient
    WARNING: An illegal reflective access operation has occurred
    WARNING: Illegal reflective access by clojure.lang.Reflector (file:/Users/bill/.lein/self-installs/leiningen-2.8.1-standalone.jar) to method com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(java.io.Reader)
    WARNING: Please consider reporting this to the maintainers of clojure.lang.Reflector
    WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    WARNING: All illegal access operations will be denied in a future release
    all artifacts are up-to-date.
    
    $ cat project.clj 
    (defproject foo "0.1.0-SNAPSHOT"
      :dependencies [[org.clojure/clojure  "1.10.0-RC1"]
                     [info.sunng/ring-jetty9-adapter "0.12.2"]
                     [compojure "1.6.1"]
                     [cheshire "5.8.1"] 
                     [funcool/clojure.jdbc "0.8.0"]
                     [org.postgresql/postgresql "42.2.5"]
                     [org.flywaydb/flyway-core "5.2.1"]
                     [mount "0.1.14"]
                     ])

**Comment by danielcompton** [comment]
Does this happen when you are just running a lein repl? At first glance, it seems like it may be an issue in lein ancient?

**Comment by billrobertson42** [comment]
The repl is fine, and after reading your comment and thinking about it I
took a look at my ~/.lein/profiles.clj, and I realized that ancient is
actually a plugin and not part of leiningen itself.

I've been using it so long now, I guess I forgot that it was separate. Will
close this, and sorry for wasting your time.
