### ISSUE TITLE
Add more user help with the error "Unknown VCS detected for 'vcs assert-committed'"

### ISSUE THREAD

**Issue by danielcompton** [technomancy/leiningen#2485]
I created a Leiningen project in a subdirectory of a Git repository. When I tried to use `lein release` on it, I got this error:

```
 $ lein release
Unknown VCS detected for 'vcs assert-committed'
```

#2128 pointed me in the right direction, I needed to add a pointer in my `project.clj` up one level to where the Git root was (`:scm {:dir ".."}`). It could be good for Leiningen to print some notes about possible solutions when this error occurs, or possibly infer the correct Git repository and use it without needing the user to manually specify it?

I don't have a full understanding of all of the implications of those ideas though or how it would interact with other VCS's (although only Git is currently supported), so opening up an issue for discussion.

**Comment by technomancy** [comment]
I suspect 95% of the time (ignoring folks using an unsupported SCM) adding `:scm {:dir ".."}` is the correct fix, so suggesting that in the error message seems like a good idea.

**Comment by rhinoman** [comment]
Any way to just disable the vcs check?  Way more trouble than it's worth.

**Comment by danielcompton** [comment]
You can remove it from your release tasks, but I don't think silently ignoring and not tagging is what people would expect.
