### ISSUE TITLE
Running tests against jar file

### ISSUE THREAD

**Issue by doubleelbow** [technomancy/leiningen#2486]
I'd like to know if it's possible to run tests against built jar. I'm looking for a way to do something like

	$ lein jar
	$ lein test target/project.jar :integration-db
	$ lein test target/project.jar :integration-ws1

I believe this would improve the experience in CD process by removing the need to rebuild the project in test stage and actually testing the jar that is going to be deployed.

**Comment by technomancy** [comment]
This would be a good thing for a plugin to support. It's not something lein can do on its own.
