### ISSUE TITLE
lein.bat refers to non-existing folder in GitHub

### ISSUE THREAD

**Issue by lgnakano** [technomancy/leiningen#2487]
Hi:

I am trying to install Leiningen in Windows, but I get an error when lein.bat tries to access this file in github:

https://github.com/technomancy/leiningen/releases/download/2.8.1/leiningen-2.8.1-standalone.zip

I logged into github and I cannot see the releases folder.

How do I go about installing without having to build from source under Windows?

Thanks in advance,

--Luis Nakano.

**Comment by winks** [comment]
Hi,
this links works for me:
```
-2-(florian@parakeet ~/tmp) $ wget https://github.com/technomancy/leiningen/releases/download/2.8.1/leiningen-2.8.1-standalone.zip                                                                            
--2018-11-28 10:15:34--  https://github.com/technomancy/leiningen/releases/download/2.8.1/leiningen-2.8.1-standalone.zip
# snip
Length: 13541128 (13M) [application/octet-stream]
Saving to: ‘leiningen-2.8.1-standalone.zip’

leiningen-2.8.1-standalone.zip                         3%[===>                                                                                                                 ] 475.56K   161KB/s               ^C
```
I suspect there's a connection problem on your end, maybe to the underlying Amazon S3 bucket.

As for building it yourself, see https://github.com/technomancy/leiningen/blob/2.8.1/CONTRIBUTING.md#bootstrapping

**Comment by winks** [comment]
Small addendum: there is no `releases` folder, this is just the Github "Releases" feature, you find all the artifacts here: https://github.com/technomancy/leiningen/releases

**Comment by technomancy** [comment]
Strongly suspect this is a misunderstanding and not a bug; if there is an actual bug to discuss feel free to reopen.
