### ISSUE TITLE
Providing an option to lein repl to not compile

### ISSUE THREAD

**Issue by fhalde** [technomancy/leiningen#2488]
I'm trying to setup my clojure project in such a way that, whenever I do a `lein compile`, the compiled classes go in a directory named after the current git branch of the project

I keep switching between branches and it's really annoying to recompile everything again and again
What I've done as of now in my `profiles.clj` is

```clojure
{:user {:target-path #=(eval (str "target/" (clojure.string/trim-newline (slurp
                                                                          (str (System/getProperty "user.dir") "/.git/current-branch")))))
        :plugins  [[refactor-nrepl "2.4.0"]
                   [cider/cider-nrepl "0.18.0"]
                   [lein-pprint "1.1.1"]]
        :dependencies [[slamhound "1.3.1"]]}}
```

Just assume for a moment I do get the current branch somehow and I set the `:target-path` to `target/$CURRENT_BRANCH`

This helps me in isolating compiled classes of each branch

Now the issue is that when a git checkout happens, the files get modified which makes the `lein repl` to assume they have modified and therefore recompile them

Is there an option in lein repl to not compile and just use whatever was compiled?

**Comment by technomancy** [comment]
Yeah, try adding `:prep-tasks ^:replace []` to disable automatic compilation. You should be able to add this to the repl profile only if you want to keep the auto-compilation active for other tasks.

**Comment by fhalde** [comment]
@technomancy let me check this

**Comment by fhalde** [comment]
@technomancy thanks for the help but I've found a better alternative for my problem - `git worktree`
