### ISSUE TITLE
:pom-plugins allows only limited plugin configuration

### ISSUE THREAD

**Issue by dancek** [technomancy/leiningen#2489]
I'm trying to achieve the following XML structure in my pom.xml:

```
      <plugin>
        <groupId>com.google.appengine</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <version>1.9.68</version>
        <configuration>
          <project>foo</project>
          <version>bar</version>
        </configuration>
      </plugin>
```

I'd expect this config to work:

```
  :pom-plugins [[com.google.appengine/appengine-maven-plugin "1.9.68"
                 [:configuration
                  [:project "foo"]
                  [:version "bar"]]]])
```

But alas, the third parameter isn't included as is but mangled such that having two second-level children is impossible (AFAICT). See https://github.com/technomancy/leiningen/blob/master/src/leiningen/pom.clj#L255

I'd be glad to post a pull request that either

- includes vectors as-is (as I would have expected)
- includes lists as-is (doesn't break any existing configs and provides a workaround)
- adds a fourth parameter that is included as-is

Or something else, if none of these is applicable.

**Comment by technomancy** [comment]
Let's go with option 2; option 1 would be better but has the potential to break things. Happy to take a PR for this; thanks.
