### ISSUE TITLE
`lein repl` times out with no useful error message when using `clojure.java.shell/sh` in user.clj

### ISSUE THREAD

**Issue by teodorlu** [technomancy/leiningen#2490]
Hello!

I spent a lot of time debugging yesterday, and thought I'd report what I experienced.

## Steps to reproduce

1. Create a new project: `lein new sh-timeout`
2. Modify `src/user.clj` to the following:

    ```clojure
    (ns user
      (:require
       [clojure.java.shell :refer [sh]]))
    
    (sh "echo" "infinite timeout!")
    ```

2. Run `lein repl`

## Observed behavior

1. Wait for about a minute with no message
2. Observe `REPL server launch timed out.` printed to the REPL
3. Leiningen exits with code 1

## Expected behavior

- Repl launched
- or a related error message

## Self criticism

Running shell commands automatically when the REPL is launched can cause unexpected consequences.

**Comment by technomancy** [comment]
Unfortunately the automatic loading of `user.clj` is a feature controlled by Clojure, not something Leiningen can affect. The fact that `sh` blocks forever in this case is also a problem with Clojure itself. Putting any code that blocks forever in `user.clj` will cause this problem but it's unfortunately not something that can be fixed within Leiningen.

**Comment by teodorlu** [comment]
Thanks for the quick response. I can reproduce with `clj`, so this isn't just a problem for leiningen.
