### ISSUE TITLE
Respect nREPL configuration files

### ISSUE THREAD

**Issue by bbatsov** [technomancy/leiningen#2492]
nREPL introduced global and project-local config files in version 0.5. The details are here https://nrepl.xyz/nrepl/usage/server.html#_server_configuration

Ideally `lein repl` should honour them when it's spinning up a new server. I think they should be treated more or less the same way as the existing `repl-options` (which were the inspiration for this feature) - values supplied via `repl-options` should have the highest precedence, but if they are not present we can fallback to whatever is in the config files. The configuration is exposed by `nrepl.config` as a simple map.

**Comment by bbatsov** [comment]
On a related note - it's going to be really nice of `repl-options` included the ability to specify which nREPL transport to use. We're very close to shipping an EDN transport by default, and now there's also an official Transit transport (https://github.com/nrepl/fastlane), so we should make it easier for users to do `lein repl` with the transport for their choice. Not sure if you'd like a separate ticket about this, or it's fine to have this as a comment here.

**Comment by PEZ** [comment]
Totally for this. And also would want to be able to supply `repl-options` on the command line. For jack-in scenarios.

**Comment by technomancy** [comment]
Makes sense. I'll try to get this in the next release.

As this is currently the only thing blocking 2.8.2, the release will happen faster if I get a patch. =)

**Comment by bbatsov** [comment]
If there's no one else who can do it faster I can do it around the end of the week (Thursday+).

**Comment by bbatsov** [comment]
@technomancy I'm starting work on this today.
