### ISSUE TITLE
How to fix insecure repository warning?

### ISSUE THREAD

**Issue by Engelberg** [technomancy/leiningen#2498]
I found the following in the FAQ, but it doesn't really explain how to actually fix the problem.  I get this warning on Windows after "lein self-install" and then invoking "lein version".  So I can't figure out what bad repository it is trying to download from, since it seems to be something leiningen is doing itself when invoking its own jar to find out the version -- no project file is involved as far as I can tell.

```
Q: I got Tried to use insecure HTTP repository without TLS, what is that about?
A: This means your project was configured to download dependencies from a repository that does not use TLS encryption. This is very insecure and exposes you to trivially-executed man-in-the-middle attacks. In the rare event that you don't care about the security of the machines running your project or can ensure that the only http traffic is going out over a trusted network, you can re-enable support for unsafe repositories by putting this in your project.clj file:
```

**Comment by technomancy** [comment]
In Leiningen 2.8.1, the message will have the URL of the repository and the path of the artifact in the message; what does it say there? It's probably coming from your plugins defined in your user profile.

**Comment by Engelberg** [comment]
Thanks, yes, now I see the info in the error message.  So you are right that it came from my user profile plugins, specifically https://clojars.org/story included by plugin https://clojars.org/lein-story.  Since these are also on clojars, why would they be any less secure?  Is it because they are snapshots?  Thanks.

**Comment by technomancy** [comment]
> Since these are also on clojars, why would they be any less secure? Is it because they are snapshots? Thanks.

The dependencies can include references to the repositories that they
use so that those repos don't have to be declared at the top-level to be
able to resolve transitive dependencies.

My guess is that one of the dependencies of one of these plugins was
created with a very, very old version of Leiningen, and thus it includes
a reference to a pre-HTTPS Clojars URL.

**Comment by Engelberg** [comment]
That would make sense. It hasn't been updated in several years.
