### ISSUE TITLE
Unable to resolve symbol: -main in this context

### ISSUE THREAD

**Issue by sarevok-anchev** [technomancy/leiningen#2501]
```
$ lein new app testlein
Warning: implicit middleware found: cider-nrepl.plugin/middleware 
Please declare all middleware in :middleware as implicit loading is deprecated.
Generating a project called testlein based on the 'app' template.
```

```
 $ cd testlein && lein repl
Warning: implicit middleware found: cider-nrepl.plugin/middleware 
Please declare all middleware in :middleware as implicit loading is deprecated.
nREPL server started on port 44641 on host 127.0.0.1 - nrepl://127.0.0.1:44641
REPL-y 0.4.3, nREPL 0.5.3
Clojure 1.9.0
OpenJDK 64-Bit Server VM 1.8.0_151-b12
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (-main)

CompilerException java.lang.RuntimeException: Unable to resolve symbol: -main in this context, compiling:(/tmp/form-init6268095195951588992.clj:1:1) 
```

Leiningen 2.8.2 on Java 1.8.0_151 OpenJDK 64-Bit Server VM

Thoughts?

I've tried removing ~/.local/lib/clojure and ~/.m2 and then reinstalling clojure (https://download.clojure.org/install/linux-install-1.9.0.397.sh) and running "lein repl" again, but the result is the same.

The way I understand it this should clean up any potential issues the hardcore way.

**Comment by bbatsov** [comment]
Are you in the right namespace? Where is this `-main` defined?

**Comment by technomancy** [comment]
Yeah; this is a bug where the repl's init-ns assumes that if `:main` is provided that it's a fully-qualified symbol, not just a namespace name.

**Comment by sarevok-anchev** [comment]
Sorry but that doesn't mean anything to me. I'm very new to clojure. Not an easy journey so far..

Is it a bug with leiningen or something else? And how to work around it?

**Comment by technomancy** [comment]
No problem; I just fixed the bug on master but it's easy to work around anyway; just run `(in-ns 'testlein.main)` to change the namespace manually.

**Comment by sarevok-anchev** [comment]
Thanks for the feedback.

I'm really sorry if this is very basic stuff, still wrapping my head around the basics..

Before when using lein 2.7 (by accident, it was the one that sdk install leiningen happened to install) I am almost sure that just typing (-main) in the repl would execute the main function at src/$projectName/core.clj.

Due to another problem I'm experiencing (unrelated to lein) [https://github.com/venantius/vim-eastwood/issues/12] I've gone back and forth between lein 2.7 and 2.8, clojure 1.9 and 1.8 and wasted hours in the process (slow internet) re-downloading everything after nuking ~/.m2 to make sure it was really starting from scratch..

I'd like to keep lein 2.8.x and clojure 1.9 because they're more recent and thus averse to downgrading (and waiting 1h to download everything again).


This is to say, I tried the proposed solution, but unfortunately the "unable to resolve symbol: -main" error remains.

Also tried with 'testlein.core because I could swear it was .core and not .main before - but as with all this stuff, very likely I could be wrong.

```
user=> (in-ns 'testlein.main')
#namespace[testlein.main']
testlein.main'=> (-main)

CompilerException java.lang.RuntimeException: Unable to resolve symbol: -main in this context, compiling:(/tmp/form-init1646741637391875273.clj:1:1) 
testlein.main'=> (in-ns 'testlein.core')
#namespace[testlein.core']
testlein.core'=> (-main)
CompilerException java.lang.RuntimeException: Unable to resolve symbol: -main in this context, compiling:(/tmp/form-init1646741637391875273.clj:1:1) 

testlein.core'=> 
```

To conclude, how can I simply run the main function from the repl ? "lein run" works right, so it's something with the repl environment/setup for sure. But this is just the default code that lein new app $something generated, hence the confusion.

Thanks for helping out, really appreciated..

**Comment by bbatsov** [comment]
If you're main is in `my.main.ns` you have to do `(in-ns 'my.main.ns)` and then run `(-main)`. You're not using `in-ns` properly - note the second `'` you're adding.

**Comment by sarevok-anchev** [comment]
Ah, missed that. Nice catch.

The example below should then work?

```
user=> (in-ns 'testlein.main)
#namespace[testlein.main]
testlein.main=> (-main)
CompilerException java.lang.RuntimeException: Unable to resolve symbol: -main in this context, compiling:(/tmp/form-init2106939766514054514.clj:1:1) 

testlein.main=> (in-ns 'testlein.core)
#namespace[testlein.core]
testlein.core=> (-main)
CompilerException java.lang.RuntimeException: Unable to resolve symbol: -main in this context, compiling:(/tmp/form-init2106939766514054514.clj:1:1) 

testlein.core=> 
```

Not sure if it's normal but after running in-ns, basic stuff like (+ 1 1) stops working too:

```
testlein.core=> (+ 1 1)
CompilerException java.lang.RuntimeException: Unable to resolve symbol: + in this context, compiling:(/tmp/form-init7070434546078573680.clj:1:1) 
```

**Comment by bbatsov** [comment]
Where exactly is your main? How does the `testlein.core` ns look like?

**Comment by sarevok-anchev** [comment]
It's just the default code generated by lein new app.

Just made a new one:

```
$ lein new app basic
Warning: implicit middleware found: cider-nrepl.plugin/middleware 
Please declare all middleware in :middleware as implicit loading is deprecated.
Generating a project called basic based on the 'app' template.
```

```
$ cd basic/
```

```
$ lein repl
Warning: implicit middleware found: cider-nrepl.plugin/middleware 
Please declare all middleware in :middleware as implicit loading is deprecated.
nREPL server started on port 44535 on host 127.0.0.1 - nrepl://127.0.0.1:44535
REPL-y 0.4.3, nREPL 0.5.3
Clojure 1.9.0
OpenJDK 64-Bit Server VM 1.8.0_151-b12
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (-main)

CompilerException java.lang.RuntimeException: Unable to resolve symbol: -main in this context, compiling:(/tmp/form-init2450216435183637230.clj:1:1) 

user=> (in-ns 'basic.core)
#namespace[basic.core]
basic.core=> (-main)
CompilerException java.lang.RuntimeException: Unable to resolve symbol: -main in this context, compiling:(/tmp/form-init2450216435183637230.clj:1:1) 

basic.core=> (in-ns 'basic.main)
#namespace[basic.main]
basic.main=> (-main)
CompilerException java.lang.RuntimeException: Unable to resolve symbol: -main in this context, compiling:(/tmp/form-init2450216435183637230.clj:1:1) 

basic.main=> 

```
```

**Comment by technomancy** [comment]
My bad; you'd need to load the code before switching to the ns. `(require 'basic.main) (in-ns 'basic.main)`

**Comment by sarevok-anchev** [comment]
It works like this (replacing main above with 'core')

```
user=> (require 'basic.core) (in-ns 'basic.core)
nil
#namespace[basic.core]
basic.core=> (-main)
Hello, World!
nil
basic.core=> 
```

To make sure I understood, this was a bug and has been fixed in master?
