### ISSUE TITLE
Mention switching to nrepl/nrepl in 2.8.2+ changelog

### ISSUE THREAD

**Issue by darwin** [technomancy/leiningen#2514]
This could be breaking change for nREPL middleware and some plugins which rely on nREPL stuff.

**Comment by bbatsov** [comment]
I can do this and link there to the upgrade notes in a couple of days, unless someone beats me to it.

**Comment by bbatsov** [comment]
I’ll link here to the upgrade notes in case someone comes across this ticket https://nrepl.org/nrepl/installation.html#upgrading

I’ll also expand the notes a bit when I can. Generally recent versions of popular middleware and transports target the new package, so the upgrade path is trivial for end users.

**Comment by bbatsov** [comment]
I've also added some troubleshooting instructions to the manual https://nrepl.org/nrepl/troubleshooting.html
