### ISSUE TITLE
`lein test` fails with `FileNotFoundException` looking for a test clj file I had deleted

### ISSUE THREAD

**Issue by alyssackwan** [technomancy/leiningen#2516]
What is being cached? I `rm`'d a test clj file, but `lein test` is still looking for it. I tried both running `lein clean` and `rm -rf target/` and the problem persists. Nothing in my code refers to this deleted clj test file. How do I clear this out?

**Comment by alyssackwan** [comment]
OMG what terrible user error. Wrong symbol in ns declaration.

**Comment by technomancy** [comment]
To be clear, this is a bad error message in Clojure, not Leiningen, right?
