### ISSUE TITLE
Error: Could not find or load main class clojure.main

### ISSUE THREAD

**Issue by berry-thawson** [technomancy/leiningen#2517]
Hi, I am using ubuntu 16.04. 
I have installed lein using script.
`lein repl` works fine.
But while creating a new app using command `lein new app clojure-newb` and running `lein run`, it gives the following error:
> Error: Could not find or load main class clojure.main

**Comment by technomancy** [comment]
I can't reproduce this problem. Can you provide the `project.clj` for the project in question as well as the version number?

**Comment by berry-thawson** [comment]
Lein version:
> Leiningen 2.8.3 on Java 1.8.0_191 Java HotSpot(TM) 64-Bit Server VM
Can't attach the  `project.clj`, but it's contents are as follows:
`(defproject clojure-newb "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.9.0"]]
  :main ^:skip-aot clojure-newb.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})`

**Comment by technomancy** [comment]
So if that file in /opt does not exist, what files *do* exist?

**Comment by berry-thawson** [comment]
What do you mean by typing the "file" that does not exist? Which one are you mentioning about?
Will give exact file tree for ref:

> /opt/clojure-newb$ tree
.
├── CHANGELOG.md
├── doc
│   └── intro.md
├── LICENSE
├── project.clj
├── README.md
├── resources
├── src
│   └── clojure_newb
│       └── core.clj
├── target
│   └── default
│       ├── classes
│       │   └── META-INF
│       │       └── maven
│       │           └── clojure-newb
│       │               └── clojure-newb
│       │                   └── pom.properties
│       └── stale
│           └── leiningen.core.classpath.extract-native-dependencies
└── test
    └── clojure_newb
        └── core_test.clj

14 directories, 9 files

**Comment by technomancy** [comment]
It looks like you moved `core.clj` out of the `src/clojure_newb` directory?

**Comment by berry-thawson** [comment]
There seems to nothing wrong with file structure since,when correct path repl was able to load and run main function properly. Refer previous comment.

**Comment by technomancy** [comment]
The `Could not find or load main class clojure.main` error seems to indicate that it's not the `.clj` file itself but the dependency on Clojure which is wrong. Perhaps a corrupted jar got downloaded somehow. Try this: `rm -rf ~/.m2/repository/org/clojure/clojure`

**Comment by berry-thawson** [comment]
That results in this.

> /opt/hit$ rm -rf ~/.m2/repository/org/clojure/clojure
/opt/hit$ cd ../clojure-newb/
/opt/clojure-newb$ lein run
Retrieving org/clojure/clojure/1.9.0/clojure-1.9.0.pom from central
Retrieving org/clojure/clojure/1.9.0/clojure-1.9.0.jar from central
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Error: Could not find or load main class clojure.main

**Comment by berry-thawson** [comment]
That results in this.

> /opt/hit$ rm -rf ~/.m2/repository/org/clojure/clojure
/opt/hit$ cd ../clojure-newb/
/opt/clojure-newb$ lein run
Retrieving org/clojure/clojure/1.9.0/clojure-1.9.0.pom from central
Retrieving org/clojure/clojure/1.9.0/clojure-1.9.0.jar from central
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Error: Could not find or load main class clojure.main

**Comment by berry-thawson** [comment]
But yeah, even `lein repl` fails to run when inside project. Somehow project setup is messed up by default, but I'm not sure how.

**Comment by glts** [comment]
I also use Ubuntu (16.04, 18.04) and haven’t experienced this.

Does this problem still exist? Can you provide complete reproduction steps? It is not clear to me how to reproduce from the discussion above …

**Comment by technomancy** [comment]
Yeah, without steps to reproduce we can't do anything here.

**Comment by 0x00002152** [comment]
is this inactionable? 
```
lein help
Error: Could not find or load main class clojure.main
Caused by: java.lang.ClassNotFoundException: clojure.main
```

**Comment by technomancy** [comment]
Can't really say without more details but it looks like a problem with how Leiningen was installed or packaged.

**Comment by svitebskiy** [comment]
I am seeing this problem on Mac OS Catalina.
I am also getting this warning when running "lein uberjar" command in a project just created with "lein new app my-app":

`Warning: The Main-Class specified does not exist within the jar. It may not be executable as expected. A gen-class directive may be missing in the namespace which contains the main method, or the namespace has not been AOT-compiled.
`

**Comment by berry-thawson** [comment]
Sorry.
I did not reply because I gave up on clojure for some time following hiccups in setup. So, reply and closing of issue went over my radar. And I tried to give clojure another try and nothing has changed. 
`"Error could not find or load main class : clojure.main"`
Is there anything I can do to help myself and you?
I am willing to spend time but not sure how to debug the problem. Can somebody some hints at that?

**Comment by technomancy** [comment]
If you can share your project in a way that allows the problem to be reproduced on another machine, then maybe someone can debug. A minimal reproduction case would be best. Without a runnable example of the problem there's not really anything that can be done.

**Comment by berry-thawson** [comment]
No. I do not think this is problem with the project. I am just trying to begin using lein. 
`lein repl` normally works. But while trying to create `lein new app my-app` that is getting created too.
But while trying to run the generated project using `lein run`, it fails.
Let me know if there is anything else I can do to help you to help me. I am just a noob and I am trying to explore clojure and I am stuck. Thanks for helping me out.

**Comment by berry-thawson** [comment]
And English is not my first language. If something I am typing does not come out as clear or appropriate, I am sorry.

**Comment by glts** [comment]
@berry-thawson Please see here for instructions how to report bugs, as detailed information as possible:

https://github.com/technomancy/leiningen/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by berry-thawson** [comment]
Thanks @glts . I will check it and reply.

**Comment by berry-thawson** [comment]
### Debugging steps:

1. Try upgrading lein

```
$ lein upgrade
The script at /home/sivachalabathid/bin/lein will be upgraded to the latest stable version.
Do you want to continue [Y/n]? y

Upgrading...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   137  100   137    0     0    145      0 --:--:-- --:--:-- --:--:--   145
100 13541  100 13541    0     0   5049      0  0:00:02  0:00:02 --:--:--  9332
Leiningen is already up-to-date.
Leiningen 2.9.4 on Java 1.8.0_262 OpenJDK 64-Bit Server VM
```

Done.

2. Moving your ~/.lein/profiles.clj (if present) out of the way. 

```
$ ls ~/.lein/
self-installs
```

Not needed.

3. Updating projects.clj
The issue is with creating new projects. So, not relevant.

4. I am using JDK 8.

### Steps to reproduce the produce the problem:

1. Create new `app` project using lein.
```
~$ lein new app my_lein_app
Generating a project called my_lein_app based on the 'app' template.

~$ cd my_lein_app/

~/my_lein_app$ ls
CHANGELOG.md  doc  LICENSE  project.clj  README.md  resources  src  test

~/my_lein_app$ cat project.clj 
(defproject my_lein_app "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.1"]]
  :main ^:skip-aot my-lein-app.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all
                       :jvm-opts ["-Dclojure.compiler.direct-linking=true"]}})
```
Sweet. That worked.

2. Let's try to run it. It is supposed to print "Hello world", I guess.

```
~/my_lein_app$ lein run
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Error: Could not find or load main class clojure.main
```

Oh! Okay. Let's see if the repl works.

```
~/my_lein_app$ lein repl
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Error: Could not find or load main class clojure.main
Subprocess failed (exit code: 1)
REPL server launch timed out.
```

3. **Does `lein repl` outside project?**

```
~/my_lein_app$ cd ..
~$ lein repl
nREPL server started on port 35023 on host 127.0.0.1 - nrepl://127.0.0.1:35023
REPL-y 0.4.4, nREPL 0.7.0
Clojure 1.10.1
OpenJDK 64-Bit Server VM 1.8.0_262-b19
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=>
```

It does. Then clojure is not found while trying to use the project generated by `lein`, it seems.

### Now, the system details.
1. **lein version**
```
$ lein version
Leiningen 2.9.4 on Java 1.8.0_262 OpenJDK 64-Bit Server VM
```

2. **lein installation method** : manual

3. **Java version**
```
$ java -version
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (Zulu 8.48.0.51-CA-linux64) (build 1.8.0_262-b19)
OpenJDK 64-Bit Server VM (Zulu 8.48.0.51-CA-linux64) (build 25.262-b19, mixed mode)
```
4. **OS** : Ubuntu 16.04 LTS 64-bit

**Anything else relevant to the problem?**
Not sure. As I have already mentioned, I am just trying to explore clojure and lein is most popular option.
Happy to provide any details needed.

Have I worked on lein before in some other version?
No. All my work is on java 8. And, just trying to setup lein for first time.

Happy to any other details if needed. Thanks for the support.

**Comment by berry-thawson** [comment]
[my_lein_app.tar.gz](https://github.com/technomancy/leiningen/files/5196475/my_lein_app.tar.gz)

The generated app as tarball for reference.

**Comment by glts** [comment]
Thank you. Unfortunately I cannot reproduce this and have no idea what the problem could be. Is this an unusual JVM, I noticed the ‘Zulu’ in the version string?

**Comment by nihilismus** [comment]
I can execute the project inside `my_lein_app.tar.gz` without any issue with AdoptOpenJDK 11 and AdoptOpenJDK8. I see you are using Zulu OpenJDK 8.

You can debug `lein` (`/home/sivachalabathid/bin/lein`, the Bash script) by adding `set -x` just below its first line (`#!/usr/bin/env bash`):

```
#!/usr/bin/env bash
set -x
# Ensure this file is executable via `chmod a+x lein`, then place it
...
```

Then execute once again `lein run` inside the project (`~/my_lein_app`) and share its output here, maybe we can notice something.

**Comment by berry-thawson** [comment]
Hey. Finally a breakthrough. 
Debugging lein script helped. Finally a breakthrough.
I had this line in `.bashrc`:
`export JVM_OPTS="-cp $CLASSPATH $JAVA_OPTS"`

If I have this line in `.bashrc`, lein fails to `run` or `repl` **from lein project alone**. But, lein repl succeeds when trying to run it from elsewhere.

Just add this line `export JVM_OPTS="-cp $CLASSPATH $JAVA_OPTS"` to the beginning of the lein script to reproduce the error. I now at least have a workaround. I can unset the **JVM_OPTS** variable while running lein and it works like charm.

Thank you @technomancy, @glts and @nihilismus everyone in helping me out. Since, this is local env variable problem, I guess we can close the issue.

**Comment by berry-thawson** [comment]
@all Please confirm if the issue can be closed.

**Comment by technomancy** [comment]
OK, I think we're good here.
