### ISSUE TITLE
LEIN_FAST_TRAMPOLINE cache doesn't respect local profiles.clj

### ISSUE THREAD

**Issue by metametadata** [technomancy/leiningen#2519]
**Steps:**

* Create `~/.lein/profiles.clj`: `{:user {:aliases {"myrepl" ["trampoline" "repl"]}}}`

* In the terminal: `export LEIN_FAST_TRAMPOLINE=1`

* Navigate to the project folder: `cd ~/myproject`

* Just in case, clear the caches: `rm -rf target`

* Try the custom alias: `lein myrepl`. This starts the repl as expected.

* Now let's override global `profiles.clj` by creating a local `profiles.clj`: `echo '{:user {}}' > profiles.clj`

* And try the alias again: `lein myrepl`

**Expected:** command fails because no alias is defined in the local `profiles.clj`.

**Actual:** REPL is shown.

**Workaround:** clear the project caches:

    rm -rf target
    lein myrepl

It prints the expected message:

```
(WARNING: user-level profile defined in project files.)
'myrepl' is not a task. See 'lein help'.
```

**Comment by technomancy** [comment]
Yeah, this is an oversight. Happy to take a patch for it.

**Comment by saitouena** [comment]
I'm taking a look into this problem.

https://github.com/technomancy/leiningen/issues/2519#issue-395103504
> Create ~/.lein/profiles.clj: {:user {:aliases {"myrepl" ["trampoline" "repl"]}}}

In my environment, `lein trampoline repl` didn't work.
```
$ lein trampoline repl
ClassCastException java.lang.String cannot be cast to java.lang.Number
	nrepl.server/start-server/addr--1161 (server.clj:120)
	nrepl.server/start-server (server.clj:128)
	nrepl.server/start-server (server.clj:96)
	reply.eval-modes.nrepl/get-connection (nrepl.clj:158)
	reply.eval-modes.nrepl/get-connection (nrepl.clj:156)
	reply.eval-modes.nrepl/main (nrepl.clj:202)
	reply.eval-modes.nrepl/main (nrepl.clj:200)
	reply.main/launch-nrepl/fn--2327 (main.clj:79)
	clojure.core/with-redefs-fn (core.clj:7514)
	clojure.core/with-redefs-fn (core.clj:7498)
	reply.main/launch-nrepl (main.clj:78)
	reply.main/launch-nrepl (main.clj:72)
Bye for now!
```

I used `Leiningen 2.9.1 on Java 1.8.0_222 OpenJDK 64-Bit Server VM` and `Clojure 1.10.0`.

I reproduced this problem with `lein trampoline run -m clojure.main/main`.
