### ISSUE TITLE
.gitignore file does not get included into a template

### ISSUE THREAD

**Issue by Heliosmaster** [technomancy/leiningen#2522]
I created, some years ago, a template: https://github.com/Heliosmaster/reagent-ajax

It's deployed on Clojars, and works fine. I wanted to change some things around and, after implementing the changes locally, I tried to do `lein install`, which succeeded.

Trying to do `lein new reagent-ajax my-new-project`, now spits an error:

```Template resource 'leiningen/new/reagent_ajax/.gitignore' not found.```

But, as you can see from the repository, the `.gitignore` file is there. It used to work, iirc.

I'm on lein `2.8.3` on MacOS Mojave.

**Comment by Heliosmaster** [comment]
I was able to fix this problem by renaming the file to `gitignore` (without leading dot) and changing the code to ensure that such file gets written into a `.gitignore` file (with the dot).

Still, I think this is an erroneous behavior, unless it was done on purpose.

**Comment by technomancy** [comment]
Unfortunately I think this is an unintended consequence of this intended change: https://github.com/technomancy/leiningen/issues/59

Invisible files will not be included in the jar, so in a template it's up to the template code to read a non-invisible file and emit a visible file.
