### ISSUE TITLE
lein repl using Clojure 1.7 even though it's not on the result of lein classpath?

### ISSUE THREAD

**Issue by didibus** [technomancy/leiningen#2523]
I'm using lein-extend-cp to provide my class path to lein, as I use another tool to bring in dependencies.

When I run lein classpath, I see my expected classpath, and the only Clojure Jar on it is clojure-1.10.0.jar

Now if I run lein repl, somehow it starts with Clojure 1.7

Any idea why?

**Comment by technomancy** [comment]
Are you running the repl in a project or outside?

**Comment by didibus** [comment]
This was from a cider-jack-in. I should try with lein repl also to see.

Still, I'm pretty sure Cider doesn't inject 1.7, in fact, latest version warns me that it doesn't support Clojure 1.7 anymore.

**Comment by didibus** [comment]
Putting a managed-dependency on Clojure 1.10 works to fix it. But I don't want to have to specify the version in the project.clj file, as I'm already specifying it in my other tool that performs the dependency resolution.

**Comment by technomancy** [comment]
Sounds like that other tool has a bug in it I guess?

**Comment by bbatsov** [comment]
CIDER doesn’t inject any Clojure. This is likely caused by something else. As the injection is nothing but passing a few parameters to Leiningen you can easily examine the command invocation and run it in a shell yourself.

**Comment by didibus** [comment]
So it seems that if I run `lein repl` I do get Clojure 1.10, but if I run the command Cider runs: `~/bin/lein update-in :dependencies conj \[nrepl\ \"0.5.3\"\] -- update-in :plugins conj \[com.billpiel/sayid\ \"0.0.17\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.20.0\"\] -- repl` then I get Clojure 1.7

**Comment by bbatsov** [comment]
No idea. I’ll have to debug this, but this won’t happen soon. Clearly something goes wrong with the deps resolution, but we’ll have to inspect the dependency tree to figure out where exactly the problem is. @cichli Can you take a look into this?

**Comment by glts** [comment]
Do we have a reproducer for this? Else from the discussion I would conclude that this is not a Leiningen issue …?

**Comment by technomancy** [comment]
Yeah seems like a problem elsewhere.

**Comment by didibus** [comment]
The issue seems to be that the `sayid` and `refactor-nrepl` plugins that Cider injects don't have exclusions on Clojure. In my `project.clj`, I do not have a dependency on Clojure, it is being brought in on the classpath as a resource from `lein-extend-cp` plugin.

To solve this, I need to add an explicit dependency or managed-dependency on the Clojure version I want.

That said, I don't like that solution, because it isn't making it so that thew Clojure on my classpath is used, instead, it just brings in a similar versioned Clojure from Maven. I still end up with two Clojure on the classpath.

Now I thought adding: `:exclusions [org.clojure/clojure]` would have fixed it, but it seems that it doesn't work to exclude plugin dependencies. Any idea why?

Here's the lein deps :tree output:

```
lein update-in :dependencies conj \[nrepl\ \"0.6.0\"\] -- update-in :plugins conj \[com.billpiel/sayid\ \"0.0.17\"\] -- update-in :plugins conj \[refactor-nrepl\ \"2.5.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.22.0-beta8\"\] -- deps :tree
Warning: implicit hook found: lein-extend-cp.plugin/hooks 
Hooks are deprecated and will be removed in a future version.
Warning: Clojure is excluded, assuming an appropriate fork (Clojure 1.8 or later) is provided.
Warning: Clojure is excluded, assuming an appropriate fork (Clojure 1.8 or later) is provided.
Possibly confusing dependencies found:
[com.billpiel/sayid "0.0.17"] -> [org.clojure/clojure "1.7.0"]
 overrides
[refactor-nrepl "2.5.0-SNAPSHOT"] -> [nrepl "0.5.3"] -> [nrepl/bencode "1.0.0"] -> [org.clojure/clojure "1.8.0"]

Consider using these exclusions:
[refactor-nrepl "2.5.0-20190723.094516-2" :exclusions [org.clojure/clojure]]

 [cider/cider-nrepl "0.22.0-beta8"]
 [clojure-complete "0.2.5" :exclusions [[org.clojure/clojure]]]
 [com.billpiel/sayid "0.0.17"]
   [org.clojure/clojure "1.7.0"]
   [org.clojure/tools.namespace "0.2.11"]
   [org.clojure/tools.reader "1.3.0-alpha3"]
   [tamarin "0.1.2"]
 [nrepl "0.6.0" :exclusions [[org.clojure/clojure]]]
 [refactor-nrepl "2.5.0-20190723.094516-2"]
```

**Comment by bbatsov** [comment]
> The issue seems to be that the sayid and refactor-nrepl plugins that Cider injects don't have exclusions on Clojure.

Just to be clear - CIDER doesn't inject any plugins, the plugins hook themselves into CIDER's injection logic. If you don't really use/need those feel free to simply remove them.
