### ISSUE TITLE
How to correctly inject dependencies from the powershell cli.

### ISSUE THREAD

**Issue by mseddon** [technomancy/leiningen#2526]
I am trying to invoke `lein` 2.8 from Powershell (5.1.17134.407), and want to inject some dependencies.

Under un*x I'd say something like:

```lein update-in :dependencies conj \[nrepl\ \"0.5.3\"\] -- repl```

Trying under powershell:

```lein update-in :dependencies conj '[nrepl "0.5.3"]' -- repl```

throws:
```
java.lang.NumberFormatException: Invalid number: 0.5.3
 at clojure.lang.LispReader.readNumber (LispReader.java:330)
    clojure.lang.LispReader.read (LispReader.java:256)
    clojure.lang.LispReader.readDelimitedList (LispReader.java:1200)
    clojure.lang.LispReader$VectorReader.invoke (LispReader.java:1150)
    clojure.lang.LispReader.read (LispReader.java:263)
    clojure.lang.LispReader.read (LispReader.java:196)
    clojure.lang.LispReader.read (LispReader.java:185)
    clojure.lang.RT.readString (RT.java:1835)
    clojure.lang.RT.readString (RT.java:1830)
    clojure.core$read_string.invokeStatic (core.clj:3687)
    clojure.core$read_string.invoke (core.clj:3677)
    clojure.core$mapv$fn__6953.invoke (core.clj:6627)
    clojure.core.protocols$fn__6755.invokeStatic (protocols.clj:167)
    clojure.core.protocols/fn (protocols.clj:124)
    clojure.core.protocols$fn__6710$G__6705__6719.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invokeStatic (protocols.clj:31)
    clojure.core.protocols$fn__6738.invokeStatic (protocols.clj:75)
    clojure.core.protocols/fn (protocols.clj:75)
    clojure.core.protocols$fn__6684$G__6679__6697.invoke (protocols.clj:13)
    clojure.core$reduce.invokeStatic (core.clj:6545)
    clojure.core$mapv.invokeStatic (core.clj:6618)
    clojure.core$mapv.invoke (core.clj:6618)
    leiningen.update_in$parse_args.invokeStatic (update_in.clj:13)
```

And attempting:
```lein update-in :dependencies conj "[nrepl \`"0.5.3\`"]" -- repl```

Just prints the help banner.

**Comment by mseddon** [comment]
As an aside- I can use the `.bat` file with no problem, for some reason this occurs with the `ps1` script.

**Comment by 573** [comment]
Same here

**Comment by juergenhoetzel** [comment]
> And attempting:
> `` lein update-in :dependencies conj "[nrepl \`"0.5.3\`"]" -- repl ``
> 
> Just prints the help banner.

I encountered the same issue. You also have to quote the dashes:
```
lein.ps1 update-in :dependencies conj '[nrepl \"0.5.5\"]' '--' repl
```
The different semantics of argument handling (cmdlet vs external command) in  Powershell  has driven nuts many users 😡: 

[PowerShell stripping double quotes from command line arguments](https://stackoverflow.com/questions/6714165/powershell-stripping-double-quotes-from-command-line-arguments)

**Comment by 573** [comment]
@juergenhoetzel So true, hard to love powershell sometimes. With the quoted double dash now works for me! Thanks!

**Comment by winks** [comment]
If any of you have a suggestion where we could add this to the docs so that future users don't have the same problems - we'd gladly do. Either send a PR or just give me something to copy/paste and where it should land ;)

**Comment by rogererens** [comment]
This bit me, too!
Using the command
`lein new figwheel cljs-weather -- --reagent`
resulted in the core.cljs file having an empty :require form in the ns macro:
`
(ns cljs-weather.core
    (:require ))
`

whereas
`lein new figwheel cljs-weather '--' --reagent`
gave me the expected
`
(ns cljs-weather.core
    (:require [reagent.core :as reagent :refer [atom]]))
`

**Comment by mseddon** [comment]
Windows cmd vs ps syntax is quite a minefield! Unfortunately I think coming from unix in an era before powershell has cursed its cli syntax to be unnecessary opaque cross platform. To be honest I am surprised at the number of people running into the same issue. Would it be worthwhile changing the cli syntax to have fewer puzzlers for windows users as a breaking change in a major release?

**Comment by mseddon** [comment]
> If any of you have a suggestion where we could add this to the docs so that future users don't have the same problems - we'd gladly do. Either send a PR or just give me something to copy/paste and where it should land ;)

Sorry I missed that! I shall try and find it in the docs and the first place I look is probably where *I* think it would be :)

**Comment by fivejjs** [comment]
If only use repl in vscode, use bb (babashka) instead can solve the issue.

**Comment by mseddon** [comment]
> If only use repl in vscode, use bb (babashka) instead can solve the issue.

I already added it to Calva ;)

**Comment by technomancy** [comment]
I don't think there's much we can do here tbh; it's up to the users of the shell to understand its quirks. Happy to continue discussion if anyone has some actionable suggestions, but it doesn't look like there's anything to do here at present.
