### ISSUE TITLE
Could not locate clojure/tools/nrepl/server__init.class

### ISSUE THREAD

**Issue by truszko1** [technomancy/leiningen#2527]
Hello,

I am doing a brand new installation of leiningen on my Mac, but I can't get that up and running. Google search gave me nothing either. Perhaps someone can help me? I tried installing this with Brew and manually with a script, both resulted in the same issue. The issue happens when I try to run anything `lein`.

I installed lein just fine, but when I execute it, I get this:

```
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate clojure/tools/nrepl/server__init.class or clojure/tools/nrepl/server.clj on classpath., compiling:(cider/nrepl.clj:1:1)
 at clojure.lang.Compiler.load (Compiler.java:7391)
    clojure.lang.RT.loadResourceScript (RT.java:372)
    clojure.lang.RT.loadResourceScript (RT.java:363)
    clojure.lang.RT.load (RT.java:453)
    clojure.lang.RT.load (RT.java:419)
    clojure.core$load$fn__5677.invoke (core.clj:5893)
```

Any ideas why this would be exploding for nrepl?

macOS: "10.14.2"
java version: "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
lein location: "/usr/local/bin/lein"
lein version: "2.8.3"

**Comment by danielcompton** [comment]
@truszko1 can you give some more information about where you're running `lein`? Are you inside a leiningen project when running this? You say this is a brand new installation, just checking you don't have anything in `~/.lein/profiles.clj`?

**Comment by truszko1** [comment]
Curiously enough, here is the content of `~/.lein/profiles.clj`:

```
{:user {:plugins [[cider/cider-nrepl "0.8.1"]]}}
```

What does this file do? Should I delete this line? I don't think I created this file manually.

**Comment by truszko1** [comment]
Problem fixed.

If a plugin is needed for a successful test or a build run, `~/.lein/profiles.clj` the file is where plugins can be defined.  

I simply removed the file and everything works just fine. 

Thank you!
