### ISSUE TITLE
Compile test files before running all the tests

### ISSUE THREAD

**Issue by fhalde** [technomancy/leiningen#2529]
Is it possible to have a configuration that will compile all the test files before running the tests? I don't want my CI to fail at the very last moment when it figures out there was a compilation error

For now we manually go across all the test files and compile them (we have written a script), but I was thinking if lein profiles would help in any way

```
:test {:source-paths ["test"]
       :prep-tasks ["compile"]}}
```

would this help?

**Comment by fhalde** [comment]
do you see any caveats here?

**Comment by technomancy** [comment]
Leiningen will in fact compile all the tests before running any of them,
but it will not AOT-compile them by default.

> I don't want my CI to fail at the very last moment when it figures out there was a compilation error

This is already the way it works out of the box.

Maybe you can provide a bit more detail about the problem you're running into.

**Comment by fhalde** [comment]
@technomancy I guess the issue we faced was because of diff-tests plugin that we have in our CI which ignores certain tests based on the changes! diff-test intelligently decides what tests need to run depending on the changes made in the project. So I guess because of AOT, this will not get caught. It will get caught when a full test suite runs!

**Comment by technomancy** [comment]
I see; if your intent is to work around a problem in a 3rd-party tool then this makes sense. You might want to consider `check` instead of `compile` as this will cover everything in `:source-paths` and not produce any output to disk.
