### ISSUE TITLE
Can't compile quil with lein 2.9.0

### ISSUE THREAD

**Issue by anthonygalea** [technomancy/leiningen#2538]
**Context**
The [quil](https://github.com/quil/quil.git) library specifies `:aot [quil.helpers.applet-listener quil.applet]`.

**Expected behavior**
```sh
# with lein 2.8.3:
$ lein do clean, compile
Compiling quil.helpers.applet-listener
Compiling quil.applet
```

**Actual behavior**
```sh
# after upgrading to lein 2.9.0:
$ lein do clean, compile
Compiling quil.applet
java.lang.ClassNotFoundException: quil.helpers.AppletListener, compiling:(quil/applet.clj:256:22)
Exception in thread "main" java.lang.ClassNotFoundException: quil.helpers.AppletListener, compiling:(quil/applet.clj:256:22)
...
Caused by: java.lang.ClassNotFoundException: quil.helpers.AppletListener
```

Should the sort of namespaces introduced by [this commit](https://github.com/technomancy/leiningen/commit/76dbf7c3ce6f8ea79e4e20014fe757048ccf9c45) only occur for `:aot :all`? (as suggested [here](https://www.reddit.com/r/Clojure/comments/aplq3x/leiningen_29_released/egaayfp/))

**Comment by technomancy** [comment]
I think it can't be just in `:all` because there is also support for regex-based searching of the filesystem, but it definitely shouldn't be applied when the namespaces are listed explicitly. I'll see what I can do.

**Comment by anthonygalea** [comment]
```sh
╭─anthony@avalon ~/Desktop/quil/quil-master  ‹master›  9:46:04
╰─$ ../../leiningen/leiningen/bin/lein --version                                                   1 ↵
Leiningen 2.9.1-SNAPSHOT on Java 1.8.0_202 Java HotSpot(TM) 64-Bit Server VM
╭─anthony@avalon ~/Desktop/quil/quil-master  ‹master›  9:46:12
╰─$ ../../leiningen/leiningen/bin/lein do clean, compile
Compiling quil.helpers.applet-listener
Compiling quil.applet
```

thanks
