### ISSUE TITLE
lein codox breaks with 2.9.0

### ISSUE THREAD

**Issue by pastafari** [technomancy/leiningen#2539]
**Describe the bug**
Context: I wanted to make a minor documentation fix for reagent. I ran `lein codox` on the reagent project to generate docs. This breaks with Leiningen 2.9.0. 

I tried an Leiningen 2.8.3 just to be sure, and it works fine. 

I do not have anything in my profiles.clj as per the guidelines.

**To Reproduce**
1. brew install leiningen
2. git clone https://github.com/reagent-project/reagent.git
3. cd reagent
4. lein codox

**Actual behavior**
A huge [stack trace](https://gist.github.com/pastafari/11f760861a9b320e0d5284f9b03866ef) 

**Expected behavior**
lein codox should generate docs in the target/docs directory

**Link to sample project**
Please see project.clj from https://github.com/reagent-project/reagent.git

**Logs**
Please see https://gist.github.com/pastafari/11f760861a9b320e0d5284f9b03866ef

**Environment**
- Leiningen Version: 2.9.0
- Leiningen installation method: Homebrew
- JDK Version: 
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
- OS: macOS 10.12.6

**Additional context**
Add any other context you have about the problem here. Did this work previously on older versions of Leiningen, or older JDK's?

The exact same command works with leiningen 2.8.3

**Comment by cichli** [comment]
This is fixed in `[lein-codox "0.10.6"]` – see weavejester/codox#181.

**Comment by pastafari** [comment]
@cichli ugh, should've checked codox issues first! Closing this.
