### ISSUE TITLE
ZSH completion after `--` could be improved

### ISSUE THREAD

**Issue by magthe** [technomancy/leiningen#2542]
The command line completion for ZSH works really well, except for after `--`. For instance after typing

```
lein run --
```

it doesn't really make sense to limit completions to namespaces (current behaviour) at all, since everything after `--` will be passed to the `main` function of the program I'm writing and therefore can't really be handled by the leiningen completions at all. What I find at the moment is that I can't complete file names among those post-`--` options, which is rather irritating to be honest :smile:

**Comment by technomancy** [comment]
Sure; makes sense to me.
