### ISSUE TITLE
Latest version of Leiningen breaks Protobuff

### ISSUE THREAD

**Issue by chorin1** [technomancy/leiningen#2543]
**Describe the bug**
Latest version of Leiningen breaks protobuf plugin and produces error on commands: lein run / deps / clean

**To Reproduce**
_Bug is reproducible in Leiningen version  2.9.1
and not reproducible in Leiningen 2.8.1_

Protobuff installation:
```
brew install autoconf

wget from https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz <target-dir>
cd <target-dir>
gunzip protobuf-2.6.1.tar.gz
tar -xvf protobuf-2.6.1.tar
cd protobuf-2.6.1
./configure
make

once make finished - create symbolic link from the original src directory (including the built protoc exec) of protobuf to ~/.lein/cache/lein-protobuf/protobuf-2.6.1/src :

1) mkdir ~/.lein/cache/lein-protobuf/protobuf-2.6.1
2) ln -s <download_dir>/protobuf-2.6.1/src ~/.lein/cache/lein-protobuf/protobuf-2.6.1/.
```

Use protobuff in your project
`
:plugins [[lein-protobuf "0.4.3"]]
`

Then:
```
lein clean
lein deps
lein run
```
Each will reproduce the following error:
[lein2.9.1error.txt](https://github.com/technomancy/leiningen/files/2930419/lein2.9.1error.txt)
Installing older version (2.8.1) makes the bug go away.

Attached is a formula to install old version of lein:
[Leiningen.txt](https://github.com/technomancy/leiningen/files/2930430/Leiningen.txt)
Change file name to Leiningen.rb
`brew install --build-from-source ~/Path/Leiningen.rb`

**Environment**
- Leiningen Version: 2.9.1
- Leiningen installation method: Homebrew
- JDK Version: build 1.8.0_192-b12
- OS:  macOS 10.14.2

[https://github.com/ninjudd/lein-protobuf
](url)

**Comment by winks** [comment]
can reproduce on Debian, self-installed lein 2.8.1 vs 2.9.1 on
Java 1.8.0_191 OpenJDK 64-Bit Server VM

**Comment by technomancy** [comment]
Given that the only significant change in 2.9.x is the upgrade to Clojure 1.10.0, it is very likely that this is simply due to an incompatibility with the underlying libraries. There's nothing we can do from Leiningen to make this plugin 1.10.0-compatible, so we'll just have to wait for them to upgrade.

In the mean time, the lein-protoc plugin does not have this problem.
