### ISSUE TITLE
:init-ns user leads to stack trace on repl startup

### ISSUE THREAD

**Issue by noisesmith** [technomancy/leiningen#2549]
If init-ns is user, and there is no user.clj on classpath, there is a stacktrace on repl startup.

**To Reproduce**
Using leiningen .2.9.1, create a new project, start a repl and verify it has no errors. Amend the project.clj to have the following contents:
```
(defproject repro "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.0"]]
  :repl-options {:init-ns user})
```

**Actual behavior**
The repl errors and shows a stack trace, despite the user namespace being found and used on startup.

**Expected behavior**
I expect to be able to explicitly start up in the user ns, even if I don't have a user.clj / user.cljc

**Logs**
```
$ lein repl
#error {
 :cause Could not locate user__init.class, user.clj or user.cljc on classpath.
 :via
 [{:type java.io.FileNotFoundException
   :message Could not locate user__init.class, user.clj or user.cljc on classpath.
   :at [clojure.lang.RT load RT.java 466]}]
 :trace
 [[clojure.lang.RT load RT.java 466]
  [clojure.lang.RT load RT.java 428]
  [clojure.core$load$fn__6824 invoke core.clj 6126]
  [clojure.core$load invokeStatic core.clj 6125]
  [clojure.core$load doInvoke core.clj 6109]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.core$load_one invokeStatic core.clj 5908]
  [clojure.core$load_one invoke core.clj 5903]
```

**Environment**
- Leiningen Version: 2.9.1
- Leiningen installation method: manual
- JDK Version: 1.8.0_171-b11

**Comment by danielcompton** [comment]
This also happens in older versions of Leiningen (2.8.1), and older versions of Clojure (1.8.0). @noisesmith did this ever work for you, or is this a brand new issue?

**Comment by noisesmith** [comment]
I discovered this behavior when checking out a project at work. I assume my coworkers all worked around this by defining a `user.clj` file or ignoring the stack trace.

It seems like exempting user.clj from the load logic for init-ns would be a safe option (if it's found, we can rely on clojure loading it, if it's not found, it shouldn't be an error).

**Comment by noisesmith** [comment]
I am considering a PR for this - would this be the right place to add a conditional blacklisting user around require?
https://github.com/technomancy/leiningen/blob/master/src/leiningen/repl.clj#L158

**Comment by technomancy** [comment]
I suspect that won't work, because that `require` call is already in a try/catch, so if that were where it failed, it should already gracefully fall back to `user`, right? I can't tell where the failure is actually coming from here.

**Comment by noisesmith** [comment]
as far as I can tell this PR fixes the issue https://github.com/technomancy/leiningen/pull/2550

**Comment by glts** [comment]
So – the pull request was merged, this is fixed, isn’t it?

**Comment by noisesmith** [comment]
yes, I should have closed this issue, thanks for the reminder
