### ISSUE TITLE
What does this sentence mean in section "Checkout Dependencies" of doc/TUTORIAL?

### ISSUE THREAD

**Issue by kaznak** [technomancy/leiningen#2554]
Hello,

I'm now translating doc/TUTORIAL.md to [Japanese](https://github.com/kaznak/leiningen/blob/translate-tutorial-ja/doc/ja/TUTORIAL_ja.md).

While reading it, I did not understand a section titled ["Checkout Dependencies"](https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#checkout-dependencies).
What does the sentence that the section starts from mean?
That is "Sometimes it is necessary to develop two projects in parallel".

I guess it says that someone develops two or more projects simultaneously, the main one and its dependencies.
And this section says Leiningen can handle dependencies at a time with checkout directory.
Is this correct?

Thank you.

**Comment by technomancy** [comment]
> I guess it says that someone develops two or more projects simultaneously, the main one and its dependencies.
> And this section says Leiningen can handle dependencies at a time with checkout directory.
> Is this correct?

Yes, it means that developing simultaneously can be done without
requiring the tedious install process after every change is made.

**Comment by kaznak** [comment]
Thank you for answering. Now things are cleared.

It was a bit confusable for the first time I read.
This may be the same for some other people,
especially for no native people like me.
So I wrote a patch. I will send it as a pull request.

Thank you again.
