### ISSUE TITLE
leiningen.core.project/meta-merge works differently than clojure.core/merge with nils

### ISSUE THREAD

**Issue by ikitommi** [technomancy/leiningen#2556]
There is no way to remove values from (meta-)merged maps:

```clj
(require '[leiningen.core.project :as l])

(#'l/meta-merge {:a 1} {:a nil})
; => {:a 1}

(merge {:a 1} {:a nil})
; => {:a nil}
```

e.g. `nil` values should override existing values to enable effectively to remove values. Can't set `:replace` meta-data to `nil`... 

```clj
user=> (#'l/meta-merge {:a 1} {:a ^:replace nil})
Syntax error reading source at (REPL:1:41).
Metadata can only be applied to IMetas
```

**Environment**
- Leiningen Version: 2.9.0

**Additional context**

https://github.com/weavejester/meta-merge/issues/11

> It might be a better idea to try to get this behavior changed in Leiningen first. Or at least ask why profiles are merged in such a manner.

**Comment by technomancy** [comment]
At this point, nearly every change that fixes something in profile merge logic introduces an equal number of bugs elsewhere. I don't think it's a good idea to make further changes.
