### ISSUE TITLE
module-info.class erroneously propagated to uberjars

### ISSUE THREAD

**Issue by ghadishayban** [technomancy/leiningen#2562]
**Describe the bug**
Uberjars should not contain module-info.class from dependencies

**To Reproduce**
```clj
(defproject aproject "0.0.1"
  :dependencies     [[org.clojure/clojure "1.10.0"]
                     [javax.xml.bind/jaxb-api "2.3.0"]])

lein uberjar
```

**Actual behavior**
The standalone jar contains module-info.class, which marks it as a Java module
**Expected behavior**
A non-module jar should be produced
**Workaround**
Specify a `:uberjar-exclusions` 
**Environment**
lein 2.9.1
jdk 11 and 8

**Comment by danielcompton** [comment]
@ghadishayban is this `module-info.class` is coming from `java.xml.bind/jaxb-api` in your example? Do you know off-hand how other JVM build tools handle this? Are there other files we shouldn't copy as well?

**Comment by ghadishayban** [comment]
@danielcompton Any module jar fetched by maven would exhibit the same issue, jaxb-api is just the quickest way to reproduce the bug.

For modules this is the only problematic file that I know of, and it will always appear top-level.

(I discovered this while running jdeps on an uberjar, and it was yapping that you can't have unpackages classes like clj_tuple in module jars, and I thought, wait a minute, hold up, this isn't a module jar.  But sure enough, it looks like a module jar because of the module-info.class)

(Separately, you'll want to make sure that multi-release jars are merged properly. https://openjdk.java.net/jeps/238   All or MRJAR's business lives within META-INF/.  I didn't explicitly bang on this aspect, nor experience any errors with it)

**Comment by danielcompton** [comment]
> Any module jar fetched by maven would exhibit the same issue, jaxb-api is just the quickest way to reproduce the bug.

Yep, that's what I thought, was just double-checking that it was jaxb-api and not Clojure that was the culprit here.

**Comment by technomancy** [comment]
It sounds like this could be fixed by adding a default entry into the `:uberjar-exclusions` list, right?
