### ISSUE TITLE
Remove dependency on nrepl

### ISSUE THREAD

**Issue by PEZ** [technomancy/leiningen#2563]
The other day I got informed that I can't inject version `0.5.3` of `nrepl`, because there is a hard dependency on version `0.6.0` in place already. This then stops me from using certain versions of `piggieback`, which currently poses a problem for me.

I will fix those problems at my end, but wanted to hear if there is an interest in me cooking a PR that removes the hard dependency? I'm thinking it should be possible to spot if an `nrepl` dependency has been injected, and inject `0.6.0`, if not.

Cheers, and many thanks for Leiningen! ❤️

**Comment by bbatsov** [comment]
> The other day I got informed that I can't inject version 0.5.3 of nrepl, because there is a hard dependency on version 0.6.0 in place already. This then stops me from using certain versions of piggieback, which currently poses a problem for me.

So, the override doesn't work only when you're using an older version, right? It certainly works in the opposite direction. I wonder if there's some special handling associate with that. 

> I will fix those problems at my end, but wanted to hear if there is an interest in me cooking a PR that removes the hard dependency? I'm thinking it should be possible to spot if an nrepl dependency has been injected, and inject 0.6.0, if not.

Keep in mind that some of the related packages might not work properly with an older version properly (e.g. `reply`, `drawbridge`) in some cases. In practice `reply` is unlikely to be a problem, I'm just saying that downgrading packages might be problematic in certain cases.

**Comment by PEZ** [comment]
Yes, you are right. Maybe a better ”fix” would be to just warn about the
injection not happening...

I haven't tried injecting something newer than 0.6.0. Not brave enough! 😎

**Comment by technomancy** [comment]
Removing the default dependency on nrepl is not really on the table; there are existing ways to disable it with profiles and to override it. I don't think there's enough details in this description for this to really be actionable otherwise; is there a suggested course of action?

**Comment by bbatsov** [comment]
@technomancy I think the problem outlined by @PEZ has been resolved already (I mean he doesn't need to use 0.5.3 anymore).

**Comment by technomancy** [comment]
Aha, cool; thanks.
