### ISSUE TITLE
Leiningen with Clojure 1.10.0

### ISSUE THREAD

**Issue by JacksonZyy** [technomancy/leiningen#2566]
Now the recent stable version for Clojure is 1.10.0.
If so, is it the case that I only need to modify the dependence version for Clojure in the project.clj, then run the project as usual? Or leiningen can only work with 1.8.0 Clojure?
Thanks for helping!

**Comment by timvisher** [comment]
Leiningen should work with essentially any version of Clojure (maybe down to 1.3?), but Clojure 1.10 dropped support for JVM < 1.8. To bump the version of Clojure (which is best thought of as a library), you do simply edit the `project.clj` and leiningen will pull in the new dependencies.
