### ISSUE TITLE
pom.properties in jar includes timestamp

### ISSUE THREAD

**Issue by technomancy** [technomancy/leiningen#2571]
This prevents jars from being reproducible and should be removed.

It doesn't look like you can fix this with `java.util.Properties`; they always include the date: https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html

Will need to find another way to write these probably?

**Comment by avfonarev** [comment]
I could implement this one. Either the second line could be dropped from the output, or I could basically reimplement the serialisation logic of `java.util.Properties`. The latter is more tedious, but relies less on the implementation details. Which one do you prefer?

**Comment by danielcompton** [comment]
I’d probably look at just dropping the comment line, perhaps doing a regex to match the time stamp in case the format changes slightly. You’re dropping a comment line, so I wouldn’t be too worried about being tied to implementation details, but others might disagree?

**Comment by technomancy** [comment]
Yeah, I think a regex to remove this would be fine.

**Comment by avfonarev** [comment]
Ok, I'll submit a pull request shortly then.
