### ISSUE TITLE
Dependencies seems to be pulled twice

### ISSUE THREAD

**Issue by jacobemcken** [technomancy/leiningen#2585]
**Initial debugging steps**
Before creating a report, _especially_ around exceptions being thrown when running Leiningen, please check if the error still occurs after:

- [x] Updating to using the latest released version of Leiningen (`lein upgrade`).
- [x] Moving your `~/.lein/profiles.clj` (if present) out of the way. This contains third-party dependencies and plugins that can cause problems inside Leiningen.
- [x] Updating any old versions of plugins in your `project.clj`, especially if the problem is with a plugin not working. Old versions of plugins like nREPL and CIDER (as well as others) can cause problems with newer versions of Leiningen.
- [ ] (If you are using Java 9 or newer) **not relevant**.

**Describe the bug**
Dependencies seems to be pulled twice.

**To Reproduce**
1. Create new project with the following `project.clj`:
```clojure
(defproject test "1.0.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.10.0"]])
```
2. run `rm -rf ~/.m2` to force lein to pull dependencies from internet.
3. In project run `lein deps`
4. See output.

**Actual behavior**
All dependencies (except `pom.contrib-0.2.2`) seems to be pulled twice from the internet.

**Expected behavior**
That dependencies are only pulled once (or that `lein` doesn't wrongly give me the impression that it is being pulled twice).

**Link to sample project**
The above project file is enough, but I stumbled over this issue during setting up CircleCI on a public repo: https://circleci.com/gh/full-spectrum/neo4clj/4

**Logs**
```
Retrieving org/clojure/clojure/1.10.0/clojure-1.10.0.pom from central
Retrieving org/clojure/spec.alpha/0.2.176/spec.alpha-0.2.176.pom from central
Retrieving org/clojure/pom.contrib/0.2.2/pom.contrib-0.2.2.pom from central
Retrieving org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44.pom from central
Retrieving nrepl/nrepl/0.6.0/nrepl-0.6.0.pom from clojars
Retrieving clojure-complete/clojure-complete/0.2.5/clojure-complete-0.2.5.pom from clojars
Retrieving org/clojure/clojure/1.10.0/clojure-1.10.0.jar from central
Retrieving org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44.jar from central
Retrieving org/clojure/spec.alpha/0.2.176/spec.alpha-0.2.176.jar from central
Retrieving nrepl/nrepl/0.6.0/nrepl-0.6.0.jar from clojars
Retrieving clojure-complete/clojure-complete/0.2.5/clojure-complete-0.2.5.jar from clojars
```

**Environment**
- Leiningen Version: 2.9.1
- Leiningen installation method: manual (*Download the lein script from the stable branch*)
- JDK Version: `openjdk version "1.8.0_212"\n OpenJDK Runtime Environment (build 1.8.0_212-b04)\n OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)`
- OS: Fedora 30 Workstation

**Additional context**
I can't think of any.

**Comment by glts** [comment]
If you look veeery closely, you’ll notice that no line appears twice.

Leiningen (actually, the underlying Maven) usually downloads both POM files containing metadata (*.pom), and JAR files containing the Clojure or Java source/classes (*.jar).

This is simply a fact of life in the Maven ecosystem.

**Comment by jacobemcken** [comment]
That was easy :-)

I was checking names and version and central vs. clojars... I guess everything but the extension :roll_eyes: 

Thanks!
