### ISSUE TITLE
ClassNotFoundException in nrepl.core.user

### ISSUE THREAD

**Issue by agriffis** [technomancy/leiningen#2590]
**Initial debugging steps**
Before creating a report, _especially_ around exceptions being thrown when running Leiningen, please check if the error still occurs after:

- [x] Updating to using the latest released version of Leiningen (`lein upgrade`).
- [x] Moving your `~/.lein/profiles.clj` (if present) out of the way. This contains third-party dependencies and plugins that can cause problems inside Leiningen.
- [x] Updating any old versions of plugins in your `project.clj`, especially if the problem is with a plugin not working. Old versions of plugins like nREPL and CIDER (as well as others) can cause problems with newer versions of Leiningen.
- [x] (If you are using Java 9 or newer), updating your dependencies to their most recent versions. Recent JDK's have introduced changes which can break some Clojure libraries.

**Describe the bug**
Running `lein nrepl :connect 7888` on a fresh user account gives an error:

```
$ lein repl :connect 7888
Downloading Leiningen to /home/vagrant/.lein/self-installs/leiningen-2.9.1-standalone.jar now...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   618    0   618    0     0   1941      0 --:--:-- --:--:-- --:--:--  1943
100 13.9M  100 13.9M    0     0  5209k      0  0:00:02  0:00:02 --:--:-- 6205k
Connecting to nREPL at 127.0.0.1:7888
Syntax error (ClassNotFoundException) compiling at (user.clj:1:82).
nrepl.core
#object[clojure.lang.Namespace 0x2d3e67b8 "user"]
Error loading namespace; falling back to user
nil
user=>
```

**To Reproduce**
1. Run an nrepl on port 7888
2. Create a new user (e.g. vagrant user)
3. Run the command `lein repl :connect 7888`

**Actual behavior**
lein downloaded `leiningen-2.9.1-standalone.jar` and started the nrepl client, but there's an error.

**Expected behavior**
No error.

**Environment**
- Leiningen Version: Leiningen 2.9.1 on Java 1.8.0_212 OpenJDK 64-Bit Server VM
- Leiningen installation method: manual download to /usr/local/bin/
- JDK Version: openjdk version "1.8.0_212"
- OS: Ubuntu 16.04 in Vagrant VM

**Additional context**
Seems to have been introduced between 2.8.1 (was fine) and 2.9.1 (recent upgrade)

**Comment by agriffis** [comment]
In fact, if I just change bin/lein to use `LEIN_VERSION="2.8.1"` (since I still have the jar around) it works without the error.

**Comment by agriffis** [comment]
A little more checking, it seems that the error first appears in 2.8.2

**Comment by glts** [comment]
@agriffis I haven’t tried reproducing yet, just looking at the error message: are you running this inside a project? Do you perhaps have a `user.clj` file containing a reference to `nrepl.core` somewhere on your classpath?

**Comment by agriffis** [comment]
I'm running in a completely fresh account in vagrant...

```
vagrant@vagrant:~$ find
.
./.bashrc
./.bash_logout
./.bash_profile
./.bash_history
./.profile
./.viminfo
./.aliases
./.ssh
./.ssh/authorized_keys

vagrant@vagrant:~$ env
XDG_SESSION_ID=338
TERM=tmux-256color
SHELL=/bin/bash
SSH_CLIENT=192.168.121.1 51262 22
SSH_TTY=/dev/pts/2
USER=vagrant
MAIL=/var/mail/vagrant
PATH=/home/vagrant/bin:/home/vagrant/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LC_COLLATE=C
PWD=/home/vagrant
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/vagrant
LANGUAGE=en_US:
LOGNAME=vagrant
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
SSH_CONNECTION=192.168.121.1 51262 192.168.121.115 22
XDG_RUNTIME_DIR=/run/user/1000
_=/usr/bin/env

vagrant@vagrant:~$ lein repl :connect 7888
Downloading Leiningen to /home/vagrant/.lein/self-installs/leiningen-2.9.1-standalone.jar now...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   618    0   618    0     0   1716      0 --:--:-- --:--:-- --:--:--  1721
100 13.9M  100 13.9M    0     0  5476k      0  0:00:02  0:00:02 --:--:-- 7519k
Connecting to nREPL at 127.0.0.1:7888
Syntax error (ClassNotFoundException) compiling at (user.clj:1:82).
nrepl.core
#object[clojure.lang.Namespace 0x115834c8 "user"]
Error loading namespace; falling back to user
nil
user=> 
```

It's possible the problem is somehow coming from inside the nrepl server I'm connecting to. It's just strange that it would appear on leiningen 2.9.1 but not on 2.8.1 which I was running previously.

**Comment by agriffis** [comment]
I just updated my project from the old nrepl 0.2.13 (`clojure.tools.nrepl.*`) to 0.6.0 (`nrepl.*`) and the problem went away.

So I'm probably all set, but I'm not sure how you'd like to handle it for leiningen. It seems like there's a bug connecting to older projects, but the bug might be in nrepl, not leiningen.

**Comment by glts** [comment]
@agriffis Well, in 2.8.2 nREPL was upgraded; they made the breaking change of renaming all namespaces from `clojure.tools.nrepl.*` to `nrepl.*`. This is flagged as a breaking change in the Leiningen changelog, but yes, it is unfortunate …

**Comment by agriffis** [comment]
Since updating the server makes this problem go away, I'll close the issue
