### ISSUE TITLE
Clearer documentation about activating and deactivating profiles 

### ISSUE THREAD

**Issue by PEZ** [technomancy/leiningen#2598]
In the documentation, the section about activating and deactivating profiles, `with-profile`:

https://github.com/technomancy/leiningen/blob/stable/doc/PROFILES.md#activating-profiles

It is mentioned how to activate several profiles, separating them with comma. It is also mentioned how to control wether the profiles replace the base profiles or not, prepending with a `+` for adding profiles (and w/o the `+` for replacing it in).

What is a bit unclear is weather this `+` affects all profiles in a comma-separated list, or if it should be prepended on a profile by profile basis.

Considering that we also can deactivate profiles by prepedning a `-`, this can get interesting. It would be clarified by an example specifying several profiles, and using all the variants, so for instance, would this command line make sense?

```sh
$ lein with-profile -repl,+dev,user repl
```

And what should I expect it to do?

**Comment by glts** [comment]
Have you tried it? This is what I see:

    $ lein with-profile -repl,+dev,user repl
    Profiles in with-profile must either all be qualified, or none qualified

**Comment by PEZ** [comment]
No, I didn't try that one. So that wasn't even a valid command line... I think the docs should clear this up some, (which is what this issue is about, but anyway :smile: ).

**Comment by technomancy** [comment]
Clarified this in 57ec15c.
