### ISSUE TITLE
How about a hosted repl?

### ISSUE THREAD

**Issue by 573** [technomancy/leiningen#2599]
I use lein repl for all my beginner tasks in learning clojure.
Thanks for the great tool.
Now my question is: Would it be hard to implement some kind of hosted lein repl to actually run in a browser.
Sorry for the pun but all I have so far is a name: **onlein**.

**Comment by technomancy** [comment]
Leiningen is a project automation tool, so running a repl in the browser outside the context of a project doesn't really make a lot of sense. I think there are a few other projects that do have in-browser repls. Nice pun though. =)
