### ISSUE TITLE
Support project.cljc?

### ISSUE THREAD

**Issue by dijonkitchen** [technomancy/leiningen#2607]
Seems like .cljc files work everywhere else, why not the project configuration too?

**Comment by technomancy** [comment]
Think about why .cljc files are supported elsewhere. Does that rationale apply to project.clj?

**Comment by dijonkitchen** [comment]
Yeah, the [reader conditionals](https://clojure.org/guides/reader_conditionals) allow us to do different things on different hosts, but I figured if there were no reader conditionals, a `project.cljc` file would work just like a `project.clj` file. Guess leiningen doesn't want to mislead users, so it only accepts the .clj version. Thanks!
