### ISSUE TITLE
High CPU usage when use `lein repl`

### ISSUE THREAD

**Issue by wangsong93** [technomancy/leiningen#2609]
Do nothing just start `lein repl` will consume 100%+ CPU usage.
Like this:
   PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                             
154113 work      20   0 7551m 2.1g  12m S 111.2 13.4  12:06.42 java     

Leiningen Version:  Leiningen 2.8.3 on Java 1.8.0_202 OpenJDK 64-Bit Server VM
Leiningen installation method: Downing lein shellscript
OS: CentOS release 6.3 (Final)  2.6.32-279.23.1.mi5.el6.x86_64

**Comment by saitouena** [comment]
@wangsong93 Are you trying `lein repl` in a leiningen project directry or not?

**Comment by wangsong93** [comment]
@saitouena Not in a project dir. The current dir has no project.clj

**Comment by glts** [comment]
@wangsong93 Could be this from 2.9.0:

> Re-enable bootclasspath optimization by default.

Can you try again with Leiningen 2.9.1?

**Comment by wangsong93** [comment]
@glts I have tried Lein2.9.1, it works. Thanks.
