### ISSUE TITLE
`lein new template` can't render picture correctly

### ISSUE THREAD

**Issue by kangbb** [technomancy/leiningen#2610]
**Initial debugging steps**
- Use `templates` functionalities in leingen to write a template
- Run `lein new my-template my-project` to create a project

**Describe the bug**
Every thing is ok, but can't render picture files (such as `.png`) correctly. The file is munged, even if you can't view them with other scanner tools.

**Comment by glts** [comment]
You shouldn’t be rendering binary files. Try the `raw-resourcer` function instead of `renderer` for PNG files: https://github.com/technomancy/leiningen/blob/2.9.1/src/leiningen/new/templates.clj#L148-L158

**Comment by kangbb** [comment]
> You shouldn’t be rendering binary files. Try the `raw-resourcer` function instead of `renderer` for PNG files: https://github.com/technomancy/leiningen/blob/2.9.1/src/leiningen/new/templates.clj#L148-L158

Thank you, it's a good resolution.
