### ISSUE TITLE
Support JDK 11 or (later)

### ISSUE THREAD

**Issue by tranpeter** [technomancy/leiningen#2612]
Has anyone looked at supporting JDK 11 or higher?

**Comment by glts** [comment]
Leiningen supports JDK 11+ as far as I know, people are already using it. Is it not working for you?

**Comment by sgerrand** [comment]
Please also note that I added tests against a matrix of OpenJDK versions in #2652.

**Comment by glts** [comment]
With many people using JDK 11+ and CI covering versions 11, 13, 14, I think this question is now resolved.
