### ISSUE TITLE
SHA1 mismatch. Looks like SHA256 checksum is used for SHA1?

### ISSUE THREAD

**Issue by delreluca** [technomancy/leiningen#2613]
**Initial debugging steps**
I am a total Clojure beginner but I get an error already when trying to `lein new`.

**Describe the bug**
Can't install leiningen because of SHA1 mismatch

**To Reproduce**
1. Download lein script from https://github.com/technomancy/leiningen/blob/cf3d9540d01bd208447cbae345babaebdcf5701d/bin/lein
2. Run the command 'lein new xxx'
3. See output below under logs

**Actual behavior**
Checksum not matching. See log below

**Expected behavior**
No checksum problem

**Logs**
```console
MacBook-Air:clj xxx$ lein new xxx
Downloading Leiningen to /Users/xxx/.lein/self-installs/leiningen-2.9.1-standalone.jar now...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   618    0   618    0     0    982      0 --:--:-- --:--:-- --:--:--   984
100 13.9M  100 13.9M    0     0   573k      0  0:00:24  0:00:24 --:--:--  776k
shasum: /Users/xxx/.lein/self-installs/leiningen-2.9.1-standalone.jar.pending.shasum: no properly formatted SHA1 checksum lines found
Failed to properly download https://github.com/technomancy/leiningen/releases/download/2.9.1/leiningen-2.9.1-standalone.zip
The checksum was mismatched. and we could not verify the downloaded
file. We expected a sha256 of
ea7c831a4f5c38b6fc3926c6ad32d1d4b9b91bf830a715ecff5a70a18bda55f8 and actually had
5f5bb6812500ffdf7e403715919c1b38a60bd970098138c374d36839e689f237.
MacBook-Air:clj xxx$ tail ~/.lein/self-installs/leiningen-2.9.1-standalone.jar.pending.shasum 
ea7c831a4f5c38b6fc3926c6ad32d1d4b9b91bf830a715ecff5a70a18bda55f8 /Users/xxx/.lein/self-installs/leiningen-2.9.1-standalone.jar.pending
```

**Environment**
- Leiningen Version: trying to install 2.9.1
- Leiningen installation method: manual (from https://github.com/technomancy/leiningen/blob/cf3d9540d01bd208447cbae345babaebdcf5701d/bin/lein)
- JDK Version: openjdk 12.0.2 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode, sharing)
- OS: macOS 10.14.6

**Comment by glts** [comment]
This is not a supported installation procedure as far as I know.

Try the instructions at leiningen.org, these should work: https://leiningen.org/#install

**Comment by technomancy** [comment]
Yeah, it's not a good expectation that a random sha from the master branch should work. Please use the stable branch.

**Comment by delreluca** [comment]
Thanks for pointing out my mistake. I somehow was browsing in between reading the steps and then got it from master instead of stable because I had the tab open.
