### ISSUE TITLE
Add support for REBL

### ISSUE THREAD

**Issue by didibus** [technomancy/leiningen#2618]
I'm trying to figure out a way to setup REBL with lein, but it is proving difficult, and non portable. It would be nice if you could somehow add to the `:user` profile the REBL jar from a local folder so that it is included in the classpath of every task which runs with the :user profile.

I have this currently:

```
{:user {:resource-paths [#=(eval
                            (let
                                [project-path
                                 (java.nio.file.Paths/get (.toURI (clojure.java.io/file (System/getProperty "user.dir"))))
                                 user-home-path
                                 (java.nio.file.Paths/get (.toURI (clojure.java.io/file (System/getProperty "user.home") "bin")))
                                 project-relative-path
                                 (.relativize project-path user-home-path)]
                              (str project-relative-path)))]}}
```

But when I start a `lein repl`, it doesn't seem to work, even though it is properly addingthe relative path to the Jar to resource-paths. I suspect resource-paths does not work when only having a .lein/profiles.clj or some such. Which means it doesn't seem there is a straightforward way to do this portably.

By portably, I mean so that my private home git repo can have both my `.lein/profiles.clj` and the REBL jar in `~/bin` in a way that by just checking it out into a home dir, I have lein automatically setup with REBL.

Thank You

**Comment by technomancy** [comment]
My understanding is that this is not licensed as free software; because of that, Leiningen will not support it, sorry.
