### ISSUE TITLE
set project version in CI environment

### ISSUE THREAD

**Issue by jinwg** [technomancy/leiningen#2622]
is it possible to pass a version variable into project instead the hard coded the version in project.clj?  it will be nice to avoid the version bump commit especially in CI environment.

**Comment by glts** [comment]
Well, you can put Clojure code in `project.clj`:

```clojure
(def my-version (or (System/getenv "MY_VERSION") "develop-SNAPSHOT"))

(defproject my-project my-version
  ,,,
  )
```

I do not know how advisable this is or if it is supported, but looks like it works.

**Comment by technomancy** [comment]
Yep; we do this at work and it doesn't cause any trouble.
