### ISSUE TITLE
Include exit code in the "Subprocess falied" error message

### ISSUE THREAD

**Issue by miikka** [technomancy/leiningen#2632]
It'd be handy if the "Subprocess failed" error message included the subprocess exit status.

My use case: I'm having problems with building uberjars on a CI server and my logs look this:

```
$ lein uberjar
Compiling backend.main
Compilation failed: Subprocess failed
```
Probably the problem is that Leiningen gets killed by the Linux OOM killer, but it's hard to confirm it from the logs. If the exit code was included, that would help, because OOM killer results in exit code 137.

**Comment by glts** [comment]
Fixed in #2633.
