### ISSUE TITLE
Clarify recommended usage of :test profile

### ISSUE THREAD

**Issue by vemv** [technomancy/leiningen#2636]
https://github.com/technomancy/leiningen/blob/fbb44ffc2b860761d54c1abcd8b2c9c740837aeb/doc/PROFILES.md#task-specific-profiles advises against putting things in the `:test` profile "as it can result in tests which can't be run from the repl".

However:

* one can `lein with-profile +test repl` for development purposes
  * at my workplace different people is doing this, successfullly, using a variety of IDEs/editors/terminals
* Cramming test things into the `:dev` profile complects dev and test concerns
  * e.g. running my test build in CI will be forced to load/run dev setup, which may be an obstacle, or make the test suite less clean or reliable.

Would it be possible to refine the advise?

I'd suggest one of:

* Stop advising against :test, point out that `+test` is a thing
* Keep advising against :test, but suggest instead a similarly-named profile, e.g. `:my-app/test`

And maybe:

* be specific about the actual risks that the advise aims to prevent. `can result` is otherwise ambiguous

WDYT?

Thanks - V

**Comment by technomancy** [comment]
> * Cramming test things into the `:dev` profile complects dev and test concerns

I disagree; testing is a thing you do during development; ideally one of
the main things you do.

> * e.g. running my test build in CI will be forced to load/run dev
> setup, which may be an obstacle, or make the test suite less clean or
> reliable.

If you have a separate suite of tests you only run in CI, then you
should create a separate :ci profile rather than using the :test
one. Because then that profile is not about testing, but about a certain
kind of testing you do in one specific environment.

**Comment by vemv** [comment]
> I disagree; testing is a thing you do during development; ideally one of
the main things you do.

Sure thing, I advocate that as well and adding `+test` while developing is all I need for that to happen.

> If you have a separate suite of tests you only run in CI, then you
should create a separate :ci profile rather than using the :test
one. Because then that profile is not about testing, but about a certain
kind of testing you do in one specific environment.

I don't really have a CI-only additional test suite. Instead I aim to run the same test suite in a lean, reliable manner.

Using an specific example: let's say I need to add the `[nubank/matcher-combinators "1.2.5"]` dep, which I only intend to use within test namespaces.

* if I add it in project.clj `:dev`, the CI runner will be forced to load all dev niceties as well
  * Slower / more bloated runtime
* if I add it in project.clj `:ci`, I will also have to add the `:ci` profile while developing (for repl-testing), which might bring CI-related stuff to the development workflow
  * extra deps, or constraints, runtime checks, etc.

So, `:test` seems a middle ground between the two problematic setups mentioned above:

* One can develop with `+test`
* One can run CI with `-dev,+test,+ci`
* Development remains isolated from CI and vice versa

If you are curious, [here](https://github.com/nedap/speced.def/blob/9f634e9409051369817b53b2a4605ef4cc273a65/project.clj) is a real setup that uses :dev, :test and :ci, those profiles being composed later.

The profiles seem to map well to their intent (:dev only contains dev tooling, :test only contains stuff needed for the test suite, :ci only contains things that are exclusively run in CI).

**Comment by technomancy** [comment]
It's fine that you found a way that works for you even though it's not what's recommended in the docs. However, if I change the recommendation in the docs, that means that *I* am on the hook for all the confused users.

There are hundreds of tutorials out there for getting started with Clojure, and many of them assume that you can run your tests after launching `lein repl`. Even if there were really good reasons to require the test profile (which I don't believe there are), it wouldn't be worth making a change with such widespread breaking consequences; those external tutorials are not going to get updated.

**Comment by vemv** [comment]
Hi @technomancy thanks for the reply and sorry for the delay.

The intent of my issue was not to get everyone (or anyone) to follow my preferred techniques. Rather, I sought the documentation to not "strongly advise against" these techniques, particularly in a way that doesn't hint why.

Else it's plausible that eventually some could say "hey @vemv your project is non-standard and flawed etc etc" when it is not, AFAICT.

I could give a shot to rewording that section in such a way that doesn't really change the suggested way, but also doesn't forbid other clean ways. WDYT?

**Comment by technomancy** [comment]
That seems fine, as long as the suggestion remains to ensure that tests work in the default lein repl.
