### ISSUE TITLE
lein search fails with java.io.IOException

### ISSUE THREAD

**Issue by anentropic** [technomancy/leiningen#2637]
```
$ lein search quil
Searching central ...
Searching clojars ...
Could not retrieve search results from https://clojars.org/search?format=xml&q=quil because of java.io.IOException
```

If I paste that url into a web browser I see:
```xml
<error message="Invalid search syntax for query `quil`" id="5fc45c32-4fa0-426b-82d1-45d74d35a97c"/>
```

If I remove the `format=xml&` part from the url then I can get results in a web browser
If I replace it with `format=json&` I can get results in a web browser

I have:
```
$ lein version
Leiningen 2.9.1 on Java 1.8.0_181 Java HotSpot(TM) 64-Bit Server VM
```
installed via homebrew

**Comment by anentropic** [comment]
I should add that I am a total newcomer to Clojure

I have literally just
```
brew install clojure
brew install leiningen
lein new app myapp
lein search ...
```

**Comment by anentropic** [comment]
well this is bizarre

A search for different text works:
https://clojars.org/search?q=incanter&format=xml

it is only the term `quil` that seems to give the syntax error

I will re-post this issue to Clojars since it seems like maybe their problem

**Comment by winks** [comment]
Thanks for the report but as you already filed it at clojars I think we can close this, there is nothing leiningen-specific, we just send the search to clojars.
