### ISSUE TITLE
lein new [template] executes, but NO directory made 

### ISSUE THREAD

**Issue by jffrydsr** [technomancy/leiningen#2638]
_This must be accounted for in the current circleci. build error -_ 
when running `lein new [app | reagent | default]` lein executes and prints the `Generating a project called my-app based on the 'app' template.` but no directory is created. when executed a second time with the same `name` parameter, `Could not create directory C:\Users\jffrydsr\apppp. Maybe it already exists?  See also :force or --force` is printed. again, no directory has been made (hidden files checked visible et all). `lein repl` works just fine but it seems creating a project directory is impossible for the time being with this failed lein ver.

**Environment**
- Leiningen Version: [e.g. 2.9.0]. Get this by running `lein version`.
- Leiningen installation method: manual, then reinstalled with choco `installed successfully`.
- JDK Version: [e.g. openjdk version "11.0.1"]. Get this by running `java -version`.
- OS: [Windows 10 1903].
- Anything else that might be relevant to your problem?

**Comment by technomancy** [comment]
I can't reproduce this problem; are you still getting it on newer versions? Could it be a windows-specific problem?

**Comment by jffrydsr** [comment]
After uninstalling Java SDK, Clojure, & Lein - it seems to be writing the template to disk now. At the time, the build on Circle CI was failing so I presumed it may have been related. Now that the build is passing, lein executes and writes to disk just fine. Strange and infuriating issue, I'm glad it's behind me now, maybe I'll give lein a try again on future projects. A thousand thanks for your awesome Clojure magic.
