### ISSUE TITLE
Update clojure dependency in leiningen-core to 1.10.1

### ISSUE THREAD

**Issue by j-cr** [technomancy/leiningen#2640]
~~Not 100% sure, but seems like 1.10.0 is causing problems with JDK11 and some 3rd-party libraries, see [this](https://github.com/weavejester/hashp/issues/5) for an example.~~

EDIT: turns out the linked issue isn't related to clojure version, sorry. Still leaving this issue open as it might be a good idea to update to 1.10.1 regardless.

**Comment by glts** [comment]
Fixed in 072dcd6.
