### ISSUE TITLE
Windows 10 install procedure

### ISSUE THREAD

**Issue by datafiend** [technomancy/leiningen#2643]
Hi all,
I'm a CLOJURE noob trying to install LEININGEN. I have followed the procedure on the installation page on the CLOJURE site. 
1. Created a .bat from LEIN.
2. PLACED the LEIN.bat file in my $PATH in my environment variables.
3. _**HOW TO I MAKE THIS AN EXECUTABLE**_
4. SEE ABOVE.

Also, I do have JAVA 1.8 installed and that is in my $PATH as well.
Thanks all

**Comment by winks** [comment]
I don't know exactly which page on clojure.org links to leiningen, but if you go to https://leiningen.org/#install you can directly download the `lein.bat` at https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat (don't use `lein` and rename it) - also you don't have to make anything executable on Windows (you actually can't), it's determined by the extension.

**Comment by datafiend** [comment]
@winks 
I did download the .bat. I ran it, and in my WINDOWS DOS prompt, it went too fast for me to see anything. 
I have the .bat in my environment path, so I'm not sure what to do here? I assume the lein.bat is downloading LEININGEN?
I

**Comment by winks** [comment]
It makes sense to start `cmd` or `powershell` beforehand and then run `lein.bat` - it's not supposed to be ran by executing it in explorer per se.
You'll see the instructions, most likely it will download the jar, and then you check if it works with `lein version` or `lein repl`, or follow the tutorial: https://github.com/technomancy/leiningen/blob/stable/doc/TUTORIAL.md
