### ISSUE TITLE
Unknown 30 second pause before tests start when running `test` target

### ISSUE THREAD

**Issue by insano10** [technomancy/leiningen#2645]
I'm using Ubuntu and lein 2.8.1.

When running the `test` target I experience a 30 second pause between compilation and the tests actually starting. I've placed logging at the absolute start of the tests so I'm sure it's nothing in the test code causing it to hang. 

What is happening under the hood between the compilation being complete and the tests actually starting?

Example output below:

```
> $ lein test my-project.my-test
Leiningen's classpath: :/usr/share/java/leiningen-2.8.1.jar
Applying task test to [my-project.my-test]
Applying task javac to nil
Running javac with [@/tmp/.leiningen-cmdline8483589484789904648.tmp]
Applying task compile to nil
All namespaces already AOT compiled.
Applying task javac to nil
Running javac with [@/tmp/.leiningen-cmdline6398520031629569200.tmp]
Applying task compile to nil
All namespaces already AOT compiled.


<< THERE IS A ~30sec PAUSE HERE >>


lein test my-project.my-test

START OF TEST
2020-01-09 16:34:28,905 [main] INFO  pg-embedded-clj.core - starting embedded-pg with config: {:port 5432, :log-redirect #object[java.io.File 0x7006e4c6 "/dev/null"]}

2020-01-09 16:34:28,956 [main] INFO  c.o.d.p.embedded.EmbeddedPostgres - Detected a Linux x86_64 system
...
```

**Comment by glts** [comment]
A 30-second pause in Clojure usually points to the agent system having been activated somewhere in the program. A call to `shutdown-agents` can fix this. Since in your case this seems to happen during compilation, it is likely you have a `def` somewhere that starts up the agent system (AOT evaluates all your `def`s!). Try to avoid that, eg by making the `def` lazy.

**Comment by insano10** [comment]
Ok thanks it sounds like this may be an issue on my side. I'll have a dig to see if I can find any stray defs.
