### ISSUE TITLE
Publish new version of lein-pprint with no-pretty option

### ISSUE THREAD

**Issue by robhanlon22** [technomancy/leiningen#2649]
Looks like an option was added to `lein-pprint` in 2018 that allows for unformatted printing: https://github.com/technomancy/leiningen/commit/454c3dc640f4b3507b13154bad2ee8ff91d702c9 However, this change was never published. Could the version of `lein-pprint` be bumped and pushed to Clojars? Thanks.

**Comment by technomancy** [comment]
Sure thing; pushed this and bumped to 1.3.0 bc368fa

**Comment by robhanlon22** [comment]
Thx!
