### ISSUE TITLE
no checksums provided when deploying

### ISSUE THREAD

**Issue by technomancy** [technomancy/leiningen#2650]
When attempting `lein deploy clojars` on the latest master version, it fails:

```
$ lein deploy clojars
No credentials found for clojars
See `lein help deploying` for how to configure credentials to avoid prompts.
Username: technomancy
Password: 
Created /home/phil/src/leiningen/lein-pprint/target/lein-pprint-1.3.0.jar
Wrote /home/phil/src/leiningen/lein-pprint/pom.xml
Need to sign 2 files with GPG
[1/2] Signing /home/phil/src/leiningen/lein-pprint/target/lein-pprint-1.3.0.jar with GPG
gpg: using "20242BACBBE95ADA22D0AFD7808A33D379C806C3" as default secret key for signing
[2/2] Signing /home/phil/src/leiningen/lein-pprint/pom.xml with GPG
gpg: using "20242BACBBE95ADA22D0AFD7808A33D379C806C3" as default secret key for signing
Sending lein-pprint/lein-pprint/1.3.0/lein-pprint-1.3.0.jar (4k)
    to https://repo.clojars.org/
Sending lein-pprint/lein-pprint/1.3.0/lein-pprint-1.3.0.pom (2k)
    to https://repo.clojars.org/
Sending lein-pprint/lein-pprint/1.3.0/lein-pprint-1.3.0.jar.asc (1k)
    to https://repo.clojars.org/
Sending lein-pprint/lein-pprint/1.3.0/lein-pprint-1.3.0.pom.asc (1k)
    to https://repo.clojars.org/
Retrieving lein-pprint/lein-pprint/maven-metadata.xml 
    from https://repo.clojars.org/
Sending lein-pprint/lein-pprint/maven-metadata.xml (1k)
    to https://repo.clojars.org/
Could not transfer metadata lein-pprint:lein-pprint/maven-metadata.xml from/to clojars (https://repo.clojars.org/): Access denied to: https://repo.clojars.org/lein-pprint/lein-pprint/maven-metadata.xml, ReasonPhrase: Forbidden - no checksums provided for lein-pprint-1.3.0.jar.asc.
Failed to deploy metadata: Could not transfer metadata lein-pprint:lein-pprint/maven-metadata.xml from/to clojars (https://repo.clojars.org/): Access denied to: https://repo.clojars.org/lein-pprint/lein-pprint/maven-metadata.xml, ReasonPhrase: Forbidden - no checksums provided for lein-pprint-1.3.0.jar.asc.
```

This is likely due to a change in the latest version of pomegranate or one of the dependencies of pomegranate.

**Comment by glts** [comment]
Oh no. Well, I did several deploy tests and it worked for me. I can also deploy lein-pprint to my own namespace in clojars.

This is how it works for me, lein-master is a symlink to ~/src/leiningen/bin/lein (current master):

```
~/src/leiningen/lein-pprint$ lein-master deploy clojars
No credentials found for clojars
See `lein help deploying` for how to configure credentials to avoid prompts.
Username: glts
Password: 
Created /home/david/src/leiningen/lein-pprint/target/lein-pprint-1.3.0.jar
Wrote /home/david/src/leiningen/lein-pprint/pom.xml
Need to sign 2 files with GPG
[1/2] Signing /home/david/src/leiningen/lein-pprint/target/lein-pprint-1.3.0.jar with GPG
gpg: using "D10B1F6211A4E68B6B63B9BBA5C4E411CD38ECAD" as default secret key for signing
[2/2] Signing /home/david/src/leiningen/lein-pprint/pom.xml with GPG
gpg: using "D10B1F6211A4E68B6B63B9BBA5C4E411CD38ECAD" as default secret key for signing
Sending org/clojars/glts/lein-pprint/1.3.0/lein-pprint-1.3.0.jar (4k)
    to https://repo.clojars.org/
Sending org/clojars/glts/lein-pprint/1.3.0/lein-pprint-1.3.0.pom (2k)
    to https://repo.clojars.org/
Sending org/clojars/glts/lein-pprint/1.3.0/lein-pprint-1.3.0.jar.asc (1k)
    to https://repo.clojars.org/
Sending org/clojars/glts/lein-pprint/1.3.0/lein-pprint-1.3.0.pom.asc (1k)
    to https://repo.clojars.org/
Could not find metadata org.clojars.glts:lein-pprint/maven-metadata.xml in clojars (https://repo.clojars.org/)
Sending org/clojars/glts/lein-pprint/maven-metadata.xml (1k)
    to https://repo.clojars.org/
```

Which lein are you using, master or stable?

**Comment by glts** [comment]
Strange, looks like your upload did succeed, the files are there: https://repo.clojars.org/lein-pprint/lein-pprint/1.3.0/

**Comment by glts** [comment]
I do not see anything suspicious in my ~/.lein/profiles.clj or ~/.m2/settings.xml, puzzling.

**Comment by glts** [comment]
This could also be a Clojars thing. Clojars has some kind of delay of up to 15 minutes (?), for example, my metadata file https://repo.clojars.org/org/clojars/glts/lein-pprint/maven-metadata.xml was uploaded successfully, but I could not access/download it until after several minutes had passed.

Comparing your log and mine, I think your upload was successful. I just cannot explain why in your case what seemed to happen was that Leiningen attempted to download the checksum files, and they weren’t available yet? Also don’t know if it is a rare occurrence or if it will happen always …

**Comment by glts** [comment]
The good news is that apart from the ‘Failed to deploy metadata’ log message dependency resolution and deployment seem to work fine. The message may be inconsequential.

Unfortunately, I suspect the changes in Leiningen and Pomegranate may have uncovered a flaw in Clojars. Question to the Clojars people (@tobias @danielcompton): About that ‘delay’ in the Clojars repository … does that still exist? Or are *all* artefacts (JARs, POMs, signature files, checksum files, Maven metadata) immediately available to resolution after deployment? I think Pomegranate/Maven may try to re-download deployed artefacts immediately for verification.

So far this is only a hypothesis. If someone is seeing the same as technomancy, if you have an account at Maven central, can you please do a deployment there and compare it with the behaviour on Clojars? Thank you.

**Comment by technomancy** [comment]
The snippet above was from running the deploy with master; later I tried with 2.8.3 and it succeeded. Then I tried again with lein-pprint 1.3.1 on 2.9.1 and it succeeded there, but when I tried to deploy 1.3.2 with master it continued to fail, and 1.3.2 hasn't showed up even after a significant wait: https://clojars.org/lein-pprint

I'm getting the same results trying to deploy `robert-hook` on this machine and will try it on another machine when I get home.

**Comment by tobias** [comment]
I'm in the middle of some work stuff atm, but I can take a look this evening.

**Comment by tobias** [comment]
I started looking at this. I haven't yet tried to deploy from `lein` master, but will. I first wanted to clarify a couple of things here.

This message:
> Could not transfer metadata lein-pprint:lein-pprint/maven-metadata.xml from/to clojars (https://repo.clojars.org/): Access denied to: https://repo.clojars.org/lein-pprint/lein-pprint/maven-metadata.xml, ReasonPhrase: Forbidden - no checksums provided for lein-pprint-1.3.0.jar.asc.

Is clojars.org reporting back that it encountered a problem when validating the deploy. Deploys go to a tmp repo, then when we see the `maven-metadata.xml` file (which is *usually* the last file uploaded as part of a deploy), we run some validation on the deploy and fail the deploy if they don't all pass. However, getting that information back to the user performing the deploy through aether isn't straightforward - the only mechanism we have is the reason phrase that is returned as part of the status; that's the only thing that aether will display to the user. So this message is saying that there wasn't an `.md5` or `.sha1` file for the `.asc` file. I looked at the tmp repos on the server for `lein-pprint`, and I can see that there indeed isn't sum files for the `.asc` files. There are, however, sum files for the `.jar` and `.pom` files, so aether is sending them for some things.

@glts I can see that your deploy to `org.clojars.glts/lein-pprint` *does* have the sum files for the `.asc` files, so succeeded. 

With regards to a delay in files showing up - there is a 15 minute delay currently when a file **changes**, but not for new files. So that would really only affect `maven-metadata.xml` files, and wouldn't be at play here. That delay should be going away soonish - hopefully within the next couple of weeks as we migrate to new infrastructure that doesn't impose that minimum TTL.

I'm going to try to deploy with `lein` master now and I'll report back.

**Comment by tobias** [comment]
I just tried deploying a test app with `lein` master (commit ` bc368fa6: Release lein-pprint 1.3.0.`) without issue - `aether` generated and uploaded both `.md5` and `.sha1` files for all of the artifacts. Note: aether doesn't report those files in the output as it uploads them, I verified their presence by looking in the repo. So I'm not sure why it's different for you @technomancy, but I'm happy to help further debug it.

**Comment by technomancy** [comment]
I can't reproduce this problem on my other machine, so I'll go ahead and assume something's funny with my checkout.

**Comment by slipset** [comment]
FWIW, I'm seeing this today:
```
08:49 $ lein deploy clojars
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
WARNING: please set :description in project.clj.
WARNING: please set :url in project.clj.
No credentials found for clojars
See `lein help deploying` for how to configure credentials to avoid prompts.
Username: erik
Password:
Created /Users/erik/Documents/ardoq.com/ardoq-swagger/target/ardoq-swagger-0.1.0.jar
Wrote /Users/erik/Documents/ardoq.com/ardoq-swagger/pom.xml
Need to sign 2 files with GPG
[1/2] Signing /Users/erik/Documents/ardoq.com/ardoq-swagger/target/ardoq-swagger-0.1.0.jar with GPG
Warning: Failed to set locale category LC_NUMERIC to en_NO.
Warning: Failed to set locale category LC_TIME to en_NO.
Warning: Failed to set locale category LC_COLLATE to en_NO.
Warning: Failed to set locale category LC_MONETARY to en_NO.
Warning: Failed to set locale category LC_MESSAGES to en_NO.
[2/2] Signing /Users/erik/Documents/ardoq.com/ardoq-swagger/pom.xml with GPG
Warning: Failed to set locale category LC_NUMERIC to en_NO.
Warning: Failed to set locale category LC_TIME to en_NO.
Warning: Failed to set locale category LC_COLLATE to en_NO.
Warning: Failed to set locale category LC_MONETARY to en_NO.
Warning: Failed to set locale category LC_MESSAGES to en_NO.
Sending com/ardoq/ardoq-swagger/0.1.0/ardoq-swagger-0.1.0.jar (11k)
    to https://repo.clojars.org/
Sending com/ardoq/ardoq-swagger/0.1.0/ardoq-swagger-0.1.0.pom (4k)
    to https://repo.clojars.org/
Sending com/ardoq/ardoq-swagger/0.1.0/ardoq-swagger-0.1.0.jar.asc (1k)
    to https://repo.clojars.org/
Sending com/ardoq/ardoq-swagger/0.1.0/ardoq-swagger-0.1.0.pom.asc (1k)
    to https://repo.clojars.org/
Could not find metadata com.ardoq:ardoq-swagger/maven-metadata.xml in clojars (https://repo.clojars.org/)
Sending com/ardoq/ardoq-swagger/maven-metadata.xml (1k)
    to https://repo.clojars.org/
Could not transfer metadata com.ardoq:ardoq-swagger/maven-metadata.xml from/to clojars (https://repo.clojars.org/): Access denied to: https://repo.clojars.org/com/ardoq/ardoq-swagger/maven-metadata.xml, ReasonPhrase: Forbidden - no checksums provided for ardoq-swagger-0.1.0.pom.asc.
Failed to deploy metadata: Could not transfer metadata com.ardoq:ardoq-swagger/maven-metadata.xml from/to clojars (https://repo.clojars.org/): Access denied to: https://repo.clojars.org/com/ardoq/ardoq-swagger/maven-metadata.xml, ReasonPhrase: Forbidden - no checksums provided for ardoq-swagger-0.1.0.pom.asc.
```

This is with lein-2.9.2

I succeeded doing a deploy with https://github.com/slipset/deps-deploy. I'm quite sure that `reps-deploy` uses an older version of `pomegranate`
