### ISSUE TITLE
project.clj :exclusions don't affect profiles.clj :deps

### ISSUE THREAD

**Issue by vemv** [technomancy/leiningen#2653]
## Context

I develop some tools (e.g. formatting) which I like to use on every project. So I place e.g. `[my.dep "1.2.3"]` in profiles.clj (`:user` profile).

That way I can require `my.dep` in every project - even in those outside of my control (where editing project.clj every time can be cumbersome)

However, when I work on `my.dep` _itself_, this setup will result in an ambiguous classpath: `my.dep`'s Clojure namespaces will be defined in a .jar in `~/.m2` _and_ in `src`.

Generally `src` wins, so it's not that much of an issue, however every now and then I run into opaque errors. It can be easy to forget that a given clojure namespace is residing in two places.

## Attempted workaround

In `my.dep`'s project.clj, add a top-level `:exclusions [my.dep]` declaration. With that I hoped to remove the dependency declaration coming from `~/profiles.clj`.

It doesn't work - probably I was hoping a behavior that's not particularly intended to be atm.

## Request

Make `:exclusions` win over `:deps`, if the `:exclusions` have more specificity (the project.clj top-level seems more specific than `~/.lein/profiles.clj`'s `:user` to me).

## Lein version

2.9.1

**Comment by technomancy** [comment]
Yeah, that sounds like an oversight. Would take a patch for this.

**Comment by vemv** [comment]
These days I've worked around the issue with the following in my project.clj:
```clj
:middleware
[~(do
    (create-ns 'vemv)
    (intern 'vemv
            'ensure-exclusions
            (fn [project]
              (let [exclusions (->> project
                                    :exclusions
                                    (map (fn [x]
                                           (str (if (namespace (symbol x))
                                                  x
                                                  (symbol (str x) (str x))))))
                                    (set))]
                (update project :dependencies (fn [deps]
                                                (->> deps
                                                     (remove (fn [[dep version]]
                                                               (exclusions (str dep))))
                                                     vec))))))
    'vemv/ensure-exclusions)]
```

i.e. I remove from :dependencies everything that belongs to global :exclusions. In the snippet, I don't have to worry about merging logic since the project is merged already.

Does it sound like good logic for a PR?

In the snippet, I'm interpreting the meaning of :exclusions as "dependency removals", which may or not be its supposed meaning already?

**Comment by vemv** [comment]
Btw, my snippet solves a more generalized problem than the original issue describes, because these days I'm also implementing the following pattern: https://clubhouse.io/blog/monolith-meet-mono-repo/ i.e. a monorepo of Lein projects which can _optionally_ share a classpath.

Can expand on that if necessary.

**Comment by technomancy** [comment]
Sorry; I misread this. There seems to be some misunderstanding about what `:exclusions` means. It's not "remove X from the list of dependencies"; instead it means "prevent X from being brought in as a transitive dependency."

We don't have a lot of control over this because it's dictated by Aether rather than Leiningen.
