### ISSUE TITLE
How can I pass my project.clj file path to lein?

### ISSUE THREAD

**Issue by Masber** [technomancy/leiningen#2655]
Dear leinigen community,

I would like to be able to run lein towards my project but from outside my project folder (I am writing an ansible script which will run **lein run**) but I can't find the way of doing this.

Any thoughts?

thank you very much

**Comment by glts** [comment]
I don’t think Leiningen supports this today, you have to be in the project’s directory (where project.clj is).

Try looking into how to set the working directory in the Ansible module/role that you’re using.

**Comment by technomancy** [comment]
I don't think this is a good idea; it's better to `cd` before your command. There are many, many places where we make the assumption that you're running from the project directory, and many plugins make this assumption as well. It's too late at this point to undo that.
