### ISSUE TITLE
Outdated key

### ISSUE THREAD

**Issue by xyproto** [technomancy/leiningen#2656]
Hi,

I'm packaging Leiningen for Arch Linux. When using this file: 

* https://github.com/technomancy/leiningen/releases/download/2.9.1/leiningen-2.9.1-standalone.zip

Together with the signature file:

* https://github.com/technomancy/leiningen/releases/download/2.9.1/leiningen-2.9.1-standalone.zip.asc

I get this warning:

    ==> WARNING: Warnings have occurred while verifying the signatures.
            Please make sure you really trust them.

Could the keys/signatures please be updated (or looked at)?

Thanks.

Best regards,
Alexander F. Rødseth

**Comment by winks** [comment]
Ah, that seems to be @technomancy 's personal key, as expected.

**Comment by technomancy** [comment]
Thanks for pointing this out. I've attached an updated signature that uses my newer key.

**Comment by xyproto** [comment]
Thanks!

**Comment by xyproto** [comment]
Just FYI:

`leiningen` is now an [official Arch Linux package](https://www.archlinux.org/packages/community/any/leiningen/).

I also bumped the package so that it uses the updated pgp key.

**Comment by technomancy** [comment]
Thanks for doing this!

**Comment by xyproto** [comment]
Thank **you** for creating and maintaining `leiningen`. It works, and makes programming Clojure easier. My hair is not on fire, yet.
