### ISSUE TITLE
:scope dependency doesn't work with uberjar

### ISSUE THREAD

**Issue by introom** [technomancy/leiningen#2657]
Add the dependency [thheller/shadow-cljs “2.8.83” :scope “provided”]

However, when run: lein uberjar

The package will be included in the final jar.

**Comment by technomancy** [comment]
Yeah, the `:scope` setting isn't actually supported by Leiningen here; it kind of works by accident elsewhere in that it's emitted in the pom during deploy. The supported way to do this is to put this in the `:provided` profile instead as per the tutorial.

That said, I would be open to accepting a patch which added support to the uberjar task for this in addition to the profile support.

**Comment by technomancy** [comment]
I'm going to close this out as it's not a bug, but if anyone wants to submit it as an enhancement they're welcome to.
