### ISSUE TITLE
Homebrew formula hasn't been updated to 2.9.2

### ISSUE THREAD

**Issue by TomSesselmann** [technomancy/leiningen#2660]
`brew upgrade leiningen`
Warning: leiningen 2.9.1 already installed

https://formulae.brew.sh/formula/leiningen
<img width="668" alt="Screen Shot 2020-03-04 at 3 50 32 pm" src="https://user-images.githubusercontent.com/23013276/75846415-5eca9f80-5e30-11ea-8320-472b805b4ec3.png">

**Comment by winks** [comment]
Hi,
afaik nobody from the team is maintaining the homebrew formula, I think you can submit a PR to https://github.com/Homebrew/homebrew-core/blob/master/Formula/leiningen.rb

**Comment by TomSesselmann** [comment]
Ah yes, I thought it was a homebrew formula version issue, but it was actually the checksum mismatch issue that I was having https://github.com/technomancy/leiningen/issues/2658

sha256sum: WARNING: 1 of 1 computed checksums did NOT match
Failed to properly download https://github.com/technomancy/leiningen/releases/download/2.9.2/leiningen-2.9.2-standalone.zip
The checksum was mismatched. and we could not verify the downloaded
file. We expected a sha256 of
09805bd809656794cfe7d9155fd4b8bea2646092318690bf68e3c379574a2d3c and actually had
c2fc53d2985b072e7f80867e067dd96ea5bf84f51eae828fbdb92f4cd0966e50.

**Comment by TomSesselmann** [comment]
Also it looks like the Homebrew formula has now been updated to 2.9.2

https://github.com/Homebrew/homebrew-core/commit/38db811bf0f1bd8fc6011ad5c49682219cb72f26
