### ISSUE TITLE
Generate bin/lein-pkg and bin/lein-sdkman from shared template

### ISSUE THREAD

**Issue by saitouena** [technomancy/leiningen#2669]
I don't like editing these files by hand. They should be kept up to date as the same as `bin/lein` in many points.
What about generating these files from shared templates?

**Comment by saitouena** [comment]
Sorry. This seems to be duplicate. https://github.com/technomancy/leiningen/issues/1996

**Comment by winks** [comment]
As you noticed while I was typing: Yes, this topic has come up in the past and we did have some fixes that were not ported properly. We didn't decide on anything, but maybe revisiting to apply 2 different patch files that are applied on release would make sense?
