### ISSUE TITLE
how to add  more clojure files to the leiningen project missing from documentation

### ISSUE THREAD

**Issue by jimka2001** [technomancy/leiningen#2672]
I'm a beginner clojure user, and I've read [the tutorial file](https://github.com/technomancy/leiningen/blob/stable/doc/TUTORIAL.md) here to find out how to set up my project directory.   The tutorial doesn't say how to add additional files to the project.   As a clojure expert, perhaps someone would know, but from the point of view of a beginner it would if the tutorial had a sections: 1) How to add a new clojure file to your project, and 2) How to refactor an existing clojure file into multiple files.

As a beginning, it is not at all clear to me what I need to do to tell the system which .clj files are actual code rather than junk/temporary files, and which order to load or compile them.

Additionally, coming from a CommonLisp/asdf and Scala/maven background, scala demands that the namespace name follows the directory path. I.e., to create namespace within a namespace, I have to create a corresponding directory within a directory.  On the contrary CommonLisp/asdf lets me put files anywhere I want and name them anything I like, as long as I register the dependencies in the .asd file so the Lisp can load and compile the system.

Does the same thing apply to leiningen?   

Perhaps part of the answer is that leiningen is not responsible but clojure itself.  Nevertheless, documentation helping the beginner set up his project would be appreciated.

**Comment by technomancy** [comment]
The tutorial has a section titled "Filename-to-Namespace Mapping Convention" that contains links to two documents which explain the details of namespaces, since they are a Clojure feature rather than a feature of Leiningen. Did you have a hard time finding those documents because they were not prominent enough, or did you read them and find them unhelpful?

**Comment by jimka2001** [comment]
Hi Technomancy, Thanks for the comment.  Yes, I saw that section, but it was not very helpful.

What I'd really like to see is a section about "How to refactor a file into several files".   Again, I suppose this is something the expert knows without even giving it a second thought.  But for the beginner it is a mystery.     I know when I learned to do this in Common Lisp, it was far from trivial, but it was easier because in Common Lisp a namespace can (and usually does) span files.  

Apparently in clojure, moving a function to a different file, involves understanding some language requirements, tooling requirements, and social conventions: perhaps creating a new namespace, including selecting the appropriate options for that `(ns ...)` form, moving the function text, moving the unit tests for the function, perhaps creating a new testing namespace, dealing with the fact that the name already exists in VM, perhaps touching (and recompiling) all the call sites,  and visiting all the name space declarations to see whether they need to now include an additional requirement.   And what about cached java class files in some hidden directory somewhere, like the `target` directory or perhaps theres a secret cache somewhere in my home directory?  Will those just magically fix themselves, or do I need to find them and delete them by hand?  Do I need to quit and restart clojure every time I move a function? What if I'm using cider, do I need to restart the inferior clojure process? 

Now imagine you are doing this for the first time as a relatively new clojure programmer.

Yes, part of this is dictated by how clojure works, indeed, but part is controlled by lein, I would suppose, as that's what manages the content of the project.  And part of it is encouraged by social convention.  Or am I mistaken?

**Comment by technomancy** [comment]
> Yes, part of this is dictated by how clojure works, indeed, but part is controlled by lein

The only part that Leiningen controls is the fact that the source files go in the `src/` directory. The rest is up to Clojure and its rules about namespaces in the linked pages.

I feel like the fact that source code goes in the src/ directory is already pretty clear in the tutorial as it is.

**Comment by jimka2001** [comment]
I created the project using lein.   lein created a basic directory structure include src and test directories.  Perhaps if it created multiple src files and test files would make the step easier of moving to a multiple file project?   Its still not clear to me how lein knows which files to load in which order and which files should be ignored.  It is not clear to mean it means to "load a project".  I don't think the project concept is built into clojure, something certainly tells clojure which files to load and in which order.  Right?  Where is that information?

**Comment by MikeyYeahYeah** [comment]
I think it would be a little more productive to change the approach here.  Perhaps it would be better to list your questions and try to get them answered.  Once you have the answers, it will be far easier to see what, if anything, needs to be added to the documentation to make the beginner experience better for all.

FWIW, there is an excellent Slack channel (https://clojurians.herokuapp.com/) that has a beginner channel that is quite helpful.

**Comment by jimka2001** [comment]
I really don't see why the resistance to documenting the refactoring process.

**Comment by technomancy** [comment]
The point is that each project should be responsible for documenting itself. I have had to deal with numerous situations where some documentation for Leiningen was written in blog posts by some random person, and eventually it became outdated and incorrect. There was no way I could fix it.

So the documentation for Leiningen should be Leiningen's responsibility, and the documentation for Clojure should be Clojure's responsibility. That's why our docs point to their docs where relevant.
