### ISSUE TITLE
lein not working

### ISSUE THREAD

**Issue by aschuhl** [technomancy/leiningen#2679]
I brew installed lein (2.9.3) and keep getting the error: `Caused by: java.io.FileNotFoundException: Could not locate clojure/tools/nrepl/server__init.class, clojure/tools/nrepl/server.clj or clojure/tools/nrepl/server.cljc on classpath.`

I also tried downloading the script to my local as well, but receive the same error.

Using macos mojave,
and tried on java 8 and 11.

**Comment by MawiraIke** [comment]
Hope these help [1](https://groups.google.com/forum/#!topic/clojure/LS9GK2VEe3k) [2](https://github.com/technomancy/leiningen/issues/1240#issuecomment-480464816).

**Comment by technomancy** [comment]
It looks like either there's an issue with brew's packaging, or possibly you have installed some plugin that depends on some old version of nrepl; hard to tell without more details. Does this happen outside a project dir? Do you have anything in `~/.lein/profiles.clj`?

**Comment by technomancy** [comment]
Closing this out as there is not enough info to be actionable. Feel free to reopen it if details can be provided.

**Comment by aschuhl** [comment]
@technomancy removing ~/.lein/profiles.clj fixed the problem, thank you!
