### ISSUE TITLE
Consider publishing your (technomancy) PGP key on keys.openpgp.org

### ISSUE THREAD

**Issue by cap10morgan** [technomancy/leiningen#2681]
@technomancy

I am one of the maintainers of [the official clojure Docker image](https://github.com/Quantisan/docker-clojure) and they would like us to verify lein downloads with your PGP key since you publish `.zip.asc` signature files with each release. However, scripting this is quite painful because of how flaky PGP keyservers tend to be. The builds break a _lot_ due to PGP key retrieval failures and the workarounds are... also painful.

There is a new, more modern PGP key server at [keys.openpgp.org](https://keys.openpgp.org) but you have to upload your key there and then verify that you own the email address associated with it before we can use it to retrieve your key. Would you mind uploading and verifying your PGP key there? Thank you!

**Comment by technomancy** [comment]
Thanks for the heads-up. I've uploaded it to the keys.openpgp.org keyserver; hope that helps! Let me know if that worked out for you.

**Comment by cap10morgan** [comment]
Awesome, thank you @technomancy! This a huge help to us.
