### ISSUE TITLE
Runtime exception reported as syntax error

### ISSUE THREAD

**Issue by smithtim** [technomancy/leiningen#2682]
**Describe the bug**

When my program throws an exception during runtime, it is incorrectly reported as a syntax error.  This only happens with `lein run`.  If I use `lein uberjar` and run the jar, the exception is reported correctly.

This happens with Clojure 1.10.0, 1.10.1, and 1.10.2-alpha1.  It does not happen with Clojure 1.8.0 or 1.9.0.

**To Reproduce**

`project.clj`:
```clojure
(defproject foo ""
  :dependencies [[org.clojure/clojure "1.10.1"]]
  :main foo)
```

`foo.clj`:
```clojure
(ns foo (:gen-class))

(defn -main []
  (println "ready")
  (throw (Exception. "some exception")))
```

`lein run`

**Actual behavior**

```
ready
Syntax error compiling at (/private/var/folders/6r/ypz180tj1jvbrxkyh5d_m2mh0000gn/T/form-init856731971820241598.clj:1:124).
some exception

Full report at:
/var/folders/6r/ypz180tj1jvbrxkyh5d_m2mh0000gn/T/clojure-3986197972893425257.edn
```

**Expected behavior**

```
ready
Exception in thread "main" java.lang.Exception: some exception
[stack trace]
```

**Environment**
- Leiningen Version: 2.9.3
- Leiningen installation method: brew
- JDK Version: 1.8.0_171
- OS: macOS 10.15.3

**Comment by technomancy** [comment]
This looks like a bug in Clojure; for some reason it misinterprets the execution as being compilation.

**Comment by smithtim** [comment]
Just a note that this still happens on Clojure 1.10.3.

**Comment by technomancy** [comment]
Unfortunately I don't think there's anything we can do about this since this is a bug in Clojure. It should be reported upstream.
