### ISSUE TITLE
Uberjar fails to pick up composite profiles

### ISSUE THREAD

**Issue by emlyn** [technomancy/leiningen#2683]
**Describe the bug**
Building an uberjar from a project with composite profiles fails to resolve the profiles correctly.

**To Reproduce**
Create a project with composite profiles, such as:
```clojure
  :profiles
  {:foo
   {:dependencies []}

   :dev
   [:foo]

   :uberjar
   [:foo
    {:aot :all}]}
```
and run `lein uberjar`.

**Actual behavior**
It prints warnings about a missing profile, even though the profile is present in project.clj:
```
> lein uberjar
Warning: profile :foo not found.
Warning: profile :foo not found.
Warning: profile :foo not found.
Warning: profile :foo not found.
Warning: profile :foo not found.
Compiling uberjartest.core
Warning: profile :foo not found.
Warning: profile :foo not found.
Warning: profile :foo not found.
Created /Users/emlyn/dev/uberjartest/target/uberjartest-0.1.0-SNAPSHOT.jar
Warning: profile :foo not found.
Warning: profile :foo not found.
Warning: profile :foo not found.
Created /Users/emlyn/dev/uberjartest/target/uberjartest-0.1.0-SNAPSHOT-standalone.jar
```
I have tried adding `^:leaky` metadata to the :foo profile, which reduces the number of times the warning is printed to just one:
```
> lein uberjar
Compiling uberjartest.core
Created /Users/emlyn/dev/uberjartest/target/uberjartest-0.1.0-SNAPSHOT.jar
Warning: profile :foo not found.
Created /Users/emlyn/dev/uberjartest/target/uberjartest-0.1.0-SNAPSHOT-standalone.jar
```
But in both cases it fails to merge in the referenced profile (e.g. extra dependencies in :foo are not pulled in to the uberjar).

**Expected behavior**
It should find the referenced profile and pull in any extra dependencies.

**Link to sample project**
https://github.com/emlyn/uberjartest/blob/master/project.clj

**Environment**
- Leiningen Version: 2.9.3
- Leiningen installation method: Homebrew
- JDK Version: 1.8.0_212 OpenJDK 64-Bit Server VM
- OS: macOS 10.14 (also observed on Ubuntu)

**Comment by technomancy** [comment]
Hey, I think this is actually the same bug as #2393. Right now the recommended workaround is to make the composite profile consist only of references to other profiles (all keywords) rather than a mix of keywords and maps. I'll update the docs to reflect this.
