### ISSUE TITLE
Should new app template uberjar profile use direct linking by default?

### ISSUE THREAD

**Issue by bsless** [technomancy/leiningen#2684]
Hello,
I was wondering what's the reason reason new app template uberjar profile doesn't use direct linking by default. It should provide better performance and better startup speed. Seems like an overall benefit.
What do you think?

Thanks
Ben

**Comment by technomancy** [comment]
Sure; that seems reasonable. The only reason it doesn't do this already is that direct linking didn't exist when the template was created.

**Comment by bsless** [comment]
Would you like me to submit a PR?

**Comment by technomancy** [comment]
Sure; go for it.
