### ISSUE TITLE
2.9.2 and 2.9.3 were released with incorrect dependencies

### ISSUE THREAD

**Issue by ehashman** [technomancy/leiningen#2690]
I noticed this while performing some packaging work:

https://github.com/technomancy/leiningen/blob/2.9.2/project.clj#L10

https://github.com/technomancy/leiningen/blob/2.9.3/project.clj#L10

Both the 2.9.2 and 2.9.3 releases of Leiningen depend on an incorrect (I think??) version of leiningen-core.

**Comment by glts** [comment]
Yes, see also discussion in #2675.

**Comment by ehashman** [comment]
Ah, that wasn't clear from the issue. Suspect this is the root cause.

@technomancy I'm going to wait until this is sorted for another release of leiningen in Debian (or I could just patch it myself), is there an ETA on 2.9.4?

**Comment by technomancy** [comment]
@ehashman I have 4 issues I would like to at least look into before cutting the next release; I've added them all to the 2.9.4 milestone here: https://github.com/technomancy/leiningen/milestone/27

I expect not all of them will get fixed, but these ones at least merit a bit more investigation.

**Comment by technomancy** [comment]
Should be fixed with 2.9.4 now: 0e8839e
