### ISSUE TITLE
lein-pkg broken in 2.9.4

### ISSUE THREAD

**Issue by cap10morgan** [technomancy/leiningen#2691]
Tried to update the official clojure images (which use the bin/lein-pkg script) to lein 2.9.4. Got this error:

```
./lein-pkg: line 110: unexpected EOF while looking for matching `''
./lein-pkg: line 148: syntax error: unexpected end of file
```

**To Reproduce**
1. Create new dir and change to it.
2. Download bin/lein-pkg to it: `curl -O https://raw.githubusercontent.com/technomancy/leiningen/2.9.4/bin/lein-pkg`
3. Allow execution: `chmod +x lein-pkg`
4. Try running it: `./lein-pkg`

**Actual behavior**
```
./lein-pkg: line 110: unexpected EOF while looking for matching `''
./lein-pkg: line 148: syntax error: unexpected end of file
```

**Expected behavior**
Script to work like it does in previous releases.

I looked at the script but it wasn't immediately obvious what was going on. The `'` character on line 110 is in the middle of an echo'ed string.

**Comment by technomancy** [comment]
Good catch; thanks. I pushed a fix to master; does that take care of things?

**Comment by cap10morgan** [comment]
This is probably a separate issue (and so I'm happy to file it as such), but the master version of `lein-pkg` is now generating the error: `Error: Could not find or load main class clojure.main
Caused by: java.lang.ClassNotFoundException: clojure.main` when I try to run `lein deps` on a very minimal `project.clj` (shown below). The only purpose of this is to have leiningen download and thus cache clojure itself in the Docker image. Maybe there's a better way to do that?

Here's the minimal `project.clj` I've been using for that:

```clojure
(defproject dummy ""
  :dependencies [[org.clojure/clojure "1.10.1"]]
)
```

**Comment by technomancy** [comment]
Do you know if this new error is coming from Leiningen's own JVM or the project JVM?

As far as I can tell the only changes to this file since 2.9.3 have been cases where `LEIN_FAST_TRAMPOLINE` is set; is that true in the case you're describing?

**Comment by cap10morgan** [comment]
I'm not sure. It's in a Docker build, so the environment should be very constrained. Here's an example full Dockerfile that's exhibiting the error: https://raw.githubusercontent.com/Quantisan/docker-clojure/try/master-lein-pkg/target/openjdk-11-slim-buster/lein/Dockerfile

If you download that to an empty dir and then run `docker build -t clojure:lein-2.9.4 .` (note the `.` on the end) you should see the error.

**Comment by cap10morgan** [comment]
I just printed out the env before running the command in the image build and saw that for some reason it appears to be using openjdk-15 in what is supposed to be an openjdk-11 image. So that may be the source of the issue. I'll keep investigating that.
