### ISSUE TITLE
Filter out / warn test namespaces that do not exist instead of aborting the test run

### ISSUE THREAD

**Issue by mourjo** [technomancy/leiningen#2693]
When the test command is passed a namespace that does not exist, no test is run and the `lein test` process exits with a positive error code. If the same is passed to the `:only` selector, the tests are run for the namespaces that exist. Do you think it would make sense to apply the same behaviour (run tests for namespaces which exist, perhaps warning about non-existent namespaces)?

I am running Leiningen `2.9.4` on Java `1.8` on MacOS `10.15.4 (19E287)`:
```shell
Leiningen 2.9.4 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM

uname -a
Darwin andromeda 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```

```shell
lein test a.b
...
Caused by: java.io.FileNotFoundException: Could not locate a/b__init.class or a/b.clj on classpath.
```

```shell
 lein test a-test-ns-that-exists a.b
...
Caused by: java.io.FileNotFoundException: Could not locate a/b__init.class or a/b.clj on classpath.
```

```shell
lein test :only a.b

lein test user

Ran 0 tests containing 0 assertions.
0 failures, 0 errors.
```

```shell
lein test :only a-test-ns-that-exists a.b

lein test a-test-ns-that-exists

Ran 3 tests containing 4 assertions.
0 failures, 0 errors.
```

**Comment by technomancy** [comment]
No, the reason that `:only` works differently is that it's built using test selectors. It's intentional that selectors work differently from providing a list of namespaces.
