### ISSUE TITLE
Lein Plugin code got ClassNotFoundException when calling Java class

### ISSUE THREAD

**Issue by guoyongxin** [technomancy/leiningen#2706]
I have a clojure plugin project with both java source code and clojure source code. And the clojure code would import the java class.

The issue I met is when I run `lein myplugin` in the plugin project itself. I will get the ClassNotFoundException. But if I call the plugin from a consumer project, there is no error.

Anyone know how I could fix the ClassNotFoundException error when in the plugin project?

I'm a clojure newbie and this error confused me a lot. Is this a bad practice to have both java code and clojure in one plugin? The reason I need to write java is because I need to check a lot of class type in some functions, which is much easier in Java.
I suspect there are some class path setting that might be missing. But I got no luck when trying to set those in project.clj.

Any help would be appreciated.

Here are the plugin code details:

```
--myplugin
       |--------java/src/com/roger/HelloUtil.java
       |--------src/leiningen/myplugin.clj
       |--------project.clj
```

project.clj
```clojure
(defproject myplugin "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :eval-in-leiningen true

  :java-source-paths ["java/src"]

  :javac-options ["-target" "1.8" "-source" "1.8"])
```

src/leiningen/myplugin.clj
```clojure
(ns leiningen.myplugin
  (:import (com.roger HelloUtil)))

(defn myplugin
  "I don't do a lot."
  [project & args]
  (.sayHelloFromJava (HelloUtil.))
  (println "Hi!"))

```

java/src/com/Roger/HelloUtil.java
```java
package com.roger;

public class HelloUtil {

    public HelloUtil() {

    }

    public void sayHelloFromJava() {
        System.out.println("Hello Java");
    }
}

```

When I run `lein myplugin` in the plugin project, I got something like below
```
clojure.lang.Compiler$CompilerException: java.lang.ClassNotFoundException: com.roger.HelloUtil, compiling:(leiningen/myplugin.clj:1:1)
 at clojure.lang.Compiler.load (Compiler.java:7391)
    clojure.lang.RT.loadResourceScript (RT.java:372)
...........
```

If I add this plugin to other project as dependency, it would work.

**Comment by technomancy** [comment]
Unfortunately this is just a limitation of how `:eval-in-leiningen` works. Once the `lein` process has started, the classpath is determined and cannot be changed. So this is an unfortunate technical limitation of how plugin classpaths work.
