### ISSUE TITLE
leiningen.clean/clean doesn't respect project root path on deleting relative paths from :clean-targets

### ISSUE THREAD

**Issue by metametadata** [technomancy/leiningen#2707]
**To Reproduce**
1) Create the project with string clean targets. E.g. `:clean-targets ^{:protect false} ["target" "resources/private/js/"]`.
1) Programmatically clean the project from another directory using `leiningen.clean/clean`.

**Actual behavior**

Project's dirs stay the same. The `target` and `resources/private/js/` dirs from the current working path are deleted instead.

**Expected behavior**

The `target` and `resources/private/js/` dirs from the project are deleted.

**Environment**
- Leiningen Version: 2.9.1.

**Additional context**

I have an in-house plugin to manage monorepos and the issue caused difficult to debug behaviour as it affects other tasks such as `install` and `uberjar`.

My current workaround is to modify the read project map before cleaning it:

```clj
(defn -with-absolute-clean-target-paths
  [project]
  (let [root-path (:root project)
        absolute-clean-targets (-> (for [clean-target (:clean-targets project)]
                                     (if (and (string? clean-target)
                                              (not (.isAbsolute (io/file clean-target))))
                                       (str (io/file root-path clean-target))
                                       clean-target))
                                   ; Meta may contain {:protect false}
                                   (with-meta (meta (:clean-targets project))))]
    (assoc project :clean-targets absolute-clean-targets)))

...

(let [project (leiningen.core.project/read ...)]
  (leiningen.clean/clean (-with-absolute-clean-target-paths project)))
```

**Comment by technomancy** [comment]
If the problem here only happens when `leiningen.clean/clean` is called as a function, rather than when running `lein clean` then I would say it's not a bug; the task functions specifically are intended to be called in a specific context with the directory set to the project root.

I would take a patch to be redundant here and calculate them based on the `:root` passed in, but in general there isn't really a guarantee about what will happen when task functions are called from arbitrary directories.

**Comment by metametadata** [comment]
OK, thanks. Then unfortunately, using the task functions programmatically becomes a minefield as there's no way to change the current working directory in Java.

**Comment by technomancy** [comment]
Sure; well if you decide you want to fix it within Leiningen I can apply that patch.

**Comment by metametadata** [comment]
Ah, I misinterpreted your last sentence. Thanks, maybe I will do a PR in the future, for now the workaround suffices my needs.
