### ISSUE TITLE
Differentiate between project directory name and project name

### ISSUE THREAD

**Issue by otjura** [technomancy/leiningen#2708]
When I run:

> lein new app MyApp
Project names containing uppercase letters are not recommended
and will be rejected by repositories like Clojars and Central.
If you're truly unable to use a lowercase name, please set the
LEIN_BREAK_CONVENTION environment variable and try again.

Which is absolutely fine and understandable. However, there is just that it also creates a directory. 

Suggestion: if creating a project with UpperCaseLetters, create directory as wanted but create project in lowercase, then notify user of convention and what the project name in project.clj is

Advantages: maintaining convention better by not encouraging people to override it

**Comment by technomancy** [comment]
I think it's better just to recommend lowercase names.
