### ISSUE TITLE
Wrong merging logic for :source-paths, :resource-paths and :test-paths

### ISSUE THREAD

**Issue by masztal** [technomancy/leiningen#2709]
In documentation in Merging section is written:
> The exception to this merge logic is that `:plugins` and `:dependencies` have custom de-duplication logic

But, when you put `#{}` as a value of `:source-paths`, `resource-paths` or `test-paths` it is converted to a list by function `leiningen.core.project/setup-map-defaults` because default empty-path value is a vector:

```
(def empty-paths
  (with-meta [] {:prepend true}))
```

**reproduce**
project.clj
```
(defproject sample "0.1.0-SNAPSHOT"
  :resource-paths #{"project" "common"}
  :profiles {:stuff {:resource-paths #{"stuff" "common"}}})
```

Run command: `lein with-profile stuff pprint`
The returned value of `:resource-paths` is a list with **duplicated** items:

```
 ("/sample/stuff"
  "/sample/common"
  "/sample/project"
  "/sample/common")
```

**workaround**
You can use `:reduce` metadata, which is not specified in documentation.
```
(defproject sample "0.1.0-SNAPSHOT"
  :resource-paths  ~(with-meta ["project" "common"]
                     {:reduce (fn [left right-item] (conj (into #{} left) right-item))})
  :profiles {:stuff {:resource-paths #{"stuff" "common"}}})
```
and the result of `lein with-profile stuff pprint` is 
```
...
:resource-paths
 ("/sample/project"
  "/sample/stuff"
  "/sample/common"),
...
```
It is the expected value.

**evironment** 
lein version: Leiningen 2.9.1 on Java 1.8.0_211 Java HotSpot(TM) 64-Bit Server VM

**Comment by technomancy** [comment]
> But, when you put `#{}` as a value of `:source-paths`, `resource-paths` or `test-paths` it is converted to a list by function `leiningen.core.project/setup-map-defaults` because default empty-path value is a vector:

Do you mean that this is only a problem if you use a set here, or are you just using a set as an example to illustrate what happens?

If it's the former then I don't think it's a problem; these values are interpreted in such a way that order is very important, so we should not go out of our way to support unordered inputs.

**Comment by masztal** [comment]
> these values are interpreted in such a way that order is very important

Good point. I belive, this information should be written in documentation.

Despite that, if someone don't what to compile multiple times the same file or don't want to see leiningen warning: 
`Warning: skipped duplicate file: a.txt` during `lein uberjar` a fixed workaround (preserve order) can be used:

`{:reduce (fn [left right-item] (distinct (concat left [right-item])))}`

**Comment by technomancy** [comment]
OK, well happy to take a patch to improve the documentation here if you have suggestions for how to make it clearer.

**Comment by technomancy** [comment]
I think this problem is solved by https://github.com/technomancy/leiningen/issues/2281 so let's track this there instead.
