### ISSUE TITLE
`lein new app` in current directory generates invalid project

### ISSUE THREAD

**Issue by terciodemelo** [technomancy/leiningen#2722]
**Initial debugging steps**
Before creating a report, _especially_ around exceptions being thrown when running Leiningen, please check if the error still occurs after:

- [x] Updating to using the latest released version of Leiningen (`lein upgrade`).
- [x] Moving your `~/.lein/profiles.clj` (if present) out of the way. This contains third-party dependencies and plugins that can cause problems inside Leiningen.
- [x] Updating any old versions of plugins in your `project.clj`, especially if the problem is with a plugin not working. Old versions of plugins like nREPL and CIDER (as well as others) can cause problems with newer versions of Leiningen.
- [x] (If you are using Java 9 or newer), updating your dependencies to their most recent versions. Recent JDK's have introduced changes which can break some Clojure libraries.

**Describe the bug**
https://github.com/technomancy/leiningen/pull/1486 Added the possibility to create new app to an existing directory, but when it is the _current_ directory, things may break down.

When you name the current directory with `.` as argument to `lein new app`, as `lein new app .`, lein correctly warns the directory exists and ou should use `--force` to confirm you wanna generate the app in the current directory. But it creates a `src/.clj` and a `test/_test.clj` (with a `(ns . (:gen-class)` and `:require [. :refer all]`).  Running `lein test` breaks.

**To Reproduce**
1. Create a new directory, say, `lein-test-dir`
2. Run `cd lein-test-dir`
3. Run `lein new app . --force`
4. Run `lein test`

**Actual behavior**
Because the step `3` creates invalid files and namespace leiningen crashes with a `FileNotFoundException`

**Expected behavior**
To either request the user a valid project name - via prompt and/or flag - at step `3` or create the project with some default namespace.

**Link to sample project**
N/A

**Logs**
![Screen Shot 2021-01-20 at 10 37 42](https://user-images.githubusercontent.com/6502871/105185549-64e07200-5b0f-11eb-8377-f1532d95b6c2.png)

![Screen Shot 2021-01-20 at 11 16 13](https://user-images.githubusercontent.com/6502871/105186904-f3092800-5b10-11eb-996e-12edb0119227.png)

**Environment**
- Leiningen Version: 2.9.5
- Leiningen installation method: manual
- JDK Version: Java 1.8.0_275 OpenJDK
- OS: macOS 10.15.7

**Additional context**
N/A

**Comment by vemv** [comment]
It appears that you are using `lein new app . --force`, while `lein new $(basename $PWD) --to-dir . --force` is a more complete invocation

**Comment by technomancy** [comment]
The `lein new` task takes the name of the project as its argument, so it's not surprising that passing `.` would fail, especially if the `--force` flag is given.
