### ISSUE TITLE
lein exceptions - AdoptOpenJDK 11 J9 JVM - especially when more than one CPU is available

### ISSUE THREAD

**Issue by pbwolf** [technomancy/leiningen#2725]
`lein` 2.9.5 throws (various exceptions) when using the AdoptOpenJDK 11 J9 (as opposed to HotSpot) JVM, especially when it can use more than one CPU; in either Linux or Windows 

**To Reproduce**
In Linux (12 "processors")
1. Install AdoptOpenJDK 11 J9 JVM (note: J9, as opposed to HotSpot)
2. Download lein script
2. Run lein (without arguments)
3. See error

In Windows (2 "processors")
1. Install AdoptOpenJDK 11 J9 JVM (note: J9, as opposed to HotSpot)
2. Download lein bat
2. Run lein (without arguments)
3. It suggests to self-install
4. lein self-install
5. self-install succeeds
6. Run lein (without arguments)
7. See error

**Actual behavior**

One of several:

 - java.lang.NullPointerException, with stack trace including clojure.main$report_error.invokeStatic(main.clj:593) - exhibit output-02
 - 
 - java.lang.NullPointerException, with stack trace including clojure.core$supers.invokeStatic(core.clj:5559) - exhibit output-08
 - 
 - java.lang.ExceptionInInitializerError, with stack trace including Execution error (NullPointerException) at cemerick.pomegranate/loading (pomegranate.clj:1) with "Full report" in an edn file (exhibit-W1) containing ExceptionInInitializerError
 - 
 - java.lang.ExceptionInInitializerError at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:185) at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:174) ...  at cllojure.lang.RT.classForName(RT.java:2211) - also in exhibit output-08

**Expected behavior**

lein (without arguments) should give a menu of subcommands.

**Link to sample project**
The problem occurs without any project.clj.

**Logs**
lein's stdout/stderr is attached in exhibits corresponding to the exceptions listed above.

**Environment**
- Leiningen Version: 2.9.5
- Leiningen installation method: download lein script or bat file
- JDK Version: Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Linux amd64-64-Bit Compressed References 20210120_910 (JIT enabled, AOT enabled)
- OS:  Ubuntu 18.04.5 LTS, and Windows 10.0.19042

**Additional context**

lein usually (but not always) worked as expected when run on _a single CPU_, an experiment I tried only in Ubuntu with numactl:

    numactl --physcpubind=+1 ./lein

J9 issue https://github.com/eclipse/openj9/issues/6623 may be relevant. It involves a similar(?) ExceptionInInitializerError - recordInitializationFailure. A comment observes that there is a circumstance where Hotspot throws an Exception and J9 throws an Error, necessitating different application programming. The closing comment says, "The initialization of the server will need to be reworked to use synchronized instead of relying on the class loading lock.".

**Comment by pbwolf** [comment]
Exceptions in attachments:

[output-02.txt](https://github.com/technomancy/leiningen/files/5940094/output-02.txt)

[output-08.txt](https://github.com/technomancy/leiningen/files/5940095/output-08.txt)

[output-W1.txt](https://github.com/technomancy/leiningen/files/5940096/output-W1.txt)

**Comment by vemv** [comment]
(disclaimer: I'm not a Lein contributor)

Have you verified that this issue specific to Leiningen? One can do so by running Clojure via `java -jar clojure.jar ...`. Similarly you can try out tools.deps if using `java` directly is too much of a hassle.

**Comment by technomancy** [comment]
If this is not a bug in J9 (which it looks like at first glance) then it seems likely to be a bug in pomegranate or one of its dependencies.

**Comment by pbwolf** [comment]
- J9 version 15 also produces the error.

 - JVM option "-Xint" ("interpreted mode execution only") in LEIN_JVM_OPTS makes Leiningen work (slowly!) even without the numactl trick.

 - JVM option "-Xcomp" ("forces compilation of methods on first invocation") in LEIN_JVM_OPTS produces the error -- even with the 1-CPU limit with numactl.

 - The problem can also be reproduced without Leiningen, using a modified version of Clojure's `clojure` (modified to honor its `-J` option in all of its invocations of Java).
