### ISSUE TITLE
Install and set up in Windows10

### ISSUE THREAD

**Issue by wrkelly** [technomancy/leiningen#2727]
Having the same problem I see may others have had but these adjustents to lein.bat file aren't resolving the issue.

C:>lein self-install
Downloading Leiningen now...
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At line:1 char:324

    ... che]::DefaultNetworkCredentials; $client.DownloadFile($a, $f); }} "ht ...

                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        CategoryInfo : NotSpecified: (:) [], MethodInvocationException
        FullyQualifiedErrorId : WebException

Failed to download https://github.com/technomancy/leiningen/releases/download/2.9.6/leiningen-2.9.6-standalone.zip

It is possible that the download failed due to "powershell",
"curl" or "wget"'s inability to retrieve GitHub's security certificate.

The PowerShell failed to download the latest Leiningen version.
Try to use "curl" or "wget" to download Leiningen by setting up
the HTTP_CLIENT environment variable with one of the following
values:

a) set HTTP_CLIENT=wget -O
b) set HTTP_CLIENT=curl -f -L -o

NOTE: Make sure to not add double quotes when setting the value
of HTTP_CLIENT

**Comment by irafunesta** [comment]
Hello, 

I don't know if you solved this somehow, but i have managed to manually download the 2.9.5 , version from here

https://github.com/technomancy/leiningen/releases/download/2.9.5/leiningen-2.9.5-standalone.zip

then move it to:

C:\Users\<Username>\.lein\self-installs

and rename the .zip to a .jar, and then the script was working. 
Look in to the lein.bat script , on the 3rd line and set the corresponding version in my case 2.9.5

**Comment by lalz001** [comment]
use 
        set HTTP_CLIENT=curl -f -L -o
before you run 
        lein self-install

**Comment by technomancy** [comment]
This should be fixed since releases no longer get uploaded as `.zip`
