### ISSUE TITLE
Allow AOT of Clojure dependencies 

### ISSUE THREAD

**Issue by mauricioszabo** [technomancy/leiningen#2729]
Hi there! First of all, thanks a lot for lein, it's an incredible tool!

I'm having some trouble bundling an app that uses confluent's parallel-consumer library. The reason is that because it creates threads in a way that overwrites Clojure classloader, the threads don't see classes that are not AOT compiled. In my case, I had to copy the whole library's source I was using so that lein could AOT the whole thing and then don't depend on the classloader anymore.

So, is it possible to add a feature to AOT compile all dependencies?

If you need more information, here's the issue to try to circumvent the problem in the parallel-consumer code: https://github.com/confluentinc/parallel-consumer/issues/78

I'm asking for this feature because Java libraries that work in a similar manner could create hard to catch, to understand, and to debug problems in production.

**Comment by technomancy** [comment]
> So, is it possible to add a feature to AOT compile all dependencies?

The Clojure compiler will actually perform AOT of all a namespace's
required namespaces when compiling it; this is actually outside the
control of Leiningen. So as long as you have one "entry point" namespace
that loads all the other namespaces you want compiled, it should be good
enough to AOT-compile that one, and the rest will be AOT'd whether you
want it or not.

**Comment by mauricioszabo** [comment]
Ah, ok.... the issue was on my side, sorry.

The problem was that, for some reason, I had `  :clean-non-project-classes true` in my config. Closing it now...
