### ISSUE TITLE
Verified Group Names and templates

### ISSUE THREAD

**Issue by seancorfield** [technomancy/leiningen#2730]
In light of Clojars improving security of group names -- see https://github.com/clojars/clojars-web/wiki/Verified-Group-Names -- we tool maintainers need to consider how to move forward with templates for Leiningen, Boot, and the CLI.

Leiningen long ago adopted the naming convention of `<template>/lein-template` and I followed suit in `boot-new` with `<template>/boot-template` and then again in `clj-new` with `<template>/clj-template`. That has led to Leiningen templates being published into "random" groups that match the name of the template but often have very little bearing on the maintainer's username and/or the URL/coordinates of the project for which the template exists.

The benefit of this naming convention is the ease of finding them programmatically, or via searches on clojars.org, or via sites like clj-templates.com but pretty much none of the existing templates have group IDs that satisfy the new Verified Group Names policy.

For existing templates, this isn't a big problem since Clojars will continue to allow new library releases into existing non-verified groups -- but by mid-April, it will not be possible to publish new project templates that have a template name that is not a reverse domain name (or at least a verified group name).

As an initial discussion point, I'm opening this issue in all three tools' GitHub repos but I don't have a solid proposal for a new naming scheme that would make templates easy to find for tools:

* Leiningen new templates: https://github.com/technomancy/leiningen/issues/2730
* Boot new templates: https://github.com/boot-clj/boot-new/issues/47
* CLI new templates: https://github.com/seancorfield/clj-new/issues/54

**Comment by seancorfield** [comment]
One possibility is allowing qualified template names in the tools, such as `com.luminusweb/starter` and then looking for `com.luminusweb/starter.clj-template`, `com.luminusweb/starter.boot-template`, `com.luminusweb/starter.clj-template` as far as coordinates are concerned, but then still treating just `starter` as the template name for the purposes of finding the namespaces.

**Comment by seancorfield** [comment]
FYI, I am making a release of `clj-new` that generates and supports templates based on `<group>/<artifact>` style names, which inserts `clj-template.` so the actual deployed library -- and what `clj-new` searches for -- is `<group>/clj-template.<artifact>`. It will also look for `<group>/lein-template.<artifact>` and `<group>/boot-template.<artifact>`.

**Comment by technomancy** [comment]
Thanks for making me aware of this change.

> FYI, I am making a release of `clj-new` that generates and supports
> templates based on `<group>/<artifact>` style names, which inserts
> `clj-template.` so the actual deployed library -- and what `clj-new`
> searches for -- is `<group>/clj-template.<artifact>`. It will also
> look for `<group>/lein-template.<artifact>` and
> `<group>/boot-template.<artifact>`.

Cool; I don't see any reason not to adopt the same convention in
Leiningen. I will give this a go.

**Comment by technomancy** [comment]
I've opened https://github.com/technomancy/leiningen/pull/2734 to reflect the changes to Clojars policy; would appreciate a second pair of eyes on that to make sure I've understood the changes correctly and that this works similarly to how other tools are responding to this change.

**Comment by seancorfield** [comment]
Will take a proper look when I'm back at my main computer (probably tomorrow) but a first glance looks good.

**Comment by seancorfield** [comment]
I added some comments and questions on the PR. Based on the discussion that comes out of those, I can certainly change `clj-new`'s `template` behavior if necessary to match Leiningen's. I don't know how active the Boot folks are these days -- I haven't had any response to my issue on their repo.

**Comment by technomancy** [comment]
Sorry; I don't see any comments on the PR. Can you provide a link?

**Comment by seancorfield** [comment]
Apparently, I don't know how to use GitHub Pull Request Reviews... Hopefully, you can see them now?

**Comment by technomancy** [comment]
Haha, yeah I've been there. Thanks; I can see it now.

**Comment by seancorfield** [comment]
Are we keeping this open until a release is made, or is it considered "done" at this point?

**Comment by technomancy** [comment]
Nah just slipped my mind. But the release is out now!
