### ISSUE TITLE
the release asset zip.asc file has been renamed to jar.asc for v2.9.6 

### ISSUE THREAD

**Issue by Quantisan** [technomancy/leiningen#2737]
This file: https://github.com/technomancy/leiningen/releases/download/2.9.6/leiningen-2.9.6-standalone.jar.asc used to be `.zip.asc` prior to 2.9.6. This is affecting https://github.com/Quantisan/docker-clojure/pull/107#issuecomment-821894817 as we've been expecting that filename.

Is this a deliberate change? If not, I can look into fixing it.

**Comment by Quantisan** [comment]
I see this comment... https://github.com/technomancy/leiningen/commit/9e8aa05f12dc8672d1514a3389b8824eb6faff71#diff-ba4e74f7fdeafe09fab0dd8bd69b66578025911d8ea9403bf70182183fdd6600R84

**Comment by winks** [comment]
This "github foolishness" has since been rectified (at least I'm 90% sure you couldn't upload a .jar years ago) and it has been kept for compatibility sake - I think this was indeed a 2.9.6 error/typo/hiccup and should be able to be fixed if @technomancy just adds the missing file, I'm not meddling with releases :)

**Comment by technomancy** [comment]
I'm not sure what happened here; I'm using the same release scripts I've been using for years but something ended up differently this time. @winks is right that the rename thing was a workaround for a stupid limitation they used to have but isn't necessary any more so I'll see if I can get it switched to using the jar for the next release. I've updated the `.asc` file in the release; thanks for the heads up. Going to keep this issue open as a reminder to fix the release script.

**Comment by technomancy** [comment]
This should be taken care of now; no more zips mentioned anywhere.
