### ISSUE TITLE
TieredStopAtLevel flag is undocumented and has undesirable effects

### ISSUE THREAD

**Issue by bsless** [technomancy/leiningen#2738]
Hello,
Some background for this issue - I'm working on a library which deals with Clojure performance on the JVM.
After some investigation and analysis for a recent issue https://github.com/bsless/clj-fast/issues/19 I found significant performance differences due to `TieredStopAtLevel=1`
While this is not an issue for regular development flows, it is significant in any case where the developer wishes to profile their code, or run it with `lein run`.
I realize TieredStopAtLevel and TieredCompilation flags are probably injected to reduce start up times - I think the best compromise is documenting this flag and ensuring it does not make its way into `lein run`

What do you think?

Thanks

**Comment by winks** [comment]
We have a ton of issues mentioning this flag in the past: https://github.com/technomancy/leiningen/search?p=2&q=TieredStopAtLevel&type=issues - not sure any of those help, and not sure if we're currently still at the point of what was mentioned in #2674

**Comment by bsless** [comment]
I'm not sure this is the main thrust of this issue, like mentioned in #1025:
> Thanks for taking the time to look into this. While this optimization probably makes sense in production, it's definitely not what you want during development, so I've added the flag to the default jvm-opts.
I think the issue is that as a default flag it creates a run time environment different than what I would expect in production, which means it will throw off any results regarding performance or profiling.
It also means `lein run` is unfit for production without explicitly overriding the default flags. By "production" I mean any process which runs for over 5-10 seconds for the JIT to start kicking in. For over 60 seconds it's a real killer.
This would have been fine had it been properly documented, and perhaps removed from the `lein run` command.
Lowering start up time for development is important and good. Not knowing the development environment is modified from the default and in what manner, less so.

**Comment by technomancy** [comment]
Yeah, `lein run` is documented as using the `:dev` profile, which optimizes for fast startup. You can do `lein with-profile production run` to avoid the tiered compilation settings.

Changing the defaults is not an option, but if you have suggestions for specifics of how to make this clearer, I'd be happy to make that happen. Maybe the docstring for the `run` task would be a good place for it?

**Comment by bsless** [comment]
There are a few possible solutions I can think of which can be mixed and matched according to your considerations:

**Comment by bsless** [comment]
Now that I knew what to look for in the documentation I was able to readily find it. How can we know if this was due to unclear documentation or oversight on mine and another party's end?
Is it reasonable in your opinion to add a warning when invoking `lein run` with the default profile that it should be run with production profile in a production environment?

**Comment by technomancy** [comment]
If there were a way to detect "production" this might be reasonable, but
I can't think of one. As it is, most people using `lein run` either
use it in a way where this warning wouldn't be relevant, or already know this,
so emitting a warning would only be an annoyance. Having a hard time
thinking of a better solution than a note in the run help text.

**Comment by bsless** [comment]
This issue and some others linked here got me thinking in a more general direction: (tell me if you want to spin a new issue off any of these ideas or they're just non-starters)
One very important consideration for leiningen is reducing start-up time.
Two "problems" are being bootstrapping with bash and determining the java version.
- Java version: I don't recall which issue I saw it on but you mentioned parsing and extracting the version introduces too much overhead. Why not just do it with Java? [This small class](https://gist.github.com/bsless/3ab8f446c9d27d41da7f911e141b1834) can be distributed alongside lein and used for quickly getting the version
- Why bootstrap with bash at all? This, too, can go in several directions:
  - Write the bootstrap in Clojure then build it with native-image
  - Bootstrap with Java? Can even build a mixed project where the entry point will be a different `main`. Then you can also stay inside one JVM, too.

**Comment by technomancy** [comment]
>   - Write the bootstrap in Clojure then build it with native-image

Last I checked this was not compatible with all the systems that we
currently support, so we would have to keep maintaining the bash version
anyway. This doesn't really seem like a step in the right direction in
terms of maintenance burden. It could be done as a 3rd-party unofficial
project tho.

>   - Bootstrap with Java? Can even build a mixed project where the
>   entry point will be a different `main`. Then you can also stay
>   inside one JVM, too.

The problem is the JVM options can't be changed once the process has
started. So in order to do this in a way that allows the customization
of Lein's own JVM options, you would require a grand total of three JVMs
to run any project code, which feels absurd to me.

**Comment by technomancy** [comment]
Open to suggestions for how to make this clearer, but if we don't get any I figure this should be closed.
