### ISSUE TITLE
Leiningen as executable

### ISSUE THREAD

**Issue by ianmubangizi** [technomancy/leiningen#2747]
Is it not possible to bundle the jvm using graalvm native to make leiningen executable. This idea I believe may help speed up the tool

**Comment by technomancy** [comment]
I haven't looked much into graalvm because of Oracle, but I heard that it could not load code at runtime. That makes it a very poor fit for Leiningen, which relies heavily on plugins.

**Comment by ianmubangizi** [comment]
Does graalvm not have support for JNI?

I don't know the performance implications of this, but is it possible to use a client & server architecture like LSPs use, that way commutations between the plugins and leiningen takes place over rpc or sockets. 

Leinginen works just fine in most cases yet the overhead of having to warm up a jvm can get a bit too much. Issues arise when in need of the repl, where multiple jvms can get orphaned in bizarre cases #gradle 👀, additionally when running tests.

**Comment by technomancy** [comment]
> Does graalvm not have support for JNI?

I have no idea; the main thing I know about JNI is that it's the easiest way to get the JVM to segfault.

> is it possible to use a client & server architecture like LSPs use, that way commutations between the plugins and leiningen takes place over rpc or sockets.

Yep! I know it's possible because I already built it. Works great and starts up very quickly: https://leiningen.org/grench.html

You don't need graalvm for that.

**Comment by ianmubangizi** [comment]
Seems you left out windows 🤣
