### ISSUE TITLE
How to get standalone Leiningen running on a sandboxed Linux?

### ISSUE THREAD

**Issue by rlhk** [technomancy/leiningen#2748]
My target Linux box has but no general internet access. Suppose I'm able to transfer the standalone release .zip file there, as a Leiningen user, what steps and extra dependencies are required to get it installed and usable? Thanks.

**Comment by winks** [comment]
the `lein` script puts into .lein/self-installs - if you downloaded a .zip, just rename to .jar
```
ls -al .lein/self-installs/
total 12464
drwxr-xr-x 1 florian florian     4096 May 26 18:21 .
drwxrwxrwx 1 florian florian     4096 May 26 18:20 ..
-rw-r--r-- 1 florian florian 12760940 May 26 18:21 leiningen-2.9.6-standalone.jar
```
