### ISSUE TITLE
[request/question/bug] Moving the .lein and .m2 folders out of the users $HOME directory

### ISSUE THREAD

**Issue by WilliamBehrens** [technomancy/leiningen#2772]
I've found a stackoverflow question that addresses the [.m2/](https://stackoverflow.com/questions/12579335/leiningen-how-to-customize-the-location-of-the-m2-folder) folder but I can't seem to get any leads on moving the .lein folder that's created by the [lein shell script](https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein) also the .m2 fix requires configuation in the .lein folder

**Comment by technomancy** [comment]
You can export a `LEIN_HOME` environment variable if you want to move it without moving `$HOME`.
