### ISSUE TITLE
How to use prep-tasks with lein run 

### ISSUE THREAD

**Issue by zendevil** [technomancy/leiningen#2783]
I want to run `lein run -m user` task as the prep-task when running `lein test`. This is my test profile:

```
{:jvm-opts ["-Dconf=test-config.edn"]
                  :resource-paths ["env/test/resources"]
                  :prep-tasks ["run -m user"]}
```
However I get the error that "run -m user" is not a task. How do I do this? Does leiningen not support this? If that's the case, is there another way to run a function before running all tests with lein test?

My goal is to run database migrations before I run all the tests. And the function I want to run with prep-task runs all the database migrations.

**Comment by technomancy** [comment]
You should be able to replace `"run -m user"` with `["run" "-m" "user"]` since they are considered separate arguments. If that doesn't work you can define an alias for the run task with those args and put that alias name into `:prep-tasks`.
