### ISSUE TITLE
could not find a non empty configuration file to load. 

### ISSUE THREAD

**Issue by zendevil** [technomancy/leiningen#2784]
I’m getting the following error when running lein run. Not sure what’s causing it:
```
Syntax error compiling at (/tmp/form-init5805669980636889423.clj:1:73).
19
could not find a non empty configuration file to load. looked in the classpath (as a "resource") and on a file system via "conf" system property
21
```
This error occurs in continuous integration and not locally

**Comment by technomancy** [comment]
Sorry but without a repro case it's difficult to see how this could be actionable.

**Comment by technomancy** [comment]
Feel free to reopen if you can provide details.
