### ISSUE TITLE
Documentation "lein help new" does not list templates

### ISSUE THREAD

**Issue by ericdlaspe** [technomancy/leiningen#2787]
I'm a Leiningen/Clojure n00b. I tried creating a new project using `lein new myproj`. The output was:

```
Generating a project called proj based on the 'default' template.
The default template is intended for library projects, not applications.
To see other templates (app, plugin, etc), try `lein help new`.
```

I thought, "I don't want to make a library. Maybe an app is what I want, but I want to see the list of templates to be surer." I figured I could see them enumerated by typing `lein help new`, as mentioned, but they are not listed there. As a beginner, I'm left wondering how to find the list of templates.

Thanks in advance for taking a look!

**Comment by ericdlaspe** [comment]
Sure is, thanks.  I'll add my configuration to the original issue.

**Comment by technomancy** [comment]
OK, let's track this in the other ticket then.
