### ISSUE TITLE
(Uber)jar name from environment variable

### ISSUE THREAD

**Issue by B-tronics** [technomancy/leiningen#2788]
Is it possible to set the (uber)jar name dynamically from environment variable? I tried to do it in the `project.clj` file, with `:uberjar-name (. System getenv "ENV_VAR")` but I get the following error, when I try to compile with `lein uberjar`: 
> java.lang.ClassCastException: class clojure.lang.PersistentList cannot be cast to class java.lang.String (clojure.lang.PersistentList is in unnamed module of loader 'bootstrap'; java.lang.String is in module java.base of loader 'bootstrap')

**Comment by technomancy** [comment]
You can use an unquote (tilde) inside project.clj to accomplish this:

    :uberjar-name ~(System/getenv "ENV_VAR")

**Comment by B-tronics** [comment]
Thank you for the answer.
