### ISSUE TITLE
Looking to Build Leiningen from Source

### ISSUE THREAD

**Issue by yewscion** [technomancy/leiningen#2797]
I am looking to try to build Leiningen from Source, without relying on a pre-built binary. Is there a way to do that, currently? I do not want to use any pre-built binaries; I want to build everything myself. It's okay if it is a long process; I'm sure I'll learn a lot.

**Comment by technomancy** [comment]
Version 2.0.0 of Leiningen can be bootstrapped using Maven, so one way to do this could be to build Maven, use it to build Leiningen 2.0.0, and then use Leiningen 2.0.0 to build the latest version. However, I'm not confident that 2.0.0 could be used to build the latest; it might be necessary to build some in between version if the most recent version relies on features that weren't present in 2.0.0.

Another option would be to follow the Debian packaging process, which I believe avoids cyclical dependencies. I don't know as much about this tho.

**Comment by yewscion** [comment]
Interesting. I'll start with the maven example You gave, I suppose. Thank You for responding!

I'll update this ticket with how it goes, in case future people are interested in the process.

**Comment by yewscion** [comment]
I checked out the 2.0.0 tag, but can't seem to find a `pom.xml` in that checkout. There's one in the 1.7.1 tag; Should I go with that one, or is there another more recent tag that might have a `pom.xml` to use?

**Comment by yewscion** [comment]
Nevermind, found one in `2.0.0-SNAPSHOT` thanks to `git log -p -- pom.xml`. This seems to be the most recent version of the file, as the next entry is its removal.

**Comment by technomancy** [comment]
If there is anything actionable here we can leave this open but otherwise I'd like to close it out.

**Comment by yewscion** [comment]
Hi there!

I am a bit stymied by the work that's involved in doing this, so feel free to close out the ticket. I will track my progress locally and post it publicly upon success.

Thanks for Your initial help! Sorry to clog up the issue tracker!
