### ISSUE TITLE
lein deps hangs and exits due to StackOverflowError

### ISSUE THREAD

**Issue by liamchzh** [technomancy/leiningen#2798]
**Initial debugging steps**
Before creating a report, _especially_ around exceptions being thrown when running Leiningen, please check if the error still occurs after:

- [x] Updating to using the latest released version of Leiningen (`lein upgrade`).
- [x] Moving your `~/.lein/profiles.clj` (if present) out of the way. This contains third-party dependencies and plugins that can cause problems inside Leiningen.
- [ ] Updating any old versions of plugins in your `project.clj`, especially if the problem is with a plugin not working. Old versions of plugins like nREPL and CIDER (as well as others) can cause problems with newer versions of Leiningen.
- [ ] (If you are using Java 9 or newer), updating your dependencies to their most recent versions. Recent JDK's have introduced changes which can break some Clojure libraries.

**Describe the bug**
`lein deps` would hang after bumping [Netty TomcatNative BoringSSL Static](https://mvnrepository.com/artifact/io.netty/netty-tcnative-boringssl-static) to `2.0.50.Final`. CPU load increases in the meantime.

**To Reproduce**
1. Create a new project: `lein new my-project`
2. Add the `netty-tcnative-boringssl-static` version `2.0.50.Final` to the dependencies: `:dependencies [[io.netty/netty-tcnative-boringssl-static "2.0.50.Final"]]`
3. Run `lein deps`

**Actual behavior**
`lein deps` hangs and exits due to `StackOverflowError` on my machine.

**Expected behavior**
Successfully install the `netty-tcnative-boringssl-static` dep.

**Environment**
- Leiningen Version: 2.9.8
- Leiningen installation method: manual
- JDK Version: openjdk version "1.8.0_282"
- OS: macOS 12.4
- Anything else that might be relevant to your problem?

**Additional context**
`2.0.50.Final` is the first version that causes the problem and it introduced circular dependency since this version.
See related issues of netty-tcnative-boringssl-static on GitHub:
* [issue1](https://github.com/netty/netty-tcnative/issues/727)
* [issue2](https://github.com/netty/netty-tcnative/issues/716)

**Comment by technomancy** [comment]
Thanks for reporting this. Will see what we can do.

In the mean time, you can work around it by putting `:pedantic? false` in your project.clj.

**Comment by technomancy** [comment]
This was tricky to debug, but I think it has to do with an assumption in the cycle detection of the pedantic implementation. We have code that does `(some #{node} parents)` where node and parents are DefaultDependencyNode objects from Aether, so that code assumes that they hash consistently, but the boringssl ones do not.

The fix is quite simple; turn everything into a string before doing cycle detection.
