### ISSUE TITLE
Leiningen Homebrew 2.9.10 Upgrade Failing

### ISSUE THREAD

**Issue by davecom** [technomancy/leiningen#2802]
**Describe the bug**
Upgrading Leiningen from 2.9.9 to 2.9.10 is failing for me via Homebrew consistently for the same reason for over a month. Based on the log it seems to be due to the manifest file.

**To Reproduce**
1. Type `brew upgrade` with Leiningen already installed via Homebrew

**Actual behavior**
Leiningen upgrade fails due invalid JSON according to the Homebrew log

**Expected behavior**
Expect Leiningen to be upgraded to 2.9.10

**Logs**
```
==> Downloading https://ghcr.io/v2/homebrew/core/leiningen/manifests/2.9.10
Already downloaded: /Users/dave/Library/Caches/Homebrew/downloads/51707dfc77a2764e382a0f368a23ed00abebea72caae6af5c3917f57516465db--leiningen-2.9.10.bottle_manifest.json
Error: leiningen: Failed to download resource "leiningen_bottle_manifest"
The downloaded GitHub Packages manifest was corrupted or modified (it is not valid JSON): 
/Users/dave/Library/Caches/Homebrew/downloads/51707dfc77a2764e382a0f368a23ed00abebea72caae6af5c3917f57516465db--leiningen-2.9.10.bottle_manifest.json
```
**Environment**
- macOS 12.6
- Upgrading Leiningen 2.9.9 to 2.9.10 via latest Homebrew

**Additional context**
Never had trouble upgrading Leiningen using Homebrew before but this specific upgrade has been consistently failing with the same log output for a month now.

**Comment by winks** [comment]
Hello,
that issue should be filed with homebrew (probably one of the repos here: https://github.com/Homebrew ) as none of the lein developers use OSX (afaik) and we don't package lein for brew, unfortunately I also don't know who wrote that manifest.
