### ISSUE TITLE
Leiningen 2.9.1 with java 7

### ISSUE THREAD

**Issue by spirosvar** [technomancy/leiningen#2806]
Hello,

I have encountered an error while trying to execute lein with java 7 (on ubuntu), is there a workaround or this happens due to incompatibility issues? I've searched the web but I found no relative answers.

Thanks in advance,
Spiros.

**Comment by technomancy** [comment]
Would you like to share what the error says?

**Comment by technomancy** [comment]
Going to close this out since there is not enough information for it to be useful; we can reopen if details are provided.
