### ISSUE TITLE
changing the error message if a parent pom file is missing

### ISSUE THREAD

**Issue by habruening** [technomancy/leiningen#2809]
I have no Internet connection on the machine, where I want to use Leiningen. I read in the FAQ that it is recommended to manually create a repository in this situation. But manually downloading the dependencies and placing them in the .m2 folder also works.

In principle this works well. Leiningen is so nice to tell me, what it wants to download, and I can manually do the download. But sometimes pom files incorporate parent pom file. I this case all I gt is an error message `Failed to read artifact descriptor for org.clojure:spec.alpha:jar`. For people who are not so familiar with Pom files, this message is not helpful.

I don't know if Leiningen can change this. I suppose, this message comes from Maven. So feel free to close this issue. Or maybe you want to add this message into the FAQ.

**Comment by technomancy** [comment]
You're right that Leiningen doesn't control these error message unfortunately; that one is particularly unhelpful.

I don't really recommend downloading these files one at a time. The best solution would be to run Leiningen on a computer that does have internet access and then copy over the `~/.m2/repository` to the isolated machine.
