### ISSUE TITLE
A way to pass a profile to generated jar

### ISSUE THREAD

**Issue by mtsbarbosa** [technomancy/leiningen#2812]
Hi,
I am generating a jar through `lein uberjar` 
I am willing to pass a profile when executing that like `java -jar target/my-app-0.0.10-standalone.jar`
is there a way to achieve this?

I am doing that because I wanna keep it running in a docker image without clojure or leiningen, just java to be lightweight

**Comment by technomancy** [comment]
No, there's no way to do this. Profiles only exist in Leiningen; the `java` command knows nothing about them. Things that are needed after the build finishes should not be placed in profiles.
