### ISSUE TITLE
`WARNING: cat already refers to: #'clojure.core/cat in namespace: net.cgrand.parsley.fold` on `lein trampoline repl`

### ISSUE THREAD

**Issue by metametadata** [technomancy/leiningen#2820]
**To Reproduce**

1. `lein new app foo`, `cd foo`.
1. `lein trampoline repl`.

**Actual behavior**

Unexpected `WARNING` log:

```
ᐅ lein trampoline repl
REPL-y 0.5.1, nREPL 1.0.0
Clojure 1.11.1
OpenJDK 64-Bit Server VM 17.0.8+7-jvmci-23.0-b15
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

foo.core=> WARNING: cat already refers to: #'clojure.core/cat in namespace: net.cgrand.parsley.fold, being replaced by: #'net.cgrand.parsley.fold/cat
```

**Expected behavior**

No warnings.

**Environment**

- Leiningen Version: 2.11.2.
- Leiningen installation method: Homebrew.
- JDK Version: Java 17.0.8 OpenJDK 64-Bit Server VM.
- OS: macOS 14.4.1.

**Comment by technomancy** [comment]
Good catch; it looks like for Leiningen's own process we pull in a patched version of `parsley` but for the repl task we just depend on `reply` which pulls in an older version indirectly.

**Comment by technomancy** [comment]
Fixed in 7a35250.

**Comment by metametadata** [comment]
Thank you!

**Comment by technomancy** [comment]
I want to take a little more time to look thru open issues, but we could do a release soon.

**Comment by technomancy** [comment]
I've just pushed out a fix for https://codeberg.org/leiningen/leiningen/issues/22 and I think that covers everything I wanted to get into the next release. If I could get more eyes on the release (especially looking at the suggestions when version ranges are encountered) it would help get confidence to get the next release out sooner.

**Comment by metametadata** [comment]
* The current issue looks solved. 
* >  If I could get more eyes on the release (especially looking at the suggestions when version ranges are encountered) it would help get confidence to get the next release out sooner.
    
    I also experienced a slowdown on a project with `aws-cdk-lib` in combination with `:pedantic? :abort`. Seems to be much faster now and suggesting managed dependencies instead of exclusions for solving conflicts is a great new feature 👍
