### ISSUE TITLE
Error: Could not find or load main clas

### ISSUE THREAD

**Issue by jcs090218** [technomancy/leiningen#2823]
I'm encountering this issue in https://github.com/the-flx/clj-flx/actions/runs/12279414828/job/34263401391#step:5:11.

The project: https://github.com/the-flx/clj-flx

Weird bug since it only happens on Windows. 🤔 Any help is appreciated!

**Comment by technomancy** [comment]
I'm not familiar with the CI system, but it looks like maybe you're using the powershell launcher? That was contributed by a user years and years ago; it's not really official, and I don't know anything about how it works.

Perhaps using `lein.bat` would work better? Not that I have any understanding of that either, but it is more widely used and less likely to have bugs in it; it's the one that's recommended on https://leiningen.org

**Comment by jcs090218** [comment]
Nice, it works!

Added `shell: cmd` to solve the issue.
