### ISSUE TITLE
lein 2 preview 4 has encoding issues in the REPL

### ISSUE THREAD

**Issue by wolverian** [technomancy/leiningen#586]
Leiningen 2.0.0-preview4 on Java 1.6.0_31 Java HotSpot(TM) 64-Bit Server VM

```
user=> "ä"
"?"
```

This is on OS X 10.7, iTerm2, and my locale is:

```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

UTF-8 works in other programs.

**Comment by keithharper** [comment]
I'm curious, why did the change in [efc8fb4](https://github.com/technomancy/leiningen/commit/efc8fb4424d23ed19552999e9ddcc8be125dec03) never make it into https://github.com/technomancy/leiningen/blob/master/bin/lein.bat?

Windows defaults to windows-1252:
```
(java.nio.charset.Charset/defaultCharset)
=> #object[sun.nio.cs.MS1252 0x136e5c2e "windows-1252"]
```

Mac:
```
(java.nio.charset.Charset/defaultCharset)
=> #object[sun.nio.cs.UTF_8 0x78e00c34 "UTF-8"]
```

**Comment by technomancy** [comment]
I guess this was because it was only ever reported as a bug on Macs; I don't know enough about Windows to know if the same problem would happen there but if it does we can apply it to the batch file too.

**Comment by keithharper** [comment]
Gotcha - @winks responded on freenode and is going to look into it

**Comment by winks** [comment]
Hmm, the test above doesn't inspire confidence

![foo](https://i.imgur.com/af1HFt8.png)

**Comment by winks** [comment]
Ok, but with my super advanced test program 

```
(ns foo.core
  (:require [clj-http.client :as client]))

(defn -main
  "I don't do a whole lot."
  [x]
  (println x "Hello, World!")
  (client/get (str "http://something:9999/ä_" x)))
```

I get these results:

```
c:\apps\bin\lein.bat run ä
Σ Hello, World!

c:\apps\bin\lein.bat run ä
├ñ Hello, World!
```

```
[17/Feb/2020 19:02:53] "GET /%C3%A4_%C3%A4 HTTP/1.1" 404 -
[17/Feb/2020 19:03:18] "GET /%C3%A4_%C3%A4 HTTP/1.1" 404 -
```


2 identical requests at  a webserver, so the 2 "ä" seem to at least be converted correctly.
