### ISSUE TITLE
gpg can't prompt for passphrase

### ISSUE THREAD

**Issue by technomancy** [technomancy/leiningen#615]
gpg has no way to suppress the passphrase prompt when gpg-agent used, (`--quiet` is ignored) so when decrypting the `~/.lein/credentials.clj.gpg` file we have to choose between forcing use of an unlocked gpg-agent (with `--batch`) and showing the prompt even when unnecessary. Since the prompt screws up M-x clojure-jack-in, we've currently opted for --batch.

Somehow `gpg` is able to print output to stdout even when using `clojure.java.shell/sh`, which supposedly captures all output and puts it in the `:out` key of its return value. Even calling `System/setOut` cannot suppress the output.

**Comment by creamidea** [comment]
Hi, I have met the same problem using cmd on Windows 10. I found the cmd doesn't support the prompt for password.
At last, I changed to use Git Bash to resolve this problem. Good luck :)
