### ISSUE TITLE
`shasum` not available on CentOS 5, Fedora 16

### ISSUE THREAD

**Issue by haus** [technomancy/leiningen#687]
Issue #458 and commit e0c6e486 changed `sha1sum` to `shasum`, which isn't available on CentOS or Fedora 16.

**Comment by icambron** [comment]
@technomancy I know this ticket is ancient, but the use of `shasum` is back: https://github.com/technomancy/leiningen/blob/ee57b19a5daae0687f22c7aba0da55538366664f/bin/lein#L308, and I had the same issue on CentOS

**Comment by Leonidas-from-XIV** [comment]
I had the same issue on Fedora 22 and Leiningen 2.5.0. I believe this issue should be reopened.

**Comment by hyPiRion** [comment]
Closed by #1918.
