### ISSUE TITLE
Deployment via scpexe

### ISSUE THREAD

**Issue by matonthecat** [technomancy/leiningen#824]
Hi,

I'm just diving into clojure and leiningen and I'm just on the edge of deploying a leiningen project into our company's repo, which - up to now - contains only maven artifacts. We use scpexe and private key authentication to deploy our artifacts to our repo. Can I configure deploy-repositories in leiningen similar to this? 

pom.xml:

``` xml
    <repository>
      <id>company</id>
      <url>scpexe://repo-host:/path-to-m2repo</url>
    </repository>
```

settings.xml:

``` xml
    <server>
      <id>company</id>
      <username>name</username>
      <privateKey>path to priv key</privateKey>
      <configuration>
        <sshExecutable>ssh</sshExecutable>
        <scpExecutable>scp</scpExecutable>
      </configuration>
    </server>
```

Thanks!

**Comment by matonthecat** [comment]
Well, it's been a while that I have been running on this type of infrastructure. Have you tried [this](https://github.com/technomancy/leiningen/blob/stable/doc/DEPLOY.md#scp) (add the register call above your project)?

**Comment by serioga** [comment]
Well, I failed with raw SSH under Windows.
But repository managers like Nexus work fine so I can live with it.
