### ISSUE TITLE
Command history and completion does not work under Cygwin + mintty

### ISSUE THREAD

**Issue by luontola** [technomancy/leiningen#850]
This is due to a problem with JLine not detecting that it's running under Cygwin. The workaround described in the following urls helps:
http://sourceforge.net/tracker/index.php?func=detail&aid=1822900&group_id=64033&atid=506056
http://weblogs.java.net/blog/cayhorstmann/archive/2010/11/24/report-sewer-hole-cygwin-jline-rxvt-and-scala-repl

I modified the lein startup script to call stty and set jline.terminal, and it seems to work:

```
    stty -icanon min 1 -echo
    $LEIN_JAVA_CMD \
        -client -XX:+TieredCompilation \
        -Djline.terminal=jline.UnixTerminal \
        $LEIN_JVM_OPTS \
        -Dfile.encoding=UTF-8 \
        -Dmaven.wagon.http.ssl.easy=false \
        -Dleiningen.original.pwd="$ORIGINAL_PWD" \
        -Dleiningen.trampoline-file="$TRAMPOLINE_FILE" \
        -cp "$CLASSPATH" \
        clojure.main -m leiningen.core.main "$@"
    EXIT_CODE=$?
    stty icanon echo
```

Maybe something similar could be done automatically when the script runs under Cygwin?

**Comment by dmos62** [comment]
@trpcolin I confirm that `lein trampoline repl` malfunctions (is unresponsive) under Cygwin.
