### ISSUE TITLE
Profile merge concatenates things that don't make sense

### ISSUE THREAD

**Issue by trptcolin** [technomancy/leiningen#878]
If I have this in `~/.lein/profiles.clj`

``` clojure
{:user {:repl-options {:init (set! *print-length* 20)}}}
```

and this in my `project.clj`:

``` clojure
{:user {:repl-options {:init (println "HI!")}}}
```

then the merged `:repl-options` end up being:

``` clojure
{:init (println "hi!" set! *print-length* 20)
```

because of [meta-merge](https://github.com/technomancy/leiningen/blob/b497494b0445cb361381c71ff86517b4697a5419/leiningen-core/src/leiningen/core/project.clj#L432-L461).

Ideally there would be something like a list of all the forms - is the full list of profile settings exposed anywhere that would allow the repl task to do something custom? I'm not sure what the right thing to do here would be. :(

**Comment by devth** [comment]
Is this a benign / ignorable error or does it actually cause problems?
Regardless of whether the types match, I'd expect the last value to win / override.

**Comment by technomancy** [comment]
> Regardless of whether the types match, I'd expect the last value to win / override.

Really? You'd expect adding :dependencies in your :dev profile to wipe out the :dependencies from the top-level defproject map? This is not how most users expect it to work.

> Is this a benign / ignorable error or does it actually cause problems?

When people expect it to work one way, and it works differently, there's always plenty of potential for problems.

**Comment by devth** [comment]
To clarify: I only meant when there's a type conflict. Always merge when possible. Fallback to replace when not.

**Comment by technomancy** [comment]
> Always merge when possible. Fallback to replace when not.

I see--this issue is actually about the fact that "always merge when possible" is not always the correct choice--merging two lists like `(require 'xyz)` and `(println "abc")` gives you `(require 'xyz println "abc")`, which is wrong. You can see some examples of this in the comments above.

**Comment by technomancy** [comment]
At this point any changes to this behavior are likely to be more disruptive than the problematic behavior itself.
