### ISSUE TITLE
:user profile not getting picked up in non-project repls

### ISSUE THREAD

**Issue by vemv** [technomancy/leiningen#966]
Given the following `~/.lein/profiles.clj`:

```
{:user {:repl-options {:port 9119}}}
```

The port gets effectively picked when running `repl` in the context of any Leiningen project. But when the current directory does not belong to a project, a random port is used instead.

Not sure if this is the expected behavior...?

**Comment by duud** [comment]
I'm facing the same issue as in https://stackoverflow.com/a/28929874 .
Is this the desired behaviour?
