### ISSUE TITLE
A better templating system for leiningen

### ISSUE THREAD

**Issue by zcaudate** [technomancy/leiningen#990]
I made a pull request to the lein-newnew about 3 months ago for a new templating system (which is also compatible with the older templates) 

The conversation I had with Raynes is here:
https://github.com/Raynes/lein-newnew/pull/54

The problem that I found with lein-newnew was that it sort of half did the job. Its only good for tiny templating solutions. If I wanted to make a template that included pictures and anything with mustaches (like an angularjs project) it would not be possible.

I added more declarative syntax for how files and entire folders should be rendered. Since lein-newnew has been merged into leiningen, I don't really know how to go about with the pull request.

There is a detailed readme for how the new templates should be defined
https://github.com/zcaudate/lein-newnew

as well as an example template for an angularjs project:
https://github.com/zcaudate/blank-angular-website

**Comment by hyPiRion** [comment]
I'll close this as this has been untouched for roughly 2 and a half years, but I'm happy to discuss potential changes for 3.0.0. If you feel it's still relevant, just reopen this issue.
